Chapter 5 - PTBR
JuliaIntro/JuliaIntroBR.jl pull request #10
Opened 2020-04-30 21:22 UTC by gustavosarturi

- Translation to PT-BR
- Fixed: Alignments

2020-04-30 21:27 UTC, gustavosarturi commented
- To me: <enter> on line 124.

2020-05-02 07:00 UTC, joaoluisro requested changes
thanks @gustavosarturi

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +=== Divisão Floor e Módulo
Divisão inteira para todos os subsequentes "Divisão floor"

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +O operador _divisão floor_, +÷+ (*+\div TAB+*), divide dois números e arredonda pra baixo para um inteiro. Por exemplo, suponha que o tempo de execução de um filme seja de 105 minutos. Você talvez sa
"O operador de _divisão inteira_ ..." e "A divisão convencional retorna ..."

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +julia> houras = minutos ÷ 60
horas

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Uma alternativa é usar o _operador módulo_, +%+, que divide dois números e retorna o restante.
"... e retorna o resto"

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +O operador módulo é mais útil do que parece. Por exemplo, você pode verificar se um número é disívell por outro — se +x % y+ é zero, então +x+ é divisível por +y+.
divisível

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Além disso, você pode extrair o dígito ou dígitos mais à direita de um número. Por exemplo, +x % 10+ gera o dígito mais à direita de um inteiro +x+ (na base 10). Da mesma forma +x % 100+ produtos os
"... produz os últimos dois dígitos"

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((declrações compostas)))(((end)))(((fim)))
declarações e remova o "(((fim)))"

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +elseif esculha == "c"
escolha

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((contador regressivo)))((("função", "programmer-defined", "contador regressivo", see="contador")))
"definido pelo programador"

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Julia fornece uma função interna chamada +readline+ que interrompe o programa e aguarda o usuário digitar algo. Quando o usuário pressiona +RETURN+ ou +ENTER+, o programa é retomado e +readline+ reto
sequência

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +decibeis = 10 * log10(razão)
decibéis

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((fermat)))((("function", "definido pelo programador", "fermat", see="fermat")))
função

2020-05-02 07:00 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +. Fire 120° para direita.
vire

2020-05-03 14:58 UTC, gustavosarturi commented on book/src/chap05.asciidoc
> +. Fire 120° para direita.
Substituido por Gire conforme padrão anterior

2020-05-07 11:30 UTC, joaoluisro requested changes
Segunda revisão

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Para obter um restante, você pode subtrair uma hora em minutos:
"Para obter o restante ... "

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
>  (((boolean expression)))(((true)))(((false)))
"expressão booleana" no parênteses

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +A expressão booleana depois de +if+ é chamada de _condição_. Se é verdadeira, então a atribuição identada é executada. Se não, nada acontece. (((condição)))
" ... atribuição indentada ... "

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((execução alternativa)))(((se não)))((("palavra-chame", "senão", see="se não")))
"palavra-chame" -> "palavra-chave" e "senão" -> "se não"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Se o resto quando +x+ é dividido por 2 é 0, então sabemos que +x+ é par, e o programa irá exibir a mensagem apropriada. Se a condição for falsa, o segundo conjunto de declarações é executado. Desde q
acho que facilita pro leitor algo como "Se o resto da divisão de x por 2 é 0, ... "

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Algumas vezes há mais do que duas possibilidades e precisamos de mais que dois ramos. Uma maneira de expressar um cálculo como esse é através das _condicionais encadeadas_:
Concordo que a tradução de "computation" é "cálculo" mas acho que seria melhor substituir por algo mais próximo de "comando" ou  "operação" , dado o contexto

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Embora a indentação não obrigatório das declarações torne a estrutura aparente, _condicionais aninhadas_ tornam-se difíceis de ler muito rapidamente. É uma boa ideia evitá-los quando puder.
"obrigatório" -> "obrigatória"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Para esse tipo de condição, Julia fornece uma sintaxe mais concisa:
"... , O Julia fornece ... "

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +É permitido que uma função chame outra; também é permitido uma função se chamar. Pode não ser óbvio por que isso é uma coisa boa, mas acaba sendo uma das coisas mais mágicas que um programa pode faze
acho que fica mais claro "se chamar" -> "chamar a si mesmo"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((contagem regressiva)))((("função", "definido pelo programador", "contagem regressiva", see="contagem")))
"contagem" -> "contagem regressiva"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Se +n+ é 0 ou negativo, será exibido a palavra, +"Vai!"+ de outra forma, exibirá +n+ e executará a função chamada +contagem_regressiva+ — a própria — passando +n-1+ como argumento.
" de outra forma, exibirá" -> " por outro lado, a função exibirá" e " a própria " -> "ela mesma"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Se +n pass:[&lt;]= 0+ a atribuição +return+ sai da função. O fluxo de execução retorna imediatamente para o chamador e as linhas restantes da função não são executadas.
"chamador" -> "quem a chamou"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((return)))((("palavra-chave", "return", see="return")))(((return statement)))((("atribuição", "return", see="atribuição de retorno")))
"statement" -> "declaração"/"comando"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +O restante da função é similar a +contagem_regressiva+: Exibirá +s+ e chamará a si mesmo para exibir +s+ latexmath:[\(n-1\)] várias vezes. Portanto, o número de linhas de saída é latexmath:[\(1 + (n
"Exibirá" -> "Ela exibirá"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Como sempre, o topo para pilha é o quadro para +Main+. Está vazio porque não criamos nenhuma variável em +Main+ ou passamos algum argumentos para ela.
"o topo para pilha" -> "o topo da pilha"  
"Está vazio" -> "Ele está vazio"  
"ou passamos algum argumentos para ela" -> "nem passamos argumentos para ela"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Os quatro quadros de +contagem_regressiva+ têm valores diferentes para o parâmetro +n+. A parte inferior da pilha, onde +n=0+, é chamada de _caso base_. Não faz uma chamada recursiva, portanto não há
"Não faz .. " -> "Ele não faz .. "

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Como exercício, desenhe um diagrama de pilha para +printn+ chamado com +s = "Olá"+ e +n = 2+. Depois, escreva uma função chamada +do_n+ que pega um objeto de função e um número, +n+, como argumento,
"times" -> "vezes"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Os erros de sintaxe geralmente são fáceis de encontrar, mas existem algumas dicas. Em geral, as mensagens de erro indicam onde o problema foi descoberto, mas o erro real pode ser anterior no código,
"mas o erro real pode ser anterior no código" -> "mas o verdadeiro erro pode estar antes no código"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Uma atribuição que faz com que uma função pare de executar imediatamente e retorne para o chamador da função.
"chamador" -> "quem chamou"

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +. Escreva uma função chamada +triangulo+ que aceite três números inteiros como argumentos e imprima “Sim” ou “Não”, dependendo de você poder ou não formar um triângulo a partir de gravetos com os com
"dependendo de você poder ou não formar ... " ->" dependendo da possibilidade de formar ou não ... "

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +. Escreva uma função chamada +triangulo+ que aceite três números inteiros como argumentos e imprima “Sim” ou “Não”, dependendo de você poder ou não formar um triângulo a partir de gravetos com os com
"triangulo" -> "triângulo", o julia aceita funções com acento, então não tem problema. Trocar também pros outros casos

2020-05-07 11:30 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Qual é a saída do seguinte programa? Desenhe um diagrama de pilha que mostre o estado do programa quando imprimir o resultado.
"quando imprimir" -> "quando ele imprimir"

2020-05-23 16:59 UTC, joaoluisro requested changes
Terceira Revisão

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +O principal tópico deste capítulo é a atribuição +if+, da qual executa diferentes códigos dependendo do critério do programa. Mas antes eu quero introduzir dois novos operadores: Divisão Inteira e mó
```suggestion
O principal tópico deste capítulo é a atribuição +if+, que executa diferentes códigos dependendo do critério do programa. Mas antes eu quero introduzir dois novos operadores: Divisão Inteira e módulo.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +O operador de _Divisão Inteira_, +÷+ (*+\div TAB+*), divide dois números e arredonda pra baixo para um inteiro. Por exemplo, suponha que o tempo de execução de um filme seja de 105 minutos. Você talv
```suggestion
O operador de _Divisão Inteira_, +÷+ (*+\div TAB+*), divide dois números e arredonda pra baixo para um inteiro. Por exemplo, suponha que o tempo de duração de um filme seja de 105 minutos. Você talvez saiba o quanto isso equivale em horas. A divisão convencional retorna um número em ponto-flutuante:
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((operador Divisão Inteira)))((("operador", "Base", "÷", see="operador Divisão Inteira")))((("÷", see="operador Divisão Inteira")))
```suggestion
(((operador divisão inteira)))((("operador", "Base", "÷", see="operador divisão inteira")))((("÷", see="operador divisão inteira")))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Porém normalmente não escrevemos horas com pontos decimais. Divisão Inteira retorna um número inteiro de horas, arredondando para baixo:
```suggestion
Porém normalmente não escrevemos horas com pontos decimais. A divisão inteira retorna um número inteiro de horas, arredondando para baixo:
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +julia> restante = minutos - houras * 60
```suggestion
julia> resto = minutos - horas * 60
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Para obter o restante, você pode subtrair uma hora em minutos:
```suggestion
Para obter o resto, você pode subtrair uma hora em minutos:
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Para escrever programas úteis, quase sempre precisamos verificar as condições e alterar o comportamento de acordo com o programa. _Declarações Condicionais_ nos fornece essa habilidade. A forma mais
```suggestion
Para escrever programas úteis, quase sempre precisamos verificar as condições e alterar o comportamento de acordo com o programa. _Declarações Condicionais_ nos fornecem essa habilidade. A forma mais simples é a atribuição _se_ (_if_ em Inglês).
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((condicionais encadeadas)))(((se então)))((("palavra-chave", "se então", see="se então")))
```suggestion
(((condicionais encadeadas)))(((elseif)))((("palavra-chave", "elseif", see="elseif")))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Novamente, exatamente um dos ramos será executado. Não há limites para o número de declarações +else if+. Se existir uma cláusula +else+, essa deve estar no final, mas não precisa haver uma.
```suggestion
Novamente, exatamente um dos ramos será executado. Não há limites para o número de declarações +elseif+. Se existir uma cláusula +else+, essa deve estar no final, mas não precisa haver uma.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((contagem regressiva)))((("função", "definido pelo programador", "contagem regressiva", see="contagem")))
```suggestion
(((contagem regressiva)))((("função", "definido pelo programador", "contagem regressiva", see="contagem regressiva")))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((printn)))((("função", "definido pelo programador", "printn", see="printn")))
```suggestion
(((imprima_n)))((("função", "definido pelo programador", "imprima_n", see="imprima_n")))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((return)))((("palavra-chave", "return", see="return")))(((declaração de retorno)))((("declaração", "return", see="declaração de retorno")))
```suggestion
(((return)))((("palavra-chave", "return", see="return")))(((declaração return)))((("declaração", "return", see="declaração return")))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +O restante da função é similar a +contagem_regressiva+: Exibirá +s+ e chamará a si mesmo para exibir +s+ latexmath:[\(n-1\)] várias vezes. Portanto, o número de linhas de saída é latexmath:[\(1 + (n
```suggestion
O restante da função é similar a +contagem_regressiva+: Ela exibirá +s+ e chamará a si mesmo para exibir +s+ latexmath:[\(n-1\)] várias vezes. Portanto, o número de linhas de saída é latexmath:[\(1 + (n - 1)\)], o que soma latexmath:[\(n\)].
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Para exemplos simples como esse, provavelmente é mais fácil usar um loop +for+. Mas veremos exemplos mais tarde que são difíceis de escrever com um loop +for+ e fáceis de escrever com recursão; porta
```suggestion
Para exemplos simples como esse, provavelmente é mais fácil usar um laço +for+. Mas veremos exemplos mais tarde que são difíceis de escrever com um laço +for+ e fáceis de escrever com recursão; portanto, é bom começar cedo.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Como sempre, o topo da pilha é o quadro para +Main+. Ele está vazio porque não criamos nenhuma variável em +Main+ ou nem passamos argumentos para ela.
```suggestion
Como sempre, o topo da pilha é o quadro para +Main+. Ele está vazio porque não criamos nenhuma variável em +Main+ ou passamos algum argumento para ela.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Os quatro quadros de +contagem_regressiva+ têm valores diferentes para o parâmetro +n+. A parte inferior da pilha, onde +n=0+, é chamada de _caso base_. Ele não faz uma chamada recursiva, portanto nã
```suggestion
Os quatro quadros de +contagem_regressiva+ tem valores diferentes para o parâmetro +n+. A parte inferior da pilha, onde +n=0+, é chamada de _caso base_. Ele não faz uma chamada recursiva, portanto não há mais quadros.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Como exercício, desenhe um diagrama de pilha para +printn+ chamado com +s = "Olá"+ e +n = 2+. Depois, escreva uma função chamada +do_n+ que pega um objeto de função e um número, +n+, como argumento,
```suggestion
Como exercício, desenhe um diagrama de pilha para +printn+ chamado com +s = "Olá"+ e +n = 2+. Depois, escreva uma função chamada +faça_n+ que pega um objeto de função e um número, +n+, como argumento, e que chama a função dada latexmath:[\(n\)] vezes.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Se uma recursão nunca atinge o caso base, ele continua fazendo chamadas recursivas para sempre e o programa nunca termina. Isso é conhecido como _recursão infinita_, e geralmente isso não é uma boa i
```suggestion
Se uma recursão nunca atinge o caso base, ela continua fazendo chamadas recursivas para sempre e o programa nunca termina. Isso é conhecido como _recursão infinita_, e geralmente isso não é uma boa ideia. Aqui está um programa pequeno com uma recursão infinita:
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Se você encontrar uma recursão infinita por acidente, revise sua função para confirmar se há um caso base que não faz uma chamada recursiva. E se houver um caso base, verifique se você está garantind
```suggestion
Se você encontrar uma recursão infinita por acidente, revise sua função para confirmar se há um caso base que não faz uma chamada recursiva. E se houver um caso base, verifique que você está garantido a alcançá-lo.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +=== Entradas de Teclado
```suggestion
=== Entradas do Teclado
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
>  (((readline)))((("function", "Base", "readline", see="readline")))
```suggestion
(((readline)))((("função, "Base", "readline", see="readline")))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((Erro de Argumento)))
```suggestion
(((ArgumentError)))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Quando ocorre um erro de sintaxe ou de tempo de execução, a mensagem de erro contém muitas informações, mas pode ser avassaladora. As partes mais úteis são geralmente:
```suggestion
Quando um erro de sintaxe ou de tempo de execução ocorrer, a mensagem de erro contém muitas informações, mas ela pode ser avassaladora. As partes mais úteis são geralmente:
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Em Julia, você pode escrever algo como isto:
```suggestion
Em Julia, você pode escrever algo como:
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Uma atribuição que faz com que uma função pare de executar imediatamente e retorne para quem chamou.
```suggestion
Uma atribuição que faz com que uma função pare de executar imediatamente e retorne para quem a chamou.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +Uma ramo condicional de uma função recursiva que não faz um chamado recursivo.
```suggestion
Uma ramo condicional de uma função recursiva que não faz um chamado recursiva.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +. Escreva uma função que solicite ao usuário que insira valores para +a+, +b+, +c+ e +n+, converta-os em números inteiros e use +fermat+ para verificar se violam o teorema de Fermat.
```suggestion
. Escreva uma função que solicite ao usuário que insira valores para +a+, +b+, +c+ e +n+, converta-os em números inteiros e use +fermat+ para verificar se eles violam o teorema de Fermat.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +. Escreva uma função chamada +triângulo+ que aceite três números inteiros como argumentos e imprima “Sim” ou “Não”, dependendo da possibilidade de formar ou não um triângulo a partir de gravetos com
```suggestion
. Escreva uma função chamada +é_triângulo+ que aceite três números inteiros como argumentos e imprima “Sim” ou “Não”, dependendo da possibilidade de formar ou não um triângulo a partir de gravetos com os comprimentos especificados.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((triângulo)))((("função", "definido pelo programador", "é triângulo", see="é triângulo")))
```suggestion
(((triângulo)))((("função", "definido pelo programador", "é_triângulo", see="é_triângulo")))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +. Escreva uma função que solicite ao usuário a inserção de três comprimentos de gravetos, os converta em números inteiros e use +triangulo+ para verificar se os gravetos com os comprimentos especific
```suggestion
. Escreva uma função que solicite ao usuário a inserção de três comprimentos de gravetos, os converta em números inteiros e use +é_triângulo+ para verificar se os gravetos com os comprimentos especificados podem formar um triângulo.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((koch)))((("function", "definido pelo programador", "koch", see="koch")))
```suggestion
(((koch)))((("função", "definido pelo programador", "koch", see="koch")))
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +. Escreva uma função chamada + floco de neve + que desenhe três curvas de Koch para fazer o contorno de um floco de neve.
```suggestion
. Escreva uma função chamada + floco_de_neve + que desenhe três curvas de Koch para fazer o contorno de um floco de neve.
```

2020-05-23 16:59 UTC, joaoluisro commented on book/src/chap05.asciidoc
> +(((floco de neve)))((("function", "definido pelo programador", "floco de neve", see="floco de neve")))
```suggestion
(((floco_de_neve)))((("function", "definido pelo programador", "floco_de_neve", see="floco _de_neve")))
```

2020-05-30 17:46 UTC, abelsiqueira requested changes
@gustavosarturi e @joaoluisro ambos leiam as modificações feitas aqui.
@gustavosarturi tem coisas pra corrigir ainda que não dá pra fazer automática.

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +O principal tópico deste capítulo é a atribuição +if+, que executa diferentes códigos dependendo do critério do programa. Mas antes eu quero introduzir dois novos operadores: Divisão Inteira e módulo
```suggestion
O principal tópico deste capítulo é o comando +if+, que executa diferentes códigos dependendo do estado do programa. Mas antes vamos introduzir dois novos operadores: divisão inteira e módulo.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +O operador de _Divisão Inteira_, +÷+ (*+\div TAB+*), divide dois números e arredonda pra baixo para um inteiro. Por exemplo, suponha que o tempo de duração de um filme seja de 105 minutos. Você talve
```suggestion
O operador de _divisão inteira_, +÷+ (*+\div TAB+*), divide dois números e arredonda pra baixo para um inteiro. Por exemplo, suponha que o tempo de duração de um filme seja de 105 minutos. Você talvez queira saber o quanto isso equivale em horas. A divisão convencional retorna um número em ponto-flutuante:
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
Passaram essas linhas acima e não consigo commitar direto.

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +O operador módulo é mais útil do que parece. Por exemplo, você pode verificar se um número é divisível por outro — se +x % y+ é zero, então +x+ é divisível por +y+.
```suggestion
O operador módulo é mais útil do que parece. Por exemplo, você pode verificar se um número é divisível por outro—se +x % y+ é zero, então +x+ é divisível por +y+.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Uma _expressão booleana_ é uma expressão que é ou verdadeira ou falsa.  Os seguintes exemplos usam o operador +==+, que compara dois operandos e gera +true+ se forem iguais e +false+ footnote:[_True_
```suggestion
Uma _expressão booleana_ é uma expressão que é ou verdadeira ou falsa.  Os seguintes exemplos usam o operador +==+, que compara dois operandos e gera +true+ se forem iguais e +false+--do inglês, verdadeiro e falso.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Embora essas operações sejam provavelmente familiares para você, os símbolos Julia são diferentes dos símbolos matemáticos. Um erro comum é usar um único sinal de igual (+=+) em vez de um duplo sinal
```suggestion
Embora essas operações sejam provavelmente familiares para você, os símbolos em Julia são diferentes dos símbolos matemáticos. Um erro comum é usar um único sinal de igual (+=+) em vez de um duplo sinal de igual (+==+). Lembre-se de que +=+ é um operador de atribuição e +==+ é um operador relacional. Não existe +=<+ ou +pass:[=>]+.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Existem três _Operadores Lógicos_: +&&+ (e), +||+ (ou) e +!+ (não). A semântica (significado) destes operadores são similiares aos seus significados em Português. Por exemplo, +x > 0 && x < 10+ é ver
```suggestion
Existem três _operadores lógicos_: +&&+ (e), +||+ (ou) e +!+ (não). A semântica (significado) destes operadores são similiares aos seus significados em Português. Por exemplo, +x > 0 && x < 10+ é verdadeiro se e somente se +x+ é maior que 0 _e_ menor que +10+.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Para escrever programas úteis, quase sempre precisamos verificar as condições e alterar o comportamento de acordo com o programa. _Declarações Condicionais_ nos fornecem essa habilidade. A forma mais
```suggestion
Para escrever programas úteis, quase sempre precisamos verificar as condições e alterar o comportamento de acordo com o programa. _Declarações condicionais_ nos fornecem essa habilidade. A forma mais simples é o comando _if_ (da conjunção se em Inglês).
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +(((atribuição condicional)))(((if)))((("palavra-chave", "se", see="se")))(((atribuição se)))((("atribuição", "se", see="atribuição se")))
```suggestion
(((declaração condicional)))(((if)))((("palavra-chave", "if", see="if")))(((comando if)))((("comando", "if", see="comando if")))
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +A expressão booleana depois de +if+ é chamada de _condição_. Se é verdadeira, então a atribuição indentada é executada. Se não, nada acontece.
```suggestion
A expressão booleana depois de +if+ é chamada de _condição_. Se é verdadeira, então o comando indentado é executado. Se não, nada acontece. 
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +A atribuição _se_ possui a mesma estrutura das definições de funções: Um cabeçalho seguido de um corpo terminado com a palavra-chave _end_. Declarações como essa são chamadas de _declarações composta
```suggestion
Declarações _if_ possuem a mesma estrutura das definições de funções: Um cabeçalho seguido de um corpo terminado com a palavra-chave _end_. Declarações como essa são chamadas de _declarações compostas_.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +    # TODO: precisa lidar com valores negativos!
```suggestion
    # LEMBRETE: precisa lidar com valores negativos!
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Uma segunda maneira de usar a atribuição _se_ é a "execução alternativa", da qual há duas possibilidades e a condição determina qual delas deverá ser executada. A sintaxe é a seguinte:
```suggestion
Uma segunda maneira de usar o comando _if_ é a "execução alternativa", da qual há duas possibilidades e a condição determina qual delas deverá ser executada. A sintaxe é a seguinte:
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +(((execução alternativa)))(((se não)))((("palavra-chave", "se não", see="se não")))
```suggestion
(((execução alternativa)))(((else)))((("palavra-chave", "else", see="else")))
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
>  end
Mudar `draw` para `desenha`.

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +O condicional externo contém dois ramos. O primeiro ramo contém uma atribuição simples. O segundo ramo contém outra atribuição +if+, da qual possui dois ramos inserida nela. Esses dois ramos são decl
```suggestion
O condicional externo contém dois ramos. O primeiro ramo contém uma declaração simples. O segundo ramo contém outro condicional +if+, que possui dois ramos inseridos nele. Esses dois ramos são declarações simples, embora também possam ter sido declarações condicionais.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +A atribuição +print+ executa somente se passarmos pelos dois condicionais, para que possamos obter o mesmo efeito com operador +&&+:
```suggestion
O comando +print+ executa somente se passarmos pelos dois condicionais, para que possamos obter o mesmo efeito com operador +&&+:
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Se +n+ é 0 ou negativo, será exibido a palavra, +"Vai!"+, por outro lado, exibirá +n+ e executará a função chamada +contagem_regressiva+ — ela mesma — passando +n-1+ como argumento.
```suggestion
Se +n+ é 0 ou negativo, será exibido a palavra +"Vai!"+. Caso contrário, a função exibe +n+ e chama uma função chamada +contagem_regressiva+—ela mesma— passando +n-1+ como argumento.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +A execução de +contagem_regressiva+ começa com +n = 3+, e desde que +n+ seja maior que 0, terá como saída o valor 3, e depois executa ela mesma...
```suggestion
A execução de +contagem_regressiva+ começa com +n = 3+, e como +n+ é maior que 0, terá como saída o valor 3, e depois executa ela mesma...
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +pass:[&#8193;]A execução de +contagem_regressiva+ começa com +n = 2+, e desde que +n+ seja maior que 0, pass:[<br/>&#8193;&#8193;]terá como saída o valor 2, e depois executa ela mesma ...
```suggestion
pass:[&#8193;]A execução de +contagem_regressiva+ começa com +n = 2+, e como +n+ é maior que 0, pass:[<br/>&#8193;&#8193;]terá como saída o valor 2, e depois executa ela mesma ...
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +pass:[&#8193;&#8193;]A execução de +contagem_regressiva+ começa com +n = 1+, e desde que +n+ seja maior que 0, pass:[<br/>&#8193;&#8193;&#8193;]terá como saída o valor 1, e depois executa ela mesma .
```suggestion
pass:[&#8193;&#8193;]A execução de +contagem_regressiva+ começa com +n = 1+, e como  +n+ é maior que 0, pass:[<br/>&#8193;&#8193;&#8193;]terá como saída o valor 1, e depois executa ela mesma ...
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +pass:[&#8193;&#8193;&#8193;]A execução de +contagem_regressiva+ começa com +n = 0+, e desde que +n+ seja maior que pass:[<br/>&#8193;&#8193;&#8193;&#8193;]0, terá como saída uma palavra, +"Vai!"+ e d
```suggestion
pass:[&#8193;&#8193;&#8193;]A execução de +contagem_regressiva+ começa com +n = 0+, e como +n+ não é maior que pass:[<br/>&#8193;&#8193;&#8193;&#8193;]0, terá como saída uma palavra, +"Vai!"+ e depois retorna.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
>  ----
printn -> imprima_n

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Se +n pass:[&lt;]= 0+ a atribuição +return+ sai da função. O fluxo de execução retorna imediatamente para quem a chamou e as linhas restantes da função não são executadas.
```suggestion
Se +n pass:[&lt;]= 0+ o comando +return+ sai da função. O fluxo de execução retorna imediatamente para quem a chamou e as linhas restantes da função não são executadas.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +=== Diagramas de Pilhas para funções recursivas
```suggestion
=== Diagramas de Pilhas para Funções Recursivas
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Os quatro quadros de +contagem_regressiva+ tem valores diferentes para o parâmetro +n+. A parte inferior da pilha, onde +n=0+, é chamada de _caso base_. Ele não faz uma chamada recursiva, portanto nã
```suggestion
Os quatro quadros de +contagem_regressiva+ têm valores diferentes para o parâmetro +n+. A parte inferior da pilha, onde +n=0+, é chamada de _caso base_. Ele não faz uma chamada recursiva, portanto não há mais quadros.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Como exercício, desenhe um diagrama de pilha para +printn+ chamado com +s = "Olá"+ e +n = 2+. Depois, escreva uma função chamada +faça_n+ que pega um objeto de função e um número, +n+, como argumento
```suggestion
Como exercício, desenhe um diagrama de pilha para +imprima_n+ chamado com +s = "Olá"+ e +n = 2+. Depois, escreva uma função chamada +faça_n+ que pega um objeto de função e um número, +n+, como argumento, e que chama a função dada latexmath:[\(n\)] vezes.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Um ponto e vírgula +;+ permite colocar multiplas atribuições na mesma linha. No REPL apenas a última atribuição retornará seu valor.
```suggestion
Um ponto e vírgula +;+ permite colocar múltiplos comandos na mesma linha. No REPL apenas o último comando retornará seu valor.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Qual é a velocidade da velocidade do ar de uma andorinha sem carga?
```suggestion
julia> println("Qual é a velocidade de vôo de uma andorinha sem carga?"); velocidade = readline()
Qual é a velocidade de vôo de uma andorinha sem carga?
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +"Como assim, uma andorinha africana ou européia?"
```suggestion
julia> println("Qual é a velocidade de vôo de uma andorinha sem carga?"); velocidade = readline()
Qual é a velocidade de vôo de uma andorinha sem carga?
Como assim, uma andorinha africana ou européia?
"Como assim, uma andorinha africana ou européia?"
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Os erros de sintaxe geralmente são fáceis de encontrar, mas existem algumas dicas. Em geral, as mensagens de erro indicam onde o problema foi descoberto, mas o verdadeiro erro pode estar antes no cód
```suggestion
Os erros de sintaxe geralmente são fáceis de encontrar, mas existem algumas ressalvas. Em geral, as mensagens de erro indicam onde o problema foi descoberto, mas o verdadeiro erro pode estar antes no código, às vezes em uma linha anterior.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Para encontrar o erro, pode ser útil imprimir o valor da razão, que acaba sendo 0. O problema está na linha 3, que usa a Divisão do piso em vez da Divisão do ponto flutuante.
```suggestion
Para encontrar o erro, pode ser útil imprimir o valor da razão, que acaba sendo 0. O problema está na linha 3, que usa a divisão do piso em vez da divisão do ponto flutuante.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Divisão Inteira::
```suggestion
divisão inteira::
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +(((Divisão Inteira)))
```suggestion
(((divisão inteira)))
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +atribuição condicional::
```suggestion
declaração condicional::
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Uma atribuição que controla o fluxo de execução dependendo de alguma condição.
```suggestion
Uma declaração que controla o fluxo de execução dependendo de alguma condição.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +(((atribuição condicional)))
```suggestion
(((declaração condicional)))
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +A expressão boleana em uma atribuição condicional que determina qual ramo executará.
```suggestion
A expressão boleana em uma declaração condicional que determina qual ramo executará.
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +(((atribuição composta)))
```suggestion
declaração composta::
Uma declaração que consiste em um cabeçalho e um corpo. O corpo é terminado com a palavra-chave +end+.
(((declaração composta)))
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +(((atribuição de retorno)))
Mudas todas essas atribuições

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +(((tempo)))((("função", "Base", "hora", see="hora")))
```suggestion
A função +time+ retorna o tempo médio atual de Greenwich em segundos desde “a época”, que é um tempo arbitrário usado como ponto de referência. Nos sistemas UNIX, a época é 1 de janeiro de 1970.
(((time)))((("função", "Base", "time", see="time")))
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +tempo()
```suggestion
time()
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Se você receber três gravetos, poderá ou não ser capaz de organizá-los em um triângulo. Por exemplo, se um dos gravetos tiver 12 centímetros de comprimento e os outros dois um centímetro, você não co
```suggestion
Se você receber três gravetos, poderá ou não ser capaz de organizá-los em um triângulo. Por exemplo, se um dos gravetos tiver 12 centímetros de comprimento e os outros dois um centímetro, você não conseguirá fazer com que os gravetos curtos se toquem no meio. Para três comprimentos, há um teste simples para verificar se é possível formar um triângulo:
```

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
>      turn(t, 2*angle)
!

2020-05-30 17:46 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +. A curva de Koch pode ser generalizada de várias maneiras. Veja https://en.wikipedia.org/wiki/Koch_snowflake para exemplos e implemente o seu favorito.
```suggestion
. A curva de Koch pode ser generalizada de várias maneiras. Veja https://en.wikipedia.org/wiki/Koch_snowflake para exemplos e implemente o seu favorito.

```

2020-05-30 18:38 UTC, gustavosarturi commented
5465e7 - Não revisar, ainda. Revisando código.

2020-06-05 16:02 UTC, abelsiqueira requested changes
Gustavo, não mexa ainda.

2020-06-05 16:02 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +O principal tópico deste capítulo é o comando +if+, que executa diferentes códigos dependendo do estado do programa. Mas antes gostaria de introduzir dois novos operadores: divisão inteira e módulo.
```suggestion
O principal tópico deste capítulo é o comando +if+, que executa diferentes códigos dependendo do estado do programa. Mas antes gostaríamos de introduzir dois novos operadores: divisão inteira e módulo.
```

2020-06-05 16:02 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +O operador de _divisão inteira_, +÷+ (*+\div TAB+*), divide dois números e arredonda pra baixo para um inteiro. Por exemplo, suponha que o tempo de duração de um filme seja de 105 minutos. Talvez voc
```suggestion
O operador de _divisão inteira_, +÷+ (*+\div TAB+*), divide dois números e arredonda pra baixo para um inteiro. Por exemplo, suponha que o tempo de duração de um filme seja de 105 minutos. Talvez você queira saber o quanto isso equivale em horas. A divisão convencional retorna um número em ponto-flutuante:
```

2020-06-05 16:02 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +Para escrever bons programas, quase sempre precisamos verificar as condições e alterar o comportamento de acordo com o programa. _Comandos condicionais_ nos fornecem essa habilidade. A forma mais sim
```suggestion
Para escrever programas úteis, quase sempre precisamos verificar as condições e alterar o comportamento de acordo com o programa. _Comandos condicionais_ nos fornecem essa habilidade. A forma mais simples é o comando _if_ (da conjunção se em Inglês).
```

2020-06-05 16:02 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +É possível fazer com que uma função chame outra; também é possível uma função chamar si mesma. Pode não parecer óbvio por que isso é uma coisa boa, mas acaba sendo uma das coisas mais mágicas que um
```suggestion
É possível fazer com que uma função chame outra; também é possível uma função chamar a si mesma. Pode não parecer óbvio por que isso é uma coisa boa, mas acaba sendo uma das coisas mais mágicas que um programa pode fazer. Por exemplo, observe a seguinte função:
```

2020-06-05 16:02 UTC, abelsiqueira commented on book/src/chap05.asciidoc
>  ----
Linha 299!

2020-06-05 16:02 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +O Julia fornece uma função interna chamada +readline+ que interrompe o programa e aguarda o usuário digitar algo. Quando o usuário pressiona +return+ ou +ENTER+, o programa é retomado e +readline+ re
```suggestion
O Julia fornece uma função interna chamada +readline+ que interrompe o programa e aguarda o usuário digitar algo. Quando o usuário pressiona +RETURN+ ou +ENTER+, o programa é retomado e +readline+ retorna o que o usuário digitou como uma sequência de caracteres.
```

2020-06-05 16:02 UTC, abelsiqueira commented on book/src/chap05.asciidoc
> +    avance(t, -comprimento*n)
```suggestion
    ângulo = 50
    forward(t, comprimento*n)
    turn(t, -ângulo)
    draw(t, comprimento, n-1)
    turn(t, 2*angle)
    draw(t, comprimento, n-1)
    turn(t, -ângulo)
    forward(t, -comprimento*n)
```

2020-06-05 16:27 UTC, merged