Translation of chapter 6 finished
JuliaIntro/JuliaIntroBR.jl pull request #12
Opened 2020-05-02 00:13 UTC by chunggnuhc

2020-05-02 18:24 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +== Funções produtivas
Camel Case: "Funções Produtivas"

2020-05-02 18:34 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +=== Valores de retorno
Camel Case

2020-05-02 18:43 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Já vimos a declaração +return+ anteriormente, mas em uma função produtiva a declaração +retorno+ inclui uma expressão. Esta declaração significa: "Retorne imediatamente a partir desta função e leve a
Sugestão, em "Como **_esta_** expressão pode ser arbitrariamente complicada, então poderíamos ter escrito uma função mais sucinta:" trocar "esta" por "esta".
Esta --> Pra quando o objeto será referido,
Essa --> Quando o objeto já foi referido.

2020-05-02 18:51 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Além disso, _variáveis temporárias_ como +var_área+ e as intruções explícitas +return+ podem contribuir para a depuração.
Depuração = Debugação (?)

2020-05-02 18:54 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +E já que estas instruções de retorno estão em uma alternativa condicional, somente uma é executada.
E já que estas instruções de retorno estão em uma **_condicional alternativa_**, somente uma é executada.

2020-05-02 18:55 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Assim que um comando +return+ é executado, a função termina sem executar qualquer comando posterior. O código que aparece após um comando +return+, ou qualquer outro lugar que o fluxo de execução não
O código que aparece após um comando +return+, ou qualquer outro lugar que o fluxo de execução **_nunca possa alcançar_**.

2020-05-02 18:57 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Esta função está incorreta porque se +x+ for 0, nenhuma das condições é verdadeira, e a função termina sem chegar a um comando de +retorno+. Quando o fluxo de execução chegar ao final de uma função,
**_Essa_** função está incorreta

2020-05-02 18:57 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Esta função está incorreta porque se +x+ for 0, nenhuma das condições é verdadeira, e a função termina sem chegar a um comando de +retorno+. Quando o fluxo de execução chegar ao final de uma função,
**_Essa_** função está incorreta

2020-05-02 18:59 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Esta função está incorreta porque se +x+ for 0, nenhuma das condições é verdadeira, e a função termina sem chegar a um comando de +retorno+. Quando o fluxo de execução chegar ao final de uma função,
Quando o fluxo de execução **_chega_** ao final de uma função, o valor de retorno é +nothing+, que não é o valor absoluto de 0.

2020-05-02 19:00 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Julia tem uma função interna chamada +abs+ que calcula valores absolutos.
"Julia **_possui_** uma função interna chamada"

2020-05-02 19:02 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +=== Desenvolvimento incremental
Camel Case

2020-05-02 19:06 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Ao lidar com programas cada vez mais complexos, tente um processo chamado _desenvolvimento incremental_, que adiciona e testa apenas uma pequena quantidade de código por vez, evitando assim longas se
evitando assim longas **_seções_** de debugging.

Seções = Corte
Sessão = Espaço de tempo. Ex.:Cinema

2020-05-02 19:08 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Para exemplificar este processo, suponha que você queira determinar a distância entre dois pontos, dada pelas coordenadas latexmath:[\(\left(x_1, y_1\right)\)] e latexmath:[\(\left(x_2, y_2\right)\)]
Para exemplificar **_esse_** processo

2020-05-02 19:17 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Obviamente que esta versão não determina as distâncias pois ela sempre retorna zero. Mas é sintaticamente correta, e roda, o que significa que você pode testá-la antes de complicá-la. Os números dos
**_Obviamente, essa_** versão não determina as distâncias pois ela sempre retorna zero.

2020-05-02 21:49 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Escolhi estes valores para que a distância horizontal seja 3 e a vertical seja 4; logo, o resultado é 5 porque é a hipotenusa de um triângulo retângulo 3-4-5. Quando testar uma função, o aconselhável
"**_Escolhi esses valores_** para que a distância"

2020-05-02 21:52 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Você executaria o programa mais uma vez nesse estágio e verificaria a saída (que deveria ser 25). Números sobrescritos também estão disponíveis (*+\^2 TAB+*). Por fim, usa-se +sqrt+ no calcular e ret
Faltou traduzir "Again" para "Novamente"

2020-05-02 21:53 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +A versão final da função não exibe nada quando é executada, retornando apenas um valor. As instruções de impressão que escrevemos são úteis para o debugging, mas depois que a função estiver funcionan
"que escrevemos são úteis para **_debugar_**,"

2020-05-02 21:54 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Ao iniciar, você deve adicionar apenas uma ou duas linhas de código por vez. À medida que você ganha mais experiência, pode se escrever e debugar pedaços maiores. De qualquer forma, o desenvolvimento
"muito tempo de **_debug_**"

2020-05-02 21:56 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +. Comece com um programa funcional e faça pequenas alterações incrementais. A qualquer momento, se houver um erro, você deverá ter uma boa idéia de onde ele está.
"ter uma boa **_ideia_** de onde ele está"

2020-05-02 21:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Como já esperado, você pode chamar uma função de dentro da outra. Para exemplificar isto, escreveremos uma função que calcula a área do círculo a partir de dois pontos, o centro do círculo e um ponto
"Para exemplificar **_isso_**"

Isto - O que vai ser mencionado
Isso - Já mencionado anteriormente

2020-05-02 22:00 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Suponha que o ponto central é indicado pelas variáveis +xc+ e +yc+, e o ponto de perímetro indicado por +xp+ e +yp+. O primeiro passo é encontrar o raio do círculo, dado pela distância entre estes do
"Suponha que o ponto central é indicado pelas variáveis +xc+ e +yc+, e **_que o_** ponto de perímetro **_é_** indicado por +xp+ e +yp+."

2020-05-02 22:03 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +=== Funções booleanas
Camel Case

2020-05-02 22:04 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +As funções podem retornar variáveis booleanas, o que muitas vezes é conveniente para ocultar testes complicados dentro de funções. Por exemplo:
"As funções podem retornar **_valores_** booleanas"

2020-05-02 22:10 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Esta definição diz que o fatorial de 0 é 1, e o fatorial de qualquer outro valor latexmath:[n] é latexmath:[n] multiplicado pelo fatorial de latexmath:[n-1]].
"**_Essa_** definição "

2020-05-02 22:13 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Se puder escrever uma definição recursiva de algo, pode-se escrever um programa em Julia para testá-la. A primeiro etapa é decidir quais devem ser os parâmetros. E neste caso, é evidente que o fatori
" E **_nesse_** caso,"

2020-05-02 22:16 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +O valor de retorno +2+ é multiplicado por +n+ (que é +3+), e o resultado (= +6+), torna-se o valor de retorno da chamada da função que iniciou todo esse processo.
"O valor de retorno, **_(= +2+)_**," para manter o mesmo padrão acima

2020-05-02 22:17 UTC, gustavosarturi commented on book/src/chap06.asciidoc
>  .Stack diagram
Traduzir para "Diagrama de Pilha"

2020-05-02 22:17 UTC, gustavosarturi commented on book/src/chap06.asciidoc
>  .Stack diagram
Traduzir para "Diagrama de Pilha"

2020-05-02 22:20 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((factorial)))((("função", "Base", "factorial", see="factorial")))
Traduzir "factorial"

2020-05-02 22:21 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +=== Salto de fé
Camel Case

2020-05-02 22:22 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +A mesma prática ocorre quando você chama uma de suas próprias funções. Por exemplo, em <<funções booleanas>>, escrevemos a função +é_divisível+ que determina se um número é divisível por outro. Depoi
Camel Case em "funções booleanas"

2020-05-03 02:23 UTC, chunggnuhc commented on book/src/chap06.asciidoc
> +=== Valores de retorno
Modified.

2020-05-03 02:26 UTC, chunggnuhc commented on book/src/chap06.asciidoc
> +Já vimos a declaração +return+ anteriormente, mas em uma função produtiva a declaração +retorno+ inclui uma expressão. Esta declaração significa: "Retorne imediatamente a partir desta função e leve a
Modified.

2020-05-03 02:26 UTC, chunggnuhc commented on book/src/chap06.asciidoc
> +Além disso, _variáveis temporárias_ como +var_área+ e as intruções explícitas +return+ podem contribuir para a depuração.
Modified.

2020-05-03 03:05 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +=== Verificação de tipos
Camel Case

2020-05-03 03:06 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Enquanto o primeiro caso-base aborda os não-inteiros; o segundo aborda os inteiros negativos. Para estes dois casos, o programa exibe uma mensagem de erro e devolve +nothing+ para indicar que algo de
"Para **_esses_** dois casos"

2020-05-03 03:08 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Este programa demonstra um padrão às vezes de _guardião_. Os dois primeiros condicionais atuam como guardiões, protegendo o código de valores que podem causar um erro. Além disso, os guardiões tornam
"**_Esse_** programa demonstra um padrão..."

2020-05-03 03:10 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Veja a função Ackermann, latexmath:[\(A(m, n)\)], definida como:
"Função **_de_** Ackermann"

2020-05-03 03:11 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Consulte https://pt.wikipedia.org/wiki/Fun%C3%A7%C3%A3o_de_Ackermann. Escreva uma função chamada +ack+ que calcula a função Ackermann. Use sua função para avaliar +ack(3, 4)+, que é 125. O que ocorre
"Função **_de_** Ackermann"

2020-05-03 03:12 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +Escreva a função +mdc+ que recebe os parâmetros +a+ e +b+ e retorna o máximo divisor comum.
"Máximo Divisor Comum" em Camel Case

2020-05-03 03:13 UTC, gustavosarturi requested changes
Well done :)

2020-05-06 19:48 UTC, gustavosarturi requested changes

2020-05-06 19:48 UTC, gustavosarturi commented on book/src/chap06.asciidoc
>  [[chap06]]
Fiz comentários no Código.

2020-05-19 01:55 UTC, gustavosarturi commented on book/src/chap06.asciidoc
>  Ao lidar com programas cada vez mais complexos, tente um processo chamado _desenvolvimento incremental_, que adiciona e testa apenas uma pequena quantidade de código por vez, evitando assim longas se
Em "_desenvolvimento incremental_" talvez deixar em Camel Case também

2020-05-19 02:02 UTC, gustavosarturi requested changes

2020-05-19 02:02 UTC, gustavosarturi commented on book/src/chap06.asciidoc
>  Ao lidar com programas cada vez mais complexos, tente um processo chamado _desenvolvimento incremental_, que adiciona e testa apenas uma pequena quantidade de código por vez, evitando assim longas se
Em "_desenvolvimento incremental_" talvez deixar em Camel Case também

2020-05-19 02:02 UTC, gustavosarturi commented on book/src/chap06.asciidoc
>  Ler programas seguindo o fluxo de execução pode se tornar rapidamente exaustivo. Uma alternativa que eu chamo de "salto de fé" faz a leitura conforme o fluxo de execução e quando se chega a uma chama
Deixar em itálico em "_assume-se_"

2020-05-19 02:02 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +A mesma prática ocorre quando você chama uma de suas próprias funções. Por exemplo, em <<boolean_functions>>, escrevemos a função +é_divisível+ que determina se um número é divisível por outro. Depoi
O que está em << >> não deveria ser traduzido?
Vou dar um double check na lista do Chris.

2020-05-19 02:02 UTC, gustavosarturi commented on book/src/chap06.asciidoc
>  Em <<catching_exceptions>>, veremos uma alternativa mais flexível para mostrar uma mensagem de erro: levantando uma exceção.
Traduzir o que está entre << >>, talvez para "Capturando Exceções". Tem que ver em qual capítulo isso deve aparecer.

2020-05-19 19:42 UTC, chunggnuhc commented on book/src/chap06.asciidoc
>  Ao lidar com programas cada vez mais complexos, tente um processo chamado _desenvolvimento incremental_, que adiciona e testa apenas uma pequena quantidade de código por vez, evitando assim longas se
Fiz a alteração. Mas a versão em inglês não está em camel case, nem a versão da tradução em espanhol (Piense en Julia) e nem o Pense em Python.

2020-05-19 19:42 UTC, chunggnuhc commented on book/src/chap06.asciidoc
> +A mesma prática ocorre quando você chama uma de suas próprias funções. Por exemplo, em <<boolean_functions>>, escrevemos a função +é_divisível+ que determina se um número é divisível por outro. Depoi
Eu segui o que a tradução em espanhol fez e eles não traduzem as referências em << >>.

2020-05-19 19:42 UTC, chunggnuhc commented on book/src/chap06.asciidoc
>  Em <<catching_exceptions>>, veremos uma alternativa mais flexível para mostrar uma mensagem de erro: levantando uma exceção.
Eu segui o que a tradução em espanhol fez e eles não traduzem as referências em << >>.

2020-05-31 14:20 UTC, abelsiqueira requested changes

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +    return var_área
```suggestion
function área(raio)
    a = π * raio^2
    return a
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Além disso, _variáveis temporárias_ como +var_área+ e as intruções explícitas +return+ podem contribuir para o debugging.
```suggestion
Além disso, _variáveis temporárias_ como +a+ e as instruções explícitas +return+ podem contribuir para o debugging.
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Essa função está incorreta porque se +x+ for 0, nenhuma das condições é verdadeira, e a função termina sem chegar a um comando de +retorno+. Quando o fluxo de execução chega ao final de uma função, o
```suggestion
Essa função está incorreta porque se +x+ for 0, nenhuma das condições é verdadeira, e a função termina sem chegar a um comando de +return+. Quando o fluxo de execução chega ao final de uma função, o valor de retorno é +nothing+, que não é o valor absoluto de 0.
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Ao lidar com programas cada vez mais complexos, tente um processo chamado _Desenvolvimento Incremental_, que adiciona e testa apenas uma pequena quantidade de código por vez, evitando assim longas se
```suggestion
Ao lidar com programas cada vez mais complexos, tente um processo chamado _desenvolvimento incremental_, que adiciona e testa apenas uma pequena quantidade de código por vez, evitando assim longas sessões de debugging.
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +O primeiro passo é avaliar como deve ser uma função de distância em Julia. Em outras palavras, quais são as entradas (os parâmetros) e qual é a saída (o valor de retorno)?
```suggestion
O primeiro passo é avaliar como deve ser uma função de distância em Julia. Em outras palavras, quais são as entradas (parâmetros) e qual é a saída (valor de retorno)?
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +(((caracter Unicode)))
```suggestion
(((caractere Unicode)))
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Escolhi estes valores para que a distância horizontal seja 3 e a vertical seja 4; logo, o resultado é 5 porque é a hipotenusa de um triângulo retângulo 3-4-5. Quando testar uma função, o aconselhável
```suggestion
Escolhemos estes valores para que a distância horizontal seja 3 e a vertical seja 4; logo, o resultado é 5 porque é a hipotenusa de um triângulo retângulo 3-4-5. Quando testar uma função, o aconselhável é já saber a resposta correta.
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Você executaria o programa mais uma vez nesse estágio e verificaria a saída (que deveria ser 25). Números sobrescritos também estão disponíveis (*+\^2 TAB+*). Por fim, usa-se +sqrt+ no calcular e ret
```suggestion
Você executaria o programa mais uma vez nesse estágio e verificaria a saída (que deveria ser 25). Números sobrescritos também estão disponíveis (*+\^2 TAB+*). Por fim, usa-se +sqrt+ para calcular e retornar o resultado final:
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +(((recursão))) (((linguagem de programação completa))) ((("linguagem de programação", "completa", veja = "linguagem de programação completa"))))
```suggestion
(((recursão)))(((linguagem de programação completa)))((("linguagem de programação", "completa", see="linguagem de programação completa")))
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Essa definição diz que o fatorial de 0 é 1, e o fatorial de qualquer outro valor latexmath:[n] é latexmath:[n] multiplicado pelo fatorial de latexmath:[n-1]].
```suggestion
Essa definição diz que o fatorial de 0 é 1, e o fatorial de qualquer outro valor latexmath:[\(n\)] é latexmath:[\(n\)] multiplicado pelo fatorial de latexmath:[\(n-1\)].
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Se puder escrever uma definição recursiva de algo, pode-se escrever um programa em Julia para testá-la. A primeiro etapa é decidir quais devem ser os parâmetros. E nesse caso, é evidente que o fatori
```suggestion
Se puder escrever uma definição recursiva de algo, pode-se escrever um programa em Julia para testá-la. A primeira etapa é decidir quais devem ser os parâmetros. E nesse caso, é evidente que o fatorial recebe um número inteiro:
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Então latexmath:[\(3!\)] é 3 vezes latexmath:[\(2!\)], que é 2 vezes latexmath:[\(1!\)], que é 1 vezes latexmath:[\(0!\)]. Colocando tudo junto, látexmath:[\(3!\)] é igual a 3 vezes 2 vezes 1 vezes 1
```suggestion
Então latexmath:[\(3!\)] é 3 vezes latexmath:[\(2!\)], que é 2 vezes latexmath:[\(1!\)], que é 1 vezes latexmath:[\(0!\)]. Colocando tudo junto, latexmath:[\(3!\)] é igual a 3 vezes 2 vezes 1 vezes 1, que dá 6.
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +(((função de fibonacci)))
```suggestion
Após fatorial, o exemplo mais familiar de uma função matemática definida recursivamente é a sequência de Fibonacci, cuja definição é (consulte https://pt.wikipedia.org/wiki/Sequência_de_Fibonacci):
(((função de Fibonacci)))
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Se tentar acompanhar o fluxo de execução aqui, mesmo para valores razoavelmente pequenos de +n+, sua cabeça vai enlouquecer. No entanto, de acordo com o salto de fé, se presumir que as duas chamadas
```suggestion
Se você tentar acompanhar o fluxo de execução aqui, mesmo para valores razoavelmente pequenos de +n+, sua cabeça vai enlouquecer. No entanto, de acordo com o salto de fé, se presumir que as duas chamadas recursivas funcionam sem erros, fica nítido que o resultado certo é obtido a partir da soma delas.
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +O que ocorre se chamarmos +fatorial+ e atribuirmos +1,5+ como argumento?
```suggestion
O que ocorre se chamarmos +fatorial+ e atribuirmos +1.5+ como argumento?
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Na primeira chamada recursiva, o valor de +n+ é +0,5+. No próximo, é +-0,5+. A partir daí, vai diminuindo e ficando cada vez mais negativo, mas nunca será +0+.
```suggestion
Na primeira chamada recursiva, o valor de +n+ é +0.5+. No próximo, é +-0.5+. A partir daí, vai diminuindo e ficando cada vez mais negativo, mas nunca será +0+.
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Um número, latexmath:[\(a\)], é dita uma potência do latexmath:[\(b\)] se for divisível por latexmath:[\(b\)] e latexmath:[\(\frac{a}{b}\)] é uma potência do latexmath:[\(b\)]. Escreva uma função cha
```suggestion
Um número, latexmath:[\(a\)], é dito uma potência de latexmath:[\(b\)] se for divisível por latexmath:[\(b\)] e latexmath:[\(\frac{a}{b}\)] for potência de latexmath:[\(b\)]. Escreva uma função chamada +é_potência+ que dados os parâmetros +a+ e +b+ devolve +true+ se +a+ for uma potência de +b+.
```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +Crédito: Este exercício é baseado em um exemplo do livro _Structure and Interpretation of Computer Programs_ de Abelson e Sussman.
```suggestion
Crédito: Este exercício é baseado em um exemplo do livro _Structure and Interpretation of Computer Programs_ de Abelson e Sussman.

```

2020-05-31 14:20 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +O fluxo de execução deste programa é similar ao fluxo de +contagem regressiva+ em <<recursão>>. Chamando +fatorial+ do valor +3+:
```suggestion
O fluxo de execução deste programa é similar ao fluxo de +contagem regressiva+ em <<recursion>>. Chamando +fatorial+ do valor +3+:
```

2020-06-04 00:41 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +As funções escritas até o momento são nulas, que significa que elas não têm valor de retorno; mais precisamente, seu valor de retorno é +nothing+. Neste capítulo, (finalmente) vamos escrever funções
```suggestion
As funções escritas até o momento são nulas, o que significa que elas não têm valor de retorno; mais precisamente, seu valor de retorno é +nothing+. Neste capítulo, (finalmente) vamos escrever funções produtivas. O primeiro exemplo é a função +área+, que retorna a área de um círculo dado um raio:
```

2020-06-04 00:58 UTC, gustavosarturi requested changes
**Sugestão:** Dar um [CTRL] + [F] em "((((", "))))" e substituir por "(((" e ")))" caso tenha passado despercebido.

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +As funções escritas até o momento são nulas, que significa que elas não têm valor de retorno; mais precisamente, seu valor de retorno é +nothing+. Neste capítulo, (finalmente) vamos escrever funções
Talvez o artigo "o" se encaixe bem

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((função booleana))) (((é_divisível))) ((("função", "definido pelo programador", "é_divisível", consulte = "é_divisível")))
```suggestion
(((função booleana)))(((é_divisível)))((("função", "definido pelo programador", "é_divisível", see="é_divisível")))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((mdc))) ((("função", "definido pelo programador", "mdc", consulte = "mdc"))))
```suggestion
(((mdc)))((("função", "definido pelo programador", "mdc", see="mdc")))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((Turing, Alan))) (((tese de Turing))))
```suggestion
(((Turing, Alan)))(((tese de Turing)))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((definição recursiva))) (((definição circular))))
```suggestion
(((definição recursiva)))(((definição circular)))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((fatorial))) (((("função", "definido pelo programador", "fatorial", see="fatorial"))))
```suggestion
(((fatorial)))((("função", "definido pelo programador", "fatorial", see="fatorial")))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((fatorial))) (((("função", "definido pelo programador", "fatorial", see="fatorial"))))
Tem um parênteses a mais.

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((fib))) (((("função", "definido pelo programador", "fib", see="fib"))))
```suggestion
(((fib)))((("função", "definido pelo programador", "fib", see="fib")))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((é_potência))) ((((função "," definido pelo programador ","é_potência", see="é_potência"))))
```suggestion
(((é_potência)))((("função", "definido pelo programador","é_potência", see="é_potência")))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +(((distância))) (((("função", "definido pelo programador", "distância", see="distância"))))
```suggestion
(((distância)))((("função", "definido pelo programador", "distância", see="distância")))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +((((andaime)))
```suggestion
(((andaime)))
```

2020-06-04 00:58 UTC, gustavosarturi commented on book/src/chap06.asciidoc
> +((((ack)))((("função", "definido pelo programador", "ack", see="ack")))
```suggestion
(((ack)))((("função", "definido pelo programador", "ack", see="ack")))
```

2020-06-04 02:47 UTC, chunggnuhc commented on book/src/chap06.asciidoc
> +Essa função está incorreta porque se +x+ for 0, nenhuma das condições é verdadeira, e a função termina sem chegar a um comando de +retorno+. Quando o fluxo de execução chega ao final de uma função, o
```suggestion
Essa função está incorreta porque se +x+ for 0, nenhuma das condições é verdadeira, e a função termina sem chegar a um comando +return+. Quando o fluxo de execução chega ao final de uma função, o valor de retorno é +nothing+, que não é o valor absoluto de 0.
```

2020-06-04 02:48 UTC, chunggnuhc commented on book/src/chap06.asciidoc
> +O primeiro passo é avaliar como deve ser uma função de distância em Julia. Em outras palavras, quais são as entradas (os parâmetros) e qual é a saída (o valor de retorno)?
Ocultar os artigos é anglicismo.

2020-06-04 02:57 UTC, abelsiqueira commented on book/src/chap06.asciidoc
> +O primeiro passo é avaliar como deve ser uma função de distância em Julia. Em outras palavras, quais são as entradas (os parâmetros) e qual é a saída (o valor de retorno)?
:+1:

2020-06-04 02:58 UTC, merged