Chapter 12 PTBR
JuliaIntro/JuliaIntroBR.jl pull request #16
Opened 2020-05-11 22:19 UTC by chunggnuhc

2020-05-22 17:09 UTC, abelsiqueira requested changes
Mudança de exemplo

2020-05-22 17:09 UTC, abelsiqueira commented on book/src/chap12.asciidoc
> +//====
```suggestion




```

2020-05-22 17:09 UTC, abelsiqueira commented on book/src/chap12.asciidoc
> +Para criar uma tupla com um único elemento, tem que inserir uma vírgula final:
```suggestion
Para criar uma tupla com um único elemento, tem que inserir uma vírgula no final:
```

2020-06-05 05:03 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +(((vírgula final)))(((typeof)))(((Tuple)))((("tipo", "Base", "Tuple", see="Tuple")))
```suggestion
(((vírgula no final)))(((typeof)))(((Tuple)))((("tipo", "Base", "Tuple", see="Tuple")))
```

2020-06-06 04:02 UTC, chunggnuhc commented on book/src/chap12.asciidoc
>  === Debugging
```suggestion
=== Depuração
```

2020-06-06 04:03 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +(((debugging)))(((estruturas de dados)))(((erro de forma))))
```suggestion
(((depuração)))(((estruturas de dados)))(((erro de forma))))
```

2020-06-10 21:10 UTC, gustavosarturi requested changes

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Uma tupla é uma sequência de valores. Estes valores podem ser de qualquer tipo e são indexados por números inteiros; logo, neste aspecto, as tuplas são muito similares a arrays. A diferença important
```suggestion
Uma tupla é uma sequência de valores. Estes valores podem ser de qualquer tipo e são indexados por números inteiros; logo, neste aspecto, as tuplas são muito similares às listas. A diferença importante é que as tuplas são imutáveis e que cada elemento pode ter seu próprio tipo.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Geralmente, o lado direito pode ser qualquer tipo de sequência (string, array ou tupla). Por exemplo, ao dividir um endereço de e-mail em um nome de usuário e um domínio, poderia-se escrever:
```suggestion
Geralmente, o lado direito pode ser qualquer tipo de sequência (string, lista ou tupla). Por exemplo, ao dividir um endereço de e-mail em um nome de usuário e um domínio, poderia-se escrever:
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +julia> nome_usuário, domínio = split(email, '@');
```suggestion
julia> email = "julio.cesar@roma"
"julio.cesar@roma"
julia> nome_usuário, domínio = split(email, '@');
```
Não é permitido acentuações em e-mails.

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +O valor de retorno de +split+ é um array com dois elementos; o primeiro elemento é atribuído a +nome_usuário+ e o segundo a +domínio+.
```suggestion
O valor de retorno de +split+ é uma lista com dois elementos; o primeiro elemento é atribuído a +nome_usuário+ e o segundo a +domínio+.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +"júlio.césar"
```suggestion
"julio.cesar"
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +(((divrem)))((("função", "Base", "divrem", see= "divrem")))
```suggestion
(((divrem)))((("função", "Base", "divrem", see="divrem")))
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +(((agrupa)))((((...)))((((printall)))((("função", "definido pelo programador", "printall", see="printall")))
```suggestion
(((agrupa)))(((...)))(((printall)))((("função", "definido pelo programador", "printall", see="printall")))
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +O objeto zip é um tipo de _iterador_, um objeto usado para percorrer uma sequência. De uma certa forma, os iteradores são similares aos arrays, e o que difere dos arrays é que não se pode usar um índ
```suggestion
O objeto zip é um tipo de _iterador_, um objeto usado para percorrer uma sequência. De uma certa forma, os iteradores são similares as listas, e o que difere das listas é que não se pode usar um índice para selecionar um elemento a partir de um iterador.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Se você quiser usar operadores e funções de arrays, pode-se usar um objeto zip para gerar um array:
```suggestion
Se você quiser usar operadores e funções de listas, pode-se usar um objeto zip para gerar uma lista:
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +O resultado é um array de tuplas; e neste exemplo, cada tupla contém um caractere da string e o elemento correspondente do array.
```suggestion
O resultado é uma lista de tuplas; e neste exemplo, cada tupla contém um caractere da string e o elemento correspondente da lista.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +A cada iteração do laço, Julia seleciona a próxima tupla no array e atribui os elementos à letra e ao número. Os parênteses em torno de +(letra, número)+ são necessários.
```suggestion
A cada iteração do laço, o Julia seleciona a próxima tupla na lista e atribui os elementos à letra e ao número. Os parênteses em torno de +(letra, número)+ são necessários.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Indo na outra direção, você pode usar um array de tuplas para inicializar um novo dicionário:
```suggestion
Indo na outra direção, você pode usar uma lista de tuplas para inicializar um novo dicionário:
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Este laço percorre os pares chave-valor em +diretório+, que são tuplas. Ele atribui os elementos da chave em cada tupla +sobrenome+ e +nome+ ao valor em +número+, e então imprime o nome completo e o
```suggestion
Esse laço percorre os pares chave-valor em +diretório+, que são tuplas. Ele atribui os elementos da chave em cada tupla +sobrenome+ e +nome+ ao valor em +número+, e então imprime o nome completo e o número de telefone correspondente.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Existem duas maneiras de representar tuplas em um diagrama de estados. A versão mais detalhada mostra os índices e os elementos exatamente como eles aparecem em um array. Por exemplo, a tupla +("Carl
```suggestion
Existem duas maneiras de representar tuplas em um diagrama de estados. A versão mais detalhada mostra os índices e os elementos exatamente como eles aparecem em uma lista. Por exemplo, a tupla +("Carlos", "João")+ apareceria como no <<fig12-1>>.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Tenho focado em arrays de tuplas, mas quase todos os exemplos neste capítulo também funcionam com arrays de arrays, tuplas de tuplas, e tuplas de arrays. Para evitar listar as possíveis combinações,
```suggestion
Tenho focado em listas de tuplas, mas quase todos os exemplos neste capítulo também funcionam com listas de listas, tuplas de tuplas, e tuplas de listas. Para evitar listar as possíveis combinações, às vezes é mais fácil falar sobre seqüências de seqüências.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +(((seqüência de seqüências)))
```suggestion
(((sequência de sequências)))
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Em muitos contextos, os diferentes tipos de seqüências (strings, arrays e tuplas) podem ser usados de forma intercambiável. Então, como você deve escolher um ao invés dos outros?
```suggestion
Em muitos contextos, os diferentes tipos de sequências (strings, listas e tuplas) podem ser usados de forma intercambiável. Então, como você deve escolher um ao invés dos outros?
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Para começar com o óbvio, as strings são mais limitadas que as outras sequências porque os elementos precisam ser caracteres, além de serem imutáveis. Se você possivelmente precisar mudar os caracter
```suggestion
Para começar com o óbvio, as strings são mais limitadas que as outras sequências porque os elementos precisam ser caracteres, além de serem imutáveis. Se você possivelmente precisar mudar os caracteres de uma string (ao invés de criar uma nova string), convém usar uma lista de caracteres em seu lugar.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Arrays são mais comuns que tuplas, principalmente porque são mutáveis. Mas existem algumas situações em que você pode preferir as tuplas:
```suggestion
Listas são mais comuns que tuplas, principalmente porque são mutáveis. Mas existem algumas situações em que você pode preferir as tuplas:
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +* Em algumas circunstâncias, como uma declaração return, sintaticamente é mais simples criar uma tupla do que um array.
```suggestion
* Em algumas circunstâncias, como um comando de retorno, sintaticamente é mais simples criar uma tupla do que uma lista.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Como as tuplas são imutáveis, elas não dispõem de funções como +sort!+ e +reverse!+, que modificam os arrays existentes. Mas Julia possui a função interna +sort+, que recebe um array e devolve um nov
```suggestion
Como as tuplas são imutáveis, elas não dispõem de funções como +sort!+ e +reverse!+, que modificam as listas existentes. Mas Julia possui a função interna +sort+, que recebe ums lista e devolve uma nova lista com os mesmos elementos na ordem classificada, e +reverse+, que recebe qualquer sequência e devolve uma sequência do mesmo tipo na ordem contrária.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Arrays, dicionários e tuplas são exemplos de _estruturas de dados_; neste capítulo, começamos a ver estruturas de dados compostas, como arrays de tuplas ou dicionários que contêm tuplas como chaves e
```suggestion
Listas, dicionários e tuplas são exemplos de _estruturas de dados_; neste capítulo, começamos a ver estruturas de dados compostas, como listas de tuplas ou dicionários que contêm tuplas como chaves e listas como valores. As estruturas de dados compostas são práticas, embora sejam propensas ao que chamo de _erros de forma_; isto é, erros causados ​​quando uma estrutura de dados tem o tipo, tamanho ou estrutura incorreta. Por exemplo, se você está esperando uma lista com um número inteiro e eu fornecer um número inteiro (que não é uma lista), não funcionará.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Uma coleção de valores relacionados, frequentemente estruturados em array, dicionários, tuplas, etc.
```suggestion
Uma coleção de valores relacionados, frequentemente estruturados numa lista, dicionários, tuplas, etc.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Você pode querer construir um dicionário que mapeia uma coleção de letras até um array de palavras que podem ser soletradas com essas letras. A questão é: como você pode representar a coleção de letr
```suggestion
Você pode querer construir um dicionário que mapeia uma coleção de letras até uma lista de palavras que podem ser soletradas com essas letras. A questão é: como você pode representar a coleção de letras de uma forma que ela possa ser usada como chave?
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +. Modifique o programa anterior para imprimir primeiro o maior array de anagramas, seguida pelo segundo mais longo e assim por diante.
```suggestion
. Modifique o programa anterior para imprimir primeiro o maior lista de anagramas, seguida pelo segundo mais longo e assim por diante.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +. No Scrabble, um "bingo" é quando você joga usa as sete peças do seu suporte, juntamente com uma letra no tabuleiro, para formar uma palavra de oito letras. Qual é a coleção de oito letras que forma
```suggestion
. No Scrabble, um “bingo” é quando você joga usa as sete peças do seu suporte, juntamente com uma letra no tabuleiro, para formar uma palavra de oito letras. Qual é a coleção de oito letras que forma o maior número possível de bingos?
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Duas palavras formam um “par de metátese“ se você puder transformar uma na outra trocando duas letras, como no caso de "converse" e "conserve". Escreva um programa que encontre todos os pares de metá
```suggestion
Duas palavras formam um “par de metátese” se você puder transformar uma na outra trocando duas letras, como no caso de “converse“ e “conserve”. Escreva um programa que encontre todos os pares de metáteses no dicionário.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +. Você pode escrever uma função que recebe uma palavra e obtenha um array de todas as palavras que podem ser formadas removendo uma letra. Este array contém os “filhos” da palavra.
```suggestion
. Você pode escrever uma função que recebe uma palavra e obtenha uma lista de todas as palavras que podem ser formadas removendo uma letra. Esta lista contém os “filhos” da palavra.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +((((soma_tudo)))((("função", "definido pelo programador", "soma_tudo", see="soma_tudo"))))
```suggestion
(((soma_tudo)))((("função", "definido pelo programador", "soma_tudo", see="soma_tudo")))
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +((((imutável)))
```suggestion
(((imutável)))
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +((((atribuição de tupla)))
```suggestion
(((atribuição de tupla)))
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +(((depuração)))(((estruturas de dados)))(((erro de forma))))
```suggestion
(((depuração)))(((estruturas de dados)))(((erro de forma)))
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +=== Arrays e Tuplas
```suggestion
=== Listas e Tuplas
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Você pode usar a atribuição de tupla em um laço +for+ para percorrer um array de tupla:
```suggestion
Você pode usar a atribuição de tupla em um laço +for+ para percorrer uma lista de tupla:
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +(((string)))(((array)))(((tupla)))
```suggestion
(((string)))(((lista)))(((tupla)))
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Um objeto que pode iterar por uma sequência, mas que não dispõe de operadores e funções de array.
```suggestion
Um objeto que pode iterar por uma sequência, mas que não dispõe de operadores e funções de listas.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Este capítulo apresenta mais um tipo interno, a tupla, e mostra como os arrays, dicionários e as tuplas trabalham juntos. Também apresento um recurso útil para os arrays de argumentos de tamanho vari
```suggestion
Este capítulo apresenta mais um tipo interno, a tupla, e mostra como os listas, dicionários e as tuplas trabalham juntos. Também apresento um recurso útil para os listas de argumentos de tamanho variável, operadores de agrupamento e de separação.
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +A maioria dos operadores de array também funciona com as tuplas. O operador colchete indexa um elemento:
```suggestion
A maioria dos operadores de lista também funciona com as tuplas. O operador colchete indexa um elemento:
```

2020-06-10 21:10 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +Este exemplo intercala uma string com uma matriz:
```suggestion
Este exemplo intercala uma string com uma lista:
```

2020-06-10 23:53 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +Este capítulo apresenta mais um tipo interno, a tupla, e mostra como os arrays, dicionários e as tuplas trabalham juntos. Também apresento um recurso útil para os arrays de argumentos de tamanho vari
```suggestion
Este capítulo apresenta mais um tipo interno, a tupla, e mostra como as listas, os dicionários e as tuplas trabalham juntos. Também apresento um recurso útil para as listas de argumentos de tamanho variável, operadores de agrupamento e de separação.
```

2020-06-10 23:55 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +A maioria dos operadores de array também funciona com as tuplas. O operador colchete indexa um elemento:
```suggestion
A maioria dos operadores da lista também funciona com as tuplas. O operador colchete indexa um elemento:
```

2020-06-11 00:03 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> ++maximum+ e +minimum+ são funções internas que encontram o maior e o menor elemento de uma sequência. +minmax+ calcula os dois e retorna-os por meio de uma tupla. Já a função interna +extrema+ é mais
```suggestion
As funções internas +maximum+ e +minimum+ encontram o maior e o menor elemento de uma sequência. +minmax+ calcula os dois e retorna-os por meio de uma tupla. Já a função interna +extrema+ é mais eficiente.
```

2020-06-11 00:05 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +O objeto zip é um tipo de _iterador_, um objeto usado para percorrer uma sequência. De uma certa forma, os iteradores são similares aos arrays, e o que difere dos arrays é que não se pode usar um índ
```suggestion
O objeto zip é um tipo de _iterador_, um objeto usado para percorrer uma sequência. De uma certa forma, os iteradores são similares às listas, e o que difere das listas é que não se pode usar um índice para selecionar um elemento a partir de um iterador.
```

2020-06-11 00:11 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +Este laço percorre os pares chave-valor em +diretório+, que são tuplas. Ele atribui os elementos da chave em cada tupla +sobrenome+ e +nome+ ao valor em +número+, e então imprime o nome completo e o
Eu não entendi pq teria q mudar para "Esse".

https://www.educamaisbrasil.com.br/enem/lingua-portuguesa/este-ou-esse

2020-06-11 00:13 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +Tenho focado em arrays de tuplas, mas quase todos os exemplos neste capítulo também funcionam com arrays de arrays, tuplas de tuplas, e tuplas de arrays. Para evitar listar as possíveis combinações,
```suggestion
Tenho focado nas listas de tuplas, mas quase todos os exemplos neste capítulo também funcionam com as listas de listas, tuplas de tuplas, e tuplas de listas. Para evitar enumerar as possíveis combinações, às vezes é mais fácil falar sobre seqüências de seqüências.
```

2020-06-11 00:14 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +Arrays são mais comuns que tuplas, principalmente porque são mutáveis. Mas existem algumas situações em que você pode preferir as tuplas:
```suggestion
As listas são mais comuns que tuplas, principalmente porque são mutáveis. Mas existem algumas situações em que você pode preferir as tuplas:
```

2020-06-11 00:15 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +* Em algumas circunstâncias, como uma declaração return, sintaticamente é mais simples criar uma tupla do que um array.
```suggestion
* Em algumas circunstâncias, como uma declaração return, sintaticamente é mais simples criar uma tupla do que uma lista.
```

2020-06-11 00:17 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +Como as tuplas são imutáveis, elas não dispõem de funções como +sort!+ e +reverse!+, que modificam os arrays existentes. Mas Julia possui a função interna +sort+, que recebe um array e devolve um nov
```suggestion
Como as tuplas são imutáveis, elas não dispõem de funções como +sort!+ e +reverse!+, que modificam os arrays existentes. Mas o Julia possui a função interna +sort+, que recebe uma lista e devolve uma nova lista com os mesmos elementos na ordem classificada, e +reverse+, que recebe qualquer sequência e devolve uma sequência do mesmo tipo na ordem contrária.
```

2020-06-11 00:17 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +(((sort)))(((sort!)))(((reverse)))(((reverse!)))(((zip)))((("função", "Base", "reverse ", see="reverse")))(((zip)))((("função","Base","reverse!", see="reverse!")))
```suggestion
(((sort)))(((sort!)))(((reverse)))(((reverse!)))(((zip)))((("função", "Base", "reverse", see="reverse")))(((zip)))((("função", "Base", "reverse!", see="reverse!")))
```

2020-06-11 00:18 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +Arrays, dicionários e tuplas são exemplos de _estruturas de dados_; neste capítulo, começamos a ver estruturas de dados compostas, como arrays de tuplas ou dicionários que contêm tuplas como chaves e
```suggestion
As listas, os dicionários e as tuplas são exemplos de _estruturas de dados_; neste capítulo, começamos a ver estruturas de dados compostas, como arrays de tuplas ou dicionários que contêm tuplas como chaves e arrays como valores. As estruturas de dados compostas são práticas, embora sejam propensas ao que chamo de _erros de forma_; isto é, erros causados ​​quando uma estrutura de dados tem o tipo, tamanho ou estrutura incorreta. Por exemplo, se você está esperando um array com um número inteiro e eu fornecer um número inteiro (que não é um array), não funcionará.
```

2020-06-11 00:19 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +Um objeto que pode iterar por uma sequência, mas que não dispõe de operadores e funções de array.
```suggestion
Um objeto que pode iterar por uma sequência, mas que não dispõe de operadores e funções de lista.
```

2020-06-11 00:20 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +Uma coleção de valores relacionados, frequentemente estruturados em array, dicionários, tuplas, etc.
```suggestion
Uma coleção de valores relacionados, frequentemente estruturados em lista, dicionários, tuplas, etc.
```

2020-06-11 00:21 UTC, chunggnuhc commented on book/src/chap12.asciidoc
> +. Modifique o programa anterior para imprimir primeiro o maior array de anagramas, seguida pelo segundo mais longo e assim por diante.
```suggestion
. Modifique o programa anterior para imprimir primeiro a maior lista de anagramas, seguida pela segunda mais longa e assim por diante.
```

2020-06-30 01:55 UTC, gustavosarturi requested changes

2020-06-30 01:55 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +O objeto zip é um tipo de _iterador_, um objeto usado para percorrer uma sequência. De uma certa forma, os iteradores são similares aos arrays, e o que difere dos arrays é que não se pode usar um índ
```suggestion
O objeto zip é um tipo de _iterador_, um objeto usado para percorrer uma sequência. De uma certa forma, os iteradores são similares às listas, e o que difere das listas é que não se pode usar um índice para selecionar um elemento a partir de um iterador.
```

2020-06-30 01:55 UTC, gustavosarturi commented on book/src/chap12.asciidoc
> +* Em algumas circunstâncias, como uma declaração return, sintaticamente é mais simples criar uma tupla do que um array.
@chunggnuhc - Alterar **_Array_** pra **_Lista_**

2020-06-30 01:56 UTC, gustavosarturi commented
@abelsiqueira  - Assim que a Kally fazer essas alterações, já pode ir pra revisão final.

2020-07-03 17:18 UTC, gustavosarturi approved these changes

2020-07-03 17:20 UTC, abelsiqueira submitted a review, later dismissed

2020-07-09 20:15 UTC, abelsiqueira approved these changes

2020-07-09 20:15 UTC, abelsiqueira commented on book/src/chap12.asciidoc
> +Tenho focado nas listas de tuplas, mas quase todos os exemplos neste capítulo também funcionam com as listas de listas, tuplas de tuplas, e tuplas de listas. Para evitar enumerar as possíveis combina
```suggestion
Temos focado nas listas de tuplas, mas quase todos os exemplos neste capítulo também funcionam com as listas de listas, tuplas de tuplas, e tuplas de listas. Para evitar enumerar as possíveis combinações, às vezes é mais fácil falar sobre seqüências de seqüências.
```

2020-07-09 20:15 UTC, abelsiqueira commented on book/src/chap12.asciidoc
> +Para começar com o óbvio, as strings são mais limitadas que as outras sequências porque os elementos precisam ser caracteres, além de serem imutáveis. Se você possivelmente precisar mudar os caracter
```suggestion
Para começar com o óbvio, as strings são mais limitadas que as outras sequências porque os elementos precisam ser caracteres, além de serem imutáveis. Se você possivelmente precisar mudar os caracteres de uma string (ao invés de criar uma nova string), pode ser melhor usar uma lista de caracteres em seu lugar.
```

2020-07-09 20:15 UTC, abelsiqueira commented on book/src/chap12.asciidoc
> +As listas, os dicionários e as tuplas são exemplos de _estruturas de dados_; neste capítulo, começamos a ver estruturas de dados compostas, como arrays de tuplas ou dicionários que contêm tuplas como
```suggestion
As listas, os dicionários e as tuplas são exemplos de _estruturas de dados_; neste capítulo, começamos a ver estruturas de dados compostas, como arrays de tuplas ou dicionários que contêm tuplas como chaves e arrays como valores. As estruturas de dados compostas são práticas, embora sejam propensas ao que chamamos de _erros de forma_; isto é, erros causados ​​quando uma estrutura de dados tem o tipo, tamanho ou estrutura incorreta. Por exemplo, se você está esperando uma lista com um número inteiro e for fornecido um número inteiro (que não é um lista), não funcionará.
```

2020-07-09 20:15 UTC, abelsiqueira commented on book/src/chap12.asciidoc
> +Qual é a palavra em inglês mais longa, que permanece uma palavra válida em inglês à medida que você remove as letras uma de cada vez?
```suggestion
Qual é a palavra em Inglês mais longa, que permanece uma palavra válida em Inglês à medida que você remove as letras uma de cada vez?
```

2020-07-09 20:15 UTC, abelsiqueira commented on book/src/chap12.asciidoc
> +Agora, as letras podem ser removidas de qualquer posição e não pode rearranjar nenhuma das letras. Toda vez que você retira uma letra, você termina com outra palavra em inglês. Se você fizer isso, ac
```suggestion
Agora, as letras podem ser removidas de qualquer posição e você não pode rearranjar nenhuma das letras. Toda vez que você retirar uma letra, você termina com outra palavra em Inglês. Se você fizer isso, acabará terminando com uma letra e essa também será uma palavra em Inglês que pode ser encontrada no dicionário. Quero saber qual é a palavra mais longa e quantas letras ela tem?
```

2020-07-09 20:15 UTC, abelsiqueira commented on book/src/chap12.asciidoc
> +Escreva um programa para encontrar todas as palavras em inglês que podem ser reduzidas desta forma, e depois encontre a mais longa.
```suggestion
Escreva um programa para encontrar todas as palavras em Inglês que podem ser reduzidas desta forma, e depois encontre a mais longa.
```

2020-07-09 20:18 UTC, merged