Chapter 07 - PTBR
JuliaIntro/JuliaIntroBR.jl pull request #17
Opened 2020-05-11 23:16 UTC by gustavosarturi

2020-05-13 22:09 UTC, chunggnuhc requested changes

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Esse capítulo é sobre iteração, que é a habilidade de executar um bloco de argumentos repetidamente. Vimos  um tipo de iteração, usando recursão, em <<recursão>>. Vimos também outro tipo, usando um l
"Neste capítulo veremos um outro tipo, _que usa_ uma _declaração_ +while+ (_enquanto_ em Português)."

(1) A frase que eu sugeri se aproxima mais do jeito que nos expressamos no Brasil.
(2) O termo atribuição em Computação tem um significado específico. Não há atribuição em particular com while. Neste caso, é melhor usar o termo declaração ou comando.

"Neste capítulo veremos um outro tipo, usando uma atribuição +while+ (_enquanto_, em Português)."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((iteração)))(((recursão)))(((atribuição for)))
(((_declaração_ for)))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Você talez tenha descoberto, que é permitido fazer mais de uma atribuição para as mesmas variáveis. Uma nova atribuição faz com que uma variável existente se refira a um novo valor (e pare de se refe
Você _talvez_ tenha descoberto que é permitido fazer...

(1) Erro de digitação
(2) Tire a vírgula pq a frase está sendo "cortada". A leitura não flui.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +<<fig07-1>> mostra que uma _reatribuição_ se parece com um diagrama de estado
Minha sugestão: "<<fig07-1>> mostra como uma _reatribuição_ funciona por meio de um diagrama de estado."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Neste ponto, quero abordar uma fonte comum de confusão. Como Julia usa o sinal de igual (+=+) para atribuição, é tentador interpretar uma afirmação como +a = b+ como uma proposição matemática de igua
Minha sugestão: "Neste ponto, quero abordar um _assunto_ comum de confusão. Como Julia usa o sinal de igual (+=+) para _a_ atribuição..."

Na minha opinião, a frase que eu sugeri se aproxima mais do jeito que nos expressamos no Brasil.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((atribuição)))
(((comando de atribuição)))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Primeiro, a igualdade é uma relação simétrica e a atribuição não é. Por exemplo, em matemática, se latexmath:[\(a=7\)] então latexmath:[\(7=a\)]. Mas em julia, a atribuição +a=7+ é permitida e +7=a+
"Mas em _Julia_, a atribuição +a=7+ é permitida e +7=a+ não."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Em matemática, também, uma proposição de igualdade ou é verdadeira ou é falta por todo o tempo. Se latexmath:[\(a=b)\)] agora, então latexmath:[\(a\)] será sempre igual a latexmath:[\(b\)]. Em Julia,
_Também na matemática_, uma proposição de igualdade ou é verdadeira ou é _falsa para sempre_. ... Em Julia, um _comando_ de atribuição pode fazer com que duas variáveis sejam iguais, mas eles não precisam ficar assim:

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A reatribuição de variáveis geralmente é útil, mas você deve usá-las com cuidado. Se os valores das variáveis mudarem com frequência, isso poderá dificultar a leitura e a depuração do código.
"... mas você deve _usá-la_ com cuidado. Se os valores das variáveis mudarem com frequência, isso poderá dificultar a leitura e _o debugging_ do código."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Não é permitido definir uma função que tenha o mesmo nome que uma variável definida anteriormente.
"Não é permitido definir uma função que tenha o mesmo nome _de_ uma variável definida anteriormente."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +=== Atualizando variáveis
"Atualizando _Variáveis_"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Isso significa "pegar o valor atual de +x+, adicionar um, e então atualizar +x+ ao novo valor."
Isso significa “pegar o valor atual de +x+, adicionar um, e então atualizar +x+ ao novo valor.”
Mudar as aspas, elas são as aspas curvas.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Se você tenta atualizar uma variável que não existe, você obterá um erro, porque Julia avalia o lado direito antes de atribuir um valor a ++:
"Se você tenta atualizar uma variável que não existe, _uma mensagem de erro aparecerá_, porque Julia avalia o lado direito antes de atribuir um valor a _+x+_:"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((UndefVarErro)))(((Erro de Variável Indefinida)))
(((UndefVarError)))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Antes que você possa atualizar uma variável, você tem que inicializar ela, geralmente com uma atribuição simples:
"Antes que você possa atualizar uma variável, você tem que _inicializá-la_, geralmente com uma atribuição simples:"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Atualizar uma variável adicionando 1 é chamado de _incremento_; subtraindo 1 é chamado de _decremento_.
Minha sugestão: "Atualizar uma variável adicionando 1 é chamado de _incremento_; _e_ subtraindo 1 é chamado de _decremento_."

Na minha opinião, a alteração dá mais fluidez para o texto.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +=== A atribuição +while+
"A _Declaração_ +while+"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Os computadores são frequentemente usados para automatizar tarefas repetitivas. Repetir tarefas idênticas ou semelhantes sem cometer erros é algo que os computadores fazem bem e as pessoas fazem mal.
"Em um programa de computador, a repetição também é chamada  _de_ _iteração_."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Já vimos duas funções, +contador_regressivo+ e +imprima_n+, que iteram usando recursão. Como essa iteração é muito comum, Julia fornece recursos para fazer isso fácil. Uma para a atribuição +for+ que
"Como _a_ iteração é muito comum, Julia _dispõe de_ recursos para _simplificá-la_. Um deles _é_ a _declaração_ +for+ que vimos em <<_Repetição__simples>>. Voltaremos a _este assunto_ mais tarde."

A referência <<simple_repetition>> também foi usado na linha 4. Vc tem que decidir qual é formatação q vc vai usar: <<repetição simples>> ou <<Repetição_simples>>.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((recursão)))(((atribuição for)))
(((declaração for)))

Já dá um replace e substitui "atribuição for" por "declaração for".

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A outra é para a _atribuição_ +while+. Aqui está a versão do +contagem_regressiva+ que utiliza a atribuição +while+:
"O outro recurso é a _declaração_ +while+. Aqui está a versão do +contagem_regressiva+ que utiliza a _declaração_ +while+:"

Já dá um replace e substitui "atribuição while" por "declaração while".

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((while)))((("keyword", "while", see="while")))(((atribuição while)))((("atribuição", "while", see="atribuição while")))
(((while)))(((_"palavra-chave_", "while", see="while")))(((_declaração while_)))((("declaração", "while", see="_declaração while_")))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Você pode ler quase toda a atribuição +while+ como se estivesse em inglês (ou _Português_). Isso significa que, "Enquanto +n+ for maior que 0, exiba o valor de +n+ e decrementa +n+. Quando atingir 0,
"Isso significa que "Enquanto +n+ for maior que 0, exiba o valor de +n+ e _diminua_ +n+. Quando _chegar a_ 0, _imprima_ a palavra Vai!"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((contagem regressiva)))
Eu acho q esta referência é para a função e neste caso, ficaria (((contagem_regressiva))).

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O corpo do laço pode mudar o valor de uma ou mais variáveis até que então a condição eventualmente torna falsa e o laço é finalizado. Caso contrário, o laço irá se repetir pra sempre, o que é um _laç
"O corpo do laço _deve_ mudar o valor de uma ou mais variáveis até que a condição eventualmente se torna falsa e o laço é finalizado. Caso contrário, o laço irá se repetir _para_ sempre, que é um _laço infinito_. Uma fonte inesgotável de diversão para os cientistas da computação _são_ as instruções nos frascos de shampoo, “ensaboar, enxaguar, repetir”, que é um laço infinito."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +No caso da +contagem_regressiva+, podemos provar que o laço é finalizado: se +n+ é zero ou negativo, o laço nunca termina. Caso contrário, +n+ vai atingindo valores menores através do laço, então eve
"Caso contrário, +n+ vai _diminuindo_ através do laço, _e_ então eventualmente chegará a 0."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Para alguns laços, não é fácil provar. Por exemplo:
"Para alguns laços, não é _tão_ fácil de provar."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Cada vez através do laço, o programa tem como saída o valor +n+ e verifica se é par ou ímpar. Se for par, +n+ é divisível por 2. Se é ímpar, o valor de +n+ é substituído por +pass:[n*3 + 1]+. Por exe
"_A cada turno_ do laço, o programa tem como saída o valor +n+ _que é verificado_ se é par ou ímpar. Se for par, +n+ é _dividido_ por 2. Se é ímpar, o valor de +n+ é substituído por +pass:[n*3 + 1]+. Por exemplo, se o argumento _passado para a_ sequência é 3, _os valores de +n+ recebidos_ são 3, 10, 5, 16, 8, 4, 2, 1."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Desde que +n+ as vezes cresça e as vezes decresça, não existe uma demonstração óbvia de que +n+ alcançará 1, o que o programa termine. Para alguns valores particulares de +n+, podemos demonstrar que
"_Já que +n+ às vezes cresce e às vezes decresce_, não existe uma demonstração óbvia de que +n+ alcançará 1, _ou que o programa termine_. Para alguns valores específicos de +n+, podemos demonstrar que termina. Por exemplo, se o valor inicial é uma potência de dois, +n+ será sempre par _durante o_ laço até que atinja 1. O exemplo anterior finaliza _essa sequência_, a partir de 16."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A parte difícil é se podemos provar que esse programa finaliza para todos os valores positivos de +n+. Portanto, ninguém foi capaz de provar ou desprovar isso! (see https://en.wikipedia.org/wiki/Coll
"_Até agora_ ninguém foi capaz de provar ou desprovar isso! (_consulte_ https://pt.wikipedia.org/wiki/Conjectura_de_Collatz.)"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Às vezes, você não sabe que é hora de terminar um laço até chegar na metade do corpo. Neste caso você pode utilizar a _atribuição de parada_ para sair do laço.
"Neste caso você pode utilizar a _declaração break_ para sair do laço."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((break)))((("palavra chave", "parada", see="parada")))(((atribuição de parada)))((("atribuição", "parada", see="atribuição de parada")))
((("palavra-chave", "break", see="break")))(((declaração break)))((("declaração", "break", see="declaração break")))

Estamos fazendo referência ao comando break, que é uma palavra-chave do Julia, não sobre o assunto de parar um laço de repetição.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +((leitura de linha))
(((readline)))

Estamos fazendo referência ao comando readline usada na função mostrada no exemplo.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A condição de laço é +true+, o que ocorre sempre, então o laço irá ser executado até que alcance a atribuição de pausa.
"A condição _deste_ laço é +true+, que é sempre verdadeiro, então o laço será interrompido somente quando chegar na declaração break."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
>      line = readline()
linha = readline()

Também estou traduzindo, qdo possível, partes do código.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +    if line == "concluído"
if linha == "concluído"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
>      println(line)
println(linha)

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A cada vez, ele solicita ao usuário um colchete angular. Se o usuário digitar +concluído+, a instrução break sai do laço. Caso contrário, o programa ecoará o que o usuário digitar e voltará ao topo d
"A cada iteração, a solicitação ao usuário ocorre por meio de um sinal de maior (">") . Se o usuário digitar +concluído+, então o comando break finaliza o laço. Caso contrário, o programa mostrará o que o usuário digitar e voltará ao topo do laço. Aqui está uma mostra da execução:"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A atribuição de parada sai do laço. Quando uma _atribuição de continuidade_ é encontrado dentro de um laço, o controle salta para o início do laço para a próxima iteração, pulando a execução de instr
"A declaração break sai do laço. Quando uma _declaração continue_ é encontrada dentro de um laço, salta-se para o início do laço da próxima iteração, pulando a execução de comandos dentro do corpo do laço da iteração atual. Por exemplo:"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((continue)))((("palavra-chave", "continuar", see="continuar")))(((atribuição de continuidade)))((("atribuição", "continuar", see="continuar", see="atribuição de continuidade")))
((("palavra-chave", "continue", see="continue")))(((declaração continue)))((("declaração", "continue", see="continue", see="declaração continue")))

(1) na linha 171, vc escreve "palavra chave", sem hífen. Vc precisa padronizar a escrita de _keyword_.
(2) esta referência é para a keyword continue, não sobre a definição de um comando sobre continuar.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Se +i+ é divisível por 3, a atribuição de continuidade para na iteração atual e a próxima iteração é iniciada. Apenas os números no intervalo entre 1 a 10 não divisíveis por 3 são exibidos.
"Se +i+ é divisível por 3, a _declaração continue_ para na iteração atual e a próxima iteração é iniciada. Apenas os números no intervalo entre 1 a 10 não divisíveis por 3 são exibidos."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Laços são geralmente usados em programas que computam resultados numéricos começando com uma resposta aproximada e iterativamente melhorando.
Minha sugestão: "... que computam resultados numéricos começando com _um valor aproximado_ e _é refinado iterativamente_."

Na minha opinião, a frase q eu sugeri se aproxima mais do jeito que nos expressamos no Brasil.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O resultado é próximo da resposta correta (latexmath:[\(\sqrt 4 = 2\)]). Se repetirmos o processo com a nova estimativa, irá ficar mais próximo ainda:
"O resultado _está mais_ próximo da resposta correta (latexmath:[\(\sqrt 4 = 2\)]). Se repetirmos o processo com a nova estimativa, irá ficar mais próximo ainda:"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Depois de algumas atualizações, a estimativa é quase exata:
Depois de _mais_ algumas atualizações, a estimativa é quase exata:

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
A linha 271 não foi traduzida.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Quando +y == x+, podemos parar. Aqui está um laço que começa com uma estimativa inicial, +x+, e melhora até que parar de mudar:
"Aqui está um laço que começa com uma estimativa inicial, +x+, e melhora até parar de mudar:"

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Para a maior parte dos valores de a funciona bem, mas em geral é perigo testar igualdade de float. Pontos Flutuantes são apenas aproximadamente corretos: números mais racionais, como latexmath:[\(\fr
"Esta função funciona bem para a maior parte dos valores de a, mas em geral é perigoso testar igualdade com pontos flutuantes. Pontos flutuantes não são totalmente corretos: a maioria dos números racionais como latexmath:[\(\frac{1}{3}\)], e números irracionais como latexmath:[\(\sqrt 2\)], não podem ser representados exatamente com um tipo +Float64+."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((abdômen)))
(((abs)))

Esta referência é para a função interna do Julia para calcular o valor absoluto.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Onde +ε+ (*+\varepsilon TAB+*) possui um valor como +0.0000001+ que determina o quão próximo está.
"que determina o quão _suficientemente_ próximo está."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O Método de Newton é um exemplo de um _algoritmo_: É um processo mecânico de se resolver uma categoria de problemas (neste caso, raízes quadradas).
"É um processo mecânico _para_ resolver uma categoria de problemas (neste caso, _o cálculo de_ raízes quadradas)."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((algoritmos)))
(((algoritmo)))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Para entender o que é um algoritmo, ajudaria começar com algo que não é um algoritmo. Quando você aprendeu a multiplicar unidades, você provavelmente memorizou a tabuada. Com efeito, você memorizou 1
"_De fato_, você memorizou 100 soluções específicas."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Similarmente, as técnicas que você aprendeu para adição com transporte de unidades, subtração com empréstimos e divisão longa são todos algoritmos. Uma das características dos algoritmos é que eles n
Minha sugestão: "Similarmente, as técnicas que você aprendeu para _a_ adição com transporte de unidades, _a_ subtração com empréstimos e _a_ divisão longa são todos algoritmos. ... São processos mecânicos em que cada etapa segue _a partir_ da última, de acordo com um conjunto simples de regras."

Na minha opinião, essa sugestão dá mais fluidez para a frase.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A execução de algoritmos é chata, mas projetá-los é interessante, intelectualmente desafiadora e parte central da ciência da computação.
"A execução de algoritmos é chata, mas _elaborá_-los é interessante, intelectualmente _desafiador_ e _uma_ parte central da ciência da computação."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Ao começar a escrever programas maiores, você pode passar mais tempo depurando. Mais código significa mais chances de cometer um erro e mais lugares para ocultar os erros.
"Ao começar a escrever programas maiores, você pode passar mais tempo _debugando_. Mais código significa mais chances de cometer um erro e mais lugares para _os erros se esconderem_."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Uma maneira de reduzir o tempo de debug é "debug por bissecção". Por exemplo, se houver 100 linhas no seu programa e você as verificar uma de cada vez, serão necessárias 100 etapas.
"Uma maneira de reduzir o tempo _do debugging_ é o “debugging por bissecção”. Por exemplo, se houver 100 linhas no seu programa e você _verificá-las_ uma de cada vez, serão necessárias 100 etapas."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((debug por bissecção)))
(((debugging por bissecção)))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Em vez disso, tente quebrar o problema ao meio. Olhe no meio do programa, ou perto dele, para um valor intermediário que você pode verificar. Adicione uma atribuição de impressão (ou outra coisa que
"Adicione _um comando print_ (ou _qualquer_ outra coisa que tenha um _propósito de verificação_) e execute o programa."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((atribuição de impressão)))
(((comando print)))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Se a verificação do ponto médio estiver incorreta, deve haver um problema na primeira metade do programa. Se estiver correto, o problema está no segundo semestre.
"Se a verificação _da região do meio_ estiver incorreta, deve haver um problema na primeira metade do programa. Se estiver correto, o problema está _na segunda metade_."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Toda vez que você executa uma verificação como essa, reduz pela metade o número de linhas que precisa pesquisar. Após seis etapas (que é menor que 100), você reduziria para uma ou duas linhas de códi
"Toda vez que você executa uma verificação como essa, reduz_-se_ pela metade o número de linhas que precisa averiguar. Após seis etapas (que é menor que 100), você reduziria para uma ou duas linhas de código, pelo menos em teoria."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Na prática, nem sempre é claro qual é o "meio do programa" e nem sempre é possível verificá-lo. Não faz sentido contar linhas e encontrar o ponto médio exato. Em vez disso, pense nos locais do progra
"Na prática, nem sempre é claro _onde_ é o "meio do programa" ..."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +atualizar::
Na minha opinião, atualização é melhor que atualizar.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Uma atualização que aumenta o valor de uma variável (geralmente em uma).
"Uma atualização que aumenta o valor de uma variável (geralmente em _um_)."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +atribuição while::
"Declaração while".

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +atribuição de parada::
"Declaração break"

Aproveita e já corrige linha 380.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Instrução que permite saltar fora de um laço.
"Declaração que permite saltar fora de um laço."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +atribuição de continuidade::
"Declaração continue"

Aproveita e já corrige linha 384.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Instrução dentro de um laço que salta para o início do laço para a próxima iteração.
"Declaração dentro de um laço que salta para o início do laço da próxima iteração."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Um laço no qual a condição final nunca é satisfeita.
Minha sugestão: "Um laço no qual a sua condição nunca é satisfeita."

Na minha opinião, esta sugestão deixa a frase mais específica.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Copie o laço de <<raízes_quadradas>> e encapsule-o em uma função chamada +minha_raiz+ que use +a+ como parâmetro, escolha um valor razoável de +x+ e retorne uma estimativa da raiz quadrada de +a+.
Copie o laço de <<raízes_quadradas>> e encapsule-o em uma função chamada +minha_raiz+ que use a variável +a+ como parâmetro, _e_ escolha um valor razoável de +x+ _que_ retorne uma estimativa da raiz quadrada de +a+.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((minha_raiz))) ((("função", "definido pelo programador", "minha_raiz", see = "minha_raiz"))))
(((minha_raiz)))((("função", "definido pelo programador", "minha_raiz", see="minha_raiz")))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Para testá-lo, escreva uma função chamada +testa_raiz+ que imprime uma tabela como esta:
"Para _testá-la_..."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((testa_raiz))) ((("função", "definido pelo programador", "testa_raiz", see = "testa_raiz"))))
(((testa_raiz)))((("função", "definido pelo programador", "testa_raiz", see="testa_raiz")))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((análise)))((("função","Meta","análise", see="análise"))) (((eval))) ((("function", "Core", "eval", see="eval")))
(((parse)))((("função", "Meta", "parse", see="parse")))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Escreva uma função chamada +avalie_laço+ que solicite iterativamente ao usuário, pegue a entrada resultante e a avalie usando +eval+ e imprima o resultado. Ele deve continuar até o usuário digitar +c
"Escreva uma função chamada +avalie_laço+ que solicite iterativamente ao usuário, _e então_ pegue a entrada _recebida_ e a avalie usando +eval+ e _depois_ imprima o resultado. Ele deve continuar até o usuário digitar +concluído+ e retornar o valor da última expressão avaliada."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Escreva uma função chamada +estimativa_pi+ que use essa fórmula para calcular e retornar uma estimativa de π. Ele deve usar um laço while para calcular os termos da soma até que o último termo seja m
"Ele deve usar um laço while para calcular os termos da soma até que o último termo seja menor que +1e-15+ (que é a notação Julia para latexmath:[\(10^{-15}\)])."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((estimativa pi))) ((("função", "definido pelo programador", "estimativa_pi", see = "estimativa_pi"))))
(((estimativa_pi)))((("função", "definido pelo programador", "estimativa_pi", see="estimativa_pi")))

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Por exemplo, suponha que você quer coletar entradas do usuário até que ele digite concluído. Você poderia escrever:
"Por exemplo, suponha que você quer _receber as_ entradas do usuário até que ele digite concluído."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Algumas das coisas que as pessoas fazem naturalmente, sem dificuldade ou pensamento consciente, são as mais difíceis de expressar por algoritmos. Compreender a linguagem natural é um bom exemplo. Tod
"Todos fazemos isso, mas até agora ninguém foi capaz de explicar como fazemos, pelo menos não na forma de um algoritmo."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +((decremento)))
São três parênteses no começo e três no final.

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Execução repetida de um conjunto de instruções usando uma chamada de função recursiva ou um laço.
"Execução repetida de um conjunto de comandos usando uma chamada de função recursiva ou um laço."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Instrução que permite iterações controladas por uma condição.
"_Declaração_ que permite iterações controladas por uma condição."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A primeira coluna é um número, +a+; a segunda coluna é a raiz quadrada de um calculado com +minha_raiz+; a terceira coluna é a raiz quadrada calculada por +sqrt+; a quarta coluna é o valor absoluto d
"A primeira coluna é _o número_ +a+; a segunda coluna é a raiz quadrada de _a_ calculado com +minha_raiz+; ..."

2020-05-13 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O matemático Srinivasa Ramanujan encontrou uma série infinita que pode ser usada para gerar uma aproximação numérica do latexmath: [\(\ frac {1}{\ pi}\)]:
"para gerar uma aproximação numérica _de_ latexmath: [\(\ frac {1}{\ pi}\)]:"

2020-06-01 21:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Esse capítulo é sobre iteração, que é a habilidade de executar um bloco de argumentos repetidamente. Vimos  um tipo de iteração, usando recursão, em <<recursão>>. Vimos também outro tipo, usando um l
Tem erro de digitação na palavra declaração: "Neste capítulo veremos um outro tipo, que usa uma _declração_ +while+ (_enquanto_ em Português)."

2020-06-01 21:12 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +<<fig07-1>> mostra que uma _reatribuição_ se parece com um diagrama de estado
Falta colocar o ponto final no final da frase.

2020-06-01 21:16 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((atribuição)))
Me desculpa, aqui eu sugeri algo q já definimos. Tem que voltar para "(((atribuição)))"

2020-06-01 21:19 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Em matemática, também, uma proposição de igualdade ou é verdadeira ou é falta por todo o tempo. Se latexmath:[\(a=b)\)] agora, então latexmath:[\(a\)] será sempre igual a latexmath:[\(b\)]. Em Julia,
Me desculpa, aqui eu sugeri algo q já definimos com o Abel. Fica assim: "Em Julia, uma _atribuição_ pode fazer com que duas variáveis sejam iguais, mas _elas_ não precisam ficar assim:

2020-06-01 21:39 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Se você tenta atualizar uma variável que não existe, você obterá um erro, porque Julia avalia o lado direito antes de atribuir um valor a ++:
O campo "++" tá vazio. Falta fazer a correção.

2020-06-01 21:45 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Já vimos duas funções, +contador_regressivo+ e +imprima_n+, que iteram usando recursão. Como essa iteração é muito comum, Julia fornece recursos para fazer isso fácil. Uma para a atribuição +for+ que
"Como a iteração é muito comum, Julia dispõe **_de_** recursos para simplificá-la. Um deles é a declaração +for+ que vimos em <<simple_repetition>>."

2020-06-01 21:54 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((while)))((("keyword", "while", see="while")))(((atribuição while)))((("atribuição", "while", see="atribuição while")))
Ainda tem correções nessa linha 104.

2020-06-01 22:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Você pode ler quase toda a atribuição +while+ como se estivesse em inglês (ou _Português_). Isso significa que, "Enquanto +n+ for maior que 0, exiba o valor de +n+ e decrementa +n+. Quando atingir 0,
Ainda tem que fazer alteração no termo "atribuição while".

"Você pode ler quase toda a **_declaração_** +while+ como se estivesse em inglês (ou _Português_). Isso significa que "Enquanto +n+ for maior que 0, exiba o valor de +n+ e diminua +n+. Quando chegar a 0, imprima a palavra Vai!"

2020-06-01 23:09 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Desde que +n+ as vezes cresça e as vezes decresça, não existe uma demonstração óbvia de que +n+ alcançará 1, o que o programa termine. Para alguns valores particulares de +n+, podemos demonstrar que
Ainda tem correções nessa linha:
"Já que +n+ **_às vezes cresce e às vezes decresce_**, não existe uma demonstração óbvia de que +n+ alcançará 1, ou que o programa termine. Para alguns valores **_específicos_** de +n+, podemos demonstrar que termina. Por exemplo, se o valor inicial é uma potência de dois, +n+ será sempre par durante o laço até que **_chega a_** 1. O exemplo anterior finaliza essa sequência, a partir de 16."

2020-06-01 23:10 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A parte difícil é se podemos provar que esse programa finaliza para todos os valores positivos de +n+. Portanto, ninguém foi capaz de provar ou desprovar isso! (see https://en.wikipedia.org/wiki/Coll
Tb tem q alterar o link do wikipedia. O link q eu coloquei no comentário é em português.

2020-06-01 23:19 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((break)))((("palavra chave", "parada", see="parada")))(((atribuição de parada)))((("atribuição", "parada", see="atribuição de parada")))
Ainda tem correção na linha 171.

((("palavra-chave", "break", see="break"))) precisa ficar assim porque break é uma palavra-chave do Julia e não pode ser usado como nome de variável.

O último conjunto de triplas aspas "((("declaração", "break", see="declaração break")))" também tem que ficar assim porque está falando da declaração break, que não é uma atribuição e reforço o que eu disse no comentário anteior, estamos falando da declaração break no Julia e não necessariamente do que o break faz em um laço. Na tradução em espanhol, ficou assim:
"(((break)))((("palabra reservada", "break", see="break")))(((sentencia break)))((("sentencia", "break", see="sentencia break")))"

2020-06-02 00:17 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A atribuição de parada sai do laço. Quando uma _atribuição de continuidade_ é encontrado dentro de um laço, o controle salta para o início do laço para a próxima iteração, pulando a execução de instr
"A declaração break sai do laço. Quando uma _declaração continue_ é **_encontrada_** dentro de um laço, salta-se para o início do laço _**da**_ próxima iteração, pulando a execução de comandos dentro do corpo do laço **_da_** iteração atual. Por exemplo:"

2020-06-02 00:19 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((continue)))((("palavra-chave", "continuar", see="continuar")))(((atribuição de continuidade)))((("atribuição", "continuar", see="continuar", see="atribuição de continuidade")))
Falta essa correção: "((("declaração", "continue", see="continue", see="declaração continue")))"

2020-06-02 01:00 UTC, chunggnuhc requested changes

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Em geral, não sabemos antecipadamente quantas etapas são necessárias para obter a resposta certa, mas sabemos quando chegamos lá porque a estimativa para de mudar:
```suggestion
Em geral, não sabemos antecipadamente quantos passos são necessários para obter a resposta certa, mas sabemos quando chegamos lá porque a estimativa para de mudar:
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Esta função funciona bem para a maior parte dos valores de a, mas em geral é perigoso testar igualdade com pontos flutuantes. Pontos flutuantes não são totalmente corretos: a maioria dos números raci
```suggestion
Esta função funciona bem para a maior parte dos valores de a, mas em geral é perigoso testar igualdade com pontos flutuantes. Pontos flutuantes não são totalmente corretos: a maioria dos números racionais, como latexmath:[(\frac{1}{3})], e números irracionais, como latexmath:[(\sqrt 2)], não podem ser representados exatamente com um tipo +Float64+.
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A execução de algoritmos é chata, mas elaborá-los é interessante, intelectualmente desafiador e uma parte central da ciência da computação.
Sugestão para deixar a frase "mais poderosa":
```suggestion
Apesar da execução de algoritmos seja chata, a construção é interessante, intelectualmente desafiadora e uma parte central da ciência da computação.
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +declração que permite iterações controladas por uma condição.
```suggestion
Declaração que permite iterações controladas por uma condição.
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +declração que permite saltar fora de um laço.
```suggestion
Declaração que permite saltar fora de um laço.
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Copie o laço de <<square_roots>> e encapsule-o em uma função chamada +minha_raiz+ que use +a+ como parâmetro, e escolha um valor razoável de +x+ e retorne uma estimativa da raiz quadrada de +a+.
```suggestion
Copie o laço de <<square_roots>> e encapsule-o em uma função chamada +minha_raiz+ que use a variável +a+ como parâmetro, e escolha um valor razoável de +x+ que retorne uma estimativa da raiz quadrada de +a+.
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((testa_raiz)))((("função", "definido pelo programador", "testa_raiz", see = "testa_raiz"))))
```suggestion
(((testa_raiz)))((("função", "definido pelo programador", "testa_raiz", see="testa_raiz"))))
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Escreva uma função chamada +avalie_laço+ que solicite iterativamente ao usuário, e então pegue a entrada recebida e a avalie usando +eval+ e depois imprima o resultado. Ele deve continuar até o usuár
```suggestion
Escreva uma função chamada +avalie_laço+ que solicite iterativamente ao usuário, e então pegue a entrada recebida, avalie-na usando +eval+ e depois imprima o resultado. Ele deve continuar até o usuário digitar +concluído+ e retornar o valor da última expressão avaliada.
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Escreva uma função chamada +estimativa_pi+ que use essa fórmula para calcular e retornar uma estimativa de π. Ele deve usar um laço while para calcular os termos da soma até que o último termo seja m
```suggestion
Escreva uma função chamada +estimativa_pi+ que use essa fórmula para calcular e retornar uma estimativa de π. Ele deve usar um laço while para calcular os termos da soma até que o último termo seja menor que +1e-15+ (que é a notação Julia para latexmath:[\(10^{-15}\)]). Você pode verificar o resultado comparando-o com +π+.
```

2020-06-02 01:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((estimativa_pi)))((("função", "definido pelo programador", "estimativa_pi", see = "estimativa_pi"))))
```suggestion
(((estimativa_pi)))((("função", "definido pelo programador", "estimativa_pi", see="estimativa_pi"))))
```

2020-06-05 04:34 UTC, chunggnuhc requested changes

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Esse capítulo é sobre iteração, que é a habilidade de executar um bloco de argumentos repetidamente. Vimos  um tipo de iteração, usando recursão, em <<recursão>>. Vimos também outro tipo, usando um l
```suggestion
Esse capítulo é sobre iteração, que é a habilidade de executar um bloco de argumentos repetidamente. Vimos  um tipo de iteração, usando recursão, em <<recursion>>. Vimos também outro tipo, usando um laço +for+, em <<simple_repetition>>. Neste capítulo, veremos um outro tipo, que usa uma declração +while+ (_enquanto_ em Português). Mas primeiro eu tenho que dizer um pouco mais sobre atribuição de variável.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +<<fig07-1>> mostra como uma _reatribuição_ funciona por meio de um diagrama de estado
```suggestion
<<fig07-1>> mostra como uma _reatribuição_ funciona por meio de um diagrama de estado.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((comando de atribuição)))
```suggestion
(((atribuição)))
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Também na matemática, uma proposição de igualdade ou é verdadeira ou é falsa para sempre. Se latexmath:[\(a=b)\)] agora, então latexmath:[\(a\)] será sempre igual a latexmath:[\(b\)]. Em Julia, um co
```suggestion
Também na matemática, uma proposição de igualdade ou é verdadeira ou é falsa para sempre. Se latexmath:[\(a=b\)] agora, então latexmath:[\(a\)] será sempre igual a latexmath:[\(b\)]. Em Julia, uma atribuição pode fazer duas variáveis iguais, mas elas não precisam ficar assim:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A reatribuição de variáveis geralmente é útil, mas você deve usá-la com cuidado. Se os valores das variáveis mudarem com frequência, isso poderá dificultar a leitura e o debugging do código.
```suggestion
A reatribuição das variáveis geralmente é útil, mas você deve usá-la com cuidado. Se os valores das variáveis mudarem com frequência, isso pode dificultar a leitura e a depuração do código.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Se você tenta atualizar uma variável que não existe, uma mensagem de erro aparecerá, porque Julia avalia o lado direito antes de atribuir um valor a ++:
```suggestion
Se você tenta atualizar uma variável que não existe, uma mensagem de erro aparecerá, porque Julia avalia o lado direito antes de atribuir um valor a +x+:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((UndefVarError)))(((Erro de Variável Indefinida)))
```suggestion
(((UndefVarError)))
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Antes que você possa atualizar uma variável, você tem que inicializá-la, geralmente com uma atribuição simples:
```suggestion
Antes que você possa atualizar uma variável, deve-se inicializá-la geralmente com uma atribuição simples:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Os computadores são frequentemente usados para automatizar tarefas repetitivas. Repetir tarefas idênticas ou semelhantes sem cometer erros é algo que os computadores fazem bem e as pessoas fazem mal.
```suggestion
Os computadores são frequentemente usados para automatizar tarefas repetitivas. Repetir tarefas idênticas ou semelhantes sem cometer erros é algo que os computadores fazem bem, ao contrário das pessoas. Em um programa de computador, a repetição também é chamada de _iteração_.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Já vimos duas funções, +contador_regressivo+ e +imprima_n+, que iteram usando recursão. Como a iteração é muito comum, Julia dispõe recursos para simplificá-la. Um deles é a declaração +for+ que vimo
```suggestion
Já vimos duas funções, +contador_regressivo+ e +imprima_n+, que iteram usando recursão. Como a iteração é muito comum, Julia dispõe de recursos para simplificá-la. Um deles é a declaração +for+ que vimos em <<simple_repetition>>. Voltaremos a este assunto mais tarde.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A outra é para a _declaração_ +while+. Aqui está a versão do +contagem_regressiva+ que utiliza a declaração +while+:
```suggestion
O outro é a _declaração_ +while+. Aqui está a versão do +contagem_regressiva+ que utiliza a declaração +while+:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((while)))((("keyword", "while", see="while")))(((declaração while)))((("atribuição", "while", see="declaração while")))
```suggestion
(((while)))((("palavra-chave", "while", see="while")))(((declaração while)))((("declaração", "while", see="declaração while")))
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Você pode ler quase toda a atribuição +while+ como se estivesse em inglês (ou _Português_). Isso significa que "Enquanto +n+ for maior que 0, exiba o valor de +n+ e diminua +n+. Quando chegar a 0, im
```suggestion
Você pode ler quase toda a declaração +while+ como se estivesse em inglês. Isso significa que "Enquanto +n+ for maior que 0, exiba o valor de +n+ e depois diminua +n+. Quando chegar a 0, imprima a palavra Vai!"
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Formalmente, aqui está o fluxo de execução de uma atribuição +while+:
```suggestion
Formalmente, aqui está o fluxo de execução de uma declaração +while+:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +. Se for falsa, saia da atribuição _while_ e continue a execução para o próximo comando.
```suggestion
. Se for falsa, saia da declaração _while_ e continue a execução para o próximo comando.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O corpo do laço deve mudar o valor de uma ou mais variáveis até que a condição eventualmente se torna falsa e o laço é finalizado. Caso contrário, o laço irá se repetir para sempre, que é um _laço in
```suggestion
O corpo do laço deve mudar o valor de uma ou mais variáveis até que eventualmente a condição se torna falsa e o laço é finalizado. Caso contrário, o laço irá se repetir para sempre, que é um _laço infinito_. Uma fonte inesgotável de diversão para os cientistas da computação são as instruções nos frascos de shampoo, “ensaboar, enxaguar, repetir”, que é um laço infinito.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +No caso da +contagem_regressiva+, podemos provar que o laço é finalizado: se +n+ é zero ou negativo, o laço nunca termina. Caso contrário, +n+ vai diminuindo através do laço, e então eventualmente ch
```suggestion
No caso da +contagem_regressiva+, podemos provar que o laço é finalizado: se +n+ é zero ou negativo, o laço nunca termina. Caso contrário, +n+ vai diminuindo durante o laço, e então eventualmente chegará a 0.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A cada turno do laço, o programa tem como saída o valor +n+ que é verificado se é par ou ímpar. Se for par, +n+ é divisível por 2. Se é ímpar, o valor de +n+ é substituído por +pass:[n*3 + 1]+. Por e
```suggestion
A cada turno do laço, o programa tem como saída o valor +n+ que é verificado se é par ou ímpar. Se for par, +n+ é dividido por 2. Se é ímpar, o valor de +n+ é substituído por +pass:[n*3 + 1]+. Por exemplo, se o argumento da sequência é 3, os valores de +n+ recebidos são 3, 10, 5, 16, 8, 4, 2, 1.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Já que +n+ as vezes cresça e as vezes decresça, não existe uma demonstração óbvia de que +n+ alcançará 1, ou que o programa termine. Para alguns valores particulares de +n+, podemos demonstrar que te
```suggestion
Já que +n+ às vezes cresce e às vezes decresce, não existe uma demonstração óbvia de que +n+ resultará em 1, ou que o programa termine. Para alguns valores particulares de +n+, podemos demonstrar que termina. Por exemplo, se o valor inicial é uma potência de dois, +n+ será sempre par durante o laço até que resulta em 1. O exemplo anterior finaliza essa sequência, a partir de 16.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A parte difícil é se podemos provar que esse programa finaliza para todos os valores positivos de +n+. Portanto, até agora ninguém foi capaz de provar ou desprovar isso! (consulte https://en.wikipedi
```suggestion
A parte difícil é se podemos provar que esse programa finaliza para todos os valores positivos de +n+. Até agora ninguém foi capaz de provar ou desprovar isso! (consulte https://pt.wikipedia.org/wiki/Conjectura_de_Collatz.)
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Reescreva a função +imprima_n+ de <<Recursão>> usando iteração ao invés de recursão.
```suggestion
Reescreva a função +imprima_n+ de <<recursion>> usando iteração ao invés de recursão.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((break)))((("palavra-chave", "parada", see="parada")))(((declaração break)))((("atribuição", "parada", see="declaração break")))
```suggestion
(((break)))((("palavra-chave", "break", see="break")))(((declaração break)))((("declaração", "break", see="declaração break")))
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Por exemplo, suponha que você quer receber entradas do usuário até que ele digite concluído. Você poderia escrever:
```suggestion
Por exemplo, suponha que você quer receber entradas do usuário até que ele digite concluído. Poderia-se escrever:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A condição deste laço é +true+, o que ocorre sempre, então o laço irá ser executado até chegar na declaração break.
```suggestion
A condição deste laço é +true+, que é sempre verdade, então o laço será executado até chegar na declaração break.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A cada iteração, a solicitação ao usuário ocorre por meio de um sinal de maior (">"). Se o usuário digitar +concluído+, então o comando break finaliza o laço. Caso contrário, o programa mostrará o qu
```suggestion
A cada iteração, a solicitação ao usuário ocorre por meio de um sinal de maior (">"). Se o usuário digitar +concluído+, então a declaração break finaliza o laço. Caso contrário, o programa mostrará o que o usuário digitar e voltará ao topo do laço. Aqui está uma mostra de execução:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A declaração break sai do laço. Quando uma _declaração continue_ é encontrado dentro de um laço, salta-se para o início do laço para a próxima iteração, pulando a execução de comandos dentro do corpo
```suggestion
A declaração break sai do laço. Quando uma _declaração continue_ é encontrada dentro de um laço, salta-se para o início do laço da próxima iteração, pulando a execução de comandos dentro do corpo do laço da iteração atual. Por exemplo:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((continue)))((("palavra-chave", "continue", see="continue")))(((declaração continue)))((("atribuição", "continuar", see="continuar", see="declaração continue")))
```suggestion
(((continue)))((("palavra-chave", "continue", see="continue")))(((declaração continue)))((("declaração", "continue", see="continue", see="declaração continue")))
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +[[raizes_quadradas]]
```suggestion
[[square_roots]]
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Laços são geralmente usados em programas que computam resultados numéricos começando com um valor aproximado e é refinado iterativamente.
```suggestion
Laços são frequentemente usados em programas que calculam resultados numéricos começando com um valor aproximado e aprimorando-o iterativamente.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Por exemplo, um jeito de computar raízes quadradas é através do Método de Newton. Suponha que você quer saber a raíz quadrada de latexmath:[\(a\)]. Se você começar com quase qualquer uma estimativa,
```suggestion
Por exemplo, um jeito de computar raízes quadradas é através do Método de Newton. Suponha que você quer saber a raiz quadrada de latexmath:[\(a\)]. Se você começar com uma estimativa qualquer, latexmath:[\(x\)], pode-se calcular uma estimativa melhor com a seguinte fórmula:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O resultado está mais próximo da resposta correta (latexmath:[\(\sqrt 4 = 2\)]). Se repetirmos o processo com a nova estimativa, irá ficar mais próximo ainda:
```suggestion
O resultado está mais próximo da resposta correta (latexmath:[\(\sqrt 4 = 2\)]). Se repetirmos o processo com a nova estimativa, ficará mais próximo ainda:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Quando +y == x+, podemos parar. Aqui está um laço que começa com uma estimativa inicial, +x+, e melhora até parar de mudar
```suggestion
Quando +y == x+, podemos parar. Aqui está um laço que começa com uma estimativa inicial +x+, e melhora até parar de mudar:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Esta função funciona bem para a maior parte dos valores de a, mas em geral é perigoso testar igualdade com pontos flutuantes. Pontos flutuantes não são totalmente corretos: a maioria dos números raci
```suggestion
Esta função funciona bem para a maior parte dos valores de a, mas em geral é perigoso testar igualdade com pontos flutuantes. Pontos flutuantes não são totalmente corretos: a maioria dos números racionais, como latexmath:[\(\frac{1}{3}\)], e números irracionais, como latexmath:[\(\sqrt 2\)], não podem ser representados exatamente com um tipo +Float64+.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Mas se você fosse "preguiçoso", talvez tivesse aprendido alguns truques. Por exemplo, para encontrar o produto de latexmath:[\(n\)] e 9, você escreve latexmath:[\(n-1\)] no primeiro dígito e latexmat
```suggestion
Mas se você fosse "preguiçoso", talvez tivesse aprendido alguns truques. Por exemplo, para encontrar o produto de latexmath:[\(n\)] e 9, você pode escrever latexmath:[\(n-1\)] no primeiro dígito e latexmath:[\(10-n\)] no segundo dígito. Esse truque é uma solução geral para multiplicar qualquer unidade por 9. Isso é um algoritmo!
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Similarmente, as técnicas que você aprendeu para a adição com transporte de unidades, a subtração com empréstimos e a divisão longa são todos algoritmos. Uma das características dos algoritmos é que
```suggestion
Similarmente, as técnicas que você aprendeu para a adição com transporte de unidades, a subtração com empréstimos e a divisão longa são todos algoritmos. Uma das características dos algoritmos é que eles não exigem nenhuma inteligência para serem executados. São processos mecânicos em que cada passo segue a partir do último, de acordo com um conjunto simples de regras.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Apesar da execução de algoritmos seja chata, a construção é interessante, intelectualmente desafiadora e uma parte central da ciência da computação.
```suggestion
Apesar da execução de algoritmos ser chata, a construção é interessante, intelectualmente desafiadora e uma parte central da ciência da computação.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Algumas das coisas que as pessoas fazem naturalmente, sem dificuldade ou pensamento consciente, são as mais difíceis de expressar por algoritmos. Compreender a linguagem natural é um bom exemplo. Tod
```suggestion
Algumas das coisas que as pessoas fazem naturalmente, sem dificuldade ou conscientemente pensado, são as mais difíceis de expressar por algoritmos. Compreender a linguagem natural é um bom exemplo. Todos fazemos isso, mas até agora ninguém foi capaz de explicar como fazemos, pelo menos não na forma de um algoritmo.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Em vez disso, tente quebrar o problema ao meio. Olhe no meio do programa, ou perto dele, para um valor intermediário que você pode verificar. Adicione um comando print (ou qualquer outra coisa que te
```suggestion
Em vez disso, tente quebrar o problema ao meio. Olhe no meio do programa, ou perto dele, para um valor intermediário que você pode verificar. Adicione um comando print (ou qualquer outra coisa que tenha um propósito de verificação) e execute o programa.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Toda vez que você executa uma verificação como essa, reduz_-se_ pela metade o número de linhas que precisa averiguar. Após seis etapas (que é menor que 100), você reduziria para uma ou duas linhas de
```suggestion
Toda vez que você executa uma verificação como essa, reduz-se pela metade o número de linhas que precisa averiguar. Após seis etapas (que é menor que 100), você reduziria para uma ou duas linhas de código, pelo menos em teoria.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +declaração dentro de um laço que salta para o início do laço para a próxima iteração.
```suggestion
Declaração dentro de um laço que salta para o início do laço da próxima iteração.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Um laço no qual a sua condição nunca é satisfeita.
```suggestion
Um laço no qual a sua condição de parada nunca é satisfeita.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Copie o laço de <<square_roots>> e encapsule-o em uma função chamada +minha_raiz+ que use a variável +a+ como parâmetro, e escolha um valor razoável de +x+ que retorne uma estimativa da raiz quadrada
```suggestion
Copie o laço de <<square_roots>> e encapsule-o em uma função chamada +minha_raiz+ que use a variável +a+ como um parâmetro, e escolha um valor razoável de +x+ que retorne uma estimativa da raiz quadrada de +a+.
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((minha_raiz)))((("função", "definido pelo programador", "minha_raiz", see = "minha_raiz"))))
```suggestion
(((minha_raiz)))((("função", "definido pelo programador", "minha_raiz", see="minha_raiz")))
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((testa_raiz)))((("função", "definido pelo programador", "testa_raiz", see="testa_raiz"))))
```suggestion
(((testa_raiz)))((("função", "definido pelo programador", "testa_raiz", see="testa_raiz")))
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +[fonte, @ julia-eval]
```suggestion
[source, @ julia-eval]
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +fora = String(take!(io))
Eu acho q o "out" é de output (resultado). Se sim, é melhor traduzir out para "res".

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A função interna +Meta.parse+ pega uma string e a transforma em uma expressão. Essa expressão pode ser avaliada em Julia com a função +Core.eval+. Por exemplo:
```suggestion
A função interna +Meta.parse+ pega uma string e transforma-a em uma expressão. Essa expressão pode ser avaliada em Julia com a função +Core.eval+. Por exemplo:
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((parse)))((("função","Meta","parse", see="parse"))) (((eval)))((("function", "Core", "eval", see="eval")))
```suggestion
(((parse)))((("função","Meta","parse", see="parse")))(((eval)))((("função", "Core", "eval", see="eval")))
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +[fonte, @ julia-eval chap07]
```suggestion
[source,@julia-eval chap07]
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +[fonte, @ julia-repl-test chap07]
```suggestion
[source,@julia-repl-test chap07]
```

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +julia> eval (expr)
Arrumar esses espaços adicionais colocado no código de Julia da linha 430 até linha 436.

2020-06-05 04:34 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Escreva uma função chamada +avalie_laço+ que solicite iterativamente ao usuário, e então pegue a entrada recebida, avalie-na usando +eval+ e depois imprima o resultado. Ele deve continuar até o usuár
```suggestion
Escreva uma função chamada +avalie_laço+ que solicite iterativamente ao usuário, e então pegue a entrada recebida, avalie-na usando +eval+ e depois imprima o resultado. Ele deve continuar até o usuário digitar +concluído+ e depois retornar o valor da última expressão avaliada.
```

2020-06-06 04:00 UTC, chunggnuhc requested changes

2020-06-06 04:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +=== Debugando
```suggestion
=== Depuração
```

2020-06-06 04:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Ao começar a escrever programas maiores, você pode passar mais tempo debugando. Mais código significa mais chances de cometer um erro e mais lugares para os erros se esconderem.
```suggestion
Ao começar a escrever programas maiores, você pode passar mais tempo depurando. Mais código significa mais chances de cometer um erro e mais lugares para os erros se esconderem.
```

2020-06-06 04:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((debugando)))
```suggestion
(((depuração)))
```

2020-06-06 04:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Uma maneira de reduzir o tempo do debugging é o “debugging por bissecção”. Por exemplo, se houver 100 linhas no seu programa e você verificá-las uma de cada vez, serão necessárias 100 etapas.
```suggestion
Uma maneira de reduzir o tempo da depuração é a “depuração por bissecção”. Por exemplo, se houver 100 linhas no seu programa e você verificá-las uma de cada vez, serão necessárias 100 etapas.
```

2020-06-06 04:00 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((debugging por bissecção)))
```suggestion
(((depuração por bissecção)))
```

2020-06-06 20:56 UTC, gustavosarturi reviewed
Realizando Auto-Revisão, não revisar.

2020-06-10 00:08 UTC, gustavosarturi commented on book/src/chap07.asciidoc
>  === Depuração
```suggestion
=== Depurando
```

2020-06-10 00:09 UTC, gustavosarturi commented on book/src/chap07.asciidoc
>  === Depuração
Apenas alterando 'Debugging" para "Depurando".

2020-06-11 03:13 UTC, chunggnuhc requested changes

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Esse capítulo é sobre iteração, que é a habilidade de executar um bloco de argumentos repetidamente. Vimos um tipo de iteração usando recursão em <<recursion>>. Vimos também outro tipo, usando um laç
```suggestion
Esse capítulo é sobre iteração, que é a habilidade de executar um bloco de argumentos repetidamente. Vimos um tipo de iteração usando recursão em <<recursion>>. Vimos também outro tipo, usando um laço +for+ em <<simple_repetition>>. Neste capítulo, veremos um outro tipo, que usa uma declaração +while+ (_enquanto_ em Português). Mas antes temos que falar um pouco mais sobre atribuição de variável.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((iteração)))(((recursão)))(((comando for)))
```suggestion
(((iteração)))(((recursão)))(((declaração for)))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Primeiro que, a igualdade é uma relação simétrica e a atribuição não é. Por exemplo, em matemática, se latexmath:[\(a=7\)] então latexmath:[\(7=a\)]. Mas em Julia, a atribuição +a=7+ é permitida e +7
```suggestion
Primeiro que a igualdade é uma relação simétrica e a atribuição não é. Por exemplo, em matemática, se latexmath:[\(a=7\)] então latexmath:[\(7=a\)]. Mas em Julia, a atribuição +a=7+ é permitida e +7=a+ não.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A reatribuição de variáveis geralmente é útil, mas, você deve usá-la com cuidado. Se os valores das variáveis mudarem com frequência, isso pode dificultar a leitura e a depuração do código.
```suggestion
A reatribuição de variáveis geralmente é útil, mas você deve usá-la com cuidado. Se os valores das variáveis mudarem com frequência, isso pode dificultar a leitura e a depuração do código.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +=== O Comando +while+
```suggestion
=== A Declaração +while+
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Já vimos duas funções, +contador_regressivo+ e +imprima_n+, que iteram usando recursão. Como a iteração é muito comum, Julia dispõe de recursos para simplificá-la. Um deles é o comando +for+ que vimo
```suggestion
Já vimos duas funções, +contador_regressivo+ e +imprima_n+, que iteram usando recursão. Como a iteração é muito comum, Julia dispõe de recursos para simplificá-la. Um deles é a declaração +for+ que vimos em <<simple_repetition>>. Voltaremos a este assunto mais tarde.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((recursão)))(((comando for)))
```suggestion
(((recursão)))(((declaração for)))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O outro é a _comando_ +while+. Aqui está a versão do +contagem_regressiva+ que utiliza o comando +while+:
```suggestion
A outra é a _declaração_ +while+. Aqui está a versão de +contagem_regressiva+ que utiliza a declaração +while+:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((while)))((("palavra-chave", "while", see="while")))(((comando while)))((("comando", "while", see="comando while")))
```suggestion
(((while)))((("palavra-chave", "while", see="while")))(((declaração while)))((("declaração", "while", see="declaraçao while")))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +    println("Feliz Ano Novo!")
```suggestion
    println("Decolar!")
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Você pode ler quase toda o comando +while+ como se estivesse em inglês. Isso significa que "Enquanto +n+ for maior que 0, exiba o valor de +n+ e depois diminua +n+. Quando chegar a 0, imprima a a fra
```suggestion
Você pode ler quase toda a declaração +while+ como se estivesse em inglês. Isso significa que “Enquanto +n+ for maior que 0, exiba o valor de +n+ e depois diminua +n+. Quando chegar a 0, imprima a palavra Decolar!”
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Formalmente, segue abaixo o fluxo de execução de um comando +while+:
```suggestion
Formalmente, segue abaixo o fluxo de execução de uma declaração +while+:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Você talvez tenha descoberto que é permitido fazer mais de uma atribuição para as mesmas variáveis. Uma nova atribuição faz com que uma variável existente se refira a um novo valor (e pare de se refe
```suggestion
Como você deve ter descoberto, é permitido fazer mais de uma atribuição para as mesmas variáveis. Uma nova atribuição faz com que uma variável existente se refira a um novo valor (e pare de se referir ao valor antigo).
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Um tipo comum de reatribuição é uma atualização, onde o novo valor da variável depende da antiga.
```suggestion
Um tipo comum de reatribuição é uma atualização, onde o novo valor da variável depende do antigo.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +. Se for falsa, saia do comando _while_ e continue a execução para a próxima instrução.
```suggestion
. Se for falsa, saia do comando _while_ e continue a execução para o próximo comando.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +. Se a condição for verdadeira, execute os comandos e então volte para o passo 1.
```suggestion
. Se a condição for verdadeira, execute os comandos do corpo e então volte para o passo 1.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A condição para esse laço é +n != 1+, então esse laço irá continuar até que +n+ atinja 1, o que faz a condição ser falsa.
```suggestion
A condição para esse laço é +n != 1+, então esse laço irá continuar até que +n+ seja 1, o que faz a condição ser falsa.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A cada turno do laço, o programa tem como saída o valor +n+ que é verificado se é par ou ímpar. Se for par, +n+ é dividido por 2. Se é ímpar, o valor de +n+ é substituído por +pass:[n*3 + 1]+. Por ex
```suggestion
A cada turno do laço, o programa tem como saída o valor +n+ que é verificado se é par ou ímpar. Se é par, +n+ é dividido por 2. Se é ímpar, o valor de +n+ é substituído por +pass:[n*3 + 1]+. Por exemplo, se o argumento da sequência é 3, os valores de +n+ recebidos são 3, 10, 5, 16, 8, 4, 2, 1.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Já que +n+ às vezes cresce e às vezes decresce, não existe uma demonstração óbvia de que +n+ resultará em 1 ou que o programa termine. Para alguns valores particulares de +n+, podemos demonstrar que
```suggestion
Já que +n+ às vezes cresce e às vezes decresce, não existe uma demonstração óbvia de que +n+ resultará em 1 ou que o programa termine. Para alguns valores particulares de +n+, podemos demonstrar que termina. Por exemplo, se o valor inicial é uma potência de dois, +n+ será sempre par durante o laço até que chega em 1. O exemplo anterior finaliza essa sequência, a partir de 16.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A parte difícil é provar que esse programa finaliza para todos os valores positivos de +n+. Até agora ninguém foi capaz de provar ou desprovar isso! (consulte https://pt.wikipedia.org/wiki/Conjectura
```suggestion
A parte difícil é provar que esse programa finaliza para todos os valores positivos de +n+. Até agora ninguém foi capaz de provar ou desprovar isso! (Consulte https://pt.wikipedia.org/wiki/Conjectura_de_Collatz.)
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Às vezes, você não sabe que é hora de terminar um laço até chegar na metade do corpo. Neste caso você pode utilizar o _comando break_ para sair do laço.
```suggestion
Às vezes, você não sabe que é hora de terminar um laço até chegar na metade do corpo. Neste caso você pode utilizar a _declaração break_ para sair do laço.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((break)))((("palavra-chave", "break", see="break")))(((comando break)))((("comando", "break", see="comando break")))
```suggestion
(((break)))((("palavra-chave", "break", see="break")))(((declaração break)))((("declaração", "break", see="declaração break")))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Por exemplo, suponha que você quer receber entradas do usuário até que ele digite concluído. Poderia-se escrever:
```suggestion
Por exemplo, suponha que você queira receber entradas do usuário até que ele digite concluído. Poderia-se escrever:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A condição deste laço é +true+, que é sempre verdade, então o laço será executado até chegar no comando break.
```suggestion
A condição deste laço é +true+, que é sempre verdade, então o laço será executado até chegar na declaração break.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A cada iteração, a solicitação ao usuário ocorre por meio de um sinal de maior (">"). Se o usuário digitar +concluído+, então o comando break finaliza o laço. Caso contrário, o programa mostrará o qu
```suggestion
A cada iteração, a solicitação ao usuário ocorre por meio de um sinal de maior (">"). Se o usuário digitar +concluído+, então a declaração break finaliza o laço. Caso contrário, o programa mostrará o que o usuário digitar e voltará ao topo do laço. Aqui está um exemplo de execução:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Essa maneira de escrever laços é comum porque você pode verificar a condição em qualquer lugar do laço (não apenas no topo) e você pode expressar a condição de parada afirmativamente ("pare quando is
```suggestion
Essa maneira de escrever laços é comum porque você pode verificar a condição em qualquer lugar do laço (não apenas no topo) e você pode expressar a condição de parada afirmativamente ("pare quando isso acontecer") ao invés de negativamente ("continue enquanto isso acontece").
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O comando break sai do laço. Quando um _comando continue_ é encontrado dentro de um laço, salta-se para o início do laço da próxima iteração, pulando a execução de comandos dentro do corpo do laço da
```suggestion
A declaração break sai do laço. Quando uma _declaração continue_ é encontrado dentro de um laço, salta-se para o início do laço da próxima iteração, pulando a execução de comandos dentro do corpo do laço da iteração atual. Por exemplo:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((continue)))((("palavra-chave", "continue", see="continue")))(((comando continue)))((("comando", "continue", see="continue", see="comando continue")))
```suggestion
(((continue)))((("palavra-chave", "continue", see="continue")))(((declaração continue)))((("declaração", "continue", see="continue", see="declaração continue")))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Se +i+ é divisível por 3, o comando continue para na iteração atual e a próxima iteração é iniciada. Apenas os números no intervalo entre 1 a 10 não divisíveis por 3 são exibidos.
```suggestion
Se +i+ é divisível por 3, a declaração continue para na iteração atual e a próxima iteração é iniciada. Apenas os números no intervalo entre 1 a 10 não divisíveis por 3 são exibidos.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Por exemplo, uma maneira de computar raízes quadradas é através do Método de Newton. Suponha que você queira saber a raíz quadrada de latexmath:[\(a\)]. Se você começar com uma estimativa qualquer, l
```suggestion
Por exemplo, uma maneira de computar raízes quadradas é através do método de Newton. Suponha que você queira saber a raíz quadrada de latexmath:[\(a\)]. Se você começar com uma estimativa qualquer, latexmath:[\(x\)], pode-se calcular uma estimativa melhor com a seguinte fórmula:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((Método de Newton)))
```suggestion
(((método de Newton)))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Depois de mais algumas atualizações a estimativa é quase exata:
```suggestion
Depois de mais algumas atualizações, a estimativa é quase exata:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +O Método de Newton é um exemplo de um _algoritmo_: Um processo mecânico para resolver uma categoria de problemas (nesse caso, o cálculo de raízes quadradas).
```suggestion
O método de Newton é um exemplo de um _algoritmo_: um processo mecânico para resolver uma categoria de problemas (nesse caso, o cálculo de raízes quadradas).
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Para entender o que é um algoritmo, talvez seja interessante mostrar algo que não é um algoritmo. Quando você aprendeu a multiplicar unidades, você provavelmente memorizou a tabuada. De fato, você me
```suggestion
Para entender o que é um algoritmo, talvez seja interessante começar com algo que não é um algoritmo. Quando você aprendeu a multiplicar unidades, você provavelmente memorizou a tabuada. De fato, você memorizou 100 soluções específicas. Esse tipo de conhecimento não é um algoritmo.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Algumas das coisas que as pessoas fazem naturalmente, sem dificuldade ou conscientemente pensado, são as mais difíceis de expressar por algoritmos. Compreender a linguagem nativa é um bom exemplo. To
```suggestion
Algumas das coisas que as pessoas fazem naturalmente, sem dificuldade ou conscientemente pensado, são as mais difíceis de expressar por algoritmos. Compreender a linguagem natural é um bom exemplo. Todos nós fazemos isso, mas até agora ninguém foi capaz de explicar _como_ fazemos, pelo menos não na forma de um algoritmo.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
>  === Depuração
@abelsiqueira , resolve aí.

Tanto a tradução espanhol como o Pense Python em português está escrito depuração.

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Ao começar a escrever programas maiores, você pode passar mais tempo depurando. Mais código significa mais chances de cometer um erro e mais lugares para os erros se esconderem.
```suggestion
Ao começar a escrever programas maiores, você pode passar mais tempo com a depuração. Mais código significa mais chances de cometer um erro e mais lugares para os erros se esconderem.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Uma maneira de reduzir o tempo da depuração é “depurar por bissecção”. Por exemplo, se houver 100 linhas no seu programa e você verificá-las uma de cada vez, serão necessárias 100 etapas.
```suggestion
Uma maneira de reduzir o tempo da depuração é a “depuração por bissecção”. Por exemplo, se houver 100 linhas no seu programa e você verificá-las uma de cada vez, serão necessárias 100 etapas.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((depurar por bissecção)))
```suggestion
(((depuração por bissecção)))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Toda vez que você executa uma verificação como essa, reduz-se pela metade o número de linhas que precisa averiguar. Após seis etapas (que é menor que 100), você reduziria para uma ou duas linhas de c
```suggestion
Toda vez que você executa uma verificação como essa, reduz-se pela metade o número de linhas que se precisa averiguar. Após seis etapas (que é menor que 100), você reduziria para uma ou duas linhas de código, pelo menos em teoria.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Na prática, nem sempre é claro onde é o "meio do programa" e nem sempre é possível verificá-lo. Não faz sentido contar linhas e encontrar o ponto médio exato. Em vez disso, pense nos locais do progra
```suggestion
Na prática, nem sempre é claro onde é o "meio do programa" e nem sempre é possível verificá-lo. Não faz sentido contar linhas e encontrar o ponto médio exato. Em vez disso, pense nos locais do programa em que pode haver erros e nos locais onde é fácil fazer uma verificação. Em seguida, escolha um local onde você acha que as chances são as mesmas de que o erro seja antes ou depois da verificação.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Uma atualização que aumenta o valor de uma variável (geralmente em um).
```suggestion
Uma atualização que aumenta o valor de uma variável (frequentemente em um).
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +comando while::
```suggestion
declaração while::
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((comando while)))
```suggestion
(((declaração while)))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +comando break::
```suggestion
declaração break::
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((comando break)))
```suggestion
(((declaração break)))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +comando continue::
```suggestion
declaração continue::
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((comando continue)))
```suggestion
(((declaração continue)))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Copie o laço de <<square_roots>> e encapsule-o em uma função chamada +minha_raíz+ que usa a variável +a+ como um parâmetro e escolha um valor razoável de +x+ que retorne uma estimativa da raíz quadra
```suggestion
Copie o laço de <<square_roots>> e encapsule-o em uma função chamada +minha_raiz+ que usa a variável +a+ como um parâmetro e escolha um valor razoável de +x+ que retorne uma estimativa da raíz quadrada de +a+.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((minha_raíz)))((("função", "definido pelo programador", "minha_raíz", see="minha_raíz")))
```suggestion
(((minha_raiz)))((("função", "definido pelo programador", "minha_raiz", see="minha_raiz")))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Para testá-la, escreva uma função chamada +testa_raíz+ que imprime uma tabela como esta:
```suggestion
Para testá-la, escreva uma função chamada +avalia_raiz_quadrada+ que imprime uma tabela como esta:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((testa_raíz)))((("função", "definido pelo programador", "testa_raíz", see="testa_raíz")))
```suggestion
(((avalia_raiz_quadrada)))((("função", "definido pelo programador", "avalia_raiz_quadrada", see="avalia_raiz_quadrada")))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +testa_raíz(io)
```suggestion
avalia_raiz_quadrada(io)
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A primeira coluna é um número, +a+; a segunda coluna é a raíz quadrada de +a+ calculado com +minha_raíz+; a terceira coluna é a raíz quadrada calculada por +sqrt+; a quarta coluna é o valor absoluto
```suggestion
A primeira coluna é um número, +a+; a segunda coluna é a raíz quadrada de +a+ calculado com +minha_raiz+; a terceira coluna é a raiz quadrada calculada por +sqrt+; a quarta coluna é o valor absoluto da diferença entre as duas estimativas.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A função interna +Meta.parse+ pega uma string e transforma-a em uma expressão. Essa expressão pode ser avaliada em Julia com a função +Core.eval+. Por exemplo:
```suggestion
A função interna +Meta.parse+ recebe uma string e transforma-a em uma expressão. Essa expressão pode ser avaliada em Julia com a função +Core.eval+. Por exemplo:
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +(((parse)))((("função","Meta","parse", see="parse")))(((eval)))((("função", "Core", "eval", see="eval")))
```suggestion
(((parse)))((("função", "Meta", "parse", see="parse")))(((eval)))((("função", "Core", "eval", see="eval")))
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Escreva uma função chamada +avalie_laço+ que solicite iterativamente ao usuário e então pegue a entrada recebida, avalie-na usando +eval+ e depois imprima o resultado. A função deve continuar até o u
```suggestion
Escreva uma função chamada +avalie_laço+ que solicite iterativamente ao usuário, pegue a entrada recebida e avalie-a usando +eval+ e depois imprime o resultado. A função deve continuar até o usuário digitar +concluído+ e depois retornar o valor da última expressão avaliada.
```

2020-06-11 03:13 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Escreva uma função chamada +estimativa_pi+ que use essa fórmula para calcular e retornar uma estimativa de π. Ele deve usar um laço while para calcular os termos da soma até que o último termo seja m
```suggestion
Escreva uma função chamada +estimativa_pi+ que use essa fórmula para calcular e retornar uma estimativa de π. Ele deve usar um laço while para calcular os termos da soma até que o último termo seja menor que +1e-15+ (que é a notação do Julia para latexmath:[\(10^{-15}\)]). Você pode verificar o resultado comparando-o com +π+.
```

2020-06-11 14:29 UTC, gustavosarturi commented on book/src/chap07.asciidoc
>  === Depuração
Então vamos manter "Depuração".

2020-06-11 15:40 UTC, abelsiqueira commented on book/src/chap07.asciidoc
>  === Depuração
@chunggnuhc, eu te coloquei como Reviewer de #29, que é esse assunto.

2020-06-11 18:45 UTC, chunggnuhc commented on book/src/chap07.asciidoc
>  === Depuração
@abelsiqueira mandou deixar "Depurando".

2020-06-19 15:23 UTC, gustavosarturi commented
@chunggnuhc - A maior parte da revisão anterior foi alteração de **_comando_** para _**declaração**_. Acredito que após a sua revisão, já podemos repassar pro Abel.

2020-06-25 02:45 UTC, chunggnuhc requested changes

2020-06-25 02:45 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Por exemplo, uma maneira de computar raízes quadradas é através do método de Newton. Suponha que você queira saber a raíz quadrada de latexmath:[\(a\)]. Se você começar com uma estimativa qualquer, l
```suggestion
Por exemplo, uma maneira de computar raízes quadradas é através do método de Newton. Suponha que você queira saber a raiz quadrada de latexmath:[\(a\)]. Se você começar com uma estimativa qualquer, latexmath:[\(x\)], pode-se calcular uma estimativa melhor com a seguinte fórmula:
```

2020-06-25 02:45 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +=== Depurando
```suggestion
=== Depuração
```

2020-06-25 02:45 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +Copie o laço de <<square_roots>> e encapsule-o em uma função chamada +minha_raiz+ que usa a variável +a+ como um parâmetro e escolha um valor razoável de +x+ que retorne uma estimativa da raíz quadra
```suggestion
Copie o laço de <<square_roots>> e encapsule-o em uma função chamada +minha_raiz+ que usa a variável +a+ como um parâmetro e escolha um valor razoável de +x+ que retorne uma estimativa da raiz quadrada de +a+.
```

2020-06-25 02:45 UTC, chunggnuhc commented on book/src/chap07.asciidoc
> +A primeira coluna é um número, +a+; a segunda coluna é a raíz quadrada de +a+ calculado com +minha_raiz+; a terceira coluna é a raiz quadrada calculada por +sqrt+; a quarta coluna é o valor absoluto
```suggestion
A primeira coluna é um número, +a+; a segunda coluna é a raiz quadrada de +a+ calculado com +minha_raiz+; a terceira coluna é a raiz quadrada calculada por +sqrt+; a quarta coluna é o valor absoluto da diferença entre as duas estimativas.
```

2020-06-29 22:41 UTC, chunggnuhc commented
Approved.

2020-06-29 22:45 UTC, chunggnuhc commented
@abelsiqueira , já faz essas 2 pequenas correções.

Linha 321:
```suggestion
Mas se você fosse “preguiçoso”, talvez tivesse aprendido alguns truques. Por exemplo, para encontrar o produto de latexmath:[\(n\)] e 9, você pode escrever latexmath:[\(n-1\)] no primeiro dígito e latexmath:[\(10-n\)] no segundo dígito. Esse truque é uma solução geral para multiplicar qualquer unidade por 9. Isso é um algoritmo!
```

Linha 415:
```suggestion
A primeira coluna é um número, +a+; a segunda coluna é a raiz quadrada de +a+ calculada com +minha_raiz+; a terceira coluna é a raiz quadrada calculada por +sqrt+; a quarta coluna é o valor absoluto da diferença entre as duas estimativas.
```

2020-06-30 01:42 UTC, gustavosarturi commented
https://github.com/JuliaIntro/JuliaIntroBR.jl/pull/17#issuecomment-651408001 - @chunggnuhc @abelsiqueira Resolvido.

2020-07-03 17:16 UTC, chunggnuhc approved these changes

2020-07-07 14:31 UTC, abelsiqueira approved these changes
Farei as mudanças eu mesmo.

2020-07-07 14:31 UTC, abelsiqueira commented on book/src/chap07.asciidoc
> +Neste ponto, quero abordar um assunto comum de confusão. Como o Julia usa o sinal de igual (+=+) para a atribuição, é tentador interpretar uma afirmação como +a = b+ como uma proposição matemática de
```suggestion
Neste ponto, queremos abordar um assunto comum de confusão. Como o Julia usa o sinal de igual (+=+) para a atribuição, é tentador interpretar uma afirmação como +a = b+ como uma proposição matemática de igualdade; isto é, a afirmação de que +a+ e +b+ são iguais. Mas essa interpretação está errada.
```

2020-07-07 14:31 UTC, abelsiqueira commented on book/src/chap07.asciidoc
> +Isso significa “pegar o valor atual de +x+, adicionar um, e então atualizar +x+ ao novo valor.”
```suggestion
Isso significa “pegue o valor atual de +x+, adicione um, e então atualize +x+ ao novo valor.”
```

2020-07-07 14:31 UTC, abelsiqueira commented on book/src/chap07.asciidoc
> +Você pode ler quase toda a declaração +while+ como se estivesse em inglês. Isso significa que “Enquanto +n+ for maior que 0, exiba o valor de +n+ e depois diminua +n+. Quando chegar a 0, imprima a pa
```suggestion
Você pode ler a declaração +while+ quase como se estivesse em Português, traduzindo _while_ por _enquanto_. Ela significa “Enquanto +n+ for maior que 0, exiba o valor de +n+ e depois diminua +n+. Quando chegar a 0, imprima a palavra Decolar!”
```

2020-07-07 14:31 UTC, abelsiqueira commented on book/src/chap07.asciidoc
> +O corpo do laço deve mudar o valor de uma ou mais variáveis até que eventualmente a condição se torna falsa e o laço é finalizado. Caso contrário, o laço irá se repetir para sempre, ou seja, um _laço
```suggestion
O corpo do laço deve mudar o valor de uma ou mais variáveis até que eventualmente a condição se torna falsa e o laço é finalizado. Caso contrário, o laço irá se repetir para sempre, ou seja, um _laço infinito_. Uma fonte inesgotável de diversão para os cientistas da computação são as instruções nos frascos de shampoo, “ensaboe, enxague, repita”, pois é um laço infinito.
```

2020-07-07 14:31 UTC, abelsiqueira commented on book/src/chap07.asciidoc
> +A cada turno do laço, o programa tem como saída o valor +n+ que é verificado se é par ou ímpar. Se é par, +n+ é dividido por 2. Se é ímpar, o valor de +n+ é substituído por +pass:[n*3 + 1]+. Por exem
```suggestion
A cada passada do laço, o programa tem como saída o valor +n+ que é verificado se é par ou ímpar. Se é par, +n+ é dividido por 2. Se é ímpar, o valor de +n+ é substituído por +pass:[n*3 + 1]+. Por exemplo, se o argumento da sequência é 3, os valores de +n+ recebidos são 3, 10, 5, 16, 8, 4, 2, 1.
```

2020-07-07 14:31 UTC, abelsiqueira commented on book/src/chap07.asciidoc
> +Por exemplo, uma maneira de computar raízes quadradas é através do método de Newton. Suponha que você queira saber a raiz quadrada de latexmath:[\(a\)]. Se você começar com uma estimativa qualquer, l
```suggestion
Por exemplo, uma maneira de calcular raízes quadradas é através do método de Newton. Suponha que você queira saber a raiz quadrada de latexmath:[\(a\)]. Se você começar com uma estimativa qualquer, latexmath:[\(x\)], pode-se calcular uma estimativa melhor com a seguinte fórmula:
```

2020-07-07 14:31 UTC, abelsiqueira commented on book/src/chap07.asciidoc
> +[source, @ julia-eval]
```suggestion
[source,@julia-eval]
```

2020-07-07 14:31 UTC, abelsiqueira commented on book/src/chap07.asciidoc
> +(((estimativa_pi)))((("função", "definido pelo programador", "estimativa_pi", see="estimativa_pi"))))
```suggestion
Escreva uma função chamada +estima_pi+ que use essa fórmula para calcular e retornar uma estimativa de π. Ela deve usar um laço while para calcular os termos da soma até que o último termo seja menor que +1e-15+ (que é a notação do Julia para latexmath:[\(10^{-15}\)]). Você pode verificar o resultado comparando-o com +π+.
(((estima_pi)))((("função", "definido pelo programador", "estima_pi", see="estima_pi"))))
```

2020-07-07 14:34 UTC, merged