Chapter 10 - PTBR
JuliaIntro/JuliaIntroBR.jl pull request #18
Opened 2020-05-11 23:39 UTC by gustavosarturi

2020-05-18 19:02 UTC, joaoluisro requested changes
primeira revisão.

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Como uma string, ua _lista_ é uma sequência de valores. Em uma string, os valores são caracteres; em um vetor, pode ser de qualquer tipo. Os valores de um vetor são chamados de _elementos_ ou por vez
ua -> uma

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Como uma string, ua _lista_ é uma sequência de valores. Em uma string, os valores são caracteres; em um vetor, pode ser de qualquer tipo. Os valores de um vetor são chamados de _elementos_ ou por vez
"em um vetor, pode ser de qualquer tipo .." -> "em um vetor, eles podem ser de qualquer tipo .."

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((vetor vazio)))
"vetor vazio" -> "lista vazia"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O tipo de lista é especificado entre as chaves e é composto pelo tipo e um número. O número indica a dimensão. A lista +vazia+ contém valores do tipo +Any+., isto é, pode ser designado a valores de t
"o número indica a dimensão" -> "o número indica as dimensões"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((Listas)))((("tipo", "Base", "Vwtor", see="Array")))(((Any)))((("type", "Base", "Any", see="Any")))
"Vwtor" -> "Lista" ou "Vetor"
" .. , see="Array" " -> ".. , see="Lista" "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Assim como strings, listas são _mutáveis_. Quando os colchetes aparecem no lado esquerdo de uma atribuição, o elemento da lista que está designado é identificado:
"Assim como strings .. " -> "Ao contrário de strings .."
Aqui vale a pena mudar "Quando os colchetes aparecem no lado esquerdo de uma atribuição, o elemento da lista que está designado é identificado: " -> "Quando os colchetes aparecem no lado esquerdo de uma atribuição, eles identificam o elemento da lista que será atribuido:"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Vetores são representados por caixas e os elementos dos vetores dentro. +vegetais+ refere-se a uma lista com três elementos indexados +1+, +2+ e +3+. +números+ contém dois elementos; o diagrama mostr
"Vetores" -> "Listas"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +* Se você tentar ler ou escrever um elemento que não existe, será exibido +BoundsError+
"será exibido" -> "você receberá um"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +=== Atravessando uma Lista
"Atravessando" -> "Percorrendo"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Isso funciona bem se você for apenas ler os alementos de uma lista. Mas se você precisa escrever ou atualizar os elementos, você precisa dos índices. Um jeito comum de fazer isso é utilizando a funçã
"... se você for apenas ler os elementos de uma lista .." -> " ... se você precisa somente ler os elementos de uma lista .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Esse laço atravessa a lista e atualiza cada elemento. +lenght+ retorna o número de elementos de uma lista. Cada vez no laço +i+ obtém o índice do próximo elemento. A declaração de atribuição no corpo
"atravessa" -> "percorre"
"+lenght+" -> "+length+"
"desgina" -> "designa"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Esse laço atravessa a lista e atualiza cada elemento. +lenght+ retorna o número de elementos de uma lista. Cada vez no laço +i+ obtém o índice do próximo elemento. A declaração de atribuição no corpo
"Cada vez no laço +i+ obtém o índice ..." -> "Toda vez que o laço é percorrido +i+ obtém o indíce .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O laço +for+ sobre uma lista vazia nunca executa o corpo:
"O laço +for+ sobre uma lista .. " -> "Utilizar um laço +for+ sobre uma lista .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O Operador de Fatais no lado esquerdo de uma atribuição pode atualizar múltiplos elementos:
"Fatais" -> "Fatias"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Julia fornece função que operam com listas. Por exemplo, +push!+ adiciona um novo elemento no final de uma lista:
"função " -> "funções"
" .. um novo elemento no final .. " -> " .. um novo elemento ao final .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Esse exemplo deixa +t2+ sem modificação.
"modificação" -> "modificações"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((sor!)))((("função", "Base", "sort!", see="sort!")))
"sor!" -> "sort!"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> ++sort_ retorna uma cópia dos elementos da lista em ordem:
"+sort_" -> "+sort+"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Como uma convenção de estilo em Julia, +! + É anexado a nomes de funções que modificam seus argumentos.
tirar o espaço de +! + e maiúscula de "É"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para aumentar todos os números de uma lista, podemos utilizar um laço como o seguinte:
"aumentar" -> "somar"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> ++total+ é iniciado em 0. Cada vez que passa pelo laço, +pass:[+=]+ captura um elemento da lista. O operador +pass:[+=]+ fornece um jeito fácil de atuaizar uma variável. Essa _declaração de atribuição
"Cada vez que passa pelo laço" -> "Toda vez que o laço é percorrido"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Muitas vezes, você deseja percorrer uma lista enquanto cria outra. Por exemplo, a função a seguir pega uma lista de strings e retorna uma nova string que contém strings de caracteres maiúsculas:
".. uma nova string .. " -> " .. uma nova lista .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> ++res+ é inicializada com uma lista vazia; a cada vez no laço, anexamos o próximo elemento. Então, +res+ é outro tipo de acumulador.
"a cada vez no laço " -> "toda vez que o laço é percorrido"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um operador como +todas_maiúsculas+ é por vezes chamado de _mapa_ pois "mapeia" a função (neste caso +maiuscúla+) em cada um dos elementos em uma sequÊncia.
"(neste caso maiuscúla)" -> "(neste caso maiúscula)"
"sequÊncia" -> "sequência"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +        if s == maiúscula(s)
aqui "uppercase" é uma função embutida do julia, então não podemos traduzir.

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um operador como +apenas_maiusculas+ é chamado de _filtro_ pois seleciona alguns dos elementos e filtra em outro.
" .. e filtra em outro. " -> ".. e filtra outros. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para cada operador binário como +pass:[^]+, existe uma correspondente em um _operador ponto_ pass:[<code>.^</code>] que é automaticamente definido para atuar +pass:[^]+ elemento-a-elemento nas listas
"existe uma correspondente em um _operador ponto_ " -> "existe um _operador ponto_ correspondente"

" ... não é definida .. " -> " .. não é definido .. "

" .. é definida computando o resultado elementar .. " -> " .. é definido como calcular elemento a elemento o resultado .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Qualquer função +f+ do Julia pode ter aplicação do resultado elementar de qualquer lista com a _sintaxe do ponto_. Por exemplo, para deiar uma lista de stringas maiúsculas, não precisamos explicitar
" .. pode ter aplicação do resultado elementar ..  " -> " .. pode ser aplicada elemento a elemento à qualquer lista ... "

" .. para deiar uma lista de stringas maiúsculas .. " -> ".. para deixar uma lista de strings com todas as strings em letra maiúscula .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +julia> t = maiúscula.(["abc", "def", "ghi"]);
"maiúscula" -> "uppercase"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Esse é um jeito elegante para criar mapeamentos. A função +todas_maiúsculas+ pode ser implementada de uma única linha:
" .. para criar mapeamentos .. " -> " .. de criar um mapeamento .. "
" ..de uma única linha .. " -> ".. em uma única linha .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +    maiúscula.(t)
maiúscula -> uppercase

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((popfirst!)))((("funlão", "Base", "popfirst!", see="popfirst!")))
"funlão" -> "função"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +A função +pushfirst!+ e +push!+ insere um elemento no início e respectivamente no fim de uma lista.
"insere" -> "inserem" 

" no início e respectivamente no fim .. " -> "no início e no fim de uma lista, respectivamente, .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Se você não precisa remover valores, você pode usar a função +deleteat!+:
"Se você não precisa remover valores .. " -> " Se você não precisa do valor removido .. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((deleteat!)))((("função", "Base", "delete!", see="deleteat!")))
"delete!" -> "deleteat!"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma string é uma sequêncuia de caracteres e uma lista é uma sequência de valores, mas uma lista de caracteres não é o mesmo que uma string. Para converter uma string em uma lista de caracteres, voc~e
"sequêncuia" -> "sequência"
"voc~e" -> "você"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
>  (((collect)))((("function", "Base", "collect", see="collect")))
"function" -> "função"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um _argumento opcional_ chamado _delimitador_ especifica quais caracteres devem ser usados como limites de palavras. Os seguintes exemplos usan um hífen como um delimitador:
"usan" -> "usam"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +No caso o delimitador é um caracter de espaço. Para concatenar strings sem espaços, você não precisa especificar um delimitador.
"caracter" -> "caractere"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um _objeto_ é algo que uma variável pode se refetir. À partir de agora, você pode usar "objeto" e "valor" intercambiavelmente.
" .. uma variável pode se refetir .. " -> " .. uma variável pode se referir a .. "

" À partir de agora, você pode usar "objeto" e "valor"  intercambiavelmente " -> " Desde então, você poderia usar "objeto" e "valor" sem distinção"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Se você execusar estas declrações de atribuições:
"Se você execusar estas declrações de atribuições" -> "Se você executar estas declarações de atribuição"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para verificar se duas variáveis se referem ao mesmo objeto, você pode usar +=+ (*+\equiv TAB+*)  ou o operador +===+.
referem -> referem-se

"você pode usar +=+ (*+\equiv TAB+*)  ou o operador +===+ " -> "você pode usar o operador +=+ (*+\equiv TAB+*) ou +===+. "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Nesse exemplo, Julia criou apenas um objeto de sequência e ambos +a+ e +b+ se referem a ele. Mas quando você cria duas listas, você obtém dois objetos:
"... Julia criou apenas um objeto de sequência e ambos +a+ e +b+ se referem a ele " ->  " O Julia apenas criou um objeto string, e ambos +a+ e +b+ referem-se a ele "

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Nesse case poderíamos dizer que duas listas são _equivalentes_, porque possuem os mesmos elementos, mas não _indênticos_, porque eles não são os mesmos objetos. Se dois objetos são idênticos, eles ta
case -> caso

"porque eles não são os mesmos objetos " -> "porque ele não são o mesmo objeto"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para sermos mais precisos, um objeto possui um valor. Se você avaliar +[1, 2, 3]+, voc~e obterá uma lista de objetos cujos os valores são uma sequência de inteiros. Se uma outra lista possuir os mesm
voc~e -> você

"obterá uma lista de objetos cujos os valores são .. " -> "obterá um objeto lista cujo valor é uma .. "

" não são os mesmos objetos." -> "não são o mesmo objeto"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((deletehead!)))((("função", "definido pelo programador", "deletehead!", see="deletehead!")))(((popfirst)))
popfirst -> popfirst!

"o chamados vê a diferença " -> "quem a chama nota a diferença"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Desde que a lista seja compartilhada por dois quadros, eu desenhei entre eles.
"Desde que a lista seja compartilhada" -> "Já que a lista é compartilhada por dois quadros"

"eu desenhei entre eles" -> "eu a desenhei entre eles"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Isto é importante para distinguir entre operações que modificam listas e operações que criam novas listas. Por exemplo, +push!+ modifica uma lista mas +vcat+ cria uma nova lista.
"Isto é importante para distinguir entre operações que modificam listas e operações que criam novas listas..." -> "É importante distinguir operações que modificam listas de operações que criam novas listas.."

" .. uma lista mas +vcat+ ..." -> " .. uma lista, mas +vcat+ ... " (vírgula)

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O operador de fatia cria uma nova lista e a atribuição faz com que +t+ se refira a ela, mas isso não afeta o chamador.
chamador -> quem a chama

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma alternativa é escrever uma função que cria e retorna uma nova lista. Por exemplo, +rabo+ retorna todos, exceto o primeiro elemento de uma lista:
substituir "rabo" e "tail" por "calda" nos casos subsequentes.

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Essa função deixa a lista original sem modificações. Veja como é usado:
" como é usado" -> "como ela é usada"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O uso descuidado de listas (e outros objetos mutáveis) podem levar a longas horas de debug. Veja algumas armadilhas comuns e maneiras de como evitá-las:
"podem" -> "pode"
"de debug" -> "de depuração" ou "pode levar a muito tempo gasto debugando"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Como +sort!+ fetorna a lista original modificada +t1+, +t2+ é um alias de +t1+.
fetorna -> retorna

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Parte do problema com listas é que existem muitas maneiras de fazer as coisas. Por exemplo, para remover um elemento de uma lista, você pode usar +pop!+, +Popfirst!+, +Delete_at+ ou mesmo uma atribui
tirar letra maiúscula dos nomes de função

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +insert!(t, 4, [x])         # ERROU!
ERROU -> ERRADO

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Se você precisa usar uma função como +sort!+, que modifica o argumento, voc~e precisa manter a lista original, você pode fazer uma cópia:
voc~e -> você

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Nesse exemplo, você também pode usar a função interna +sort+, que retorna uma nova lista classificada e deixa o original em paz:
classificada -> ordenada
"o original" -> "a original"

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um dos valores de uma lista (ou outra sequência), também chama items.
chama items -> chamado de itens

2020-05-18 19:02 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um caracter ou ustring utilizada para indicar onde uma string deve ser cortada.
ustring -> string

2020-06-21 18:53 UTC, joaoluisro requested changes
Segunda revisão

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Este capítulo apresenta um dos tipos internos mais úteis do Julia, as listas. Você também aprenderá sobre objetos e o que pode acontecer quando você tiver mais de um nome para o mesmo objeto.
```suggestion
Este capítulo apresenta um dos tipos internos mais úteis do Julia, as listas. Você também aprenderá sobre objetos e o que pode acontecer quando se tem mais de um nome para o mesmo objeto.
```
Uma sugestão para evitar a repetição do pronome

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Como uma string, uma _lista_ é uma sequência de valores. Em uma string, os valores são caracteres; em um lista, pode ser de qualquer tipo. Os valores de um lista são chamados de _elementos_ ou por ve
```suggestion
Assim como uma string, uma _lista_ é uma sequência de valores. Em uma string, os valores são caracteres; em uma lista, eles podem ser de qualquer tipo. Os valores de uma lista são chamados de _elementos_ ou por vezes _itens_.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Existem diversas maneiras de criar uma nova lista; a mais simples é inserir os elementos entre colchetes (+[ ]+), exemplo:
```suggestion
Existem diversas maneiras de criar uma nova lista; a mais simples é inserir os elementos entre colchetes (+[ ]+), da seguinte forma:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma lista com outra lista é dita _aninhada_.
```suggestion
Uma lista dentro de outra lista é dita _aninhada_.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +julia> números = [42, 1997];
```suggestion
julia> números = [42, 123];
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O tipo de lista é especificado entre as chaves e é composto pelo tipo e um número. O número indica as dimensões. A lista +vazia+ contém valores do tipo +Any+., isto é, pode ser designado a valores de
```suggestion
O tipo de lista é especificado entre as chaves e é composto por um tipo e um número. O número indica as dimensões. A lista +vazia+ contém valores do tipo +Any+., isto é, ela pode conter valores de todos os tipos.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +A sintaxe para acessar elementos de uma lista é a mesma para acessar caracteres de uma string - colchetes. A expressão dentro dos colchetes especifica o índice. Lembre-se que o índice começa em 1:
```suggestion
A sintaxe para acessar elementos de uma lista é a mesma para acessar caracteres de uma string com o operador colchetes. A expressão dentro dos colchetes especifica o índice. Lembre-se que o índice começa em 1:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O segundo elemento de +números+, que costumava ser 1997, agora é 7.
```suggestion
O segundo elemento de +números+, que costumava ser 123, agora é 7.
``

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Listas são representadas por caixas e pelos elementos das listas dentro. +vegetais+ refere-se a uma lista com três elementos indexados +1+, +2+ e +3+. +números+ contém dois elementos; o diagrama most
```suggestion
Listas são representadas por caixas e pelos elementos das listas dentro. +vegetais+ refere-se a uma lista com três elementos indexados +1+, +2+ e +3+. +números+ contém dois elementos; o diagrama mostra que o valor do segundo elemento foi reatribuído de +123+ para +7+. +vazia+ refere-se a uma lista sem elementos.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Os índices das listas funcionam do mesmo jeito que os índices de string (mas sem as ressalvas do UTF-8):
```suggestion
Os índices das listas funcionam do mesmo jeito que os índices de strings (mas sem as ressalvas do UTF-8):
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +* Se você tentar ler ou escrever um elemento que não existe, você obterá um +BoundsError+.
```suggestion
* Se você tentar ler ou escrever um elemento que não existe, um +BoundsError+ (erro de limite) será gerado.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Esse laço percorre a lista e atualiza cada elemento. +length+ retorna o número de elementos de uma lista. Toda vez que o laço é percorrido, +i+ obtém o índice do próximo elemento. O comando de atribu
```suggestion
Esse laço percorre a lista e atualiza cada elemento. +length+ retorna o número de elementos de uma lista. Toda vez que o laço é percorrido, +i+ obtém o índice do próximo elemento. O comando de atribuição no corpo usa +i+ para ler o valor antigo do elemento e atribuir ao novo valor:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> ++append!+ adiciona elementos da segunda lista ao final da primeira:
```suggestion
+append!+ adiciona os elementos da segunda lista ao final da primeira:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> ++sort!+ retorna uma cópia dos elementos da lista em ordem:
```suggestion
+sort+ retorna uma cópia dos elementos da lista em ordem:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para somar todos os números de uma lista, podemos utilizar um laço como o seguinte:
```suggestion
Para somar todos os números de uma lista, podemos utilizar um laço da seguinte forma:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> ++total+ é iniciado em 0. Toda vez que o laço é percorrido, +pass:[+=]+ captura um elemento da lista. O operador +pass:[+=]+ fornece um jeito fácil de atuaizar uma variável. Esse _comando de atribuiçã
```suggestion
+total+ é iniciado em 0. Toda vez que o laço é percorrido, +pass:[+=]+ captura um elemento da lista. O operador +pass:[+=]+ fornece um jeito fácil de atualizar uma variável. Esse _comando de atribuição aumentada_,
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma operação como essa que combina uma sequência de elementos a um único valor por vezes é chamado de _operação de redução_.
```suggestion
Uma operação como essa que combina uma sequência de elementos a um único valor por vezes é chamada de _operação de redução_.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um operador como +todas_maiúsculas+ é por vezes chamado de _mapa_ pois "mapeia" a função (neste caso +uppercase+) em cada um dos elementos em uma sequência.
```suggestion
Uma operação como +todas_maiúsculas+ é por vezes chamado de _mapa_ pois "mapeia" uma função (neste caso +uppercase+) a cada um dos elementos em uma sequência.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Outro tipo comum de operação é selecionar alguns dos elementos de uma lista e retornar uma sublista. Por exemplo, a seguinte função pega uma lista de strings e retorna uma lista que contém apenas str
```suggestion
Outro tipo comum de operação é selecionar alguns dos elementos de uma lista e retornar uma sublista. Por exemplo, a seguinte função recebe uma lista de strings e retorna uma lista que contém apenas as strings com letras maiúsculas:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Operações mais comuns de listas podem ser exprressas como uma combinação de mapeamento, filtro e redução.
```suggestion
Operações mais comuns de listas podem ser expressas como uma combinação de mapeamento, filtro e redução.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> ++splice!+ modifica a lista e retorna um elemento que foi removido.
```suggestion
+splice!+ modifica a lista e retorna o elemento que foi removido.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> ++join+ é o inverso de +split+. Ela pega uma lista de strings e concatena os elementos:
```suggestion
+join+ é o inverso de +split+. Ela recebe uma lista de strings e concatena os elementos:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +No caso o delimitador é um caractere de espaço. Para concatenar strings sem espaços, você não precisa especificar um delimitador.
```suggestion
Neste caso o delimitador é um caractere de espaço. Para concatenar strings sem espaços, você não precisa especificar um delimitador.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um _objeto_ é algo que uma variável pode se referir. Desde então, você poderia usar "objeto" e "valor" sem distinção.
```suggestion
Um _objeto_ é algo que uma variável pode se referir a. Até agora, você poderia usar "objeto" e "valor" sem distinção.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Em um caso, +a+ e +b+ referem-se a dois objetos diferentes que possuem o mesmo valor. No segundo caso, referem-se ao mesmo objeto.
```suggestion
Em um caso, +a+ e +b+ referem-se a dois objetos diferentes que possuem o mesmo valor. No segundo caso, elas referem-se ao mesmo objeto.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Portanto, o diagrama de estado se parece com <<<fig10-3>>.
```suggestion
Portanto, o diagrama de estado se parece com <<fig10-3>>.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Nesse caso poderíamos dizer que as duas listas são _equivalentes_, porque possuem os mesmos elementos, mas não _indênticos_, porque elas não são o mesmo objeto. Se dois objetos são idênticos, eles ta
```suggestion
Nesse caso poderíamos dizer que as duas listas são _equivalentes_, porque possuem os mesmos elementos, mas não _idênticos_, porque elas não são o mesmo objeto. Se dois objetos são idênticos, eles também são equivalentes, mas se eles são equivalentes, eles não necessariamente são idênticos.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O diagrama de estado se parece com <<<fig10-4>>.
```suggestion
O diagrama de estado se parece com <<fig10-4>>.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Quando você passa uma lista para uma função, a função obtém uma referência para a lista. Se a função modifica a lista, quem chama nota a diferença. Por exemplo, +deleta_cabeça!+ remove o primeiro ele
```suggestion
Quando você passa uma lista para uma função, a função recebe uma referência para a lista. Se a função modifica a lista, quem chama nota a diferença. Por exemplo, +deleta_cabeça!+ remove o primeiro elemento de uma lista:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +* A maioria das funções de lista modifica o argumento. É o oposto das funções de sequência, que retornam uma nova sequência e deixam o original em paz.
```suggestion
* A maioria das funções de lista modifica o argumento. É o oposto das funções de strings, que retornam uma nova string e deixam a original em paz.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((faixa)))(((sort!)))
```suggestion
(((strip)))(((sort!)))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Parte do problema com listas é que existem muitas maneiras de fazer as coisas. Por exemplo, para remover um elemento de uma lista, você pode usar +pop!+, +popfirst!+, +Delete_at+ ou mesmo uma atribui
```suggestion
Parte do problema com listas é que existem muitas maneiras de fazer as coisas. Por exemplo, para remover um elemento de uma lista, você pode usar +pop!+, +popfirst!+, +delete_at+ ou até mesmo uma atribuição de fatia. Para adicionar um elemento, você pode usar +push!+, +pushfirst!+, +insert!+ Ou +vcat+. Supondo que +t+ é uma lista e +x+ é um elemento da lista, os seguintes estão corretos:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Se você precisa usar uma função como +sort!+, que modifica o argumento, você precisa manter a lista original, você pode fazer uma cópia:
```suggestion
Se você quer usar uma função como +sort!+ que modifica o argumento, mas você precisa manter a lista original, você pode fazer uma cópia:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma lista é um elemento de outra lista.
```suggestion
Uma lista que é um elemento de uma outra lista.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma atribuição que atualiza o valor de uma variável utilizando um operador +=+.
```suggestion
Uma atribuição que atualiza o valor de uma variável utilizando um operador como +=+.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Sintaxe utilizada para aplicar uma função resultado elementar a qualquer lista.
```suggestion
Sintaxe utilizada para aplicar uma função elemento a elemento a qualquer lista.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Sendo o mesmo objeto (o que implica equivalencia).
```suggestion
Ser o mesmo objeto (o que implica equivalência).
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma circunstância onde duas ou mais variáveis referem-se ao mesmo objeto.
```suggestion
Uma circunstância no qual duas ou mais variáveis referem-se ao mesmo objeto.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um caracter ou string utilizada para indicar onde uma string deve ser cortada.
```suggestion
Um caractere ou string utilizada para indicar onde uma string deve ser cortada.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
>    for nested in t
```suggestion
  for aninhado in t
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
>      total += sum(nested)
```suggestion
    total += sum(aninhado)
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Escreva uma função chamada +soma_aninhada+ que pega uma lista de listas com números inteiros e adicione os elementos de todas as listas aninhadas. Por exemplo:
```suggestion
Escreva uma função chamada +soma_aninhada+ que recebe uma lista de listas de números inteiros e some os elementos de todas as listas aninhadas. Por exemplo:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Escreva uma função chamada +soma_cumulativa+ que pega uma lista de números e retorne a soma cumulativa; isto é, uma nova lista em que o latexmath:[\(i\)]-ésimo elemento é a soma do primeiro elemento
```suggestion
Escreva uma função chamada +soma_cumulativa+ que recebe uma lista de números e retorne a soma cumulativa; isto é, uma nova lista em que o latexmath:[\(i\)]-ésimo elemento é a soma do primeiro elemento latexmath:[\(i\)] da lista original. Por exemplo:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Escreva uma função chamada +interior+ que pega uma lista e retorna uma nova lista que contém tudo exceto o primeiro e o último elemento. Por exemplo:
```suggestion
Escreva uma função chamada +interior+ que recebe uma lista e retorna uma nova lista que não contém o primeiro e o último elemento. Por exemplo:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Escreva uma função chamada +interior!+ que pega uma lista, modifique-a removendo o primeiro e o último elementos e retorne +nothing+. Por exemplo:
```suggestion
Escreva uma função chamada +interior!+ que recebe uma lista, modifique-a removendo o primeiro e o último elemento e retorne +nothing+. Por exemplo:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Escreva uma função chamada +é_ordenada+ que use uma lista como parâmetro e retorne +true+ se a lista for classificada em ordem crescente e +false+ caso contrário. Por exemplo:
```suggestion
Escreva uma função chamada +é_ordenada+ que use uma lista como parâmetro e retorne +true+ se a lista estiver ordenada em ordem crescente e +false+ caso contrário. Por exemplo:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Duas palavras são anagramas se você puder reorganizar as letras de uma para soletrar a outra. Escreva uma função chamada +é_anagrama+ que use duas strings e retorne + true + se forem anagramas.
```suggestion
Duas palavras são anagramas se você puder reorganizar as letras de uma para formar a outra. Escreva uma função chamada +é_anagrama+ que recebe duas strings e retorne +true+ se elas forem anagramas.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Escreva uma função chamada +tem_repetidas+ que pegue uma lista e retorne +true+ se houver algum elemento que apareça mais de uma vez. Não deve modificar a lista original.
```suggestion
Escreva uma função chamada +tem_duplicatas+ que recebe uma lista e retorne +true+ se houver algum elemento que apareça mais de uma vez. Ela não deve modificar a lista original.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Escreva uma função que leia o arquivo +words.txt+ e crie uma lista com um elemento por palavra. Escreva duas versões dessa função, uma usando +push!+ e a outra usando o idioma +t=[pass:[t ...], x]+.
```suggestion
Escreva uma função que leia o arquivo +words.txt+ e crie uma lista com um elemento por palavra. Escreva duas versões dessa função, uma usando +push!+ e a outra usando o idioma +t=[pass:[t ...], x]+. Qual delas demora mais para ser executada? Por quê?
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para verificar se uma palavra está na lista de palavras, você pode usar o operador +∈+, mas seria lento porque pesquisará as palavras em ordem.
```suggestion
Para verificar se uma palavra está na lista de palavras, você poderia usar o operador +∈+, mas isto seria lento porque  as palavras seriam pesquisadas em ordem.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Como as palavras estão em ordem alfabética, podemos acelerar as coisas com uma pesquisa por bissecção (também conhecida como pesquisa binária), que é semelhante ao que você faz quando procura uma pal
```suggestion
Como as palavras estão em ordem alfabética, podemos acelerar as coisas com uma busca bissecção (também conhecida como busca binária), que é semelhante ao que você faz quando procura uma palavra no dicionário. Você começa no meio e verifica se a palavra que você procura vem antes da palavra no meio da lista. Nesse caso, você pesquisa a primeira metade da lista da mesma maneira. Caso contrário, você pesquisará a segunda metade.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +De qualquer forma, você reduz pela metade o espaço restante da pesquisa. Se a lista de palavras tiver 113.809 palavras, serão necessárias 17 etapas para encontrar a palavra ou concluir que ela não ex
```suggestion
De qualquer forma, você reduz pela metade o espaço restante da busca. Se a lista de palavras possuir113.809 palavras, serão necessárias 17 etapas para encontrar a palavra ou concluir que ela não está na lista.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Escreva uma função chamada +é_bisseção+ que usa uma lista classificada e um valor-alvo e retorna +true+ se a palavra estiver na lista e +false+ se não estiver.
```suggestion
Escreva uma função chamada +em_bisseção+ que usa uma lista ordenada e um valor-alvo e retorna +true+ se a palavra estiver na lista e +false+ se não estiver.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Duas palavras são um "par reverso" se cada uma for o inverso da outra. Escreva um programa +par_reverso+ que encontre todos os pares reversos na lista de palavras.
```suggestion
Duas palavras são um “par reverso” se uma for o inverso da outra. Escreva um programa +par_reverso+ que encontre todos os pares reversos na lista de palavras.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Duas palavras "interligam" se receber letras alternadas de cada uma forma uma nova palavra. Por exemplo, "micro" e "ondas" se interligam para formar "microondas".
Aqui acho que vale a pena encontrar outro exemplo, já que o exercício não se resume a simplesmente conectar duas palavras. A partir daqui as linhas também estão desalinhadas.

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +. Escreva um programa que encontre todos os pares de palavras que se entrelaçam.
interligam ou entrelaçam?

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +. Você consegue encontrar alguma palavra intertravada de três vias; isto é, toda terceira letra forma uma palavra, começando na primeira, segunda ou terceira?
```suggestion
. Você consegue encontrar alguma palavra interligada/entrelaçada de três vias; isto é, toda terceira letra forma uma palavra, começando na primeira, segunda ou terceira?
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +No início de +não_deleta_cabeça+, +t+ e +t3+ se referem à mesma lista. No final, +t+ se refere a uma nova lista, mas +t3+ continua a se referir à original, uma lista não modificada.
```suggestion
No início de +não_deleta_cabeça+, +t+ e +t3+ referem-se à mesma lista. No final, +t+ refere-se a uma nova lista, mas +t3+ continua a referir-se à lista original, que não foi modificada.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((colchetes)))
```suggestion
(((operador colchetes)))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((colchetes)))(((índice)))
```suggestion
(((operador colchetes)))(((índice)))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((diagrama de pilha)))
```suggestion
(((diagrama de estado)))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +.Diagrama de pilha
```suggestion
.Diagrama de estado
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((percorrer)))(((comando for)))
```suggestion
(((percorrer)))(((declaração for)))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((sort)))((("função", "Base", "sort"m, see="sort")))
```suggestion
(((sort)))((("função", "Base", "sort", see="sort")))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +function somar_todos(t)
```suggestion
function soma_todos(t)
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((soma)))((("função", "Base", "soma", see="soma")))
```suggestion
(((sum)))((("função", "Base", "sum", see="sum")))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um operador como +apenas_maiusculas+ é chamado de _filtro_ pois seleciona alguns dos elementos e filtra outros.
```suggestion
Uma operação como +apenas_maiusculas+ é chamada de _filtro_ pois seleciona alguns dos elementos e filtra outros.
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para cada operador binário como +pass:[^]+, existe um _operador ponto_ pass:[<code>.^</code>] correspondente que é automaticamente definido para atuar +pass:[^]+ elemento-a-elemento nas listas. Por e
```suggestion
Para cada operador binário como +pass:[^]+, existe um _operador ponto_ pass:[<code>.^</code>] correspondente que é automaticamente definido para efetuar +pass:[^]+ elemento-a-elemento nas listas. Por exemplo, pass:[<code>&#91;1, 2, 3&#93; ^ 3</code>] não é definido, mas pass:[<code>&#91;1, 2, 3&#93; .^ 3</code>] é definido como calcular elemento a elemento o resultado pass:[<code>&#91;1^3, 2^3, 3^3&#93;</code>]:
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((operador ponto)))((("operador", "base", ".", see="operador ponto")))(((".", see="operador ponto")))
```suggestion
(((operador ponto)))((("operador", "Base", ".", see="operador ponto")))(((".", see="operador ponto")))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((pushfirst!)))((("função", "Base", "pushfirst", see="pushfirst!")))(((push!)))
```suggestion
(((pushfirst!)))((("função", "Base", "pushfirst!", see="pushfirst!")))(((push!)))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((joing)))((("função", "Base", "join", see="join")))
```suggestion
(((join)))((("função", "Base", "join", see="join")))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((tail)))((("função", "definido pelo programador", "calda", see="calda")))
```suggestion
(((calda)))((("função", "definido pelo programador", "calda", see="calda")))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +julia> t2 = t[:]; # t2 = cópia(t)
```suggestion
julia> t2 = t[:]; # t2 = copy(t)
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((tem_repetidas)))((("função", "definida pelo programador", "tem_repetidas", see="tem_repetidas")))
```suggestion
(((tem_duplicatas)))((("função", "definida pelo programador", "tem_duplicatas", see="tem_duplicatas")))
```

2020-06-21 18:53 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((aleatório)))((("função", "Base", "aleatório", see="aleatório")))
```suggestion
(((rand)))((("função", "Base", "rand", see="rand")))
```

2020-07-02 23:26 UTC, joaoluisro requested changes

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +<<fig10-1>> mostra o diagrama de pilha para "vegetais", "números" e "vazia".
```suggestion
<<fig10-1>> mostra o diagrama de pilha para +vegetais+, +números+ e +vazia+.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +``
```suggestion

```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Listas são representadas por caixas e pelos elementos das listas dentro. +vegetais+ refere-se a uma lista com três elementos indexados +1+, +2+ e +3+. +números+ contém dois elementos; o diagrama most
```suggestion
Uma lista é representada por uma caixa e pelos elementos da lista dentro dela. +vegetais+ refere-se a uma lista com três elementos indexados +1+, +2+ e +3+. +números+ contém dois elementos; o diagrama mostra que o valor do segundo elemento foi reatribuído de +123+ para +7+. +vazia+ refere-se a uma lista sem elementos.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +A maneira mais comum de percorrer os elementos de uma lista é através do laço +for+. A sintaxe é a mesma para strings:
```suggestion
A maneira mais comum de percorrer os elementos de uma lista é através de um laço +for+. A sintaxe é a mesma para strings:
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O Operador de Fatia +[:]+, faz uma cópia em toda a lista:
```suggestion
O Operador de Fatia +[:]+, faz uma cópia de toda a lista:
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Muitas vezes, você deseja percorrer uma lista enquanto cria outra. Por exemplo, a função à seguir pega uma lista de strings e retorna uma nova lista que contém strings de caracteres maiúsculas:
```suggestion
Muitas vezes, você deseja percorrer uma lista enquanto cria outra. Por exemplo, a função à seguir recebe uma lista de strings e retorna uma nova lista que contém as strings com todos os seus caracteres maiúsculos:
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma operação como +todas_maiúsculas+ é por vezes chamado de _mapa_ pois "mapeia" uma função (neste caso +uppercase+) a cada um dos elementos em uma sequência.
```suggestion
Uma operação como +todas_maiúsculas+ é por vezes chamado de _mapa_ pois “mapeia” uma função (neste caso +uppercase+) a cada um dos elementos em uma sequência.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +(((apenas_maiusculas)))((("função", "definido pelo programador", "apenas maiusculas", see="apenas_maiusculas")))
```suggestion
(((apenas_maiúsculas)))((("função", "definido pelo programador", "apenas_maiúsculas", see="apenas_maiúsculas")))
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +function apenas_maiusculas(t)
```suggestion
function apenas_maiúsculas(t)
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Uma operação como +apenas_maiusculas+ é chamada de _filtro_ pois seleciona alguns dos elementos e filtra outros.
```suggestion
Uma operação como +apenas_maiúsculas+ é chamada de _filtro_ pois seleciona alguns dos elementos e filtra outros.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +<<fig10-1>> mostra o diagrama de estado para "vegetais", "números" e "vazia".
```suggestion
<<fig10-1>> mostra o diagrama de estado para +vegetais+, +números+ e +vazia+.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +julia> números[2] = 7
```suggestion
julia> números[2] = 5
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +7
```suggestion
5
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para cada operador binário como +pass:[^]+, existe um _operador ponto_ pass:[<code>.^</code>] correspondente que é automaticamente definido para efetuar +pass:[^]+ elemento-a-elemento nas listas. Por
```suggestion
Para cada operador binário como +pass:[^]+, existe um _operador ponto_ pass:[<code>.^</code>] correspondente que é automaticamente definido para efetuar +pass:[^]+ elemento-a-elemento em listas. Por exemplo, pass:[<code>&#91;1, 2, 3&#93; ^ 3</code>] não é definido, mas pass:[<code>&#91;1, 2, 3&#93; .^ 3</code>] é definido como calcular elemento a elemento o resultado pass:[<code>&#91;1^3, 2^3, 3^3&#93;</code>]:
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Um _objeto_ é algo que uma variável pode se referir a. Até agora, você poderia usar "objeto" e "valor" sem distinção.
```suggestion
Um _objeto_ é algo que uma variável pode se referir a. Até agora, você poderia usar “objeto” e “valor” sem distinção.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Para verificar se uma palavra está na lista de palavras, você poderia usar o operador +∈+, mas isto seria lento porque  as palavras seriam pesquisadas em ordem.
```suggestion
Para verificar se uma palavra está na lista de palavras, você poderia usar o operador +∈+, mas isto seria lento porque as palavras seriam pesquisadas em ordem.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +De qualquer forma, você reduz pela metade o espaço restante da busca. Se a lista de palavras possuir113.809 palavras, serão necessárias 17 etapas para encontrar a palavra ou concluir que ela não está
```suggestion
De qualquer forma, você reduz pela metade o espaço restante da busca. Se a lista de palavras possuir 113.809 palavras, serão necessárias 17 etapas para encontrar a palavra ou concluir que ela não está na lista.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Duas palavras "interligam" se receber letras alternadas de cada uma forma uma nova palavra. Por exemplo, "micro" e "ondas" se interligam para formar "microondas".
```suggestion
Duas palavras “interligam” se receber letras alternadas de cada uma forma uma nova palavra. Por exemplo, “micro” e “ondas” se interligam para formar “microondas”.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +. Escreva um programa que encontre todos os pares de palavras que se entrelaçam.
```suggestion
. Escreva um programa que encontre todos os pares de palavras que se interligam.
```

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Duas palavras "interligam" se receber letras alternadas de cada uma forma uma nova palavra. Por exemplo, "micro" e "ondas" se interligam para formar "microondas".
inserir [[ex10-12]] na linha 1048

2020-07-02 23:26 UTC, joaoluisro commented on book/src/chap10.asciidoc
> -===== Exercise 10-12
isso também foi removido

2020-07-07 20:37 UTC, joaoluisro requested changes

2020-07-07 20:37 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +Duas palavras "interligam" se receber letras alternadas de cada uma forma uma nova palavra. Por exemplo, "micro" e "ondas" se interligam para formar "microondas".
```suggestion
Duas palavras “interligam” se receber letras alternadas de cada uma forma uma nova palavra. Por exemplo, “micro” e “ondas” se interligam para formar “microondas”.
```

2020-07-08 14:37 UTC, joaoluisro requested changes

2020-07-08 14:37 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +julia> números[2] = 7
mudar pra não ter conflito com a imagem

2020-07-08 14:37 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +[42, 7]
```suggestion
[42, 5]
```

2020-07-08 14:37 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +O segundo elemento de +números+, que costumava ser 123, agora é 7.
```suggestion
O segundo elemento de +números+, que costumava ser 123, agora é 5.
```

2020-07-08 14:37 UTC, joaoluisro commented on book/src/chap10.asciidoc
> +<<fig10-1>> mostra o diagrama de estado para "vegetais", "números" e "vazia".
nomes de variáveis.

2020-07-08 21:19 UTC, joaoluisro approved these changes

2020-07-10 01:54 UTC, abelsiqueira approved these changes

2020-07-10 01:54 UTC, abelsiqueira commented on book/src/chap10.asciidoc
> +* Se você tentar ler ou escrever um elemento que não existe, um +BoundsError+ (erro de limite) será gerado.
```suggestion
* Se você tentar ler ou escrever um elemento que não existe, um +BoundsError+ (erro de limites) será gerado.
```

2020-07-10 01:54 UTC, abelsiqueira commented on book/src/chap10.asciidoc
> +(((pop!)))((("função", "Base", "pop!", veja="pop!")))
```suggestion
(((pop!)))((("função", "Base", "pop!", see="pop!")))
```

2020-07-10 01:54 UTC, abelsiqueira commented on book/src/chap10.asciidoc
> +Para verificar se duas variáveis referem-se ao mesmo objeto, você pode usar o operador +=+ (*+\equiv TAB+*) ou +===+.
```suggestion
Para verificar se duas variáveis referem-se ao mesmo objeto, você pode usar o operador +≡+ (*+\equiv TAB+*) ou +===+.
```

2020-07-10 01:54 UTC, abelsiqueira commented on book/src/chap10.asciidoc
> +julia> calda = ['a', 'b', 'c'];
```suggestion
julia> letras = ['a', 'b', 'c'];
```

2020-07-10 01:54 UTC, abelsiqueira commented on book/src/chap10.asciidoc
> +Como as palavras estão em ordem alfabética, podemos acelerar as coisas com uma busca bissecção (também conhecida como busca binária), que é semelhante ao que você faz quando procura uma palavra no di
```suggestion
Como as palavras estão em ordem alfabética, podemos acelerar as coisas com uma busca por bissecção (também conhecida como busca binária), que é semelhante ao que você faz quando procura uma palavra no dicionário. Você começa no meio e verifica se a palavra que você procura vem antes da palavra no meio da lista. Nesse caso, você pesquisa a primeira metade da lista da mesma maneira. Caso contrário, você pesquisará a segunda metade.
```

2020-07-10 01:54 UTC, abelsiqueira commented on book/src/chap10.asciidoc
> +(((é_bisseção)))((("função", "definido pelo programador", "é_bisseção", see="é_bisseção")))
```suggestion
Escreva uma função chamada +em_bisseção+ que usa uma lista ordenada e um valor-alvo e retorna +true+ se a palavra estiver na lista e +false+ se não estiver.
(((em_bisseção)))((("função", "definido pelo programador", "em_bisseção", see="em_bisseção")))
```

2020-07-10 01:54 UTC, abelsiqueira commented on book/src/chap10.asciidoc
> +Duas palavras “interligam” se receber letras alternadas de cada uma forma uma nova palavra. Por exemplo, “micro” e “ondas” se interligam para formar “microondas”.
```suggestion
Duas palavras “interligam” se receber letras alternadas de cada uma forma uma nova palavra. Por exemplo, “shoe” e “cold” se interligam para formar “schooled”.
```
É alternadamente, e vai ser utilizado a lista de palavras em inglês.

2020-07-10 01:55 UTC, merged