Chapter 9 PTBR
JuliaIntro/JuliaIntroBR.jl pull request #19
Opened 2020-05-12 00:31 UTC by chunggnuhc

2020-05-23 16:25 UTC, joaoluisro requested changes
primeira revisão.

2020-05-23 16:25 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +Este arquivo está em texto sem formatação e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como p
```suggestion
Este arquivo está em texto não formatado, e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como parâmetro e retorna um _objeto de fluxo de arquivo_ usado para a leitura do arquivo.
```

2020-05-23 16:25 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +(((laço for)))(((eachline)))((("função", "Base", "eachline", see="eachline")))
```suggestion
(((declaração for)))(((eachline)))((("função", "Base", "eachline", see="eachline")))
```

2020-05-23 16:25 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +Você poderia escrever esta função de forma mais sucinta usando o operador +∉+ (*+\notin TAB+*), mas comecei com essa versão porque ela mostra a lógica do padrão de pesquisa.
```suggestion
Você poderia escrever esta função de forma mais sucinta usando o operador +∉+ (*+\notin TAB+*), mas comecei com essa versão porque ela mostra a lógica do padrão de busca.
```

2020-05-27 02:45 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +Este arquivo está em texto sem formatação e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como p
Alterado.

2020-05-27 02:45 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +(((laço for)))(((eachline)))((("função", "Base", "eachline", see="eachline")))
Alterado.

2020-05-27 02:45 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +Você poderia escrever esta função de forma mais sucinta usando o operador +∉+ (*+\notin TAB+*), mas comecei com essa versão porque ela mostra a lógica do padrão de pesquisa.
Alterado

2020-06-02 18:15 UTC, joaoluisro reviewed
Segunda revisão

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +O laço começa em +i=1+ e +j=nextind(palavra, 1)+ e termina quando +j> sizeof(palavra)+. A cada iteração no laço, ele compara o ++i++-ésimo caractere (que pode ser apontado como o caractere atual) com
```suggestion
O laço começa em +i=1+ e +j=nextind(palavra, 1)+ e termina quando +j> sizeof(palavra)+. A cada iteração no laço, ele compara o ++i++-ésimo caractere (você pode pensar que ele é o caractere atual) com o ++j++-ésimo caractere (você pode pensar que ele é o próximo).
```

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +Um caso de teste que é atípico ou que não é óbvio (e com menos probabilidade de ser abordado corretamente).
```suggestion
Um caso de teste que é atípico ou que não é óbvio (e com menor chance de ser abordado corretamente).
```

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +Este arquivo está em texto não formatado e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como pa
Aqui vale a pena pensar a respeito de coisas que não precisam ser traduzidas, o termo _file stream_ pode até virar _stream de arquivo_ sem comprometer muito o linguajar de programação.

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +Julia fornece várias funções para leitura, como a +readline+, que lê caracteres do arquivo até chegar a um comando de +nova linha+ e retorna o resultado como uma string:
```suggestion
O Julia fornece várias funções para leitura, como a +readline+, que lê caracteres do arquivo até chegar a um comando de +nova linha+ e retorna o resultado como uma string:
```

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +Julia fornece várias funções para leitura, como a +readline+, que lê caracteres do arquivo até chegar a um comando de +nova linha+ e retorna o resultado como uma string:
Em relação ao +NEWLINE+, é viável também manter o termo em inglês e adicionar uma breve explicação. Mas isso é apenas uma sugestão e acho que vale a pena discutir a respeito.

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +O objeto de fluxo de arquivo monitora sua localização no arquivo; portanto, se chamar novamente o comando readline, recebe a próxima palavra:
```suggestion
O objeto de fluxo de arquivo monitora sua localização no arquivo; portanto, se nós chamarmos novamente o comando readline, recebemos a próxima palavra:
```
Acho que algumas coisas podem ser mudadas da 2ª pessoa do singular para a 1ª do plural (na minha opinião isso facilita a leitura), acredito que isso não comprometa tanto o significado (que é sempre o mais importante).

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +O termo subsequente em inglês é "aah", que é perfeitamente legítima, então pare de me olhar desse jeito.
```suggestion
O termo subsequente em inglês é "aah", que é uma palavra perfeitamente legítima, então pare de me olhar desse jeito.
```

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +Você também pode usar um objeto de arquivo em um laço de repetição +for+. Este programa lê +palavras.txt+ e imprime cada palavra, uma por linha:
```suggestion
Você também pode usar um objeto de arquivo em um laço +for+. Este programa lê +palavras.txt+ e imprime cada palavra, uma por linha:
```

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +Este é um exemplo de um plano de desenvolvimento para um programa chamado _redução para um problema previamente resolvido_, onde você reconhece o problema em que está trabalhando como uma instância d
```suggestion
Este é um exemplo de um plano de desenvolvimento para um programa chamado _redução para um problema previamente resolvido_, no qual você reconhece o problema em que está trabalhando como uma instância de um problema resolvido e aplica uma solução existente.
```

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +(((objeto de fluxo de arquivo)))(((entrada de dados)))(((readline)))((("função", "Base", "readline", see="readline")))(((fechar)))
```suggestion
(((objeto de fluxo de arquivo)))(((entrada de dados)))(((readline)))((("função", "Base", "readline", see="readline")))(((close)))
```
close é uma função embutida.

2020-06-02 18:15 UTC, joaoluisro commented on book/src/chap09.asciidoc
> +(((usa_todas)))((("função", "definido pelo programador", "usa_todas", veja="usa_todas")))
```suggestion
(((usa_todas)))((("função", "definido pelo programador", "usa_todas", see="usa_todas")))
```

2020-06-05 04:45 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +O objeto de fluxo de arquivo monitora sua localização no arquivo; portanto, se nós chamarmos novamente o comando readline, recebemos a próxima palavra:
```suggestion
O objeto de fluxo de arquivo monitora sua localização no arquivo; portanto, se chamarmos novamente o comando readline, recebemos a próxima palavra:
```

2020-06-05 04:47 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +O laço começa em +i=1+ e +j=nextind(palavra, 1)+ e termina quando +j> sizeof(palavra)+. A cada iteração no laço, ele compara o ++i++-ésimo caractere (que pode ser apontado como o caractere atual) com
Minha sugestão:
```suggestion
O laço começa em +i=1+ e +j=nextind(palavra, 1)+ e termina quando +j> sizeof(palavra)+. A cada iteração no laço, ele compara o ++i++-ésimo caractere (que você pode pensar como sendo o caracter atual) com o ++j++-ésimo caractere (que você pode pensar como o próximo).
```

2020-06-05 04:48 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +Se a posição do próximo caractere é alfabeticamente antecedente à posição do caractere atual, descobrimos uma quebra na tendência alfabética e retornamos +false+.
```suggestion
Se a posição do próximo caractere é alfabeticamente antecedente à posição do caracter atual, descobrimos uma quebra na tendência alfabética e retornamos +false+.
```

2020-06-05 04:49 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +O Julia fornece várias funções para leitura, como a +readline+, que lê caracteres do arquivo até chegar a um comando de +nova linha+ e retorna o resultado como uma string:
```suggestion
O Julia fornece várias funções para leitura, como a +readline+, que lê os caracteres do arquivo até chegar a um comando de +nova linha+ e retorna o resultado como uma string:
```

2020-06-05 04:56 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +Este arquivo está em texto não formatado e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como pa
Vou deixar para @abelsiqueira decidir. Eu entendo seu ponto de vista, mas qdo traduzi, não encontrei um nome traduzido para esse termo e criei esse termo "_objeto de fluxo de arquivo_" do que eu entendi sobre este capítulo falando do file stream. Eu sei q o termo q eu criei tb não é legal.

2020-06-05 04:58 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +O Julia fornece várias funções para leitura, como a +readline+, que lê os caracteres do arquivo até chegar a um comando de +nova linha+ e retorna o resultado como uma string:
Sobre o seu comentário aqui para NEWLINE, eu concorda se o Julia estivesse falando do "\n". Por isso q eu acabei traduzindo para "nova linha".

2020-06-05 05:01 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +Julia fornece várias funções para leitura, como a +readline+, que lê caracteres do arquivo até chegar a um comando de +nova linha+ e retorna o resultado como uma string:
Sobre o seu comentário aqui para NEWLINE, eu concorda se o Julia estivesse falando do "\n". Por isso q eu acabei traduzindo para "nova linha".

2020-06-05 17:16 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +Este arquivo está em texto não formatado e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como pa
```suggestion
Este arquivo está em texto não formatado e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como parâmetro e retorna um _fluxo (stream) de arquivo_ usado para a leitura do arquivo.
```

2020-06-05 17:41 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +O laço começa em +i=1+ e +j=nextind(palavra, 1)+ e termina quando +j> sizeof(palavra)+. A cada iteração no laço, ele compara o ++i++-ésimo caracter (que você pode pensar como sendo o caracter atual)
```suggestion
O laço começa em +i=1+ e +j=nextind(palavra, 1)+ e termina quando +j> sizeof(palavra)+. A cada iteração no laço, ele compara o ++i++-ésimo caractere (que você pode pensar como sendo o caractere atual) com o ++j++-ésimo caractere (que você pode pensar como o próximo).
```

2020-06-06 00:52 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +Se a posição do próximo caracter é alfabeticamente antecedente à posição do caracter atual, descobrimos uma quebra na tendência alfabética e retornamos +false+.
```suggestion
Se a posição do próximo caractere é alfabeticamente antecedente à posição do caractere atual, descobrimos uma quebra na tendência alfabética e retornamos +false+.
```

2020-06-06 00:53 UTC, chunggnuhc commented on book/src/chap09.asciidoc
>  === Debugging
```suggestion
=== Depuração
```

2020-06-06 00:53 UTC, chunggnuhc commented on book/src/chap09.asciidoc
>  (((debugging)))
```suggestion
(((depuração)))
```

2020-06-06 00:56 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +Este arquivo está em texto não formatado e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como pa
```suggestion
Este arquivo está em texto não formatado e portanto, pode ser aberto com um editor de texto, inclusive também pode ser lido em Julia. A função interna +open+ precisa receber o nome do arquivo como parâmetro e retorna um _fluxo de arquivo_ usado para a leitura do arquivo.
```

2020-06-06 00:57 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> ++arquivo_entrada+ é um objeto de fluxo de arquivo usado para a entrada de dados e quando não for mais necessário, deve ser fechado com +close(arquivo_entrada)+.
```suggestion
+arquivo_entrada+ é um fluxo de arquivo usado para a entrada de dados e quando não for mais necessário, deve ser fechado com +close(arquivo_entrada)+.
```

2020-06-06 00:58 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +(((objeto de fluxo de arquivo)))(((entrada de dados)))(((readline)))((("função", "Base", "readline", see="readline")))(((close)))
```suggestion
(((fluxo de arquivo)))(((entrada de dados)))(((readline)))((("função", "Base", "readline", see="readline")))(((close)))
```

2020-06-06 00:59 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +O objeto de fluxo de arquivo monitora sua localização no arquivo; portanto, se chamarmos novamente o comando readline, recebemos a próxima palavra:
```suggestion
O fluxo de arquivo monitora sua localização no arquivo; portanto, se chamarmos novamente o comando readline, recebemos a próxima palavra:
```

2020-06-06 01:00 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +objeto de fluxo de arquivo::
```suggestion
fluxo de arquivo::
```

2020-06-06 01:00 UTC, chunggnuhc commented on book/src/chap09.asciidoc
> +(((objeto de fluxo de arquivo)))
```suggestion
(((fluxo de arquivo)))
```

2020-06-06 20:13 UTC, joaoluisro approved these changes
Approval

2020-07-07 19:59 UTC, abelsiqueira approved these changes

2020-07-07 19:59 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +== Estudo de caso: jogo de palavras
```suggestion
== Estudo de Caso: Jogo de Palavras
```

2020-07-07 19:59 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +Este capítulo apresenta o segundo estudo de caso, que envolve solucionar um quebra-cabeças onde devemos encontrar palavras com certas propriedades. Por exemplo, encontraremos os palíndromos mais long
```suggestion
Este capítulo apresenta o segundo estudo de caso, que envolve solucionar um quebra-cabeças onde devemos encontrar palavras com certas propriedades. Por exemplo, encontraremos os palíndromos mais longos em Inglês e as palavras cujas letras aparecem em ordem alfabética. Além disso, apresentaremos outro plano de desenvolvimento de programa: redução até um problema previamente resolvido.
```

2020-07-07 19:59 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +=== Lendo listas de palavras
```suggestion
=== Lendo Listas de Palavras
```

2020-07-07 19:59 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +Para os exercícios deste capítulo, será necessária uma lista de palavras em inglês. Existem muitas listas de palavras disponíveis na internet, e a mais adequada para o nosso propósito é uma das lista
```suggestion
Para os exercícios deste capítulo, será necessária uma lista de palavras em inglês. Existem muitas listas de palavras disponíveis na internet, e a mais adequada para o nosso propósito é uma das listas de palavras coletadas e disponibilizadas em domínio público por Grady Ward como parte do projeto léxico da Moby (consulte https://wikipedia.org/wiki/Moby_Project). É uma lista com 113.809 palavras cruzadas oficiais; isto é, termos considerados válidos em palavras cruzadas e outros jogos com palavras. Na coleção de Moby, o nome do arquivo é _113809of.fic_ e você pode fazer o download de uma cópia, com o nome mais simples _palavras.txt_, em https://github.com/JuliaIntro/JuliaIntroBR.jl/blob/master/data/palavras.txt.
```

2020-07-07 19:59 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +A primeira palavra em inglês nesta lista especial é "aa", que é uma espécie de lava.
```suggestion
A primeira palavra em Inglês nesta lista especial é "aa", que é uma espécie de lava.
```

2020-07-07 19:59 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +De fato, é difícil elaborar um único pensamento sem conter essa letra mais usada. É lento no início, mas com cautela e horas de treinamento, você pode gradualmente aprimorar essa habilidade até ficar
```suggestion
De fato, é difícil elaborar um único pensamento sem conter essa letra mais usada. É lento no início, mas com cautela e horas de treinamento, você pode gradualmente aprimorar essa habilidade até ficar mais fácil. Em Inglês, este parágrafo não contém a letra e.
```

2020-07-07 19:59 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +O laço começa em +i=1+ e +j=nextind(palavra, 1)+ e termina quando +j> sizeof(palavra)+. A cada iteração no laço, ele compara o ++i++-ésimo caractere (que você pode pensar como sendo o caractere atual
```suggestion
O laço começa em +i=1+ e +j=nextind(palavra, 1)+ e termina quando +j>sizeof(palavra)+. A cada iteração no laço, ele compara o ++i++-ésimo caractere (que você pode pensar como sendo o caractere atual) com o ++j++-ésimo caractere (que você pode pensar como o próximo).
```

2020-07-07 19:59 UTC, abelsiqueira commented on book/src/chap09.asciidoc
> +Escreva um programa para encontrar essa palavra em inglês.
```suggestion
Escreva um programa para encontrar essa palavra em Inglês.
```

2020-07-07 20:52 UTC, merged