chapter8 translation
JuliaIntro/JuliaIntroBR.jl pull request #21
Opened 2020-05-13 22:49 UTC by joaoluisro

2020-06-04 01:06 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Strings não são como inteiros, pontos flutuante, e tipos booleanos. Uma string é uma _sequência_, o que significa que ela está em uma coleção ordenada de outros valores. Neste capítulo você verá como
```suggestion
Strings não são como inteiros, pontos flutuante e tipos booleanos. Uma string é uma _sequência_, o que significa que ela está em uma coleção ordenada de outros valores. Neste capítulo você verá como acessar os caracteres que compõem uma string, e você irá aprender sobre algumas funções auxiliares de strings fornecidas pelo Julia.
```

2020-06-04 02:38 UTC, gustavosarturi requested changes
- Dar um [CTRL] + [F] na palavra "indíce" e substituir por "ìndice";
- Nomes de funções, só dar um double check se não estamos usando "_" para variáveis e funções;
- Cifra de César: Ver exercício, coloquei um link que talvez ajude a escolher uma palavra em portugues e rotacionar.

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Strings não são como inteiros, pontos flutuante, e tipos booleanos. Uma string é uma _sequência_, o que significa que ela está em uma coleção ordenada de outros valores. Neste capítulo você verá como
- Remover vírgula antes de "e"

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Falantes da língua portuguesa estão familiarizados com caracteres como as letras do alfabeto (A, B, C, ...), numerais, e a pontuação comum. Esses caracteres são padronizados e mapeados para valores i
```suggestion
Falantes da língua portuguesa estão familiarizados com caracteres como as letras do alfabeto (A, B, C, ...), numerais e a pontuação comum. Esses caracteres são padronizados e mapeados para valores inteiros entre 0 e 127 pelo _padrão ASCII_ (American Standard Code for Information ou "Código Padrão Americano de Intercâmbio de Informações")
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Existem, é claro, muitos outros caracteres usados em línguas diferentes do Português, incluindo variantes dos caracteres ASCII com acentos e outras modificações, scripts relacionados como o Cirílico
```suggestion
Existem, é claro, muitos outros caracteres usados em línguas diferentes do Português, incluindo variantes dos caracteres ASCII com acentos e outras modificações, scripts relacionados como o Cirílico e o Grego e scripts completamente não relacionados ao ASCII e ao Português, incluindo Árabe, Chinês, Hebreu, Hindi, Japonês e Koreano.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +O _padrão Unicode_ lida com as complexidades do que exatamente é um caractere, e é geralmente aceitado como o padrão definitivo que resolve esse problema. Ele fornece um número único para todo caract
```suggestion
O _padrão Unicode_ lida com as complexidades do que exatamente é um caractere e é geralmente aceitado como o padrão definitivo que resolve esse problema. Ele fornece um número único para todo caractere em uma escala mundial.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +O _padrão Unicode_ lida com as complexidades do que exatamente é um caractere, e é geralmente aceitado como o padrão definitivo que resolve esse problema. Ele fornece um número único para todo caract
- **Linha 14**: Dar um enter.

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Um valor +Char+ representa um único caractere e está cercado por aspas únicas:
```suggestion
Um valor +Char+ representa um único caractere e está cercado por aspas simples:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +'x': ASCII/Unicode U+0078 (category Ll: letra, lowercase)
```suggestion
'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Uma string é uma sequência
```suggestion
=== Uma String é uma sequência
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +'b': ASCII/Unicode U+0062 (category Ll: letter, lowercase)
```suggestion
'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +A segunda declaração seleciona o caractere número 1 de +fruta+ e o atribui para +letra+.
```suggestion
O segundo comando seleciona o primeiro caractere de +fruta+ e o atribui para +letra+.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +A expressão em colchetes é chamada de _indíce_. O indíce indica qual caractere da sequência você deseja (por isso o nome).
```suggestion
A expressão em colchetes é chamada de _índice_. O índice indica qual caractere da sequência você deseja (por isso o nome).
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +(((indíce)))
```suggestion
(((índice)))
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Toda indexação no Julia começa em 1, o primeiro elemento de qualquer objeto inteiramente indexado é encontrado no indíce 1 e o último no indíce +end+:
```suggestion
Toda indexação no Julia começa em 1, o primeiro elemento de qualquer objeto inteiramente indexado é encontrado no índice 1 e o último no índice +end+:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +'a': ASCII/Unicode U+0061 (category Ll: letra, lowercase)
```suggestion
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +'n': ASCII/Unicode U+006E (category Ll: letter, lowercase)
```suggestion
julia> fruta[i+1]
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
julia> fruta[end-1]
'n': ASCII/Unicode U+006E (category Ll: Letter, lowercase)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +julia> len = length(frutas)
```suggestion
julia> tamanho = length(frutas)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +A função +sizeof+ retorna o número de bytes em uma string:
```suggestion
A função +sizeof+ fornece o número de bytes em uma string:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +No caso de +frutas+, o caractere +🍌+ é um caractere de quatro bytes, então os indíces 2,3 e 4 são inválido e o indíce do próximo caractere é 5; esse próximo indíce válido pode ser calculado por +next
```suggestion
No caso de +frutas+, o caractere +🍌+ é um caractere de quatro bytes, então os indíces 2,3 e 4 são inválido e o indíce do próximo caractere é 5; esse próximo índice válido pode ser calculado por +nextind(frutas, 1)+ e o índice depois dele por +nextind(frutas, 5)+ e assim por diante.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Muitos cálculos envolvem o processamento de uma string, um caractere de cada vez. Comumente eles começam no início, selecionando cada caractere por vez, fazendo algo com ele, e continuando até o fina
```suggestion
O processamento de uma string, caractere a caractere, envolve muitos cálculos. Comumente eles começam no início, selecionando cada caractere por vez, fazendo algo com ele e continuando até o final. Esse padrão de processamento é denominado de _travessia_. Um jeito de escrever uma travessia é com um laço +while+:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +indíce = firstindex(frutas)
```suggestion
índice = firstindex(frutas)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +while indíce <= sizeof(frutas)
```suggestion
while índice <= sizeof(frutas)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +    letra = frutas[indíce]
```suggestion
    letra = frutas[índice]
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +    global indíce = nextind(frutas, indíce)
```suggestion
    global índice = nextind(frutas, índice)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Esse loop faz a travessia da string e exibe cada letra em uma linha por si só. A condição do loop é +index pass:[&lt;=] sizeof(fruta)+, então quando o indíce é maior que o número de bytes em uma stri
```suggestion
Esse laço faz a travessia da string e exibe cada letra em uma linha por si só. A condição do laço é +índice pass:[&lt;=] sizeof(fruta)+, então quando o índice é maior que o número de bytes em uma string a condição é +false+ e o corpo do laço não executa.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +A função +firstindex+ retorna o primeiro indíce de bytes válido. A palavra-chave +global+ antes de +indíce+ indica que nós queremos re-atribuir a variável +indíce+ definida em +Main+ (ver <<global_va
```suggestion
A função +firstindex+ retorna o primeiro índice de bytes válido. A palavra-chave +global+ antes de +índice+ indica que nós queremos re-atribuir a variável +índice+ definida em +Main+ (ver <<global_variables>>).
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Outro jeito de escrever uma travessia é com o loop +for+:
```suggestion
Outra maneira de escrever uma travessia é com o laço +for+:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +(((declaração for)))(((in)))
```suggestion
(((comando for)))(((in)))
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
>  ----
Testado no Julia. Ok.
![image](https://user-images.githubusercontent.com/34655704/83705938-9f32e880-a5ec-11ea-8405-206a02105d8f.png)

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Cada vez que o loop é percorrido, o próximo caractere na string é atribuido para a variável +letra+. O loop continua até que não hajam mais caracteres sobrando.
```suggestion
Cada vez que o laço é percorrido, o próximo caractere na string é atribuido para a variável +letra+. O laço continua até que não haja mais caracteres sobrando.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +O próximo exemplo mostra como usar concatenação (multiplicação de strings) e um loop +for+ para gerar séries abecedárias (isto é, em ordem alfabética). No livro de Robert McCloskey, _Make way for Duc
```suggestion
O próximo exemplo mostra como usar concatenação (multiplicação de strings) e um laço+for+ para gerar séries abecedárias (isto é, em ordem alfabética). No livro de Robert McCloskey, _Make way for Ducklings_ (Abram caminho para os Patinhos), os nomes dos patinhos são Jack, Kack, Lack, Mack, Nack, Ouack, Pack, e Quack. Esse laço gera os nomes em ordem:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +É claro, isto não está completamente correto pois, “Ouack” E “Quack” estão incorretos.
```suggestion
É claro, isso não está completamente correto pois “Ouack” e “Quack” estão incorretos.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Modifique o programa para consertar esse erro.
```suggestion
Modifique o programa para consertar este erro.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Um segmento de uma string é chamado de _fatia_. Selecionar uma fatia é similar a selecionar um caractere:
```suggestion
Um pedaço de uma string é chamado de _fatia_. Selecionar uma fatia é similar a selecionar um caractere:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
>  "Caesar"
```suggestion
"César"
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Se o primeiro indíce é maior que o segundo, o resultado é uma _string vazia_, representada por duas aspas:
```suggestion
Se o primeiro índice é maior que o segundo, o resultado é uma _string vazia_, representada por aspas duplas:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Uma string vazia não contém nenhum caractere e possui tamanho 0, mas diferente disso, é igual a qualquer outra string.
```suggestion
Uma string vazia não contém nenhum caractere e possui tamanho 0, mas fora isso, é igual a qualquer outra string.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Construir strings usando concatenação pode vir a ser um incómodo. Para reduzir a necessidade dessas chamadas verbosas para +string+ ou multiplicações repetidas, O Julia permite _interpolação de strin
```suggestion
Construir strings usando concatenação pode vir a ser um incômodo. Para reduzir a necessidade dessas chamadas verbosas para +string+ ou multiplicações repetidas, o Julia permite _interpolação de strings_ usando +$+:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +            return indíce
```suggestion
function buscar(palavra, letra)
    índice = firstindex(palavra)
    while indíce <= sizeof(palavra)
        if palavra[índice] == letra
            return índice
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +        indíce = nextind(palavra, indíce)
```suggestion
        índice = nextind(palavra, índice)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +De certo modo, buscar é o inverso do operador +[]+. Ao invés de pegar um indíce e extrair o caractere correspondente, ela recebe o caractere e busca o indíce aonde este caractere aparece. Se o caract
```suggestion
De certo modo, buscar é o inverso do operador +[]+. Ao invés de pegar um índice e extrair o caractere correspondente, ela recebe o caractere e busca o índice donde este caractere aparece. Se o caractere não é encontrado, a função retorna -1.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Esse é o primeiro exemplo que nós vimos de uma declaração return dentro de um loop. Se +palavra[indíce] == letra+, a função sai do loop e retorna imediatamente.
```suggestion
Esse é o primeiro exemplo que nós vimos de uma comando de retorno dentro de um laço. Se +palavra[índice] == letra+, a função sai do laço e retorna imediatamente.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Se o caractere não aparece na string, o programa sai do loop normalmente e retorna -1.
```suggestion
Se o caractere não aparece na string, o programa sai do laço normalmente e retorna -1.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Esse padrão de computação-percorrendo a sequência e retornando quando achamos o que estamos procurando-é chamado de _busca_.
Talvez encontrar uma tradução melhor para "computation-traversing"

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Esse padrão de computação-percorrendo a sequência e retornando quando achamos o que estamos procurando-é chamado de _busca_.
```suggestion
Esse padrão de computar-travessar uma sequência e retorno quando achamos o que estamos procurando-é chamado de _busca_.
```

Não acho que "travessar" seja a melhor, mas, acho que resolve um pouco.

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Modifique +busca+ para que ela tenha um terceiro parâmetro, o indíce em +palavra+ aonde ela deve começar a procurar.
```suggestion
Modifique +busca+ para que ela tenha um terceiro parâmetro, o índice em +palavra+ aonde ela deve começar a procurar.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Dando loop e contando
```suggestion
=== Realizando Laços e Contando
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +countador = 0
```suggestion
contador = 0
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Esse programa demonstra outro padrão de computação chamado _contador_. A variável +contador+ é inicializada com 0 e incrementada toda vez que um +a+ é achado. Quando a função sai do loop, +contador+
```suggestion
Esse programa demonstra outro padrão de programação chamado _contador_. A variável +contador+ é inicializada com 0 e incrementada toda vez que um +a+ é encontrado. Quando a função sai do loop, +contador+ contém o resultado-o número total de +a+’s.
```

Acho que esse termo se encaixa melhor

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Encapsule esse código em uma função chamada +conte+, e a generealize para que ela aceite a string e a letra como argumentos.
```suggestion
Encapsule esse código em uma função chamada +conte+ e generealize para que ela aceite a string e a letra como argumentos.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Biblioteca String
```suggestion
=== Biblioteca de String
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +(((maiúscula)))((("função", "Base", "maiúscula", see="maiúscula")))
```suggestion
(((maiúscula)))((("função", "Base", "uppercase", see="uppercase")))
```
Verificar, talvez só a primeira parte se traduz, a segunda não, por se tratar de um comando interno

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Por padrão, +findfirst+ começa no início da string, mas a função +findnext+ recebe um terceiro argumento, o +indíce+ onde ela deve começar:
```suggestion
Por padrão, +findfirst+ começa no início da string, mas a função +findnext+ recebe um terceiro argumento, o +índice+ onde ela deve começar:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== O operador +∈+
```suggestion
=== O Operador +∈+
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +(((emambos)))((("função", "definido pelo programador", "emambos", see="emambos")))
```suggestion
(((em_ambos)))((("função", "definido pelo programador", "em_ambos", see="em_ambos")))
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +function emambos(palavra1, palavra2)
```suggestion
function em_ambos(palavra1, palavra2)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Com variáveis de nomes bem escolhidos, o Julia as vezes lê como Inglês. Você poderia ler este loop, “para (cada) letra na (primeira) palavra, se (a) letra é um elemento da (segunda) palavra, imprima
```suggestion
Com variáveis de nomes bem escolhidos, o Julia às vezes lê como Inglês. Você poderia ler este laço da seguinte forma: “para (cada) letra na (primeira) palavra, se (a) letra é um elemento da (segunda) palavra, imprima (a) letra”
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +julia> emambos("maçãs", "laranjas")
```suggestion
julia> em_ambos("maçãs", "laranjas")
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Julia não lida letras maiúsculas e minúsculas do mesmo jeito que as pessoas lidam. Todas as letras maiúsculas vem antes de todas as letras minúsculas, então:
```suggestion
O Julia não lida letras maiúsculas e minúsculas do mesmo jeito que as pessoas lidam. Todas as letras maiúsculas vem antes de todas as letras minúsculas, então:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Um jeito comum de resolver este problema é convertendo strings para um formato padrão, como todas minúsculas, antes de efetuar a comparação.
```suggestion
Uma maneira comum de resolver este problema é convertendo strings para um formato padrão, como todas minúsculas, antes de efetuar a comparação.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Quando você usa indíces para percorrer os valores em uma sequência, é difícil de obter o começo e o fim da travessia direito. Aqui está uma função que deveria comparar duas palavras e retornar +true+
```suggestion
Quando você usa índices para percorrer os valores em uma sequência, é difícil de obter o começo e o fim da travessia direito. Aqui está uma função que deveria comparar duas palavras e retornar +true+ se uma das palavras é o inverso da outra, mas ela contém dois erros:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
>  ----
Manter padrão de colocar "_", talvez trocar o nome da função para "é_inversa"

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +A primeira declaração +if+ verifica se as palavras são do mesmo tamanho. Se não, nós podemos retornar +false+ imediatamente. Caso contrário, para o resto da função, nós podemos assumir que as palavra
```suggestion
O primeiro comando +if+ verifica se as palavras são do mesmo tamanho. Se não, nós podemos retornar +false+ imediatamente. Caso contrário, para o resto da função, nós podemos assumir que as palavras são do mesmo tamanho. Isso é um exemplo do padrão guardião.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> ++i+ e +j+ são indíces: +i+ percorre a +palavra1+ de frente para trás, enquanto +j+ percorre a +palavra2+ de trás para frente. Se nós acharmos duas letras que não são iguais, nós podemos retornar +fal
```suggestion
+i+ e +j+ são indíces: +i+ percorre a +palavra1+ de frente para trás, enquanto +j+ percorre a +palavra2+ de trás para frente. Se nós acharmos duas letras que não são iguais, nós podemos retornar +false+ imediatamente. Se nós passarmos pelo laço inteiro e todas as letras forem iguais, nós retornamos +true+.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +A função +lastindex+ retorna o último indíce de bytes válido de uma string e +prevind+ o último indíce válido de um caractere.
```suggestion
A função +lastindex+ retorna o último índice de bytes válido de uma string e +prevind+ o último índice válido de um caractere.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +julia> éinversa("pots", "stop")
```suggestion
julia> é_inversa("pare", "erap")
```

Colocando um exemplo em PT-BR

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Se nós testarmos essa função com as palavras "pots" e "stop", nós esperamos que o valor de retorno seja +true+, mas nós obtemos +false+:
```suggestion
Se nós testarmos essa função com as palavras "pare" e "erap", nós esperamos que o valor de retorno seja +true+, mas nós obtemos +false+:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Para debugar esse tipo de erro, o primeiro passo é imprimir os valores dos indíces:
```suggestion
Para debugar esse tipo de erro, o primeiro passo é imprimir os valores dos índices:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +function éinversa(palavra1, palavra2)
```suggestion
function é_inversa(palavra1, palavra2)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +julia> éinversa("pots", "stop")
```suggestion
julia> é_inversa("erap", "pare")
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +A primeira vez dentro do loop, o valor de +j+ é 3, que tem que ser 4. Isso pode ser consertado movendo +j = prevind(palavra2, j)+ para o final do loop +while+.
```suggestion
Na primeira vez dentro do laço, o valor de +j+ é 3, que tem que ser 4. Isso pode ser consertado movendo +j = prevind(palavra2, j)+ para o final do laço +while+.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Se consertamos este erro e executamos novamente o programa, obtemos:
```suggestion
Se consertamos este erro e executarmos novamente o programa, obtemos:
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +function éinversa(palavra1, palavra2)
```suggestion
function é_inversa(palavra1, palavra2)
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +julia> éinversa("pots", "stop")
```suggestion
julia> é_inversa("pots", "stop")
```

Só verifica, mas, acho que acordamos em colocar nomes e funções e variáveis com "_", caso contrário, não precisa alterar...

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +indíce::
```suggestion
índice::
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Um valor inteiro usado para selecionar um item em uma sequência, como um caractere em uma string. Em Julia indíces começam em 1.
```suggestion
Um valor inteiro usado para selecionar um item em uma sequência, como um caractere em uma string. Em Julia índices começam em 1.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +(((indíce)))
```suggestion
(((índice)))
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Uma string sem caracteres e comprimento 0, representada por duas aspas.
```suggestion
Uma string sem caracteres e comprimento 0, representada por aspas duplas.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Leia a documentação das funções string em https://docs.julialang.org/en/v1/manual/strings/. Você pode querer experimentar com algumas delas para garantir que você entende como elas funcionam. +strip+
```suggestion
Leia a documentação das funções string em https://docs.julialang.org/en/v1/manual/strings/. Você talvez queira experimentar algumas delas para garantir que você entende como elas funcionam. +strip+ e +replace+ são particulamente utéis.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +(((busca)))((("função", "Base", "busca", see="busca")))
```suggestion
(((busca)))((("função", "Base", "busca", see="busca")))
```
Verificar se aqui se traduz ou não dado o contexto da linha anterior.

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Uma fatia de string pode receber um terceiro indíce. O primeiro especifica o começo, o terceiro o fim e o segundo o “tamanho do passo”; isto é, o número de espaços entre caracteres sucessivos. Um tam
```suggestion
Um pedaço de string pode receber um terceiro índice. O primeiro especifica o começo, o terceiro o fim e o segundo o “tamanho do passo”; isto é, o número de espaços entre caracteres sucessivos. Um tamanho de passo de 2 significa que andamos de dois em dois; 3 significa de três em três e etc.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +(((fatia)))
```suggestion
(((pedaço)))
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Um tamanho de passo -1 percorre a palavra ao contrário, então a fatia +[end:-1:1]+ gera uma string reversa.
```suggestion
Um tamanho de passo -1 percorre a palavra ao contrário, então o pedaço +[end:-1:1]+ gera uma string reversa.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Use esse idioma para escrever uma versão de uma linha de +ispalindrome+ do <<ex06-3>>.
```suggestion
Use esse idioma para escrever uma versão de uma linha de +ispalindrome+ do <<ex06-3>>.
```

Ver como foi traduzido no capítulo 6, se eu não me engano foi "é_palíndromo" - Capítulo da Kally.

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
>  (((ispalindrome)))
Mesma coisa.

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Para rotacionar uma palavra, rotacione cada letra pelo mesmo valor. Por exemplo +"cheer"+ rotacionado por 7 é +"jolly"+ e +"melon"+ rotacionado por -10 é +"cubed"+. No filme _2001: Odisseia no espaço
verificar o contexto e colocar uma palavra em portugues na cifra, trocar "cheer" por alguma palavra em PT-BR e rotacionar.

Talvez esse link te ajude a saber como fica rotacionado:
https://cryptii.com/pipes/caesar-cipher

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Por quê +'c'+ é a terceira letra do alfabeto. Mas tome cuidado: os códigos numéricos para letras maiúsculas são diferentes.
```suggestion
Por que +'c'+ é a terceira letra do alfabeto. Mas tome cuidado: os códigos numéricos para letras maiúsculas são diferentes.
```

2020-06-04 02:38 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +'a': ASCII/Unicode U+0061 (category Ll: letra, lowercase)
```suggestion
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
```

2020-06-12 05:58 UTC, joaoluisro commented on book/src/chap08.asciidoc
> +A função +sizeof+ retorna o número de bytes em uma string:
Acho que aqui o retorna está correto não? ``sizeof`` é uma função embutida

2020-06-12 06:02 UTC, joaoluisro commented on book/src/chap08.asciidoc
> +Esse padrão de computação-percorrendo a sequência e retornando quando achamos o que estamos procurando-é chamado de _busca_.
Acho que "percorrer" é muito mais intuitivo no contexto de laços, "travessar" aparece mais quando se fala de estruturas de dados mais complexas (árvores ou grafos), por isso a escolha.

2020-06-12 06:11 UTC, joaoluisro commented on book/src/chap08.asciidoc
> +Muitos cálculos envolvem o processamento de uma string, um caractere de cada vez. Comumente eles começam no início, selecionando cada caractere por vez, fazendo algo com ele, e continuando até o fina
Acho que aqui vale a pena mudar "cálculos" para "problemas computacionais", já que o autor não se referia à dificuldade do processamento de uma string, mas sim de que uma grande gama de problemas computacionais envolve o processamento de uma string caractere a caractere.

2020-06-12 06:13 UTC, joaoluisro commented on book/src/chap08.asciidoc
> +Esse padrão de computação-percorrendo a sequência e retornando quando achamos o que estamos procurando-é chamado de _busca_.
```suggestion
Percorrer uma sequência e retornar o objeto que estamos procurando quando achamos-o é um padrão de computação chamado de _busca_.
```
Que tal algo assim? Acho que fica melhor.

2020-06-12 06:18 UTC, joaoluisro commented on book/src/chap08.asciidoc
> +(((maiúscula)))((("função", "Base", "maiúscula", see="maiúscula")))
```suggestion
(((uppercase)))((("função", "Base", "uppercase", see="uppercase")))
```
Acho que todas se referem a função embutida, então acho que nenhuma deve ser traduzida

2020-06-12 06:19 UTC, joaoluisro commented on book/src/chap08.asciidoc
> +(((busca)))((("função", "Base", "busca", see="busca")))
```suggestion
(((search)))((("função", "Base", "search", see="search")))
```
Verdade, aqui também todas se referem a função embutida

2020-06-26 21:20 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Strings não são como inteiros, pontos flutuante e tipos booleanos. Uma string é uma _sequência_, o que significa que ela está em uma coleção ordenada de outros valores. Neste capítulo você verá como
```suggestion
Strings não são como inteiros, pontos flutuante e tipos booleanos. Uma string é uma _sequência_, o que significa que ela está em uma coleção ordenada de outros valores. Neste capítulo você verá como acessar os caracteres que compõem uma string e irá aprender sobre algumas funções auxiliares de strings fornecidas pelo Julia.
```

2020-06-26 21:21 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +O _padrão Unicode_ lida com as complexidades do que exatamente é um caractere e é geralmente aceitado como o padrão definitivo que resolve esse problema. Ele fornece um número único para todo caracte
Linha 14 é vazia, dar um _enter_ aqui

2020-06-26 21:23 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Uma String é uma sequência
```suggestion
=== Uma String é uma Sequência
```

2020-06-26 21:25 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> ++length+ é uma função embutida que retorna o número de caracteres em uma string:
Veja se fica melhor
```suggestion
+length+ é uma função interna que retorna o número de caracteres em uma string:
```

2020-06-26 21:27 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Mas você pode não conseguir o que espera.
Caso não aceite essa sugestão, clica em "Resolve Conversation" pra não aparecer na próxima revisão.

2020-06-26 21:28 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Muitos problemas computacionais envolvem o processamento de uma string, um caractere de cada vez. Comumente eles começam no início, selecionando cada caractere por vez, fazendo algo com ele, e contin
```suggestion
Muitos problemas computacionais envolvem o processamento de uma string, um caractere de cada vez. Geralmente eles começam no início, selecionando cada caractere por vez, fazendo algo com ele, e continuando até o final. Esse padrão de processamento é denominado de _travessia_. Um jeito de escrever uma travessia é com um laço +while+:
```

2020-06-26 21:29 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Muitos problemas computacionais envolvem o processamento de uma string, um caractere de cada vez. Comumente eles começam no início, selecionando cada caractere por vez, fazendo algo com ele, e contin
```suggestion
Muitos problemas computacionais envolvem o processamento de uma string, um caractere de cada vez. Comumente eles começam no início, selecionando cada caractere por vez, fazendo algo com ele e continuando até o final. Esse padrão de processamento é denominado de _travessia_. Um jeito de escrever uma travessia é com um laço +while+:
```

2020-06-26 21:30 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +O próximo exemplo mostra como usar concatenação (multiplicação de strings) e um laço+for+ para gerar séries abecedárias (isto é, em ordem alfabética). No livro de Robert McCloskey, _Make way for Duck
```suggestion
O próximo exemplo mostra como usar concatenação (multiplicação de strings) e um laço +for+ para gerar séries abecedárias (isto é, em ordem alfabética). No livro de Robert McCloskey, _Make way for Ducklings_ (Abram caminho para os Patinhos), os nomes dos patinhos são Jack, Kack, Lack, Mack, Nack, Ouack, Pack, e Quack. Esse laço gera os nomes em ordem:
```

2020-06-26 21:33 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +O próximo exemplo mostra como usar concatenação (multiplicação de strings) e um laço+for+ para gerar séries abecedárias (isto é, em ordem alfabética). No livro de Robert McCloskey, _Make way for Duck
Não consegui achar o nome original do livro em Português. Mas, talvez fique melhor assim, você decide ;)
```suggestion
O próximo exemplo mostra como usar concatenação (multiplicação de strings) e um laço+for+ para gerar séries abecedárias (isto é, em ordem alfabética). No livro de Robert McCloskey, _Make way for Ducklings_ (Abre alas para os Patinhos), os nomes dos patinhos são Jack, Kack, Lack, Mack, Nack, Ouack, Pack, e Quack. Esse laço gera os nomes em ordem:
```

2020-06-26 21:46 UTC, gustavosarturi requested changes

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Esse padrão de computação-percorrendo a sequência e retornando quando achamos o que estamos procurando-é chamado de _busca_.
Boa. Fica melhor.

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Realizando laços e Contando
```suggestion
=== Criando Laços e Contando
```

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Realizando laços e Contando
"Gerando", "Criando" ou até mesmo "Realizando", veja qual você acha melhor. Vou deixar as opções. Em ambos os casos, Camel Case.

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Realizando laços e Contando
```suggestion
=== Gerando Laços e Contando
```

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Realizando laços e Contando
```suggestion
=== Realizando Laços e Contando
```

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Encapsule esse código em uma função chamada +conte+, e a generealize para que ela aceite a string e a letra como argumentos.
```suggestion
Encapsule esse código em uma função chamada +conte+ e a generealize para que ela aceite a string e a letra como argumentos.
```

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Para debugar esse tipo de erro, o primeiro passo é imprimir os valores dos índices:
```suggestion
Para depurar esse tipo de erro, o primeiro passo é imprimir os valores dos índices:
```

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Debugando
```suggestion
=== Depuração
```

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +(((debugando)))(((travessia)))(((é_inversa)))((("função", "definido pelo programador", "é_inversa", see="é_inversa")))
```suggestion
(((depuração)))(((travessia)))(((é_inversa)))((("função", "definido pelo programador", "é_inversa", see="é_inversa")))
```

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Agora quando executamos novamente o programa, obtemos mais informação:
Plural
```suggestion
Agora quando executamos novamente o programa, obtemos mais informações:
```

2020-06-26 21:46 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Desta vez um +BoundsError+ foi gerado. O valor de +i+ é 5, que está fora do alcance para a string +"pare"+.
```suggestion
Desta vez um +BoundsError+ foi gerado. O valor de +i+ é 5, que está fora do alcance para a string +"erap"+.
```

2020-06-26 21:47 UTC, gustavosarturi commented
@joaoluisro - Acredito que, fazendo essas alterações, dando mais um check final, já dá pra repassar pro Abel.

2020-06-30 01:27 UTC, gustavosarturi reviewed
- Linha 316: Camel Case.
- Linha 581: Trocar "pots" por "erap", contrário da palavra "pare".

2020-06-30 01:27 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +=== Realizando laços e Contando
@joaoluisro - **_Camel Case._**

2020-06-30 01:27 UTC, gustavosarturi commented on book/src/chap08.asciidoc
> +Desta vez um +BoundsError+ foi gerado. O valor de +i+ é 5, que está fora do alcance para a string +"pare"+.
@joaoluisro - Aqui era um exemplo do contrário da palavra "stop - pots", no caso, "pare - erap". Linha 492.

2020-06-30 20:36 UTC, gustavosarturi approved these changes

2020-07-07 14:47 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> ++length+ é uma função embutida que retorna o número de caracteres em uma string:
```suggestion

+length+ é uma função interna que retorna o número de caracteres em uma string:
```

2020-07-07 19:02 UTC, abelsiqueira approved these changes

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +No caso de +frutas+, o caractere +🍌+ é um caractere de quatro bytes, então os índices 2,3 e 4 são inválidos e o índice do próximo caractere é 5; esse próximo índice válido pode ser calculado por +nex
```suggestion
No caso de +frutas+, o caractere +🍌+ é um caractere de quatro bytes, então os índices 2, 3 e 4 são inválidos e o índice do próximo caractere é 5; esse próximo índice válido pode ser calculado por +nextind(frutas, 1)+ e o índice depois dele por +nextind(frutas, 5)+ e assim por diante.
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +A função +firstindex+ retorna o primeiro índice de bytes válido. A palavra-chave +global+ antes de +índice+ indica que nós queremos re-atribuir a variável +índice+ definida em +Main+ (ver <<global_va
```suggestion
A função +firstindex+ retorna o primeiro índice de bytes válido. A palavra-chave +global+ antes de +índice+ indica que nós queremos reatribuir a variável +índice+ definida em +Main+ (ver <<global_variables>>).
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
>  julia> str[8:end]
```suggestion
julia> str[7:end]
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +O Julia não lida letras maiúsculas e minúsculas do mesmo jeito que as pessoas lidam. Todas as letras maiúsculas vem antes de todas as letras minúsculas, então:
```suggestion
O Julia não trata letras maiúsculas e minúsculas do mesmo jeito que as pessoas lidam. Todas as letras maiúsculas vem antes de todas as letras minúsculas, então:
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +Desta vez um +BoundsError+ foi gerado. O valor de +i+ é 5, que está fora do alcance para a string +"pare"+.
```suggestion
Desta vez um +BoundsError+ foi gerado. O valor de +i+ é 5, que está fora do alcance para a string +"erap"+.
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +Padrão ASCII::
```suggestion
padrão ASCII::
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +Padrão Unicode::
```suggestion
padrão Unicode::
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +Codificação UTF-8::
```suggestion
codificação UTF-8::
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +Leia a documentação das funções string em https://docs.julialang.org/en/v1/manual/strings/. Você talvez queira experimentar algumas delas para garantir que você entende como elas funcionam. +strip+ e
```suggestion
Leia a documentação das funções de string em https://docs.julialang.org/en/v1/manual/strings/. Você talvez queira experimentar algumas delas para garantir que você entende como elas funcionam. +strip+ e +replace+ são particulamente utéis.
```

2020-07-07 19:02 UTC, abelsiqueira commented on book/src/chap08.asciidoc
> +(((cifra de César)))
```suggestion
===== Exercício 8-11

Uma cifra de César é uma forma fraca de criptografia que envolve “rotacionar” cada letra por um número fixo de lugares. Rotacionar uma letra significa deslocar ela através do alfabeto, retornando ao começo se necessário, então +’A’+ rotacionada por 3 é +’D’+ e +’Z’+ rotacionada por 1 é +’A’+.
(((cifra de César)))
```

2020-07-07 19:21 UTC, merged