chapter11 translation
JuliaIntro/JuliaIntroBR.jl pull request #22
Opened 2020-05-15 16:49 UTC by joaoluisro

@abelsiqueira como fazemos com a quote do O'Leary ?

2020-05-18 13:09 UTC, abelsiqueira commented
Vamos fazer como no pense python, e não traduzir as palavras do puzzle: https://penseallen.github.io/PensePython2e/11-dicionarios.html
Como o material para resolver o puzzle é em inglês, não tem muito que dá pra fazer.

2020-05-27 02:24 UTC, chunggnuhc requested changes
1a revisão da Kally

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Este capítulo apresenta outra estrutura de dados embutida chamada de dicionário.
```suggestion
Este capítulo apresenta outra estrutura de dados embutida chamado dicionário.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +=== Um Dicionário é um Mapeamento
A numeração das linhas está diferente.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Um _dicionário_ é como um array, mas mais geral. Em um array, os indíces tem que ser inteiros; em um dicionário eles podem ser (quase) de qualquer tipo.
```suggestion
Um _dicionário_ é como um array, mas mais geral. Em um array, os índices devem ser inteiros e em um dicionário, eles podem (quase) ser de qualquer tipo.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Um _dicionário_ é como um array, mas mais geral. Em um array, os indíces tem que ser inteiros; em um dicionário eles podem ser (quase) de qualquer tipo.
O único erro que eu encontrei foi o acento na palavra "índices", de resto é sugestão de minha opinião para dar mais fluidez na leitura.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Um dicionário contém uma coleção de indíces, que são chamados de _chaves_, e uma coleção de valores. Cada chave é associada a um único valor. A associação de uma chave e um valor é chamada de _par ch
```suggestion
Um dicionário contém uma coleção de índices, que são chamados de _chaves_, e uma coleção de valores. Cada chave é associada a um único valor. A associação de uma chave e um valor é chamada de _par chave-valor_ ou, às vezes, de item.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Em linguagem matemática, um dicionário representa um _mapeamento_ de chave para valores, então você também pode dizer que cada chave “é mapeado” para um valor. Como um exemplo, iremos construir um di
```suggestion
Na linguagem matemática, um dicionário representa um _mapeamento_ da chave para os valores, então você também pode dizer que cada chave “é mapeado” para um valor. Como um exemplo, iremos construir um dicionário que mapeia palavras em Português para palavras em Espanhol, com as chaves e os valores todos strings.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +julia> por2sp = Dict()
Será que não faz mais sentido traduzir para "por_para_sp" ou "port_para_esp"?

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Esse formato de resultado também é um formato de entrada. Por exemplo, você pode criar um novo dicionário com três itens:
```suggestion
Essa formatação de saída também é uma formatação de entrada. Por exemplo, você pode criar um novo dicionário com três itens:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Esse formato de resultado também é um formato de entrada. Por exemplo, você pode criar um novo dicionário com três itens:
A tradução de format pode ser formato ou formatação. Mas na minha opinião, eu acho que o termo "formatação" está mais associado ao jeito de escrever do que o termo "formato".

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +  "dois"   => "dos"
Arrumar o espaçamento, como nas linhas de baixo.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Mas isso não é um problema pois os elementos de um dicionário nunca são indexados com indíces inteiros. Ao invés disso, nós usamos as chaves para consultar os valores correspondentes:
```suggestion
Mas isso não é um problema pois os elementos de um dicionário nunca são indexados com índices inteiros. Ao invés disso, nós usamos as chaves para consultar os valores correspondentes:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +A chave "dois" sempre é mapeada par ao valor "dos", então a ordem dos itens não importa.
```suggestion
A chave "dois" sempre é mapeada para o valor "dos", então a ordem dos itens não importa.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  ERROR: KeyError: key "four" not found
```suggestion
ERROR: KeyError: key "quatro" not found
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +A função +length+ funciona em dicionários; ela retorna o número de pares chave-valor:
```suggestion
A função +length+ funciona nos dicionários e retorna o número de pares chave-valor:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +A função +length+ funciona em dicionários; ela retorna o número de pares chave-valor:
Não tem nenhum erro, mas
(1) em "A função +length+ funciona em dicionários", essa mania de comer os artigos (_o, a, os, as_) se chama anglicismo. Tem gente q tem estramento com a leitura qdo isso acontece.
(2) Eu fiz a sugestão que, na minha opinião, melhoram a fluidez da leitura.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  (((in)))
Eu acho q poderia traduzir para (((operador in))). O q vc acha @joaoluisro ?

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Para verificar se algo aparece como um valor em um dicionário, você pode usar a função +values+, que retorna uma coleção de valores, e em seguida usar o operador +∈+:
```suggestion
Para verificar se algo aparece como um valor em um dicionário, você pode usar a função +values+ que retorna uma coleção de valores, e em seguida usar o operador +∈+:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Para verificar se algo aparece como um valor em um dicionário, você pode usar a função +values+, que retorna uma coleção de valores, e em seguida usar o operador +∈+:
Sugestão só para melhorar a fluidez da leitura.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +O operador +∈+ utiliza algoritmos diferentes para arrays e dicionários. Para arrays, ele busca os elementos do array em ordem, como em <<searching>>. À medida que o array fica maior, o tempo de busca
```suggestion
O operador +∈+ utiliza algoritmos diferentes para os arrays e dicionários. Para os arrays, ele busca os elementos do array em ordem, como em <<searching>>. À medida que o array fica maior, o tempo de busca cresce diretamente proporcional.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +O operador +∈+ utiliza algoritmos diferentes para arrays e dicionários. Para arrays, ele busca os elementos do array em ordem, como em <<searching>>. À medida que o array fica maior, o tempo de busca
São só sugestões... não tem nenhum erro.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Para dicionários, o Julia usa um algoritmo chamado de _tabela hash_ que possui uma propriedade expecional: o operador +∈+ leva aproximadamente o mesmo não importa quantos itens o dicionário possui.
```suggestion
Para os dicionários, o Julia usa um algoritmo chamado _tabela hash_ (ou tabela de dispersão ou tabela de espalhamento) que possui uma propriedade excepcional: o operador +∈+ leva aproximadamente o mesmo tempo independente da quantidade de itens do dicionário.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Suponha que é dado à você uma string e você gostaria de contar quantas vezes cada letra aparece. Existem muitas maneiras de fazer isso:
Sugestão 1: 
```suggestion
Suponha que é dado a você uma string e você gostaria de contar quantas vezes cada letra aparece. Existem muitas maneiras de fazer isso:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +* Você poderia criar 26 variáveis, um para cada letra do alfabeto. Em seguida você poderia percorrer a string, e para cada caractere, incrementar o contador correspondente, provávelmente usando um co
```suggestion
* Você poderia criar 26 variáveis, um para cada letra do alfabeto. Em seguida você poderia percorrer a string, e para cada caractere, incrementar o contador correspondente, provavelmente usando um condicional encadeado.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +* Você poderia criar um array com 26 elementos. Em seguida você poderia converter cada caractere para um número (usando a função embutida +Int+), usar o número como um indíce para o array, e incremen
Sugestão para tirar repetição do você na 1a frase e logo em seguida na 2a frase.
```suggestion
* Você poderia criar um array com 26 elementos. Em seguida pode-se converter cada caractere para um número (usando a função embutida +Int+), usar o número como um índice para o array, e incrementar o contador adequado.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +* Você poderia criar um dicionário com caracteres como chaves e contadores como seus valores correspondentes. A primeira vez que você vê um caractere, você adicionaria um item no dicionário. Após iss
Minha sugestão para melhorar a leitura do texto.
```suggestion
* Você poderia criar um dicionário com os caracteres como as chaves e os contadores como seus valores correspondentes. A primeira vez que você vê um caractere, adicionaria um item no dicionário. Após isso, você só incrementaria o valor de um item existente.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Cada uma dessas opções efetua o mesmo cálculo, mas cada uma delas implementa este cálculo de maneiras diferentes.
Vc tem usado mto "maneira". Como vc já vai usar o termo "maneira" no próximo parágrafo, vamos dar uma variada.
```suggestion
Cada uma dessas opções efetua o mesmo cálculo, mas cada uma delas implementa este cálculo de formas diferentes.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma _implementação_ é uma maneira de efetuar um cálculo; algumas implementações são melhores que outras. Por exemplo, uma vantagem da implementação do dicionário é que nós não temos que saber antecip
Minha sugestão para melhorar a fluidez da leitura.
```suggestion
Uma _implementação_ é uma maneira de efetuar um cálculo e algumas implementações são melhores que outras. Por exemplo, uma vantagem da implementação do dicionário é que nós não temos que saber antecipadamente quais letras aparecem na string, e sim criar espaço só para as letras que aparecem.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +A primeira linha da função cria um dicionário vazio. O loop +for+ percorre a string. Toda vez que o loop é percorrido, se o caractere +c+ não está no dicionário, nós criamos um novo item com a chave
Eu tinha a impressão de que combinamos de usar laço como tradução de loop.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +julia> h = histograma("brontosaurus")
```suggestion
julia> h = histograma("brontossauro")
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  ----
Arrumar a saída do dicionário tb após mudar para "brontossauro".

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +O histograma indica que as letras +'a'+ e +'b'+ aparecem uma vez; +'o'+ aparece duas, e assim em diante.
```suggestion
O histograma indica que as letras +'a'+ e +'b'+ aparecem uma vez; +'o'+ aparece três, e assim em diante.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Novamente, as chaves não estão em nenhuma ordem específica. Para percorrer as chaves em ordem, você pode combinar +sort+ e +collect+:
```suggestion
Novamente as chaves não estão em nenhuma ordem específica. Para percorrer as chaves em ordem, você pode combinar +sort+ e +collect+:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +=== Dando Laços e Dicionários
```suggestion
=== Laços e Dicionários
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +=== Consulta Invertida
Minha sugestão:
```suggestion
=== Consulta Inversa
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Mas e se você tem +v+ e quer achar +k+? Você tem dois problemas: primeiro, pode haver mais de uma chave que mapeia para o valor +v+. Dependendo da aplicação, você poderia escolher um, ou você teria q
```suggestion
Mas e se você tem +v+ e quer achar +k+? Você tem dois problemas: primeiro, pode haver mais de uma chave que mapeia para o valor +v+. Dependendo do que é pedido, você poderia escolher um, ou teria que criar um array que contém todos eles. Segundo, não há uma sintaxe simples que faz uma _consulta invertida_; você tem que procurar.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +=== Consulta Invertida
Se vc aderir à sugestão, acho legal vc trocar todos os termos "consulta invertida" para "consulta inversa" e não ficar só no título.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  ERROR: LookupError
Faltou traduzir o "reverselookup" e "LookupError".

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +O efeito de uma exceção gerada é o mesmo quando o Julia gera um: ele exibe o stracktrace e uma mensagem de erro.
```suggestion
O resultado de uma exceção gerada é o mesmo quando o Julia gera um: ele exibe o stracktrace e uma mensagem de erro.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma consulta invertida é muito  mais devagar que uma consulta normal; se você tiver que executá-la várias vezes, ou se o dicionário ficar muito grande, a performance do seu programa irá diminiuir.
```suggestion
Uma consulta invertida é muito mais demorada que uma consulta normal; se você tiver que executá-la várias vezes, ou se o dicionário ficar muito grande, o desempenho do seu programa diminuirá.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Arrays podem aparecer como valores em um dicionário. Por exemplo, se você receber um dicionário que mapeia letras à frequências, você pode querer invertê-lo; isto é, criar um dicionário que mapeia fr
```suggestion
Arrays podem aparecer como valores em um dicionário. Por exemplo, se você receber um dicionário que mapeia letras às frequências, você pode querer invertê-lo; isto é, criar um dicionário que mapeia frequências até as letras. Já que várias letras podem ter a mesma frequência, cada valor em um dicionário invertido deve ser um array de letras.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  ----
Talvez traduzir invertdict para inverte_dict ou invertedict? Traduzir outros termos dentro da function.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Cada vez que o loop é percorrido, +key+ recebe uma chave de +d+ e +val+ recebe o valor correspondente. Se +vaç+ não está em +inverse+, isto significa que não a vimos ainda, então criamos um novo item
```suggestion
Cada vez que o loop é percorrido, +key+ recebe uma chave de +d+ e +val+ recebe o valor correspondente. Se +val+ não está em +inverse+, isto significa que não a vimos ainda, então criamos um novo item e inicializamos com um _singleton_ (um array que contém um único elemento). Caso contrário esse valor já foi visto, e então acrescentamos a chave correspondente ao array.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  julia> inverse = invertdict(hist)
Faltou tradução aqui.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +<<fig11-1>> é um diagrama de estado mostrando +hist+ e +inverse+. Um dicionário é representado como uma caixa com os pares chave-valor dentro. Se os valores são inteiros, pontos flutuantes ou strings
Sugestão:
```suggestion
<<fig11-1>> é um diagrama de estado mostrando +hist+ e +inverse+. Um dicionário é representado como uma caixa com os pares chave-valor dentro. Para os valores que são inteiros, pontos flutuantes ou strings, eu os desenho dentro da caixa, já para os arrays normalmente desenho fora da caixa, só para simplificar o diagrama.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Eu mencionei anteriormente que um dicionário é implementado usando uma tabela hash e isso significa que as chaves devem ser _hashable_.
Como não tem tradução para hashable, dei essa sugestão:
```suggestion
Eu mencionei anteriormente que um dicionário é implementado usando uma tabela hash e isso significa que as chaves devem ser _hashable_, ou de um tipo que tem uma função hash.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se você já brincou com a função +fibonacci+ de <<one_more_exemplo>>, você pode ter percebido que quanto maior o argumento que você fornece, mais tempo a função leva para executar. Além disso, o tempo
```suggestion
Se você já brincou com a função +fibonacci+ de <<one_more_exemple>>, você pode ter percebido que quanto maior o argumento que você fornece, mais tempo a função leva para executar. Além disso, o tempo de execução cresce rapidamente.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  (((fibonnaci)))
@abelsiqueira , essa referência está errada. O correto é 
```suggestion
(((fibonacci)))
```
@abelsiqueira, tem q criar um issue.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Para entender o por que, considere <<fig11-2>>, que mostra um _grafo de chamada_ para +fibonacci+ com +n = 4+:
```suggestion
Para entender o porquê, considere <<fig11-2>>, que mostra um _grafo de chamada_ para +fibonacci+ com +n = 4+:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Um grafo de chamada mostra um conjunto de quadros de função, com linhas conectando cada quadro à quadros no qual a função chama. No topo do grafo, +fibonacci+ com +n = 4+ chama +fibonacci+ com +n = 3
```suggestion
Um grafo de chamada mostra um conjunto de quadros da função, com linhas conectando cada quadro aos quadros (que/os quais) a função chama. No topo do grafo, +fibonacci+ com +n = 4+ chama +fibonacci+ com +n = 3+ e +n = 2+. Por sua vez, +fibonacci+ com +n = 3+ chama +fibonacci+ com +n = 2+ e +n = 1+. E assim em diante.
```
Você pode usar ou "que" ou "os quais" no final da 1a frase. Pensa assim: (1) _A função chama os quadros_ ou (2)_A função chama nos quadros_? Se a opção (2) for a mais apropriada, vc usa "no que" ou suas variações como "no qual/nos quais".

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Conte quantas vezes +fibonacci(0)+ e +fibonacci(1)+ são chamadas. Está é uma solução ineficiente do problema, e fica pior a medida em que o argumento aumenta.
```suggestion
Conte quantas vezes +fibonacci(0)+ e +fibonacci(1)+ são chamadas. Está é uma solução ineficiente do problema, e fica pior à medida em que o argumento aumenta.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma solução é acompanhar os valores que já foram calculados armazenando eles em um dicionário. Um valor previamente calculado que é armazenado para uso posterior é chamado de _memo_. Aqui está uma ve
```suggestion
Uma solução é acompanhar os valores já calculados armazenando-os em um dicionário. Um valor previamente calculado que é armazenado para uso posterior é chamado de _memo_. Aqui está uma versão “memoizada” de fibonacci:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> ++conhecido+ é um dicionáro que acompanha os números de fibonacci que já sabemos. Ele começa com dois itens: +0+ mapeia para +0+ e +1+ mapeia para +1+.
```suggestion
+conhecido+ é um dicionáro que guarda os números de Fibonacci que já sabemos. Ele começa com dois itens: +0+ mapeia para +0+ e +1+ mapeia para +1+.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Toda vez que +fibonacci+ é chamada, ela checa +conhecidos+. Se o resultado já está lá, ela retorna imediatamente. Por outro lado ela tem que computar um novo valor, adicionar ao dicionário, e retorná
Sugestão para melhorar a sintaxe da frase.
```suggestion
Toda vez que +fibonacci+ é chamada, ela checa +conhecidos+. Se o resultado já está lá, ela retorna imediatamente. Por outro lado, ela tem que computar um novo valor, que é adicionado no dicionário e devolvido.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se você executar esta versão de +fibonacci+ e comparar com a original, você verá que ela é muito mais rápida.
```suggestion
Se você executar esta versão de +fibonacci+ e comparar com a original, você verá que a atual é muito mais rápida.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +No exemplo anterior, conhecidos é criado fora da função, então ela pertence ao quadro especial chamado +Main+. Variáveis em +Main+ são as vezes chamadas de _globais_ pois podem ser acessadas de qualq
```suggestion
No exemplo anterior, conhecidos é criado fora da função, então ela pertence ao quadro especial chamado +Main+. Variáveis em +Main+ são às vezes chamadas de _globais_ pois podem ser acessadas de qualquer função. Diferente de variáveis locais, que desaparecem quando a função acaba, variáveis globais persistem de uma chamada de função para a próxima.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +(((global)))((("palavra-chave", "global", see="global")))(((global variable)))
```suggestion
(((global)))((("palavra-chave", "global", see="global")))(((variável global)))
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +É comum usar variáveis globais para _flags_; isto é, variáveis booleanas que indicam (“flag”) se uma condição é verdadeira. Por exemplo, alguns programas usam uma flag chamada +verbose+ para controla
```suggestion
É comum usar variáveis globais para _flags_; isto é, variáveis booleanas que indicam (“sinal”) se uma condição é verdadeira. Por exemplo, alguns programas usam uma flag chamada +verbose+ para controlar o nível de detalhamento na saída:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se você tentar re-atribuir uma variável global, você poderá se surpreender. O exemplo a seguir deve acompanhar se a função foi chamada:
```suggestion
Se tentar reatribuir uma variável global, você poderá se surpreender. O exemplo a seguir deve acompanhar se a função foi chamada:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Mas se você executar ela você verá que o valor de +foi_chamada+ não muda. O problema é que +exemplo2+ cria uma nova variável local chamada +foi_chamada+. A variável local vai embora quando a função t
```suggestion
Mas se você executar a função, você verá que o valor de +foi_chamada+ não muda. O problema é que +exemplo2+ cria uma nova variável local denominada +foi_chamada+. A variável local é removida quando a função termina, e não tem nenhum efeito sobre a variável global.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Para re-atribuir uma variável global dentro de uma função você deve _declarar_ a variável global antes de usá-la:
```suggestion
Para reatribuir uma variável global dentro de uma função, você deve _declarar_ a variável global antes de usá-la:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +(((declaração)))(((re-atribuição)))
```suggestion
(((declaração)))(((reatribuição)))
```
Pelo o que eu pesquisei, é reatribuir, td junto.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +A _declaração global_ indica ao interpretador algo como, “Nesta função, quando eu digo +foi_chamada+, eu quero dizer a variável global; não crie uma local”
```suggestion
A _declaração global_ indica ao interpretador algo como “Nesta função, quando eu digo +foi_chamada+, eu quero dizer a variável global; não crie uma local.”
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +function exrmplo3()
```suggestion
function exemplo3()
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se você executá-la, você recebe:
Sugestão para evitar a repetição do "você".
```suggestion
Ao executar a função, você recebe:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  ERROR: UndefVarError: count not defined
```suggestion
ERROR: UndefVarError: conta not defined
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +O Julia assume que +conta+ é local, e a partir desta suposição, de que você está lendo antes de escrevê-la. A solução, novamente, é declarar +conta+ como global.
```suggestion
O Julia assume que +conta+ é local, partindo da suposição de que você está lendo a função antes de escrevê-la. A solução, novamente, é declarar +conta+ como global.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Então você pode adicionar, remover e substituir elementos de um array global ou dicionário, mas se você quiser re-atribuir uma variável, você deve declarar ela como global:
```suggestion
Então você pode adicionar, remover e substituir os elementos de um array global ou dicionário, mas se você quiser reatribuir a variável, você deve declará-la como global:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Por razões de performance, você deve declarar uma variável global como constante. Você não pode mais re-atribuir a variável mas se ela refere-se a um valor mutável, você pode modificar o valor.
Sugestões para evitar repetição de "você".
```suggestion
Por razões de performance, deve-se declarar uma variável global como constante. Não é mais possível reatribuir a variável mas caso ela faz referência a um valor mutável, você pode modificar o valor.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Variáveis globais podem ser utéis, mas se você tem muitas delas, e você as modifica frequentemente, elas podem fazer com que programas sejam dificéis de debugar e possuam performance ruim.
```suggestion
Variáveis globais podem ser utéis, mas se tem muitas delas, e você modifica-as frequentemente, elas podem ser a causa dos programas serem dificéis de debugar e terem performance ruim.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +A medida em que você trabalha com datasets maiores, pode ser que seja difícil debugar imprimindo e checando a saída na mão. Aqui estão algumas sugestões para debugar datasets maiores:
```suggestion
Na medida em que você trabalha com datasets maiores, pode ser que seja difícil debugar imprimindo e checando a saída na mão. Aqui estão algumas sugestões para debugar datasets maiores:
```
https://www12.senado.leg.br/manualdecomunicacao/redacao-e-estilo/estilo/a-medida-na-medida-em-que

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se possível, reduza o tamanho do dataset. Por exemplo, se o programa lê um arquivo de texto, comece com apenas as 10 primeiras linhas, ou com o menor exemplo que você encontre que gere um erro. Você
```suggestion
Se possível, reduza o tamanho do dataset. Por exemplo, se o programa lê um arquivo de texto, comece com apenas as 10 primeiras linhas, ou com o menor exemplo que dá erro. Você não deve editar os arquivos em si, mas modificar o programa para que ele leia somente as primeiras latexmath:[\(n\)] linhas.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se existe um erro, você pode reduzir latexmath:[\(n\)] para o menor valor que gera um erro, e em seguida incrementá-lo gradualmente a medida em que você encontra e corrige erros.
```suggestion
Se existe um erro, você pode reduzir de latexmath:[\(n\)] para o menor valor que dá erro, e em seguida incrementá-lo gradualmente à medida que você encontra e corrige os erros.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +* Verifique os resumos e tipos:
```suggestion
* Verifique os resumos e os tipos:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +(((verificar)))
```suggestion
(((verificação)))
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma causa comum de erros de execução é um valor que não é do tipo correto. Para debugar esse tipo de erro, é geralmente suficiente imprimir o tipo de um valor.
```suggestion
Uma causa comum de erros de execução é um valor que não é do tipo correto. Para debugar esse tipo de erro, geralmente é suficiente imprimir o tipo de um valor.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Algumas vezes você pode escrever código para checar erros automaticamente. Por exemplo, se você está calculando a média de um array de números, você poderia checar que o resultado não é maior que o m
```suggestion
Algumas vezes você pode escrever código para checar os erros automaticamente. Por exemplo, se você está calculando a média de um array de números, você poderia checar que o resultado não está acima do maior elemento do array ou abaixo do menor elemento. Isso é chamado de “verificação de sanidade”.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Resultados de depuração formatados podem facilitar a detecção de erros. Nós vimos um exemplo em <<deb06>>.
```suggestion
Resultados de debugging formatados podem facilitar a detecção de erros, como visto em um exemplo em <<deb06>>.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +(((Formatação)))
```suggestion
(((formatação)))
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Novamente, tempo que você gasta construindo andaimes pode reduzir o tempo gasto debugando.
Só sugestões:
```suggestion
E mais uma vez, o tempo que você usa construindo andaimes pode reduzir o tempo gasto no debugging.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +(((andaimes)))(((debugando)))
```suggestion
(((andaime)))(((debugging)))
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +=== Debugando
Vc acha ruim deixar o próprio termo "Debugging"? Nos capítulos q eu traduzi, em particular esses, eu nunca traduzi o título.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Um mapeamento de chaves para seus valores correspondentes.
```suggestion
Um mapeamento de chaves para os seus valores correspondentes.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +consulta inversa::
Vc tem que decidir se usa "consulta inversa" ou "consulta invertida". Em particular, eu gosto mais de "consulta inversa".

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma operação de dicionário que recebe um valor e encontra uma ou mais chaves que o mapeiam.
```suggestion
Uma operação em um dicionário que recebe um valor e encontra uma ou mais chaves mapeadas para ele.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Um diagrama que mostra todo quadro criado durante a execução do programa, com uma flecha que vai de quem chama para quem é chamado.
```suggestion
Um diagrama que mostra todo quadro criado durante a execução de um programa, com uma flecha que vai de quem chama para quem é chamado.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Um valor computado guardado para evitar cálculos futuros desnecessários.
Só sugestões:
```suggestion
Um valor já computado e guardado para evitar cálculos futuros desnecessários.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma declaração que declara um nome de variável como global.
Sugestão para evitar declaração e declara.
```suggestion
Uma declaração para tornar um nome de variável como global.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma declaração como +global+ que indica ao interpretador algo sobre a variável.
```suggestion
Uma declaração como +global+ que informa ao interpretador algo sobre a variável.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma variável global que não pode ser re-atribuida.
```suggestion
Uma variável global que não pode ser reatribuída.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Escreva uma função que leia palavras em _words.txt_ e as guarde como chaves em um dicionário. Não importa quais sejam os valores. Em seguida você pode usar o operador +∈+ como uma maneira rápida de v
```suggestion
Escreva uma função que leia palavras em _palavras.txt_ e guarde-as como chaves em um dicionário. Não importa quais sejam os valores. Em seguida, você pode usar o operador +∈+ como uma maneira rápida de verificar se uma string está ou não no dicionário.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se você fez <<ex10-10>>, você pode comparar a velocidade desta implementação com o operador +∈+ em arrays e a busca bissecção.
Sugestão para tirar repetição de "você":
```suggestion
Se você fez <<ex10-10>>, é possível comparar o tempo desta implementação com o operador +∈+ em arrays e na busca em bissecção.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Leia a documentação da função de dicionário +get!+ e a use para escrever uma versão mais concisa de +invertdict+.
```suggestion
Leia a documentação da função de dicionário +get!+ e use-a para escrever uma versão mais concisa de +invertdict+.
```
Além disso, não esqueça de traduzir "invertdict".

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Memoize a função Ackermann de <<ex06-2>> e verifique se a memoização faz possível avaliar a função com argumentos maiores.
```suggestion
Memoize a função de Ackermann de <<ex06-2>> e verifique se a memoização possibilita a avaliação da função com argumentos maiores.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  (((memo)))(((Ackermann function)))
```suggestion
(((memo)))(((função de Ackermann)))
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se você fez <<ex10-7>>, você já possui uma função chamada +hasduplicates+ que recebe um array como parâmetro e retorna +true+ se há qualquer objeto que aparece mais de uma vez em um array.
Sugestão para tirar repetição de "você":
```suggestion
Se você fez <<ex10-7>>, então já possui uma função chamada +tem_duplas+ que recebe um array como parâmetro e retorna +true+ se há qualquer objeto que aparece mais de uma vez no array.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Use um dicionário para escrever uma versão mais rápida, e mais simples de +hasduplicates+.
```suggestion
Use um dicionário para escrever uma versão mais rápida e simplificada de +tem_duplas+.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Escreva um programa que lê um array e ache todos os pares rotacionados.
```suggestion
Escreva um programa que lê um array e encontra todos os pares rotacionados.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  (((hasduplicates)))
```suggestion
(((tem_duplas)))
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  This was sent in by a fellow named Dan O’Leary. He came upon a common one-syllable, five-letter word recently that has the following unique property. When you remove the first letter, the remaining l
João, tem q traduzir aqui tb... Se vc preferir, vc traduz assim:
"Isto foi enviado por uma pessoa chamado Dan O'Leary. Ele encontrou recentemente uma palavra comum de inglês de uma sílaba e cinco letras que tem a seguinte propriedade única. ....."

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Now I’m going to give you an exemplo that doesn’t work. Let’s look at the five-letter word, ‘wrack.’ W-R-A-C-K, you know like to ‘wrack with pain.’ If I remove the first letter, I am left with a four
Aqui tb tem q traduzir.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  But there is, however, at least one word that Dan and we know of, which will yield two homophones if you remove either of the first two letters to make two, new four-letter words. The question is, wh
Aqui tb tem q traduzir.

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Você pode usar um dicionário de <<ex11-1>> para verificar se uma string está no array de palavras.
```suggestion
Você pode usar o dicionário de <<ex11-1>> para verificar se uma string está no array de palavras.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Para verificar se duas palavras são homofones, você pode usar o Dicionário CMU de Pronunciação. Você pode baixá-lo em  http://www.speech.cs.cmu.edu/cgi-bin/cmudict.
```suggestion
Para verificar se duas palavras em inglês são homônimas, você pode usar o Dicionário CMU de Pronunciação. Pode-se baixá-lo em  http://www.speech.cs.cmu.edu/cgi-bin/cmudict.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +O tipo de dicionário é cercado por chaves: as chaves são do tipo +Any+ e os valores também são do tipo +Any+.
```suggestion
O tipo do dicionário é cercado por chaves: as chaves são do tipo +Any+ e os valores também são do tipo +Any+.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Essa linha cria um item que mapeia a chave "um" para o valor "uno". Se nós imprimirmos o dicionário novamente, nós vemos o par chave-valor com a flecha +pass:[=&gt;]+ entre a chave e o valor:
```suggestion
Essa linha cria um item que mapeia a chave "um" para o valor "uno". Se imprimirmos o dicionário novamente, nós vemos o par chave-valor com a flecha +pass:[=&gt;]+ entre a chave e o valor:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +A ordem do par chave-valor pode não ser a mesma. Se você digitar o mesmo exemplo no seu computador, você pode obter um resultado diferente. Em geral, a ordem dos itens em um dicionário é imprevisível
Sugestão para tirar repetição de "você":
```suggestion
A ordem do par chave-valor pode não ser a mesma. Se você digitar o mesmo exemplo no seu computador, pode obter um resultado diferente. Em geral, a ordem dos itens em um dicionário é imprevisível.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Dicionários possuem uma função chamada +get+ que recebe uma chave e uma valor padrão. Se a chave aparece no dicionário, +get+ retorna o valor correspondente; caso contrário ela retorna o valor padrão
```suggestion
Dicionários possuem uma função chamada +get+ que recebe uma chave e um valor padrão. Se a chave aparece no dicionário, +get+ retorna o valor correspondente; caso contrário ela retorna o valor padrão. Por exemplo:
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma função usado por uma tabela hash para calcular a localização de uma chave.
```suggestion
Uma função usado por uma tabela hash para determinar a localização de uma chave.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma operação de dicionário que recebe uma chave e encontra o valor correspondente.
Sugestão só para deixar mais bonito. 
```suggestion
Uma operação em um dicionário que recebe uma chave e encontra o valor correspondente.
```

2020-05-27 02:24 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma variável booleana usada para inidicar se uma condição é verdadeira.
```suggestion
Uma variável booleana usada para indicar se uma condição é verdadeira.
```

2020-05-31 16:33 UTC, joaoluisro commented
@chunggnuhc o motivo pelo qual não traduzi o parágrafo do puzzle:
> Vamos fazer como no pense python, e não traduzir as palavras do puzzle: https://penseallen.github.io/PensePython2e/11-dicionarios.html
> Como o material para resolver o puzzle é em inglês, não tem muito que dá pra fazer.

Uma opção seria encontrar algo parecido e semelhante em português, pelo que vi na versão em espanhol o puzzle também não foi traduzido.

2020-05-31 16:58 UTC, joaoluisro commented on book/src/chap11.asciidoc
>  (((in)))
Acho que não, dependendo de como foi feito nos outros capítulos é melhor deixar por enquanto.

2020-06-02 01:17 UTC, chunggnuhc commented on book/src/chap11.asciidoc
>  (((in)))
Blz

2020-06-02 02:42 UTC, abelsiqueira commented
> @chunggnuhc o motivo pelo qual não traduzi o parágrafo do puzzle:
> 
> > Vamos fazer como no pense python, e não traduzir as palavras do puzzle: [penseallen.github.io/PensePython2e/11-dicionarios.html](https://penseallen.github.io/PensePython2e/11-dicionarios.html)
> > Como o material para resolver o puzzle é em inglês, não tem muito que dá pra fazer.
> 
> Uma opção seria encontrar algo parecido e semelhante em português, pelo que vi na versão em espanhol o puzzle também não foi traduzido.

@joaoluisro, não fui claro aqui, o que eu quis dizer é traduzir o quote, exceto nas palavras do puzzle, i.e., traduzir mas deixar esse `W-R-E-C-K`, etc..

2020-06-02 02:45 UTC, chunggnuhc requested changes

2020-06-02 02:45 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Mas e se você tem +v+ e quer achar +k+? Você tem dois problemas: primeiro, pode haver mais de uma chave que mapeia para o valor +v+. Dependendo do que é pedido, você poderia escolher um, ou teria que
```suggestion
Mas e se você tem +v+ e quer achar +k+? Você tem dois problemas: primeiro, pode haver mais de uma chave que mapeia para o valor +v+. Dependendo do que é pedido, você poderia escolher um, ou teria que criar um array que contém todos eles. Segundo, não há uma sintaxe simples que faz uma _consulta inversa_; você tem que procurar.
```

2020-06-02 02:45 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +<<fig11-1>> é um diagrama de estado mostrando +hist+ e +inverse+. Um dicionário é representado como uma caixa com os pares chave-valor dentro. Para os valores que são inteiros, pontos flutuantes ou s
```suggestion
<<fig11-1>> é um diagrama de estado mostrando +hist+ e +inverso+. Um dicionário é representado como uma caixa com os pares chave-valor dentro. Para os valores que são inteiros, pontos flutuantes ou strings, eu os desenho dentro da caixa, já para os arrays normalmente desenho fora da caixa, só para simplificar o diagrama.
```

2020-06-02 02:45 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Conte quantas vezes +fibonacci(0)+ e +fibonacci(1)+ são chamadas. Está é uma solução ineficiente do problema, e fica pior à medida em que o argumento aumenta.
Eu deixei passar esse erro na 1a vez.
```suggestion
Conte quantas vezes +fibonacci(0)+ e +fibonacci(1)+ são chamadas. Está é uma solução ineficiente do problema, e fica pior à medida que o argumento aumenta.
```

2020-06-02 02:45 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se você fez <<ex10-10>>, você pode comparar a velocidade desta implementação com o operador +∈+ em arrays e na busca em bissecção.
```suggestion
Se <<ex10-10>> foi feito, você pode comparar a velocidade desta implementação com o operador +∈+ em arrays e na busca em bissecção.
```

2020-06-02 02:45 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Para verificar se duas palavras em inglês são homônimas, você pode usar o Dicionário CMU de Pronunciação. Pode-se baixá-lo em  http://www.speech.cs.cmu.edu/cgi-bin/cmudict.
```suggestion
Para verificar se duas palavras em inglês são homônimas, você pode usar o Dicionário CMU de Pronunciação. E também pode baixá-lo em  http://www.speech.cs.cmu.edu/cgi-bin/cmudict.
```

2020-06-02 18:39 UTC, joaoluisro commented on book/src/chap11.asciidoc
> +Uma função usado por uma tabela hash para calcular a localização de uma chave.
Aqui não estaria errado trocar "calcular" por "determinar", mas o algoritmo da tabela hash de fato "calcula" a localização da chave (mas pode ser frescura minha !).

2020-06-05 05:11 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma função usado por uma tabela hash para calcular a localização de uma chave.
```suggestion
Uma função usado por uma tabela hash para computar a localização de uma chave.
```
O que vc acha dessa sugestão? Segundo o dicionário, computar é sinônimo de calcular e na minha opinião, me parece até melhor q o "determinar".

2020-06-06 00:36 UTC, chunggnuhc requested changes

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Na linguagem matemática, um dicionário representa um _mapeamento_ da chave para os valores, então você também pode dizer que cada chave “é mapeado” para um valor. Como um exemplo, iremos construir um
```suggestion
Na linguagem matemática, um dicionário representa um _mapeamento_ das chaves para os valores, então você também pode dizer que cada chave “é mapeado” para um valor. Como um exemplo, iremos construir um dicionário que mapeia palavras em Português para palavras em Espanhol, com as chaves e os valores todos strings.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Todas as chaves e os valores iniciais são strings, então um +Dict{String, String}+ é criado.
```suggestion
Todas as chaves e os valores iniciais são strings, então um +Dict{String,String}+ é criado.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +(((valores)))((("função", "Base", "valores", see="valores")))
Eu acho q neste caso não precisa traduzir para valores porque estamos falando da função embutida values.
```suggestion
(((values)))((("função", "Base", "values", see="values")))
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Você pode percorrer as chaves de um dicionário em uma declaração +for+. Por exemplo, +imprimehist+ exibe cada chave e o seu valor correspondente:
Vc vai deixar "imprime_hist" ou "imprimehist" mesmo?

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se você já brincou com a função +fibonacci+ de <<one_more_exemple>>, você pode ter percebido que quanto maior o argumento que você fornece, mais tempo a função leva para executar. Além disso, o tempo
Sugestão para tirar um pouco da repetição de "você".
```suggestion
Se você já brincou com a função +fibonacci+ de <<one_more_exemple>>, pode ter percebido que quanto maior o argumento que você fornece, mais tempo a função leva para executar. Além disso, o tempo de execução cresce rapidamente.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Se tentar reatribuir uma variável global, você poderá se surpreender. O exemplo a seguir deve acompanhar se a função foi chamada:
```suggestion
Se você tentar reatribuir uma variável global, poderá se surpreender. O exemplo a seguir deve acompanhar se a função foi chamada:
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Por razões de performance, deve-se declarar uma variável global como constante. Não é mais possível reatribuir a variável mas caso ela faça referência a um valor mutável, você pode modificar o valor.
```suggestion
Por razões de performance, deve-se declarar uma variável global como constante. Você já não pode reatribuir a variável mas caso ela faça referência a um valor mutável, pode-se modificar o valor.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Variáveis globais podem ser utéis, mas se tem muitas delas, e você modifica-as frequentemente, elas podem ser a causa dos programas serem dificéis de debugar e terem mau desempenho.
```suggestion
Variáveis globais podem ser utéis, mas se tem muitas delas, e você modifica-as frequentemente, elas podem ser a causa dos programas serem dificéis de depurar e terem mau desempenho.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +=== Debugando
```suggestion
=== Depuração
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Na medida em que você trabalha com datasets maiores, pode ser que seja difícil debugar imprimindo e checando a saída na mão. Aqui estão algumas sugestões para debugar datasets maiores:
```suggestion
Na medida em que você trabalha com datasets maiores, pode ser que seja difícil depurar imprimindo e checando a saída na mão. Aqui estão algumas sugestões para depurar datasets maiores:
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +(((debugando)))
```suggestion
(((depuração)))
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma causa comum de erros de execução é um valor que não é do tipo correto. Para debugar esse tipo de erro, geralmente é suficiente imprimir o tipo de um valor.
```suggestion
Uma causa comum de erros de execução é um valor que não é do tipo correto. Para a depuração desse tipo de erro, geralmente é suficiente imprimir o tipo de um valor.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Resultados de debugging formatados podem facilitar a detecção de erros, como visto em um exemplo em <<deb06>>.
```suggestion
Resultados de depuração formatados podem facilitar a detecção de erros, como visto em um exemplo em <<deb06>>.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +E mais uma vez, o tempo que você usa construindo andaimes pode reduzir o tempo gasto no debugging.
```suggestion
E mais uma vez, o tempo que você usa construindo andaimes pode reduzir o tempo gasto na depuração.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +(((andaime)))(((debugging)))
```suggestion
(((andaime)))(((depuração)))
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Uma maneira de efetuar cálculos.
```suggestion
Uma maneira de efetuar os cálculos.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +O algoritmo usado para implementar dicionários em Julia.
```suggestion
O algoritmo usado para implementar os dicionários em Julia.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Escreva uma função que leia palavras em _palavras.txt_ e guarde-as como chaves em um dicionário. Não importa quais sejam os valores. Em seguida, você pode usar o operador +∈+ como uma maneira rápida
```suggestion
Escreva uma função que leia as palavras em _palavras.txt_ e guarde-as como chaves em um dicionário. Não importa quais sejam os valores. Em seguida, você pode usar o operador +∈+ como uma maneira rápida de verificar se uma string está ou não no dicionário.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Duas palavras são “pares rotacionados” se você pode rotacionar um deles e obter o outro (ver +rotacionapalavra+ em <<ex08-5>>).
Vc vai manter "rotaciona_palavra" ou "rotacionapalavra"? Comentário válido para linha 679.

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Essa foi enviada por um sujeito chamado Dan O’Leary. ele encontrou uma palavra comum de uma sílaba e cinco letras recentemente que possui a seguinte propriedade. Quando você remove a primeira letra,
```suggestion
Essa foi enviada por um sujeito chamado Dan O’Leary. Ele encontrou recentemente uma palavra em inglês comum de uma sílaba e cinco letras, que possui a seguinte propriedade peculiar. Quando você remove a primeira letra, as letras restantes formam um homófono da palavra original, isto é, uma palavra que soa exatamente igual. Troque a primeira letra, isto é, coloque-a novamente e remova a segunda letra, e o resultado é outro homófono da palavra original. E a pergunta é, qual é a palavra?
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Agora irei dar um exemplo que não funciona. Vamos olhar para uma palavra de cinco letras, ‘wrack.’ W-R-A-C-K, sabe como ‘wrack with pain.’ Se você remover a primeira letra, tenho uma palavra de quatr
```suggestion
Agora irei dar um exemplo que não funciona. Vamos olhar para uma palavra de cinco letras, ‘wrack.’ W-R-A-C-K, como na expressão ‘wrack with pain.’ Se eu remover a primeira letra, tenho uma palavra de quatro letras, ’R-A-C-K.’ Como em, ‘Holy cow, did you see the rack on that buck! It must have been a nine-pointer!’ É um homófono perfeito. Se você colocar o ‘w’ novamente, e remover o ‘r’, você fica com a palavra ‘wack,’ que é uma palavra real, só não é um homófona das outras duas palavras.
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Mas há, no entanto, pelo menos uma palavra que Dan e nós conhecemos, que irá produzir dois homófonos se você remover tanto as primeiras duas letras para criar duas novas palavras de quatro letras. A
Eu sugeri tirar o termo "no entanto" porque já existe o mas. Como mas e no entanto são conjuções que passa a mesma ideia, de contradição, acabei retirando um. Na minha opinião, se aproxima mais do português.
```suggestion
Mas há pelo menos uma palavra, que Dan e nós conhecemos, que irá produzir dois homófonos se você remover tanto as duas primeiras letras para criar duas novas palavras de quatro letras. A pergunta é, qual é a palavra?
```

2020-06-06 00:36 UTC, chunggnuhc commented on book/src/chap11.asciidoc
> +Para verificar se duas palavras em inglês são homônimas, você pode usar o Dicionário CMU de Pronunciação. E também pode baixá-lo em  http://www.speech.cs.cmu.edu/cgi-bin/cmudict.
Desculpa, eu errei aqui.
```suggestion
Para verificar se duas palavras em inglês são homófonas, você pode usar o Dicionário CMU de Pronunciação. E também pode baixá-lo em  http://www.speech.cs.cmu.edu/cgi-bin/cmudict.
```

2020-06-08 19:51 UTC, chunggnuhc commented
Review approved!

2020-07-03 17:19 UTC, chunggnuhc approved these changes

2020-07-10 03:15 UTC, abelsiqueira approved these changes

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +Este capítulo apresenta outra estrutura de dados embutida chamado dicionário.
```suggestion
Este capítulo apresenta outra estrutura de dados embutida chamada dicionário.
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +Um _dicionário_ é como uma lista, mas mais geral. Em uma lista, os índices devem ser inteiros e em um dicionário, eles podem (quase) ser de qualquer tipo.
```suggestion
Um _dicionário_ é como uma lista, mas mais geral. Em uma lista, os índices devem ser inteiros e em um dicionário, eles podem ser de (quase) qualquer tipo.
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +Na linguagem matemática, um dicionário representa um _mapeamento_ das chaves para os valores, então você também pode dizer que cada chave “é mapeado” para um valor. Como um exemplo, iremos construir
```suggestion
Na linguagem matemática, um dicionário representa um _mapeamento_ das chaves para os valores, então você também pode dizer que cada chave “é mapeada” para um valor. Como um exemplo, iremos construir um dicionário que mapeia palavras em Português para palavras em Espanhol, com as chaves e os valores todos strings.
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +julia> por_para_esp["um"] = "uno";
```suggestion
julia> pt_para_esp["um"] = "uno";
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +julia> por_para_esp
```suggestion
julia> pt_para_esp
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +julia> por_para_esp = Dict("um" => "uno", "dois" => "dos", "três" => "tres")
```suggestion
julia> pt_para_esp = Dict("um" => "uno", "dois" => "dos", "três" => "tres")
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +julia> por_para_esp["dois"]
```suggestion
julia> pt_para_esp["dois"]
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +julia> por_para_esp["quatro"]
```suggestion
julia> pt_para_esp["quatro"]
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +julia> length(por_para_esp)
```suggestion
julia> length(pt_para_esp)
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +julia> ks = keys(por_para_esp);
```suggestion
julia> ks = keys(pt_para_esp);
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +julia> vs = values(por_para_esp);
```suggestion
julia> vs = values(pt_para_esp);
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +O resultado de uma exceção gerada é o mesmo quando o Julia gera um: ele exibe o stracktrace e uma mensagem de erro.
```suggestion
O resultado de uma exceção gerada é o mesmo quando o Julia gera um: ele exibe o stacktrace e uma mensagem de erro.
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +Eu mencionei anteriormente que um dicionário é implementado usando uma tabela hash e isso significa que as chaves devem ser _hashable_, ou de um tipo que permite que uma função hash atuem sobre elas.
```suggestion
Mencionamos anteriormente que um dicionário é implementado usando uma tabela hash e isso significa que as chaves devem ser _hashable_, isto é, de um tipo que permite que uma função hash atuem sobre elas.
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> ++conhecido+ é um dicionáro que guarda os números de Fibonacci que já sabemos. Ele começa com dois itens: +0+ mapeia para +0+ e +1+ mapeia para +1+.
```suggestion
+conhecidos+ é um dicionáro que guarda os números de Fibonacci que já sabemos. Ele começa com dois itens: +0+ mapeia para +0+ e +1+ mapeia para +1+.
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +É comum usar variáveis globais para _flags_; isto é, variáveis booleanas que indicam (“sinal”) se uma condição é verdadeira. Por exemplo, alguns programas usam uma flag chamada +verbose+ para control
```suggestion
É comum usar variáveis globais para _flags_; isto é, variáveis booleanas que indicam (“sinalizam”) se uma condição é verdadeira. Por exemplo, alguns programas usam uma flag chamada +verbose+ para controlar o nível de detalhamento na saída:
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +Na medida em que você trabalha com datasets maiores, pode ser que seja difícil depurar imprimindo e checando a saída na mão. Aqui estão algumas sugestões para depurar datasets maiores:
```suggestion
Na medida em que você trabalha com conjuntos de dados maiores, pode ser que seja difícil depurar imprimindo e checando a saída na mão. Aqui estão algumas sugestões para depurar conjuntos de dados maiores:
```

2020-07-10 03:15 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +Se possível, reduza o tamanho do dataset. Por exemplo, se o programa lê um arquivo de texto, comece com apenas as 10 primeiras linhas, ou com o menor exemplo que dá erro. Você não deve editar os arqu
```suggestion
Se possível, reduza o tamanho do conjunto de dados. Por exemplo, se o programa lê um arquivo de texto, comece com apenas as 10 primeiras linhas, ou com o menor exemplo que dá erro. Você não deve editar os arquivos em si, mas modificar o programa para que ele leia somente as primeiras latexmath:[\(n\)] linhas.
```

2020-07-10 03:16 UTC, abelsiqueira commented on book/src/chap11.asciidoc
> +Ao invés de imprimir e checar o dataset inteiro, considere imprimir os resumos dos dados: por exemplo, o número de itens em um dicionário ou o total de uma lista de números.
```suggestion
Ao invés de imprimir e checar o conjunto de dados inteiro, considere imprimir os resumos dos dados: por exemplo, o número de itens em um dicionário ou o total de uma lista de números.
```

2020-07-10 03:17 UTC, merged