Chapter 15 PTBR
JuliaIntro/JuliaIntroBR.jl pull request #23
Opened 2020-05-18 21:38 UTC by chunggnuhc

2020-06-06 04:05 UTC, chunggnuhc commented on book/src/chap15.asciidoc
>  === Debugging
```suggestion
=== Depuração
```

2020-06-06 04:05 UTC, chunggnuhc commented on book/src/chap15.asciidoc
>  (((debugging)))
```suggestion
(((depuração)))
```

2020-06-10 01:03 UTC, joaoluisro requested changes
first review

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +A esta altura, você sabe como usar funções para organizar o código e os tipos internos para organizar os dados. O próximo passo é aprender a criar seus próprios tipos para organizar o código e os dad
```suggestion
A esta altura, você sabe como usar funções para organizar o código e os tipos internos para organizar os dados. O próximo passo é aprender a criar seus próprios tipos para organizar tanto o código como os dados. Este é um tópico importante e serão necessários alguns capítulos para abordar o tema.
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +A struct é como se fosse uma fábrica para criar os objetos. Para criar um ponto, chama-se +Ponto+ como se fosse uma função tendo como argumentos os valores dos campos. Quando +Ponto+ é usado como uma
```suggestion
A struct é como uma fábrica para criar os objetos. Para criar um ponto, chama-se +Ponto+ como se fosse uma função tendo como argumentos os valores dos campos. Quando +Ponto+ é usado como uma função, ele é chamado de _construtor_.
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Na notação matemática, os pontos geralmente são escritos entre parênteses com uma vírgula separando as coordenadas. Por exemplo, latexmath:[\(\left(0,0\right)\)] representa a origem e latexmath:[\(\l
```suggestion
Na notação matemática, os pontos geralmente são escritos entre parênteses com uma vírgula separando as coordenadas. Por exemplo, latexmath:[\(\left(0,0\right)\)] representa a origem e latexmath:[\(\left(x,y\right)\)] representa o ponto latexmath:[\(x\)] unidades à direita e latexmath:[\(y\)] unidades acima da origem, se o ponto estiver no 1o. quadrante.
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +A criação de um novo tipo é mais complicado que as outras opções, mas possui vantagens que serão mostradas em breve.
```suggestion
Criar um novo tipo é mais complicado que as outras opções, mas possui vantagens que serão mostradas em breve.
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Um _tipo composto_ definido pelo programador também é denominado de _estrutura_. A definição +struct+ para um ponto é dada por:
```suggestion
Um _tipo composto_ definido pelo programador também é denominado de _estrutura_ (struct). A definição +struct+ para um ponto pode ser representada por:
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Quando você imprime uma instância, Julia informa a que tipo pertence e quais os valores dos atributos.
```suggestion
Quando você imprime uma instância, o Julia informa a que tipo pertence e quais os valores dos atributos.
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Você pode passar uma instância como um argumento, da maneira tradicional. Por exemplo:
```suggestion
Você pode passar uma instância como um argumento da maneira tradicional. Por exemplo:
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +=== Cópia
```suggestion
=== Copiando
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Alias ocorre quando um mesmo local da memória é acessado por diferentes variáveis. Além disso, alias pode dificultar a leitura de um programa, pois as alterações em um local podem ter efeitos inesper
```suggestion
"Aliasing" é um termo que refere-se ao acesso de um mesmo local da memória por variáveis diferentes. Ele pode dificultar a leitura de um programa, pois as alterações em um local podem ter efeitos inesperados em outro local. É difícil acompanhar todas as variáveis que podem se referir a um dado objeto.
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +A cópia de um objeto é muitas vezes uma alternativa ao alias. Julia possui uma função chamada +deepcopy+ que pode duplicar qualquer objeto:
```suggestion
A cópia de um objeto é muitas vezes uma alternativa ao aliasing. O Julia possui uma função chamada +deepcopy+ que pode duplicar qualquer objeto:
```

2020-06-10 01:03 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +O operador +≡+ indica que +p1+ e +p2+ não são o mesmo objeto, que é o que imaginávamos. Mas você pode ter esperado que +==+ devolvesse +true+ porque esses pontos contêm os mesmos dados. Nesse caso, v
```suggestion
O operador +≡+ indica que +p1+ e +p2+ não são o mesmo objeto, que é o que imaginávamos. Mas você pode ter esperado que +==+ devolvesse +true+ porque esses pontos contêm os mesmos dados. Nesse caso, você ficará desapontado ao saber que, para objetos mutáveis, o comportamento padrão do operador +==+ é o mesmo do operador +===+ pois verifica-se a identidade do objeto e não a equivalência do objeto. Isso ocorre porque, para tipos compostos mutáveis, o Julia não sabe o que deve ser considerado equivalente. Pelo menos, ainda não.
```

2020-06-10 01:59 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +Um _tipo composto_ definido pelo programador também é denominado de _estrutura_. A definição +struct+ para um ponto é dada por:
@joaoluisro , que tal:
```suggestion
Um _tipo composto_ definido pelo programador também é denominado de _estrutura_. A definição +struct+ para um ponto pode ser representada da seguinte maneira:
```

2020-06-10 20:14 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +* Poderíamos armazenar as coordenadas como elementos de um array ou de uma tupla.
```suggestion
* Poderíamos armazenar as coordenadas como elementos de um vetor ou de uma tupla.
```

2020-06-10 20:45 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +Todo objeto é uma instância de algum tipo; portanto, "objeto" e "instância" são permutáveis. Mas neste capítulo, eu uso "instância" para indicar que estou falando de um tipo definido pelo programador
```suggestion
Todo objeto é uma instância de algum tipo; portanto, “objeto” e “instância” são permutáveis. Mas neste capítulo, eu uso “instância” para indicar que estou falando de um tipo definido pelo programador.
```

2020-06-10 20:57 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +Um diagrama de estado que mostra um objeto e seus campos é denominado de _diagrama do objeto_, conforme <<fig15-1>>.
```suggestion
Um diagrama de estado que mostra um objeto e os seus campos é denominado _diagrama do objeto_, conforme <<fig15-1>>.
```

2020-06-10 20:58 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +A expressão +p.x+ significa: "Vá até a referência do objeto +p+ e obtenha o valor de +x+". No exemplo, atribuímos esse valor a uma variável +x+. Não há conflito entre a variável +x+ e o campo +x+.
```suggestion
A expressão +p.x+ significa: “Vá até a referência do objeto +p+ e obtenha o valor de +x+.” No exemplo, atribuímos esse valor a uma variável +x+. Não há conflito entre a variável +x+ e o campo +x+.
```

2020-06-10 21:05 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +Por padrão, as structs são  imutáveis, isto é, após a construção, os campos não podem mudar de valor:
```suggestion
Por padrão, as structs são imutáveis, isto é, após a construção, os campos não podem mudar de valor:
```

2020-06-10 22:29 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> ++imprimir_ponto+ recebe como argumento um +ponto+ e o apresenta em notação matemática. Para chamá-lo, você pode passar +p+ como argumento:
```suggestion
A função +imprimir_ponto+ recebe como argumento um +ponto+ e o apresenta em notação matemática. Para chamá-lo, você pode passar +p+ como argumento:
```

2020-06-10 23:06 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +A expressão +ret.vértice.x+ significa: "Vá ao objeto +ret+ e selecione o campo +vértice+; depois vá a esse objeto e selecione o campo +x+".
```suggestion
A expressão +ret.vértice.x+ significa: “Vá ao objeto +ret+ e selecione o campo +vértice+; depois vá a esse objeto e selecione o campo +x+.”
```

2020-06-10 23:08 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +"Aliasing" é um termo que refere-se ao acesso de um mesmo local da memória por variáveis diferentes. Ele pode dificultar a leitura de um programa, pois as alterações em um local podem ter efeitos ine
```suggestion
"Aliasing" é um termo que refere-se ao acesso de um mesmo local da memória por variáveis diferentes. Ele pode dificultar a leitura de um programa, pois as alterações em um local podem ter efeitos inesperados em outro local. É difícil acompanhar todas as variáveis que podem se referir a um objeto dado.
```

2020-06-10 23:09 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +O operador +≡+ indica que +p1+ e +p2+ não são o mesmo objeto, que é o que imaginávamos. Mas você pode ter esperado que +==+ devolvesse +true+ porque esses pontos contêm os mesmos dados. Nesse caso, v
```suggestion
O operador +≡+ indica que +p1+ e +p2+ não são o mesmo objeto, que é o que imaginávamos. Mas você pode ter pensado que +==+ devolvesse +true+ porque esses pontos contêm os mesmos dados. Nesse caso, você ficará desapontado ao saber que, para objetos mutáveis, o comportamento padrão do operador +==+ é o mesmo do operador +===+ pois verifica-se a identidade do objeto e não a equivalência do objeto. Isso ocorre porque, para tipos compostos mutáveis, o Julia não sabe o que deve ser considerado equivalente. Pelo menos, ainda não.
```

2020-06-10 23:14 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +Se não tem certeza de qual é o tipo de objeto, você pode perguntar:
```suggestion
Se você não tem certeza de qual é o tipo de objeto, pode-se perguntar:
```

2020-06-10 23:14 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +Se você não tem certeza se um objeto tem um determinado atributo, pode-se usar a função interna +fieldnames+:
```suggestion
Se você não tem certeza se um objeto possui um determinado atributo, pode-se usar a função interna +fieldnames+:
```

2020-06-11 00:59 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +=== Cópia
O que vc acha de "Fazendo cópia"?

Eu estou incomodada de usar o termo "copiando" pq em nenhum momento apareceu essa palavra no texto. Desculpa pelo toc.

2020-06-16 06:36 UTC, joaoluisro requested changes
segunda revisão

2020-06-16 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Um _tipo composto_ definido pelo programador também é denominado de _estrutura_. A definição +struct+ para um ponto é dada por:
Acho que fica melhor assim. Mas ainda acho que vale a pena colocar o termo em inglês entre parêntses "struct", que tal algo como:
```suggestion
Um _tipo composto_ definido pelo programador também é denominado de _estrutura_ (struct). A definição +struct+ pode ser representada da seguinte maneira:
```

2020-06-16 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +A struct é como uma fábrica para criar os objetos. Para criar um ponto, chama-se +Ponto+ como se fosse uma função tendo como argumentos os valores dos campos. Quando +Ponto+ é usado como uma função,
```suggestion
Uma struct é como uma fábrica que cria objetos. Para criar um ponto, chama-se +Ponto+ como se fosse uma função tendo como argumentos os valores dos campos. Quando +Ponto+ é usado como uma função, ele é chamado de _construtor_.
```
Aqui acho que o autor quis generalizar o termo "struct", como se estivesse falando da declaração struct, ao invés de uma struct específica.

2020-06-16 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +A expressão +p.x+ significa: “Vá até a referência do objeto +p+ e obtenha o valor de +x+.” No exemplo, atribuímos esse valor a uma variável +x+. Não há conflito entre a variável +x+ e o campo +x+.
```suggestion
A expressão +p.x+ significa: “Vá até a referência do objeto +p+ e obtenha o valor de +x+.” No exemplo, atribuímos esse valor a uma variável denominada +x+. Não há conflito entre a variável +x+ e o campo +x+.
```

2020-06-16 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Dentro da função, +p+ é um alias (ou apelido) para +origem+, então quando a função modifica +p+, +origem+ também muda.
```suggestion
Dentro da função, +p+ é um alias (ou uma referência) para +origem+, então quando a função modifica +p+, +origem+ também muda.
```
Não sou muito fã do termo "apelido" para falar de aliasing, o que acha de "referência"?

2020-06-16 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Passar um objeto +Ponto+ imutável para +move_ponto!+ faz uma mensagem de erro aparecer:
```suggestion
Passar um objeto +Ponto+ imutável para +move_ponto!+ gera um erro:
```
simplifica um pouco.

2020-06-16 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Agora +p+ em +move_ponto!+ é um apelido para +ret.vértice+, então quando +p+ é modificado, +ret.vértice+ também muda:
```suggestion
Agora +p+ em +move_ponto!+ é uma referência para +ret.vértice+, então quando +p+ é modificado, +ret.vértice+ também muda:
```
discussão Aliasing

2020-06-16 06:39 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +=== Cópia
Acho que se encaixa. Mas eu prefereria
```suggestion
=== Copiando Objetos
```

2020-06-19 17:19 UTC, abelsiqueira commented on book/src/chap15.asciidoc
> +"Aliasing" é um termo que refere-se ao acesso de um mesmo local da memória por variáveis diferentes. Ele pode dificultar a leitura de um programa, pois as alterações em um local podem ter efeitos ine
Remover definição

2020-06-27 18:17 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +"Aliasing" é um termo que refere-se ao acesso de um mesmo local da memória por variáveis diferentes. Ele pode dificultar a leitura de um programa, pois as alterações em um local podem ter efeitos ine
```suggestion
Usar um alias pode dificultar a leitura de um programa, pois as alterações em um local podem ter efeitos inesperados em outro local. É difícil acompanhar todas as variáveis que podem se referir a um objeto dado.
```

2020-06-27 18:51 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +A esta altura, você sabe como usar funções para organizar o código e os tipos internos para organizar os dados. O próximo passo é aprender a criar seus próprios tipos para organizar tanto o código co
```suggestion
A esta altura, você sabe como usar funções para organizar o código e os tipos internos para organizar os dados. O próximo passo é aprender a criar os seus próprios tipos para organizar tanto o código como os dados. Este é um tópico importante e serão necessários alguns capítulos para abordar o tema.
```

2020-06-27 19:39 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +Uma struct é como uma fábrica que cria objetos. Para criar um ponto, chama-se +Ponto+ como se fosse uma função tendo como argumentos os valores dos campos. Quando +Ponto+ é usado como uma função, ele
```suggestion
Uma struct é como uma fábrica que cria objetos. Para criar um ponto, chama-se +Ponto+ como se fosse uma função que tem os valores dos campos como argumentos. Quando +Ponto+ é usado como uma função, ele é chamado de _construtor_.
```

2020-06-27 19:48 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +A função +imprimir_ponto+ recebe como argumento um +ponto+ e o apresenta em notação matemática. Para chamá-lo, você pode passar +p+ como argumento:
```suggestion
A função +imprimir_ponto+ recebe como argumento um +ponto+ e apresenta-o em notação matemática. Para chamá-lo, você pode passar +p+ como argumento:
```

2020-06-27 19:49 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +Dentro da função, +p+ é um alias (ou apelido) para +origem+, então quando a função modifica +p+, +origem+ também muda.
Achei ótimo esse termo para alias.

2020-06-27 19:51 UTC, chunggnuhc commented on book/src/chap15.asciidoc
> +//coloquei a definição de aliasing antes de traduzir o parágrafo
```suggestion

```

2020-07-01 06:36 UTC, joaoluisro requested changes

2020-07-01 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Nesse momento, é difícil dizer se um é melhor que o outro e portanto, implementaremos o primeiro, apenas como exemplo.
```suggestion
Nesse momento, é difícil dizer se uma é melhor que a outra e portanto, implementaremos a primeira, apenas como exemplo.
```
Já que refere-se à possibilidade

2020-07-01 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +Para a representação de um retângulo, você tem que instanciar um objeto +Retângulo+:
```suggestion
Para representar um retângulo, você precisa instanciar um objeto +Retângulo+:
```

2020-07-01 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> +* Podemos armazenar as coordenadas separadamente em duas variáveis, +x+ e +y+.
```suggestion
* Poderíamos armazenar as coordenadas separadamente em duas variáveis, +x+ e +y+.
```

2020-07-01 06:36 UTC, joaoluisro commented on book/src/chap15.asciidoc
> -=== Copying
linha 298 desalinhada - dar um enter

2020-07-08 14:38 UTC, joaoluisro approved these changes

2020-07-22 12:41 UTC, abelsiqueira approved these changes

2020-07-22 12:41 UTC, abelsiqueira commented on book/src/chap15.asciidoc
>  ----
```suggestion
----
function imprimir_ponto(p)
```

2020-07-22 12:41 UTC, abelsiqueira commented on book/src/chap15.asciidoc
> +A função +imprimir_ponto+ recebe como argumento um +ponto+ e apresenta-o em notação matemática. Para chamá-lo, você pode passar +p+ como argumento:
```suggestion
A função +imprimir_ponto+ recebe como argumento um +Ponto+ e apresenta-o em notação matemática. Para chamá-lo, você pode passar +p+ como argumento:
```

2020-07-22 12:41 UTC, abelsiqueira commented on book/src/chap15.asciidoc
> + [2] top-level scope at none:0
```suggestion
```

2020-07-22 12:41 UTC, abelsiqueira commented on book/src/chap15.asciidoc
> +(((desenha_círculo)))((("função", "definido pelo programador", "desenha_círculo", see="desenha_círculo")))
```suggestion
(((desenha_círculo)))((("função", "definido pelo programador", "desenha_círculo", see="desenha_círculo")))

```

2020-07-22 12:42 UTC, merged