Chapter 13 - PTBR
JuliaIntro/JuliaIntroBR.jl pull request #25
Opened 2020-05-29 02:38 UTC by gustavosarturi

- Rubberducking traduzido como "Conversa com o Pato de Borracha" (ou similar).
- Texto de música em inglês mantida (verificar na reunião se alteraremos ou não).

2020-06-10 01:34 UTC, chunggnuhc requested changes

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A essa altura você deve ter aprendido sobre o núcleo de estrutura de dados do Julia e também deve ter visto alguns dos algoritmos que usam eles.
```suggestion
A essa altura você deve ter aprendido sobre as estruturas de dados essenciais do Julia e também deve ter visto alguns dos algoritmos que usam elas.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Como sempre, você deve pelo menos tentar os exercícios antes de ler as soluções.
```suggestion
Como sempre, você deve pelo menos tentar fazer os exercícios antes de ver as soluções.
```
Na minha opinião, essa sugestão fica mais próxima do jeito que falamos.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Escreva um programa que leia um arquivo, divida cada linha em palavras, retire o espaço em branco e a pontuação das palavras e as converta em minúsculas.
```suggestion
Escreva um programa que leia um arquivo, separe cada linha em palavras, retire o espaço em branco e a pontuação das palavras e coloque-as em letras minúsculas.
```
Na minha opinião, essa sugestão fica mais próxima do jeito que falamos.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A função +é_letra+ verifica se o caracter é alfabético.
```suggestion
A função +isletter+ verifica se o caractere é do alfabeto.
```
A função isletter é uma função interna do Julia.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((é_letra)))((("função", "Base", "é_letra", see="é_letra")))
```suggestion
(((isletter)))((("função", "Base", "isletter", see="isletter")))
```
A função isletter é uma função interna do Julia.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Va até o Projeto Gutenberg (https://guttenberg.org) e baixe seu livro favorito sem direitos autorais em formato de texto sem formatação.
```suggestion
Va até o Projeto Gutenberg (https://guttenberg.org) e baixe seu livro favorito de domínio público em formato de texto sem formatação.
```
Pesquisei na internet e em particular para livros, não existe livro sem direitos autorais. É dito que ou o livro é de domínio público ou é de direito autoral. Mas para imagens e músicas, existem imagens sem direitos autores, existem música sem direitos autorais, mas para livro, não existe o termo "livro sem direitos autorais".

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Modifique o seu programa do exercício anterior para ler o livro que você baixou, pule a informação do cabeçalho no início do arquivo e processe o resto das palavras como antes.
```suggestion
Modifique o seu programa do exercício anterior para ler o livro que você baixou, pule a informação do cabeçalho no início do arquivo e trabalhe com o resto das palavras como no exercício anterior.
```
Na minha opinião, essa sugestão fica mais próxima do jeito que falamos.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Imprima o número das diferentes palavras usadas no livro. Compare livros diferentes de diferentes autores, escritos em épocas diferentes. Qual autor usa um vocabulário mais prolixo?
```suggestion
Imprima o número das palavras diferentes usadas no livro. Compare outros livros de autores diferentes, escritos em épocas diferentes. Qual autor usa um vocabulário mais extenso?
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Dadas as mesmas entradas, a maioria dos programas de computadores geram a mesma entrada o tempo todo, eles são ditos _determinísticos_. O determinismo é geralmente uma coisa boa, pois esperamos que o
```suggestion
Dadas as mesmas entradas, a maioria dos programas de computadores geram a mesma entrada o tempo todo e por isso eles são ditos _determinísticos_. O determinismo é geralmente uma coisa boa pois esperamos que o mesmo cálculo produza o mesmo resultado. Mas para algumas aplicações, queremos que o computador seja imprevisível. Os jogos são um exemplo óbvio, porém há mais exemplos.
```
A tradução tá correta, mas sugeri modificações
(1) para dar mais fluidez ao texto considerando o jeito que lemos no Brasil,
(2) tirar repetição de "porém" na 2a metade da frase.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Desenvolver um programa puramente não determinístico acaba sendo difícil, mas há maneiras de fazer pelo menos com que ele se pareça não determinístico. Uma destas maneiras é usar algoritmos que geram
```suggestion
Desenvolver um programa puramente não determinístico acaba sendo difícil, mas há maneiras de fazer pelo menos com que ele pareça não determinístico. Uma delas é usar algoritmos que geram números _pseudoaleatórios_. Os números pseudoaleatórios só não são exatamente aleatórios porque eles são gerados por um cálculo determinístico, mas só de olhá-los, é praticamente impossível distingui-los da aleatoriedade.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((pseudo aleatórios)))
```suggestion
(((pseudoaleatório)))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A função +rand+ retorna um float aleatório entre +0.0+ e +1.0+ (incluindo 0.0 mas não 1.0). Toda vez que você usa o comando +rand+, você obtém o próximo número em uma longa série. Para ver uma amostr
```suggestion
A função +rand+ retorna um ponto flutuante aleatório entre +0.0+ e +1.0+ (incluindo 0.0 mas não 1.0). Toda vez que você usa o comando +rand+, você obtém o próximo número de uma longa série. Para ver uma amostra disso, execute este laço:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A função +rand+ pode pegar um iterador ou uma lista como argumentos e retorna um elemento aleatório:
```suggestion
A função +rand+ pode receber um iterador ou uma lista como argumentos e retorna um elemento aleatório:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Escreva uma função chamada +escolhido_do_histograma+ que pega um histograma definido em <<dictionary_collection_counters>> e retorna um valor aleatório do histograma, dada uma probabilidade em propor
```suggestion
Escreva uma função chamada +escolhido_do_histograma+ que recebe um histograma definido em <<dictionary_collection_counters>> e retorna um valor aleatório do histograma, escolhido conforme a probabilidade proporcional à frequência. Por exemplo, para este histograma:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Você deve tentar os exercícios anteriores antes de continuar. Você também precisará de https://github.com/BenLauwens/ThinkJulia.jl/blob/master/data/emma.txt.
```suggestion
Você deve tentar fazer os exercícios anteriores antes de continuar. Você também precisará de https://github.com/JuliaIntro/JuliaIntroBR.jl/blob/master/data/emma.txt.
```
@abelsiqueira , mantém o link do original do autor ou manter o novo link da tradução?

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((processa_arquivo)))((("função", "definido pelo programador", "processa_arquivo")))(((processa_linha)))((("função", "definido pelo programador", "processa_linha", see="processa_linha")))
```suggestion
(((processa_arquivo)))((("função", "definido pelo programador", "processa_arquivo", see="processa_arquivo")))(((processa_linha)))((("função", "definido pelo programador", "processa_linha", see="processa_linha")))
```
Aqui vc traduz "programmer-defined" para a versão masculina ("definido pelo programador"). Vc tem q decidir se vc vai traduzir para a versão masculina ou a versão feminina.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +function processa_arquivo(nomedoarquivo)
Pela convenção que estamos adotando, a variável não fica "nome_do_arquivo"?

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +        palavra = string(filter(é_letra, [palavra...])...)
```suggestion
        palavra = string(filter(isletter, [palavra...])...)
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +        palavra = minúscula(palavra)
```suggestion
        palavra = lowercase(palavra)
```
A função lowercase é uma função interna do Julia.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Esse programa lê _emma.txt_, que contém o texto de _Emma_ por Jane Austen.
Você escolhe: 
```suggestion
Esse programa lê _emma.txt_, que contém o texto de _Emma_ de Jane Austen.
```
ou
```suggestion
Esse programa lê _emma.txt_, que contém o texto de _Emma_ escrito por Jane Austen.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> ++processa_arquivo+ percorre as linhas do arquivo passando-as uma vez de cada para +processa_linha+. O histograma +hist+ é utilizado como um acumulador.
```suggestion
A função +processa_arquivo+ percorre as linhas do arquivo passando-as uma vez de cada para +processa_linha+. O histograma +hist+ é utilizado como um acumulador.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> ++processa_linha+ usa a função +replace+ para substituir os hífens e espaços antes de usar +split+ para separar a linha em uma lista de strings. Ela atravesse a lista de palavras e usa +filter+, +é_le
```suggestion
A função +processa_linha+ usa a função +replace+ para substituir os hífens e espaços antes de usar +split+ para separar a linha em uma lista de strings. Ela percorre a lista de palavras e usa +filter+, +isletter+ e +lowercase+ para remover as pontuações e converter em letras minúsculas. (Apesar de dizer que as strings são "convertidas", lembre-se de que as strings são imutáveis e portanto, uma função como +lowercase+ retorna novas strings.)
```
A tradução não está errada, mas alterei algumas coisas para a frase ter sentido.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((replace)))(((separação)))(((é_letra)))(((minúscula)))(((get!)))(((filtro)))((("função")))((("função", "Base", "filtro", see="filtro")))
```suggestion
(((replace)))(((split)))(((isletter)))(((lowercase)))(((get!)))(((filter)))((("função", "Base", "filter", see="filter")))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Para contar o número total de palavras do arquivo, podemos adicionar as frequências do histograma:
```suggestion
Para contar o número total de palavras no arquivo, podemos adicionar as frequências no histograma:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +À seguir, um código que imprime os resultados:
```suggestion
A seguir, um código que imprime os resultados:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +=== As Palavras Mais Frequentes
```suggestion
=== Palavras Mais Frequentes
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Para encontrar as palavras mais frequentes, podemos fazer uma tupla de listas, onde cada tupla contém uma palavra e sua frequência e ordena. A seguinte função pega um histrograma e retorna uma lista
```suggestion
Para encontrar as palavras mais frequentes, podemos fazer uma lista de tuplas, onde cada tupla contém uma palavra e a sua frequência e fazemos a ordenação. A função seguinte recebe um histograma e retorna uma lista de tuplas que contém a frequência de palavras.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +    for (chave, value) in hist
```suggestion
    for (chave, valor) in hist
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +        push!(t, (value, chave))
```suggestion
        push!(t, (valor, chave))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((mais_comum)))((("função", "definida pelo programador", "mais_comum", see="mais_comum")))(((reverse)))(((ordena)))
```suggestion
(((mais_comum)))((("função", "definida pelo programador", "mais_comum", see="mais_comum")))(((reverse)))(((sort)))
```
Aqui vc traduz "programmer-defined" para a versão feminina ("definida pelo programador"). Vc tem q decidir se vc vai traduzir para a versão masculina ou a versão feminina.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
>  t = mostcommon(hist)
```suggestion
t = mais_comum(hist)
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Usamos o caracter "tab" (+pass:['\t']+) como um "separador", ao invés de um espaço, então a segunda coluna está alinha. Abaixo, os resultados de _Emma_:
```suggestion
Usamos o caractere tab (+pass:['\t']+) como um “separador”, ao invés de um espaço, fazendo com que a segunda coluna fique alinhada. Abaixo, os resultados de _Emma_:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Esse código pode ser simplificado usando o comando +rev+ da função +sort+. Você pode ler mais sobre isto em https://docs.julialang.org/en/v1/base/sort/#Base.sort.
```suggestion
Esse código pode ser simplificado usando a palavra-chave +rev+ como argumento da função +sort+. Você pode ler mais sobre isto em https://docs.julialang.org/en/v1/base/sort/#Base.sort.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Temos visto funções embutidas que pegam argumentos opcionais. É possível escrever funções definidas pelo programados com argumentos opcionais também. Por exemplo, no exemplo a seguir, temos uma funçã
```suggestion
Temos visto as funções embutidas que recebem argumentos opcionais. É possível definir as funções com argumentos opcionais também. Por exemplo, eis uma função que imprime as palavras mais frequentes em um histograma:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((argumentos opcionais)))(((imprime_mais_frequentes)))((("função", "definido pelo programador", "imprime_mais_frequentes", see="imprime_mais_frequentes")))
```suggestion
(((argumento opcional)))(((imprime_mais_frequentes)))((("função", "definido pelo programador", "imprime_mais_frequentes", see="imprime_mais_frequentes")))
```
Aqui vc traduz "programmer-defined" para a versão masculina ("definido pelo programador"). Vc tem q decidir se vc vai traduzir para a versão masculina ou a versão feminina.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> ++num+ obtém o valor padrão. Se você fornecer dois argumentos:
```suggestion
o argumento +num+ recebe o valor padrão. Se você fornecer dois argumentos:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> ++num+ obtém o valor do argumento. Em outras palavras, o valor opcional _sobrepõe_ o valor padrão.
```suggestion
o argumento +num+ fica com o valor do argumento. Em outras palavras, o valor opcional _sobrepõe_ o valor padrão.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Se uma função possui argumentos obrigatórios e opcionais, todos os parâmetros obrigatórios deverão aparecer antes, seguido dos ocionais.
```suggestion
Se uma função possui tanto os argumentos obrigatórios e os opcionais, todos os parâmetros obrigatórios deverão ficar entre os primeiros, seguido dos opcionais.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Encontrar as palavras do livro que não estão na lista de palavras de +palavras.txt+ é um problema que você pode reconhecer como subtração definida, isto é, queremos encontrar todas as palavras de um
```suggestion
Encontrar as palavras do livro que não estão na lista de palavras em +palavras.txt+ é um problema que você pode reconhecer como subtração de conjuntos, isto é, queremos encontrar todas as palavras de um conjunto (as palavras do livro) que não estão no outro (as palavras da lista).
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> ++subtrair+ pega os dicionários +d1+ e +d2+ e retorna um novo dicionário que contém todas as entradas de +d1+ que não estão em +d2+. Como realmente não nos importamos com os valores, definios todos co
```suggestion
A função +subtrair+ recebe os dicionários +d1+ e +d2+ e retorna um novo dicionário que contém todas as chaves de +d1+ que não estão em +d2+. Como realmente não nos importamos com os valores, definimos todos como +nothing+.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((subtrair)))((("função", "definido pelo programador", "subtrair", see="subtrair")))(((nothing)))(((n)))((("operador", "Base", "n", see="n")))
```suggestion
(((subtrair)))((("função", "definido pelo programador", "subtrair", see="subtrair")))(((nothing)))(((∩)))((("operador", "Base", "∩", see="∩")))
```
Aqui vc traduz "programmer-defined" para a versão masculina ("definido pelo programador"). Vc tem q decidir se vc vai traduzir para a versão masculina ou a versão feminina.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +    for chave in chaves(d1)
```suggestion
    for chave in keys(d1)
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +        if chave ∉ chaves(d2)
```suggestion
        if chave ∉ keys(d2)
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Para encontrar palavras do livro que não estão em +palavras.txt+, podemos usar +processa_arquivo+ para construir um histograma para +palavras.txt+, e então +subtrair+:
```suggestion
Para encontrar as palavras do livro que não estão em +palavras.txt+, podemos usar +processa_arquivo+ para construir um histograma para +palavras.txt+, e depois +subtrair+:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +for palavra in chaves(diff)
```suggestion
for palavra in keys(diff)
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Abaixo alguns resultados de _Emma_:
```suggestion
Eis alguns resultados de _Emma_:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +outree visão rápida externamente adelaide rencontre jeffreys dixons sem reservas entre ...
```suggestion
outree quicksighted outwardly adelaide rencontre jeffereys unreserved dixons betweens
```
Não traduz porque o livro Emma não está em domínio público do Brasil.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Algumas dessas palavras são nomes e possessivos. Outros, como "reencontre" não são mais de uso comum. Mas algumas são palavras comuns que realmente devem estar na lista!
```suggestion
Algumas dessas palavras são nomes e preposições. Outros, como "rencontre" não são mais usados. Mas algumas são as palavras comuns que realmente devem estar na lista!
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +O Julia fornece uma estrutuda de dados chamado +Set+ que fornece muitos conjuntos de operações comuns. Você pode ler mais sobre em <<collections_and_data_structures>>, ou ler a documentação em https:
```suggestion
O Julia fornece uma estrutura de dados chamado +Set+ que fornece várias operações usuais de conjuntos. Você pode ler mais sobre elas em <<collections_and_data_structures>>, ou ler a documentação em https://docs.julialang.org/en/v1/base/collections/#Set-Like-Collections-1.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Escreva um programa que usa o conjunto subtração para encontrar palavras do livro que não estão na lista de palavras.
```suggestion
Escreva um programa que usa a subtração de conjuntos para encontrar as palavras do livro que não estão na lista de palavras.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Para escolher uma palavra aleatória do histograma, o algoritmo mais simples é construir uma lista com múltiplas cópias de cada palavra, de acordo com a frequêcia observada e depois escolher na lista:
```suggestion
Para escolher uma palavra aleatória do histograma, o algoritmo mais simples é construir uma lista com múltiplas cópias de cada palavra, de acordo com a frequêcia observada e depois escolher da lista:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((palavra_aleatória)))((("função", "definido pelo programador", "palavra_aleatório", see="palavra_aleatória")))
```suggestion
(((palavra_aleatória)))((("função", "definido pelo programador", "palavra_aleatória", see="palavra_aleatória")))
```
Aqui vc traduz "programmer-defined" para a versão masculina ("definido pelo programador"). Vc tem q decidir se vc vai traduzir para a versão masculina ou a versão feminina.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Esse algoritmo funciona, mas, não é muito eficiente; toda vez que você escolhe uma palavra aleatória, ele reconstrói a lista, o que é tão grande quanto o livro original. Uma melhoria óbvia é construi
```suggestion
Esse algoritmo funciona, mas não é muito eficiente; toda vez que você escolhe uma palavra aleatória, ele reconstrói a lista, o que é tão grande quanto o livro original. Uma melhoria óbvia é construir uma lista uma vez e então realizar múltiplas seleções, mas a lista continua grande.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +. Usar +chaves+ para obter uma lista de palavras do livro.
```suggestion
. Usar +keys+ para obter uma lista das palavras do livro.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +. Construir uma lista que contenha uma soma acumulativa da frequência da palavra (veja <<ex10-2>>). O último item é uma lista e o número total de palavras do livro, latexmath:[\(n\)].
```suggestion
. Construir uma lista que contenha uma soma acumulativa da frequência da palavra (veja <<ex10-2>>). O último item nesta lista é o número total de palavras no livro, latexmath:[\(n\)].
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +. Escolher um número aleatório de 1 até latexmath:[\(n\)]. Usar uma busca por bissecção (veja <<ex10-10>>) para encontrar o índice de onde o número aleatório deverá ser inserido na soma acumulativa.
```suggestion
. Escolher um número aleatório de 1 até latexmath:[\(n\)]. Usar uma busca por bissecção (veja <<ex10-10>>) para encontrar o índice no qual o número aleatório deverá ser inserido na soma acumulativa.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +. Usar o índice para encontrar a palavra correspondentes na lista de palavras.
```suggestion
. Usar o índice para encontrar a palavra correspondente na lista de palavras.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Se você escolher palavras do livro aleatoriamente, vocÊ poderá obter um senso de vocabulário, mas você provavelmente não obterá a sentença:
```suggestion
Se você escolher as palavras do livro aleatoriamente, pode-se obter um senso de vocabulário, mas você provavelmente não obterá uma sentença:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +esta pequena consideração Harriet que Knightley é mais coisas
```suggestion
this the small regard harriet which knightley's it most things
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Uma série de palavras aleatórias raramente faz sentido pois não há relação com as palavras sucessivas. Por exemplo, numa sentença real você experaria um artigo como "é" a ser seguido por um abjetivo
```suggestion
Uma série de palavras aleatórias raramente faz sentido pois não há relação com as palavras sucessivas. Por exemplo, numa sentença real você esperaria um artigo como “the” ser seguido por um adjetivo ou um substantivo, e provávelmente não um verbo ou advérbio.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Um jeito de medir essa relação é através da Análise de Markov, que caracteriza, para uma sequência de palavras dadas, a probabilidade das palavras que possam vir à seguir. Por exemplo, a música _Eric
```suggestion
Um jeito de medir essa relação é através da análise de Markov, que caracteriza, para uma sequência de palavras dadas, a probabilidade das palavras que possam vir a seguir. Por exemplo, a música _Epitáfio_ (do Titãs) tem o seguinte trecho:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +No texto, a frase "half the" é sempre seguida da palavra "bee", mas a frase "the bee" pode ser seguida ou de "has" ou de "is".
```suggestion
No texto, o termo “devia” é sempre seguido da palavra “ter”, mas a palavra “ter” pode ser seguida de “amado” ou “arriscado”.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
>  ____
Devia ter amado mais
Ter chorado mais
Ter visto o Sol nascer
Devia ter arriscado mais
E até errado mais
Ter feito o que eu queria fazer

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +O resultado da Análise de Markov é um mapeamento de cada prefixo (como "half the" e "the bee") a todos os possíveis sufixos (como "has" e "is").
```suggestion
O resultado da análise de Markov é um mapeamento de cada prefixo (como “devia” e “ter”) a todos os possíveis sufixos (como “amado” ou “arriscado”).
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Dado esse mapeamento, você pode gerar um texto aleatório começando com qualquer prefixo e escolhendo aleatoriamente dentre os possíveis sufixos. Em seguida, você pode combinar o final do prefixo e o
```suggestion
Dado esse mapeamento, você pode gerar um texto aleatório começando com qualquer prefixo e escolhendo aleatoriamente dentre os possíveis sufixos. Em seguida, você pode combinar o final do prefixo e o novo sufixo para formar o próximo prefixo, e repetir.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Por exemplo, se você começar com o prefixo "Half a", então a póxima palavra deverá ser "bee", pois é o prefixo que aparece apenas uma vez no texto. O próximo prefiro é "a bee", então o próximo sufixo
```suggestion
Por exemplo, se você começar com o prefixo “devia“, então a póxima palavra deverá ser “ter”, pois é o prefixo que aparece apenas uma vez no texto. O próximo prefixo é “devia ter”, então o próximo sufixo poderá ser “amado” ou “arriscado”.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Nesse exemplo o tamanho do prefixo é sempre dois, mas você pode fazer uma Análise de Markov com qualquer tamanho de prefixo.
```suggestion
Nesse exemplo o tamanho do prefixo é sempre dois, mas você pode fazer uma análise de Markov com qualquer tamanho de prefixo.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +. Escreva um programa que leia um texto de um arquivo e processe a Análise de Markov. O resultado deverá ser um dicionário que mapeia de prefixos a uma coleção de possíveis sufixos. A coleção poderá
```suggestion
. Escreva um programa que leia um texto de um arquivo e realize a análise de Markov. O resultado deverá ser um dicionário que mapeia os prefixos a uma coleção dos possíveis sufixos. A coleção poderá ser uma lista, tupla ou um dicionário; cabe a você fazer uma escolha apropriada. Você pode testar seu programa com o comprimento do prefixo dois, mas deve escrever o programa de uma maneira que facilite a tentativa de outros comprimentos.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +. Adicione uma função ao programa anterior para gerar textos aleatórios baseados na Análise de Markov. Aqui vai um exemplo de Emma com prefixo de tamanho 2:
```suggestion
. Adicione uma função ao programa anterior para gerar textos aleatórios baseados na análise de Markov. Aqui vai um exemplo de Emma com prefixo de tamanho 2:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Usar a Análise de Markov para gerar textos aleatórios é divertido, mas há também um ponto para este exercício: seleção da estrutura de dados. Na sua solução para os exercícios anteriores, você teve q
```suggestion
Usar a análise de Markov para gerar textos aleatórios é divertido, mas há também um propósito para este exercício: seleção da estrutura de dados. Na sua solução para os exercícios anteriores, você teve que escolher:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A última é fácil: Um dicionário é a escolha óbvia para um mapeamento de chaves a valores correspondentes.
```suggestion
A última é fácil: Um dicionário é a escolha óbvia para um mapeamento de chaves aos valores correspondentes.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Para os prefixos, as opções mais óbvias são strings, listas de strings ou truplas de strings.
```suggestion
Para os prefixos, as opções mais óbvias são as strings, listas de strings ou tuplas de strings.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Como você deve escolher? O primeiro passo é pensar nas operações que você precisará implementar para cada estrutura de dados. Para os prefixos, precisamos remover palavras do começo e adicionar ao fi
```suggestion
Como você deve escolher? O primeiro passo é pensar nas operações que você precisará implementar para cada estrutura de dados. Para os prefixos, precisamos remover palavras do começo e adicionar ao final. Por exemplo, se o prefixo atual é "devia" e a próxima palavra é "ter", você precisa formar o próximo prefixo, "devia ter".
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Adicionar um novo sufixo é igualmente fácil para a implementação da lista ou do histograma. Escolher um elemento aleatório de uma lista é fácil; escolher um histograma é mais difícil de ser feito efi
```suggestion
Adicionar um novo sufixo é igualmente fácil para a implementação da lista ou do histograma. Escolher um elemento aleatório de uma lista é fácil; escolher de um histograma é mais difícil de ser feito eficientemente (veja <<ex13-7>>).
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Até agora, conversamos principalmente sobre a facilidade de implementação, mas há outros fatores a serem considerados na escolha de estruturas de dados. Um deles é o tempo de execução. Às vezes, exis
```suggestion
Até agora, conversamos principalmente sobre a facilidade de implementação, mas há outros fatores a serem considerados na escolha das estruturas de dados. Um deles é o tempo de execução. Às vezes, existe uma razão teórica para esperar que uma estrutura de dados seja mais rápida que outra; por exemplo, mencionamos que o operador +in+ é mais rápido paraos dicionários do que para as listas, pelo menos quando o número de elementos é grande.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Mas muitas vezes você não sabe antecipadamente qual implementação será mais rápida. Uma opção é implementar os dois e ver qual é o melhor. Essa abordagem é chamada _benchmarking_. Uma alternativa prá
```suggestion
Mas muitas vezes você não sabe antecipadamente qual implementação será mais rápida. Uma opção é implementar os dois e ver qual é o melhor. Essa abordagem é chamado de _benchmarking_. Uma alternativa prática é escolher a estrutura de dados mais fácil de implementar e verificar se é rápida o suficiente para a aplicação pretendida. Se sim, não há necessidade de continuar. Caso contrário, existem ferramentas, como o módulo +Profile+, que podem identificar os locais em um programa que mais demoram.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Uma indagação final: Nesta discussão, sugerimos que devemos usar uma estrutura de dados para análise e geração. Mas como essas são fases separadas, também seria possível usar uma estrutura para análi
```suggestion
Uma indagação final: nesta discussão, sugerimos que devemos usar uma estrutura de dados para a análise e geração. Mas como essas fases são separadas, também seria possível usar uma estrutura para a análise e depois converter em outra estrutura para a geração. Isso seria uma vitória se o tempo economizado durante a geração excedesse o tempo gasto na conversão.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +O pacote do Julia, +DataStructures+ (veja https://github.com/JuliaCollections/DataStructures.jl) implementa uma variedade de estruturas de dados.
```suggestion
O pacote +DataStructures+ do Julia (consulte https://github.com/JuliaCollections/DataStructures.jl) implementa uma variedade de estruturas de dados.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +=== Debugando
```suggestion
=== Depuração
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Quando você está debugando um programa, e especialmente se você está trabalhando em um bug difícil, existem cinco coisas a se tentar:
```suggestion
Quando você está depurando um programa, e especialmente se você está trabalhando em um erro difícil, existem cinco atividades para se tentar:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((debugando)))
```suggestion
(((depuração)))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Experimente fazer alterações e executas versões diferentes. Geralmente se você visualiza a coisa certa no lugar certo do programa, o problema se torna óbvio, mas às vezes você tem que construir andai
```suggestion
Experimente fazer alterações e executar versões diferentes. Geralmente se você exibe a coisa certa no lugar certo no programa, o problema se torna óbvio, apesar de às vezes você ter que construir andaimes.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Tire algum tempo para pensar! Que tipo de erro é: sintaxe, tempo de execução ou semântica? Que informações você pode obter das mensagens de erro ou da saída do programa? Que tipo de erro pode causar
```suggestion
Tire algum tempo para pensar! Qual o tipo de erro é: sintaxe, tempo de execução ou semântica? Quais informações você pode obter das mensagens de erro ou da saída do programa? Que tipo de erro pode causar o problema que você está tendo? O que você mudou por último, antes que o problema aparecesse?
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Se você explicar o problema para outra pessoa, às vezes encontrará a resposta antes de terminar de fazer a pergunta. Muitas vezes você não precisa da outra pessoa; você poderia apenas conversar com u
```suggestion
Se você explicar o problema para outra pessoa, às vezes encontrará a resposta antes de terminar de fazer a pergunta. Muitas vezes você não precisa da outra pessoa, poderia apenas conversar com pato de borracha. E essa é a origem da estratégia conhecida chamada depuração com o pato de borracha. Não estamos inventando isso, veja https://pt.wikipedia.org/wiki/Debug_com_Pato_de_Borracha.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((debugação de pato de borracha)))
```suggestion
(((depuração com pato de borracha)))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Em um determinado ponto, a melhor coisa a fazer é voltar atrás e desfazer as alterações recentes, até chegar de volta a um programa que funcione e que você entenda. Então você pode começar a reconstr
```suggestion
Em um determinado ponto, a melhor coisa a fazer é voltar atrás e desfazer as alterações recentes, até voltar a ter um programa que funcione e que você entenda. Então você pode começar a reconstruir.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Programadores iniciantes às vezes ficam presos em uma dessas atividades e esquecem das outras. Cada atividade vem com o seu próprio erro.
```suggestion
Programadores iniciantes às vezes ficam presos em uma dessas atividades e esquecem das outras. Cada atividade tem a sua própria maneira de falhar.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((programação de passeio aleatório)))
Vc tem q decidir se vai usar o termo "programação de passeio aleatório" ou "programação aleatória".

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +É preciso pensar um pouco. Debugar é como ciência experimental. Deve haver pelo menos uma hipótese sobre qual é o problema. Se houver duas ou mais possibilidades, tente pensar em um teste que elimina
```suggestion
Você precisa ter um tempo para pensar. Depuração é como um experimento científico. Deve haver pelo menos uma hipótese sobre qual é o problema. Se houver duas ou mais possibilidades, tente pensar em um teste que eliminaria uma delas.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Mas até mesmo as melhores técnicas de debug falham se houver erros demais, ou se o código que está tentando corrigir for grande e complicado demais. Às vezes, a melhor opção é voltar atrás, simplific
```suggestion
Mas até mesmo as melhores técnicas de depuração falham se houver erros demais, ou se o código que você está tentando corrigir for muito grande e complicado. Às vezes, a melhor opção é voltar atrás, simplificando o programa até chegar a algo que funcione e que você entenda.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Programadores iniciantes muitas vezes relutam em voltar atrás porque não suportam a ideia de eliminar sequer uma linha de código (mesmo se estiver errada). Para você se sentir melhor, copie seu progr
```suggestion
Programadores iniciantes muitas vezes relutam em voltar atrás porque não conseguem eliminar uma linha de código (mesmo se estiver errada). Se isso faz você se sentir melhor, copie seu programa para um outro arquivo antes de começar a desmontá-lo. Então você pode copiar as partes de volta, uma a uma.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Encontrar um erro difícil exige leitura, execução, ruminação, e, às vezes, a retirada. Se você empacar em alguma dessas atividades, tente as outras.
```suggestion
Encontrar um erro difícil exige a leitura, execução, ruminação, e, às vezes, o recuo. Se você empacar em alguma dessas atividades, tente as outras.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Retirada::
```suggestion
Recuo::
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +determinista::
```suggestion
determinístico::
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +É relativo a um programa que faz a mesma coisa toda vez que é executado, dada uma mesma entrada.
```suggestion
Referente a um programa que faz a mesma coisa toda vez que é executado, dada a mesma entrada.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((determinista)))
```suggestion
(((determinístico)))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +É relativo à sequência de números que parecem ser aleatórios, mas é gerado por um programa determinista.
```suggestion
Referente a uma sequência de números que parecem ser aleatórios, mas é gerada por um programa determinístico.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Valor dado a um parâmetro opcional se não houver nenhum argumento.
```suggestion
valor padrão::
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +valor padrão::
```suggestion
O valor dado a um parâmetro opcional se nenhum argumento é fornecido.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +ignorar(override)::
Você usou o termo sobreposição na linha 253 e 254. Lendo as traduções das linhas 253, 254, 505, não me parece que o termo "ignorar" é o mais apropriado. Se vc desejar usar o termo "ignorar", por favor alinhar a tradução da linha 253, 254 e recusar a sugestão das linhas 505 e 506.
```suggestion
sobreposição::
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Substituir um valor padrão por um argumento.
```suggestion
A sobreposição de um valor padrão por um argumento.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((ignorar)))
```suggestion
(((sobreposição)))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +O processo de escolha entre estruturas de dados implementando alternativas e testando-as em uma amostra das entradas possíveis.
```suggestion
O processo de seleção das estruturas de dados ao implementar as alternativas e testá-las em uma amostra com as entradas possíveis.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +debugação de pato de borracha (Rubberducking)::
```suggestion
depuração com pato de borracha::
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Debugar explicando seu problema a um objeto inanimado como um pato de borracha. Articular o problema pode ajudá-lo a resolvê-lo, mesmo que o pato de borracha não conheça o Julia.
```suggestion
Depuração ao explicar seu problema a um objeto inanimado como um pato de borracha. Articular o problema pode ajudá-lo a resolvê-lo, mesmo que o pato de borracha não conheça o Julia.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((debugação de pato de borracha)))
```suggestion
(((depuração com pato de borracha)))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A “classificação” de uma palavra é sua posição em uma lista de palavras classificadas por frequência: a palavra mais comum tem classificação 1, a segunda mais comum tem classificação 2, etc.
```suggestion
A “classificação” de uma palavra é a sua posição em uma lista de palavras ordenada pela frequência: a palavra mais comum tem classificação 1, a segunda mais comum tem classificação 2, etc.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +onde latexmath:[\(s\)] e latexmath:[\(c\)] são parâmetros que dependem da linguagem e do texto. Se você pegar o logaritmo em ambos os lados desta equação, você obtém:
```suggestion
onde latexmath:[\(s\)] e latexmath:[\(c\)] são parâmetros que dependem da linguagem e do texto. Se você pegar o logaritmo em ambos os lados desta equação, obtém-se:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Se você plotar latexmath:[\(\log f\)] contra o latexmath:[\(\log r\)], você obterá uma linha reta com uma inclinação latexmath:[\(-s\)] e interceptar latexmath:[\(\log c\)].
```suggestion
Se você plotar latexmath:[\(\log f\)] por latexmath:[\(\log r\)], obterá uma linha reta com a inclinação latexmath:[\(-s\)] e o intercepto latexmath:[\(\log c\)].
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Instale uma biblioteca de Plot:
```suggestion
Instale uma biblioteca para plotar os gráficos:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
>  (((Plots)))((("module", "Plots", see="Plots")))
```suggestion
(((Plots)))((("módulo", "Plots", see="Plots")))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Use a biblioteca do +Plots+ para plotar resultados e verificar se eles formam ou não uma linha reta.
```suggestion
Use a biblioteca +Plots+ para plotar os resultados e verificar se eles formam ou não uma linha reta.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Neste capítulo apresentaremos um estudo de caso com exercícios que permitirá pensar na escolha de estruturas de dados e praticar o uso delas.
```suggestion
Neste capítulo apresentaremos um estudo de caso com os exercícios que permitirão pensar na escolha de estruturas de dados e praticar o uso delas.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((escolhido_do_histograma)))((("função", "definida pelo programador", "escolhido_do_histograma", see="escolhido_do_histograma")))
Vc tem q decidir se vc vai traduzir "programmer-defined" em "definida pelo programador" ou "definido pelo programador". No cap 7, vc usou a frase no masculino: "definido pelo programador", daí no cap 8, vc usou tanto na versão masculina e versão feminina.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((total_de_palavras)))((("função", "definido pelo programador", "total_de_palavras", see="total_de_palavras")))
Aqui vc traduz "programmer-defined" para a versão masculina ("definido pelo programador"). Vc tem q decidir se vc vai traduzir para a versão masculina ou a versão feminina.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((palavras_diferentes)))((("função", "definido pelo programador", "palavras_diferentes", see="palavras_diferentes")))
Aqui vc traduz "programmer-defined" para a versão masculina ("definido pelo programador"). Vc tem q decidir se vc vai traduzir para a versão masculina ou a versão feminina.

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((Análise de Markov)))
```suggestion
(((análise de Markov)))
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Análise de Markov
```suggestion
Análise de Markov:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +“Ele era muito esperto, quer fosse doçura, quer se zangasse, envergonhasse ou apenas se divertisse com esse golpe. Ela nunca pensou em Hannah até que você nunca foi para mim? "" Eu não posso fazer di
```suggestion
“He was very clever, be it sweetness or be angry, ashamed or only amused, at such a stroke. She had never thought of Hannah till you were never meant for me?" "I cannot make speeches, Emma:" he soon cut it all himself.”
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +. Depois que o programa estiver funcionando, convém tentar um mash-up: se você combinar textos de dois ou mais livros, o texto aleatório que você gerar irá mesclar o vocabulário e as frases das fonte
```suggestion
. Depois que o programa estiver funcionando, convém tentar uma combinação: se você combinar textos de dois ou mais livros, o texto aleatório gerado irá mesclar o vocabulário e as frases das fontes de maneiras interessantes.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +* Como representar a coleção de possíveis sufixos.
```suggestion
* Como representar a coleção dos possíveis sufixos.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Para a coleta de sufixos, as operações que precisamos executar incluem adicionar um novo sufixo (ou aumentar a frequência de um existente) e escolher um sufixo aleatório.
```suggestion
Para a coleta dos sufixos, as operações que precisamos executar incluem a adição de um novo sufixo (ou aumento da frequência de um existente) e a seleção de um sufixo aleatório.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +O outro fator a considerar é o espaço de armazenamento. Por exemplo, o uso de um histograma para a coleção de sufixos pode exigir menos espaço, pois você só precisa armazenar cada palavra uma vez, nã
```suggestion
O outro fator a considerar é o espaço de armazenamento. Por exemplo, o uso de um histograma para a coleção de sufixos pode exigir menos espaço, pois você só precisa armazenar cada palavra uma vez, não importa quantas vezes apareça no texto. Em alguns casos, economizar espaço também pode fazer com que seu programa seja executado mais rapidamente e, em um caso extremo, seu programa poderá não executar se você ficar sem memória. Porém, para muitos aplicativos, o espaço é uma consideração secundária após o tempo de execução.
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A lei de Zipf descreve a relação entre posições e frequências de linguagens naturais (https://en.wikipedia.org/wiki/Zipfpass:[&apos;]s_law). Especificamente, ele prediz que a frequência, latexmath:[\
```suggestion
A lei de Zipf descreve a relação entre as posições e as frequências das palavras nas linguagens naturais (https://pt.wikipedia.org/wiki/Lei_de_Zipf). Especificamente, ela prediz que a frequência latexmath:[\(f\)] da palavra com o ranqueamento latexmath:[\(r\)] dada por:
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Escreva um programa que leia um texto em um arquivo, conte as frequências das palavras e exiba uma linha para cada palavra, em ordem descendente da frequência, com latexmath:[\(\log f\)] e latexmath:
```suggestion
Escreva um programa que leia um texto em um arquivo, conta as frequências das palavras e exiba uma linha para cada palavra, em ordem decrescente da frequência, com latexmath:[\(\log f\)] e latexmath:[\(\log r\)].
```

2020-06-10 01:34 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> -
Abel vai pedir para vc gerar essa linha.

2020-06-11 14:38 UTC, gustavosarturi commented on book/src/chap13.asciidoc
> +(((escolhido_do_histograma)))((("função", "definida pelo programador", "escolhido_do_histograma", see="escolhido_do_histograma")))
@chunggnuhc - Resolvido, traduzido como "defninido pelo programador"

2020-06-27 05:39 UTC, chunggnuhc requested changes

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Va até o Projeto Gutenberg (https://guttenberg.org) e baixe seu livro favorito de domínio público em formato de texto sem formatação.
Vou dar mais uma sugestão que na minha opinião melhora a frase:
```suggestion
Va até o Projeto Gutenberg (https://guttenberg.org) e baixe seu livro favorito de domínio público em texto simples, isto é, texto sem formatação.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A função +rand+ retorna um ponto flutuante aleatório entre +0.0+ e +1.0+ (incluindo 0.0 mas não 1.0). Toda vez que você usa o comando +rand+, você obtém o próximo número de uma longa série. Para ver
Sugestão para tirar repetição de "você":
```suggestion
A função +rand+ retorna um ponto flutuante aleatório entre +0.0+ e +1.0+ (incluindo 0.0 mas não 1.0). Toda vez que se usa o comando +rand+, você obtém o próximo número de uma longa série. Para ver uma amostra disso, execute este laço:
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +    for linha in eachlinha(nomedoarquivo)
```suggestion
    for linha in eachline(nomedoarquivo)
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +outree quicksighted outwardly adelaide rencontre jeffereys unreserved dixons betweens
```suggestion
outree quicksighted outwardly adelaide rencontre jeffereys unreserved dixons betweens ...
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Algumas dessas palavras são nomes e preposições. Outros, como "rencontre" não são mais usados. Mas algumas são as palavras comuns que realmente devem estar na lista!
```suggestion
Algumas dessas palavras são nomes e preposições. Outros, como “rencontre” não são mais usados. Mas algumas são as palavras comuns que realmente devem estar na lista!
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Um jeito de medir essa relação é através da análise de Markov, que caracteriza, para uma sequência de palavras dadas, a probabilidade das palavras que possam vir a seguir. Por exemplo, a música _Epit
Encontrei um exemplo melhor de análise de Markov.
```suggestion
Um jeito de medir essa relação é através da análise de Markov, que caracteriza, para uma sequência de palavras dadas, a probabilidade das palavras que possam vir a seguir. Por exemplo, a música _Amor Pra Recomeçar_ (do Frejat) tem o seguinte trecho:
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Ter feito o que eu queria fazer
Apaga da linha 364 até linha 369 e coloca essa música "nova":
```suggestion
Eu te desejo não parar tão cedo
Pois toda idade tem prazer e medo
E com os que erram feio e bastante
Que você consiga ser tolerante
Quando você ficar triste
Que seja por um dia, e não o ano inteiro
E que você descubra que rir é bom,
mas que rir de tudo é desespero

Desejo que você tenha a quem amar
E quando estiver bem cansado
Ainda, exista amor pra recomeçar
Pra recomeçar

Eu te desejo muitos amigos
Mas que em um você possa confiar
E que tenha até inimigos
Pra você não deixar de duvidar
Quando você ficar triste
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +No texto, o termo “devia” é sempre seguido da palavra “ter”, mas a palavra “ter” pode ser seguida de “amado” ou “arriscado”.
```suggestion
No texto, o trecho “eu te” é sempre seguido da palavra “desejo”, mas o trecho “te desejo” pode ser seguido de “não” ou “muitos”.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +O resultado da análise de Markov é um mapeamento de cada prefixo (como “devia” e “ter”) a todos os possíveis sufixos (como “amado” ou “arriscado”).
```suggestion
O resultado da análise de Markov é um mapeamento de cada prefixo (como “eu te” e “te desejo”) a todos os possíveis sufixos (como “não” ou “muitos”).
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Por exemplo, se você começar com o prefixo “devia“, então a póxima palavra deverá ser “ter”, pois é o prefixo que aparece apenas uma vez no texto. O próximo prefixo é “devia ter”, então o próximo suf
```suggestion
Por exemplo, se você começar com o prefixo “eu te“, então a próxima palavra deverá ser “desejo”, pois é o prefixo que aparece apenas uma vez no texto. O próximo prefixo é “te desejo”, então o próximo sufixo poderá ser “não” ou “muitos”.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Como você deve escolher? O primeiro passo é pensar nas operações que você precisará implementar para cada estrutura de dados. Para os prefixos, precisamos remover palavras do começo e adicionar ao fi
```suggestion
Como você deve escolher? O primeiro passo é pensar nas operações que você precisará implementar para cada estrutura de dados. Para os prefixos, precisamos remover palavras do começo e adicionar ao final. Por exemplo, se o prefixo atual é "eu te" e a próxima palavra é "desejo", você precisa formar o próximo prefixo, "te desejo".
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Até agora, conversamos principalmente sobre a facilidade de implementação, mas há outros fatores a serem considerados na escolha das estruturas de dados. Um deles é o tempo de execução. Às vezes, exi
```suggestion
Até agora, conversamos principalmente sobre a facilidade de implementação, mas há outros fatores a serem considerados na escolha das estruturas de dados. Um deles é o tempo de execução. Às vezes, existe uma razão teórica para esperar que uma estrutura de dados seja mais rápida que outra; por exemplo, mencionamos que o operador +in+ é mais rápido para os dicionários do que para as listas, pelo menos quando o número de elementos é grande.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Modifique o programa anterior para ler uma lista de palavras e depois imprima todas as palavras do livro que não estão nessa lista de palavras. Quantas delas são erros de digitação? Quantas delas são
```suggestion
Modifique o programa anterior para ler uma lista de palavras e depois imprima todas as palavras do livro que não estão nessa lista. Quantas delas são erros de digitação? Quantas delas são palavras comuns que deveriam estar na lista de palavras e quantas delas são realmente obscuras?
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A função +processa_linha+ usa a função +replace+ para substituir os hífens e espaços antes de usar +split+ para separar a linha em uma lista de strings. Ela percorre a lista de palavras e usa +filter
```suggestion
A função +processa_linha+ usa a função +replace+ para substituir os hífens e espaços antes de usar +split+ para separar a linha em uma lista de strings. Ela percorre a lista de palavras e usa +filter+, +isletter+ e +lowercase+ para remover as pontuações e converter em letras minúsculas. (Apesar de dizer que as strings são “convertidas”, lembre-se de que as strings são imutáveis e portanto, uma função como +lowercase+ retorna novas strings.)
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Para encontrar as palavras mais frequentes, podemos fazer uma lista de tuplas, onde cada tupla contém uma palavra e a sua frequência e fazemos a ordenação. A função seguinte recebe um histograma e re
```suggestion
Para encontrar as palavras mais frequentes, podemos fazer uma lista de tuplas, onde cada tupla contém uma palavra e a sua respectiva frequência e fazemos a ordenação. A função seguinte recebe um histograma e retorna uma lista de tuplas que contém a frequência de palavras.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Em cada tupla, a frequência aparece primeiro, então o resultado da lista é ordenada por frequência. Aqui está um laço que imprime as 10 palavras mais frequentes:
```suggestion
Em cada tupla, a frequência aparece primeiro, então o resultado da lista é ordenada pela frequência. Aqui está um laço que imprime as 10 palavras mais frequentes:
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +o argumento +num+ fica com o valor do argumento. Em outras palavras, o valor opcional _sobrepõe_ o valor padrão.
```suggestion
o argumento +num+ fica com o valor passado no argumento. Em outras palavras, o valor opcional _sobrepõe_ o valor padrão.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +(((sobreposisão)))
```suggestion
(((sobreposição)))
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Esse algoritmo funciona, mas não é muito eficiente; toda vez que você escolhe uma palavra aleatória, ele reconstrói a lista, o que é tão grande quanto o livro original. Uma melhoria óbvia é construir
```suggestion
Esse algoritmo funciona, mas não é muito eficiente; toda vez que você escolhe uma palavra aleatória, ele reconstrói a lista, o que é tão grande quanto o livro original. Uma melhoria óbvia é construir uma lista uma vez e então realizar múltiplas seleções, apesar da lista continuar grande.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Você deve tentar esse execício antes de continuar.
```suggestion
Você deveria tentar esse execício antes de continuar.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Adicionar um novo sufixo é igualmente fácil para a implementação da lista ou do histograma. Escolher um elemento aleatório de uma lista é fácil; escolher de um histograma é mais difícil de ser feito
```suggestion
Adicionar um novo sufixo é igualmente fácil para a implementação da lista ou do histograma. Escolher um elemento aleatório de uma lista é fácil enquanto que escolher de um histograma é mais difícil de ser feito eficientemente (veja <<ex13-7>>).
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Se você explicar o problema para outra pessoa, às vezes encontrará a resposta antes de terminar de fazer a pergunta. Muitas vezes você não precisa da outra pessoa, poderia apenas conversar com pato d
```suggestion
Se você explicar o problema para outra pessoa, às vezes encontrará a resposta antes de terminar de fazer a pergunta. Muitas vezes você não precisa da outra pessoa, poderia apenas conversar com um pato de borracha. E essa é a origem da familiar estratégia chamada depuração com o pato de borracha. Não estamos inventando isso, veja https://pt.wikipedia.org/wiki/Debug_com_Pato_de_Borracha.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Referente a um programa que faz a mesma coisa toda vez que é executado, dada a mesma entrada.
```suggestion
Referente a um programa que faz a mesma coisa toda vez que é executado quando se é fornecida a mesma entrada.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +O processo de seleção das estruturas de dados ao implementar as alternativas e testá-las em uma amostra com as entradas possíveis.
```suggestion
O processo de seleção das estruturas de dados ao implementar as alternativas e testá-las em uma amostra com as possíveis entradas.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +A “classificação” de uma palavra é a sua posição em uma lista de palavras ordenada pela frequência: a palavra mais comum tem classificação 1, a segunda mais comum tem classificação 2, etc.
```suggestion
A “classificação” de uma palavra é a sua posição em uma lista ordenada pela frequência: a palavra mais comum tem classificação 1, a segunda mais comum tem classificação 2, etc.
```

2020-06-27 05:39 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Escreva um programa que leia um texto em um arquivo, conta as frequências das palavras e exiba uma linha para cada palavra, em ordem decrescente da frequência, com latexmath:[\(\log f\)] e latexmath:
```suggestion
Escreva um programa que leia um texto em um arquivo, conta as frequências das palavras e exibe uma linha para cada palavra, em ordem decrescente da frequência, com latexmath:[\(\log f\)] e latexmath:[\(\log r\)].
```

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Desejo que você tenha a quem amar
Pular linha para separar verso, como eu tinha colocado na revisão anterior.

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Eu te desejo muitos amigos
Pular linha para separar verso, como eu tinha colocado na revisão anterior.

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Temos visto as funções embutidas que recebem argumentos opcionais. É possível definir as funções com argumentos opcionais também. Por exemplo, eis uma função que imprime as palavras mais frequentes e
```suggestion
Temos visto as funções embutidas que recebem os argumentos opcionais. É possível definir as funções com os argumentos opcionais também. Por exemplo, eis uma função que imprime as palavras mais frequentes em um histograma:
```

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
>  ____
Prestar atençar que qdo vc cola os três versos juntos, dificulta a leitura e neste caso dificulta o leitor entender o exemplo qdo faz busca na letra da música.

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Você deveria tentar esse execício antes de continuar.
```suggestion
Você deveria tentar fazer esse execício antes de continuar.
```

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Usar a análise de Markov para gerar textos aleatórios é divertido, mas há também um propósito para este exercício: seleção da estrutura de dados. Na sua solução para os exercícios anteriores, você te
```suggestion
Usar a análise de Markov para gerar textos aleatórios é divertido, mas há também um propósito para este exercício: a seleção da estrutura de dados. Na sua solução para os exercícios anteriores, você teve que escolher:
```

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Sua primeira escolha pode ser uma lista, pois é fácil adicionar e remover elementos.
```suggestion
Sua primeira escolha pode ser uma lista, pois é fácil adicionar e remover os elementos.
```

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Experimente fazer alterações e executar versões diferentes. Geralmente se você exibe a coisa certa no lugar certo no programa, o problema se torna óbvio, apesar de às vezes você ter que construir and
```suggestion
Experimente fazer as alterações e executar versões diferentes. Geralmente se você exibe a coisa certa no lugar certo no programa, o problema se torna óbvio, apesar de às vezes você ter que construir andaimes.
```

2020-07-06 04:42 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Depuração ao explicar seu problema a um objeto inanimado como um pato de borracha. Articular o problema pode ajudá-lo a resolvê-lo, mesmo que o pato de borracha não conheça o Julia.
```suggestion
Depuração ao explicar seu problema a um objeto inanimado como um pato de borracha. Articular o problema pode te ajudar a resolvê-lo, mesmo que o pato de borracha não conheça o Julia.
```

2020-07-06 16:48 UTC, gustavosarturi commented
Principais atualizações:
- Atualização nos nomes das funções, removido o "_", mantive conforme no livro com o nome junto sem separação conforme já discutimos em reunião.
- Espaçamento na letra da musica.

2020-07-07 03:21 UTC, chunggnuhc commented
@abelsiqueira , vc pode me confirmar sobre o que foi falado na reunião de 6a feira 03/07/2020 sobre as variáveis? Eu tinha entendido que era para manter só o camel case e o resto era para manter do jeito que estávamos fazendo. Eu entendi errado?

2020-07-07 11:07 UTC, abelsiqueira commented
A struct minha_hora deve ficar CamelCase. Não discutimos mudanças pras
outras variáveis

On Tue, Jul 7, 2020, 00:21 Kally Chung <notifications@github.com> wrote:

> @abelsiqueira <https://github.com/abelsiqueira> , vc pode me confirmar
> sobre o que foi falado na reunião de 6a feira 03/07/2020 sobre as
> variáveis? Eu tinha entendido que era para manter só o camel case e o resto
> era para manter do jeito que estávamos fazendo. Eu entendi errado?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaIntro/JuliaIntroBR.jl/pull/25#issuecomment-654575325>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIE5UEELZKTB3IRJVTKRCDR2KIDRANCNFSM4NNU45OQ>
> .
>

2020-07-07 13:09 UTC, gustavosarturi commented
Foi erro meu, por isso removi o "_" de funções. No Slack, foi acertado que deveria seguir conforme o livro, exemplo:
- nome_de_variável
- nomedefunção

https://cidamo.slack.com/archives/G012BD8V0PQ/p1588213810022400

2020-07-09 17:37 UTC, chunggnuhc requested changes

2020-07-09 17:37 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +Como você deve escolher? O primeiro passo é pensar nas operações que você precisará implementar para cada estrutura de dados. Para os prefixos, precisamos remover palavras do começo e adicionar ao fi
```suggestion
Como você deve escolher? O primeiro passo é pensar nas operações que você precisará implementar para cada estrutura de dados. Para os prefixos, precisamos remover palavras do começo e adicionar ao final. Por exemplo, se o prefixo atual é “eu te” e a próxima palavra é “desejo”, você precisa formar o próximo prefixo, “te desejo”.
```

2020-07-09 17:37 UTC, chunggnuhc commented on book/src/chap13.asciidoc
> +onde latexmath:[\(s\)] e latexmath:[\(c\)] são parâmetros que dependem da linguagem e do texto. Se você pegar o logaritmo em ambos os lados desta equação, obtém-se:
```suggestion
onde latexmath:[\(s\)] e latexmath:[\(c\)] são os parâmetros que dependem da linguagem e do texto. Se você pegar o logaritmo em ambos os lados desta equação, obtém-se:
```

2020-07-10 17:04 UTC, chunggnuhc approved these changes

2020-07-17 22:20 UTC, abelsiqueira approved these changes

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +Dadas as mesmas entradas, a maioria dos programas de computadores geram a mesma entrada o tempo todo e por isso eles são ditos _determinísticos_. O determinismo é geralmente uma coisa boa pois espera
```suggestion
Dadas as mesmas entradas, a maioria dos programas de computadores sempre geram a mesma saída e por isso eles são ditos _determinísticos_. O determinismo é geralmente uma coisa boa pois esperamos que o mesmo cálculo produza o mesmo resultado. Mas para algumas aplicações, queremos que o computador seja imprevisível. Os jogos são um exemplo óbvio, porém há mais exemplos.
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +Desenvolver um programa puramente não determinístico acaba sendo difícil, mas há maneiras de fazer pelo menos com que ele pareça não determinístico. Uma delas é usar algoritmos que geram números _pse
```suggestion
Desenvolver um programa puramente não determinístico acaba sendo difícil, mas há maneiras de fazer pelo menos com que ele pareça não determinístico. Uma delas é usar algoritmos que geram números _pseudoaleatórios_. Os números pseudoaleatórios não são aleatórios de verdade porque eles são gerados por um cálculo determinístico, mas só olhando, é praticamente impossível distingui-los da aleatoriedade.
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +Temos visto as funções embutidas que recebem os argumentos opcionais. É possível definir as funções com os argumentos opcionais também. Por exemplo, eis uma função que imprime as palavras mais freque
```suggestion
Temos visto funções embutidas que recebem argumentos opcionais. É possível escrever as funções com argumentos opcionais também. Por exemplo, eis uma função que imprime as palavras mais frequentes em um histograma:
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +diff = subtrair(hist, palavras)
```suggestion
diferença = subtrair(hist, palavras)
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +for palavra in keys(diff)
```suggestion
for palavra in keys(diferença)
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +Esse algoritmo funciona, mas não é muito eficiente; toda vez que você escolhe uma palavra aleatória, ele reconstrói a lista, o que é tão grande quanto o livro original. Uma melhoria óbvia é construir
```suggestion
Esse algoritmo funciona, mas não é muito eficiente; toda vez que você escolhe uma palavra aleatória, ele reconstrói a lista, o que é tão grande quanto o livro original. Uma melhoria óbvia é construir uma lista uma vez e então realizar múltiplas seleções, mas a lista continua grande.
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +Realizar experiências pode ajudar, especialmente se você executar testes pequenos e simples. No entanto, se executar experiências sem pensar ou ler seu código, pode cair em um padrão que eu chamo de
```suggestion
Realizar experimentos pode ajudar, especialmente se você executar testes pequenos e simples. No entanto, se você executar experimentos sem pensar ou ler seu código, pode cair em um padrão que eu chamo de “programação aleatória”, que é o processo de fazer alterações aleatórias até que o programa faça a coisa certa. Obviamente, a programação aleatória pode levar muito tempo.
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +A “classificação” de uma palavra é a sua posição em uma lista ordenada pela frequência: a palavra mais comum tem classificação 1, a segunda mais comum tem classificação 2, etc.
```suggestion
O “ranque” de uma palavra é a sua posição em uma lista ordenada pela frequência: a palavra mais comum tem ranque 1, a segunda mais comum tem ranque 2, etc.
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +A lei de Zipf descreve a relação entre as posições e as frequências das palavras nas linguagens naturais (https://pt.wikipedia.org/wiki/Lei_de_Zipf). Especificamente, ela prediz que a frequência late
```suggestion
A lei de Zipf descreve a relação entre os ranque e as frequências das palavras nas linguagens naturais (https://pt.wikipedia.org/wiki/Lei_de_Zipf). Especificamente, ela prediz que a frequência latexmath:[\(f\)] da palavra com o ranque latexmath:[\(r\)] é dada por:
```

2020-07-17 22:20 UTC, abelsiqueira commented on book/src/chap13.asciidoc
> +Use a biblioteca +Plots+ para plotar os resultados e verificar se eles formam ou não uma linha reta.
```suggestion
Use a biblioteca +Plots+ para plotar os resultados e verificar se eles formam ou não uma linha reta.

```

2020-07-17 22:22 UTC, merged