Chapter14
JuliaIntro/JuliaIntroBR.jl pull request #26
Opened 2020-05-29 15:45 UTC by joaoluisro

chapter 14 translation.

2020-06-19 04:00 UTC, gustavosarturi requested changes

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +=== Persistência
Dar um "enter" para ajustar as linhas.
Linhas 5 e 6, vazias.

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Uma das maneiras mais simples que programas usam para manter seus dados é lendo e escrevendo _arquivos de texto_. Nós já vimos programas que lêm arquivos de texto; neste capítulo nós veremos programa
```suggestion
Uma das maneiras mais simples que os programas usam para manter seus dados é lendo e escrevendo _arquivos de texto_. Nós já vimos programas que leem arquivos de texto; neste capítulo nós veremos programas que as escrevem.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Uma das maneiras mais simples que programas usam para manter seus dados é lendo e escrevendo _arquivos de texto_. Nós já vimos programas que lêm arquivos de texto; neste capítulo nós veremos programa
Ref.: https://duvidas.dicio.com.br/leem-ou-leem/#:~:text=Leem%20%C3%A9%20a%20forma%20conjugada,palavra%20l%C3%AAm%20tamb%C3%A9m%20est%C3%A1%20errada.

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Uma alternativa é armazenar o estado do programa em um banco de dados. Neste capítulo eu também irei apresentar como usar um banco de dados simples.
```suggestion
Uma alternativa é armazenar o estado do programa em um banco de dados. Neste capítulo, iremos apresentar como usar um banco de dados simples.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Um arquivo de texto é uma sequência de caracteres armazenado em um meio permanente como um disco rígido, ou memória flash. Nós vimos como abrir e ler um arquivo em <<reading_word_lists>>.
```suggestion
Um arquivo de texto é uma sequência de caracteres armazenado em um meio permanente como um disco rígido ou memória flash. Nós vimos como abrir e ler um arquivo em <<reading_word_lists>>.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Exemplos de programas persistentes são sistemas operacionais, que são executados toda vez que um computador é ligado, e servidores web, que são executados toda hora, aguardando solicitações vindos da
```suggestion
Exemplos de programas persistentes são sistemas operacionais, que são executados toda vez que um computador é ligado e servidores web, que são executados toda hora, aguardando solicitações vindos da rede.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Este capítulo introduz a ideia de programas “persistentes” que mantêm dados permanentemente armazenados, e mostra como usar tipos diferentes de armazenamentos permanentes, como arquivos e banco de da
```suggestion
Este capítulo introduz a ideia de programas “persistentes” que mantêm dados permanentemente armazenados e mostra como usar tipos diferentes de armazenamentos permanentes, como arquivos e banco de dados.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Quando você acabar de escrever no arquivo, ele deve ser fechado.
```suggestion
Quando você terminar de escrever no arquivo, ele deve ser fechado.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +O argumeto da função write precisa ser uma string, então se nós quisermos colocar outros valores no arquivo, nós temos que convertê-los para string. A maneira mais fácil de fazer isso é com +string+
```suggestion
O argumeto da função write precisa ser uma string, então se quisermos colocar outros valores no arquivo, temos que convertê-los para string. A maneira mais fácil de fazer isso é usando +string+ ou interpolação de strings:
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +julia> println(fout, "Eu vi $camels camelos.")
```suggestion
julia> println(fout, "Eu vi $camelos camelos.")
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +julia> println(fout, "Eu vi $camels camelos.")
$camels é traduzido?

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Uma alternativa mais poderosa é o macro +@printf@+ que imprime usando uma string de especificação de formato de estilo C, você pode ler mais a respeito em https://docs.julialang.org/en/v1/stdlib/Prin
```suggestion
Uma alternativa mais poderosa é a macro +@printf@+ que imprime usando uma string de especificação de formato de estilo C, você pode ler mais a respeito em https://docs.julialang.org/en/v1/stdlib/Printf/
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +=== Filenames e Paths
@joaoluisro - Acho que seria interessante ver se esse subtítulo deve ser traduzido. Podemos discutir na reunião. Vou traduzir aqui, e aí, você decide se adiciona ou não.

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> ++cwd+ significa “current working directory” (diretório atual funcional). O resultado neste exemplo é +home/ben+, que é o diretório home do usuário chamado +ben+.
```suggestion
+cwd+ significa “current working directory” (diretório atual funcional). O resultado nesse exemplo é +home/ben+, que é o diretório home do usuário chamado +ben+.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +=== Filenames e Paths
```suggestion
=== Nomes de Arquivos e Caminhos
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Uma string como +"/home/ben"+ que identifica um arquivo ou diretório é chamado de _path_ (caminho).
```suggestion
Uma string como +"/home/ben"+ que identifica um arquivo ou diretório é chamado de _caminho_.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Um nome de arquivo simples, como +memo.txt+ também é considerado um path, mas é um _path relativo_ porque se refere ao diretório atual. Se o diretório atual é +/home/ben+, o nome do arquivo +memo.txt
```suggestion
Um nome de arquivo simples, como +memo.txt+ também é considerado um caminho, mas é um _caminho relativo_ porque se refere ao diretório atual. Se o diretório atual é +/home/ben+, o nome do arquivo +memo.txt+ se referiria à +/home/ben/memo.txt+.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
>  (((path)))
```suggestion
(((caminho)))
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +(((path relativo)))((("path", "relativo", see="path relativo")))
```suggestion
(((caminho relativo)))((("caminho", "relativo", see="caminho relativo")))
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Um path que começa com +/+ não depende do diretório atual; ele é chamado de _path absoluto_. Para achar um path absoluto para um arquivo, você pode usar +abspath+:
```suggestion
Um caminho que começa com +/+ não depende do diretório atual; ele é chamado de _caminho absoluto_. Para achar um caminho absoluto para um arquivo, você pode usar +abspath+:
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +(((path absoluto)))((("path", "absoluto", see="path absoluto")))(((abspath)))((("função", "Base", "abspath", see="abspath")))
```suggestion
(((caminho absoluto)))((("caminho", "absoluto", see="caminho absoluto")))(((abspath)))((("função", "Base", "abspath", see="abspath")))
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +O Julia fornece outras funções para trabalhar com nomes de arquivos e paths. Por exemplo, +ispath+ verifica se um arquivo ou diretório existe:
```suggestion
O Julia fornece outras funções para trabalhar com nomes de arquivos e caminhos. Por exemplo, +ispath+ verifica se um arquivo ou diretório existe:
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> ++readdir+ retorna um array de arquivos (e outros diretórios) no diretório dado:
```suggestion
+readdir+ retorna uma lista de arquivos (e outros diretórios) no diretório dado:
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> + "musica"
```suggestion
 "música"
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Para demonstrar estas funções, o exemplo a seguir “anda” por um diretório, exibe os nomes de todos os arquivos, e chama a si mesmo recursivamente em todos os diretórios.
```suggestion
Para demonstrar estas funções, o exemplo a seguir “caminha” por um diretório, exibe os nomes de todos os arquivos e chama a si mesmo recursivamente em todos os diretórios.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Para demonstrar estas funções, o exemplo a seguir “anda” por um diretório, exibe os nomes de todos os arquivos, e chama a si mesmo recursivamente em todos os diretórios.
Duas opções. Veja qual você acha que fique mais fluído.

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Para demonstrar estas funções, o exemplo a seguir “anda” por um diretório, exibe os nomes de todos os arquivos, e chama a si mesmo recursivamente em todos os diretórios.
```suggestion
Para demonstrar estas funções, o exemplo a seguir “percorre” por um diretório, exibe os nomes de todos os arquivos e chama a si mesmo recursivamente em todos os diretórios.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +(((anda)))((("função", "definido pelo programador", "anda", see="anda")))
```suggestion
(((caminha)))((("função", "definido pelo programador", "caminha", see="caminha")))
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +function anda(nomedir)
```suggestion
function caminha(nomedir)
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +            anda(path)
Não consegui colocar aqui. Mas, talvez trocar o nome da função por "caminha". Veja se fica melhor...

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> ++joinpath+ recebe um diretório e um nome de arquivo e junta-os em um path completo.
```suggestion
+joinpath+ recebe um diretório e um nome de arquivo e junta-os em um caminho completo.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +O Julia fornece uma função chamada +walkdir+ (veja https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.walkdir) que é similar a esta mas é mais versátil. Como um exercício, leia a documentaçã
```suggestion
O Julia fornece uma função chamada +walkdir+ (consulte https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.walkdir) que é similar a esta mas é mais versátil. Como um exercício, leia a documentação e a use para imprimir os nomes dos arquivos em um dado diretório e seus subdiretórios.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Para evitar estes erros, você pode usar funções como +ispath+ e +isfile+, mas levaria muito tempo e código para verificar todas as possibilidades.
```suggestion
Para evitar estes erros, você pode usar funções como +ispath+ e +isfile+, porém, tomaria muito tempo e código para verificar todas as possibilidades.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +O Julia inicia executando a cláusula +try+. Se tudo der certo, ele pula a cláusula +catch+ e segue adiante. Se uma exceção ocorre, ele pula fora da cláusula +try+ e executa a cláusula +catch+.
```suggestion
O Julia inicia executando a cláusula +try+. Se tudo der certo, ele pula a cláusula +catch+ e segue adiante. Se ocorrer alguma exceção, ele pula fora da cláusula +try+ e executa a cláusula +catch+.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Lidar com uma exceção com uma declaração +try+ é chamado de _capturar_ uma exceção. Neste exemplo, a cláusula exceto imprime uma mensagem de erro que não é muito útil. Em geral, capturar uma exceção
```suggestion
Lidar com uma exceção com uma declaração +try+ é chamado de _capturar_ uma exceção. Neste exemplo, a cláusula exceto imprime uma mensagem de erro que não é muito útil. Em geral, capturar uma exceção nos da uma chance de consertar o problema, ou tentar novamente ou pelo menos encerrar o programa graciosamente.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Em código que realiza mudanças de estado ou usa recursos como arquivos, há geralmente trabalho de limpeza (como fechar arquivos) que precisa ser feito quando o código é encerrado. Exceções potencialm
```suggestion
Em código que realiza mudanças de estado ou usa recursos como arquivos, geralmente há um trabalho de limpeza (como fechar arquivos) que precisa ser feito quando o código é encerrado. Exceções potencialmente complicam esta tarefa, já que elas podem causar a saída de um bloco de código antes dele atingir seu fim normal. A palavra-chave +finally+ fornece uma maneira de executar código quando um dado bloco de código sai, independente de como ele saiu:
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +A limitação do +GDBM+ é de que as chaves e valores precisam ser strings ou arrays de bytes. Se você tentar usar qualquer outro tipo, você recebe um erro.
Acredito que aqui esteja tratando de _array_ e não de _listas_. Dê um _double check_ nessa parte caso precise mudar.

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> ++serialize+ e +deserialize+ escrevem para e lêm de um objeto iobuffer que representa um fluxo I/O em memória. A função +take!+ busca os conteúdos do iobuffer como um array de bytes e reinicia o iobuf
```suggestion
+serialize+ e +deserialize+ escrevem para e leem de um objeto iobuffer que representa um fluxo I/O em memória. A função +take!+ busca os conteúdos do iobuffer como uma lista de bytes e reinicia o iobuffer para seu estado inicial.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> ++serialize+ e +deserialize+ escrevem para e lêm de um objeto iobuffer que representa um fluxo I/O em memória. A função +take!+ busca os conteúdos do iobuffer como um array de bytes e reinicia o iobuf
Caso não for alterar para "lista de bytes"...
```suggestion
+serialize+ e +deserialize+ escrevem para e leem de um objeto iobuffer que representa um fluxo I/O em memória. A função +take!+ busca os conteúdos do iobuffer como um array de bytes e reinicia o iobuffer para seu estado inicial.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Apesar do objeto novo ter o mesmo valor do antigo, ele não é (em geral) o mesmo objeto:
```suggestion
Apesar do novo objeto ter o mesmo valor do antigo, ele não é (em geral) o mesmo objeto:
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +A maioria dos sistemas operacionais fornecem uma interface de linha de comando, também conhecida como uma _shell_. Shells geralmente fornecem comandos para navegar o sistema de arquivos e iniciar apl
```suggestion
A maioria dos sistemas operacionais fornecem uma interface de linha de comando, também conhecida como uma _shell_. Shells geralmente fornecem comandos para navegar o sistema de arquivos e iniciar aplicações. Por exemplo, no Unix você pode mudar de diretório com o comando +cd+, exibir o conteúdo do diretório com +ls+ e iniciar o web browser digitando (por exemplo) +firefox+.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Por exemplo, a maioria dos sistemas Unix fornecem um comando chamado +md5sum+ ou +md5+ que lê o conteúdo de um arquivo e calcula a “checksum”. Você pode ler mais sobre MD5 em https://en.wikipedia.org
Veja se fica bom:
```suggestion
Por exemplo, a maioria dos sistemas Unix fornecem um comando chamado +md5sum+ ou +md5+ que lê o conteúdo de um arquivo e calcula uma “soma de verificação” para checar a integridade dos dados. Você pode ler mais sobre MD5 em https://pt.wikipedia.org/wiki/MD5. Este comando fornece uma maneira eficiente de verificar se dois arquivos possuem o mesmo conteúdo. A probabilidade de que conteúdos diferentes produzem a mesma soma de verificação é muito pequena (isto é, improvável de acontecer antes que o universo entre em colapso).
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +A função embutida +repr+ ou +dump+ podem ajudar. Elas recebem qualquer objeto como argumento e retornam uma string representando o objeto.
```suggestion
As funções embutidas +repr+ ou +dump+ podem ajudar. Elas recebem qualquer objeto como argumento e retornam uma string representando o objeto.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Para a maioria dos sistemas, existem aplicações que convertem de um formato para o outro. Você pode achá-los (e ler mais a respeito deste problema) em https://en.wikipedia.org/wiki/Newline. Ou, é cla
```suggestion
Para a maioria dos sistemas, existem aplicações que convertem de um formato para o outro. Você pode achá-los (e ler mais a respeito deste problema) em https://pt.wikipedia.org/wiki/Nova_linha. Ou, é claro, você pode escrever um por conta própria.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
>  (((persistent)))
```suggestion
(((persistente)))
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
>  path::
```suggestion
caminho::
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
>  (((path)))
```suggestion
(((caminho)))
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Um path que inicia no diretório atual.
```suggestion
Um caminho que inicia no diretório atual.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +path relativo::
```suggestion
caminho relativo::
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +(((path relativo)))
```suggestion
(((caminho relativo)))
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +path absoluto::
```suggestion
caminho absoluto::
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Um path que inicia do diretório mais a cima no sistema de arquivos.
```suggestion
Um caminho que inicia do diretório mais a cima no sistema de arquivos.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +(((path absoluto)))
```suggestion
(((caminho absoluto)))
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Escreva uma função chamada +sed+ que recebe como argumento uma string de padrão, uma string de substituição, e dois nomes de arquivos; ela deva ler o primeiro arquivo e escrever o conteúdo no segundo
```suggestion
Escreva uma função chamada +sed+ que recebe como argumento uma string padrão, uma string de substituição e dois nomes de arquivos; ela deva ler o primeiro arquivo e escrever o conteúdo no segundo arquivo (criando ele ser for necessário). Se o padrão aparece em qualquer lugar no arquivo, ele deve ser substituido pela string de substituição.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Se um erro ocorre durante a abertura, leitura, escrita ou fechamento dos arquivos, seu programa deve capturar a exceção, exibir a mensagem de erro, e sair.
```suggestion
Se um erro ocorre durante a abertura, leitura, escrita ou fechamento dos arquivos, seu programa deve capturar a exceção, exibir a mensagem de erro e sair.
```

2020-06-19 04:00 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Se você fez <<ex12-2>>, você verá que um dicionário é criado que mapeia uma string ordenada de letras para uma lista de palavras que podem ser escritas com estas letras.Por exemplo, +"opst"+ é mapead
```suggestion
Se você fez <<ex12-2>>, você verá que um dicionário é criado que mapeia uma string ordenada de letras para uma lista de palavras que podem ser escritas com estas letras. Por exemplo, +"opst"+ é mapeado para a lista +["opts", "post", "pots", "spot", "stop", "tops"]+.
```

2020-07-02 03:48 UTC, gustavosarturi requested changes

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +O argumeto da função write precisa ser uma string, então se quisermos colocar outros valores no arquivo, temos que convertê-los para string. A maneira mais fácil de fazer isso é usando +string+ ou in
```suggestion
O argumento da função write precisa ser uma string, então se quisermos colocar outros valores no arquivo, temos que convertê-los para string. A maneira mais fácil de fazer isso é usando +string+ ou interpolação de strings:
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Uma string como +"/home/ben"+ que identifica um arquivo ou diretório é chamado de _caminho_.
```suggestion
Uma string como +"/home/ben"+ que identifica um arquivo ou diretório é chamada de _caminho_.
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Um caminho que começa com +/+ não depende do diretório atual; ele é chamado de _caminho absoluto_. Para achar um caminho absoluto para um arquivo, você pode usar +abspath+:
```suggestion
Um caminho que começa com +/+ não depende do diretório atual; ele é chamado de _caminho absoluto_. Para encontrar um caminho absoluto para um arquivo, você pode usar +abspath+:
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +O Julia fornece uma função chamada +walkdir+ (consulte https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.walkdir) que é similar a esta mas é mais versátil. Como um exercício, leia a documen
```suggestion
O Julia fornece uma função chamada +walkdir+ (consulte https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.walkdir) que é similar a esta, porém, é mais versátil. Como um exercício, leia a documentação e a use para imprimir os nomes dos arquivos em um dado diretório e seus subdiretórios.
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +É mais fácil tentar de uma vez-e lidar com os problemas se eles ocorrerem-que é exatamente o que a declaração +try+ faz. A sintaxe é similar a uma declaração +if+:
Travessão
```suggestion
É mais fácil tentar de uma vez—e lidar com os problemas se eles ocorrerem—que é exatamente o que a declaração +try+ faz. A sintaxe é similar a uma declaração +if+:
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Se você faz outra atribuição para uma chava já existe, +GDBM+ substitui o valor antigo:
```suggestion
Se você faz outra atribuição para uma chave já existente, +GDBM+ substitui o valor antigo:
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +julia> db["cleese.png"] = "Foto de John Cleese fazendo uma andada engraçada."
```suggestion
julia> db["cleese.png"] = "Foto de John Cleese fazendo uma caminhada engraçada."
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +"Foto de John Cleese fazendo uma andada engraçada."
```suggestion
"Foto de John Cleese fazendo uma caminhada engraçada."
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +"Foto de John Cleese fazendo uma andada engraçada."
```suggestion
"Foto de John Cleese fazendo uma caminhada engraçada."
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +As funções +serialize+ e +deserialize+ podem ajudar. Elas traduzem quase todo tipo de objeto em um array de bytes (um iobuffer) adequado para armazenamento em um banco de dados, e em seguida traduz o
```suggestion
As funções +serialize+ e +deserialize+ podem ajudar. Elas traduzem quase todo tipo de objeto em uma lista de bytes (um iobuffer) adequado para armazenamento em um banco de dados e em seguida traduz a lista de bytes em objetos:
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +Em outras palavras, serialization e em seguida deserialization tem o mesmo efeito de copiar o objeto.
```suggestion
Em outras palavras, serialização e em seguida desserialização tem o mesmo efeito de copiar o objeto.
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +As funções embutidas +repr+ ou +dump+ podem ajudar. Elas recebem qualquer objeto como argumento e retornam uma string representando o objeto.
```suggestion
As funções internas +repr+ ou +dump+ podem ajudar. Elas recebem qualquer objeto como argumento e retornam uma string representando o objeto.
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +=== Depurando
```suggestion
=== Depuração
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +(((depurando)))
```suggestion
(((depuração)))
```

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +. Para verificar novamente, você pode usar o comando Unix +diff+.
Gerar linha "625"

2020-07-02 03:48 UTC, gustavosarturi commented on book/src/chap14.asciidoc
> +. Para reconhecer duplicatas, você pode usar +md5sum+ ou +md5+ para computar a “checksum” de cada arquivo. Se dois arquivos tem a mesma checksum, eles provavelmente tem o mesmo conteúdo.
```suggestion
. Para reconhecer duplicatas, você pode usar +md5sum+ ou +md5+ para computar uma "verificação de soma” de cada arquivo. Se dois arquivos tem a mesma checksum, eles provavelmente tem o mesmo conteúdo.
```

2020-07-06 21:32 UTC, joaoluisro commented on book/src/chap14.asciidoc
> +. Para reconhecer duplicatas, você pode usar +md5sum+ ou +md5+ para computar a “checksum” de cada arquivo. Se dois arquivos tem a mesma checksum, eles provavelmente tem o mesmo conteúdo.
acho melhor não traduzir, checksum é um termo bastante recorrente. O que acha @abelsiqueira ?

2020-07-06 22:30 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +. Para reconhecer duplicatas, você pode usar +md5sum+ ou +md5+ para computar a “checksum” de cada arquivo. Se dois arquivos tem a mesma checksum, eles provavelmente tem o mesmo conteúdo.
Concordo

2020-07-08 04:00 UTC, gustavosarturi approved these changes

2020-07-21 23:53 UTC, abelsiqueira approved these changes

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +Uma alternativa mais poderosa é a macro +@printf@+ que imprime usando uma string de especificação de formato de estilo C, você pode ler mais a respeito em https://docs.julialang.org/en/v1/stdlib/Prin
```suggestion
Uma alternativa mais poderosa é a macro +@printf+ que imprime usando uma string de especificação de formato de estilo C, você pode ler mais a respeito em https://docs.julialang.org/en/v1/stdlib/Printf/
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> ++cwd+ significa “current working directory” (diretório atual funcional). O resultado nesse exemplo é +home/ben+, que é o diretório home do usuário chamado +ben+.
```suggestion
+cwd+ significa “current working directory” (diretório de trabalho atual). O resultado nesse exemplo é +home/ben+, que é o diretório home do usuário chamado +ben+.
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +            anda(path)
```suggestion
            caminha(path)
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +Lidar com uma exceção com uma declaração +try+ é chamado de _capturar_ uma exceção. Neste exemplo, a cláusula exceto imprime uma mensagem de erro que não é muito útil. Em geral, capturar uma exceção
```suggestion
Lidar com uma exceção com uma declaração +try+ é chamado de _capturar_ uma exceção. Neste exemplo, a cláusula de exceção imprime uma mensagem de erro que não é muito útil. Em geral, capturar uma exceção nos da uma chance de consertar o problema, ou tentar novamente ou pelo menos encerrar o programa graciosamente.
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +O ThinkJulia fornece uma interface para +GDBM+ (GNU dbm) para criar e atualizar arquivos de bancos de dados. Como um exemplo, irei criar um banco de dados que contém legendas para arquivos de imagens
```suggestion
O JuliaIntroBR fornece uma interface para +GDBM+ (GNU dbm) para criar e atualizar arquivos de bancos de dados. Como um exemplo, irei criar um banco de dados que contém legendas para arquivos de imagens.
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +(((DBM)))((("tipo", "ThinkJulia", "DBM", see="DBM")))
```suggestion
(((DBM)))((("tipo", "JuliaIntroBR", "DBM", see="DBM")))
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +(((escopo)))(((módulo)))((("palavra-chave", "módulo", see="módulo")))(((end)))(((import)))((("palavra-chave", "import", see="import")))(((export)))((("palavra-chave", "export", see="export")))(((cont
```suggestion
(((escopo)))(((módulo)))((("palavra-chave", "módulo", see="módulo")))(((end)))(((import)))((("palavra-chave", "import", see="import")))(((export)))((("palavra-chave", "export", see="export")))(((ContaLinha)))((("module", "ContaLinha", see="ContaLinha")))((("function", "ContaLinha", "contalinha", see="contalinha")))
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +module contalinha
```suggestion
module ContaLinha
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +O módulo objeto +contalinha+ fornece +contalinha+:
```suggestion
O objeto de tipo módulo +ContaLinha+ fornece +contalinha+:
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +julia> using contalinha
```suggestion
julia> using ContaLinha
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +Digite este exemplo em um arquivo chamado _wc.jl_, inclua-o no REPL e insira +using contalinha+.
```suggestion
Digite este exemplo em um arquivo chamado _wc.jl_, inclua-o no REPL e insira +using ContaLinha+.
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +Um outro problema que você pode encontrar é que sistemas diferentes usam caracteres diferentes para indicar o final da linha. Alguns sistemas usam uma nova linha, representada por +\n+. Outros usam u
```suggestion
Um outro problema que você pode encontrar é que sistemas diferentes usam caracteres diferentes para indicar o final da linha. Alguns sistemas usam uma nova linha, representada por +\n+. Outros usam um caractere de retorno, representado por +\r+. Alguns usam ambos. Se você mover arquivos entre sistemas diferentes, essas inconsistências podem causar problemas.
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +Pertencente a um programa que é executado indefinidamente e mantém pelo menos alguns de seus dados em armazenamento permanente.
```suggestion
Referente a um programa que é executado indefinidamente e mantém pelo menos alguns de seus dados em armazenamento permanente.
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +Um caminho que inicia do diretório mais a cima no sistema de arquivos.
```suggestion
Um caminho que inicia do diretório mais acima no sistema de arquivos.
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +Escreva uma função chamada +sed+ que recebe como argumento uma string padrão, uma string de substituição e dois nomes de arquivos; ela deva ler o primeiro arquivo e escrever o conteúdo no segundo arq
```suggestion
Escreva uma função chamada +sed+ que recebe como argumento uma string padrão, uma string de substituição e dois nomes de arquivos; ela deve ler o primeiro arquivo e escrever o conteúdo no segundo arquivo (o criando se for necessário). Se o padrão aparece em qualquer lugar no arquivo, ele deve ser substituido pela string de substituição.
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +(((guardaanagramas)))((("função", "programmer-defined", "guardaanagramas", see="guardaanagramas")))(((leranagramas)))((("função", "definido pelo programador", "leranagramas", see="leranagramas")))
```suggestion
(((guardaanagramas)))((("função", "definido pelo programador", "guardaanagramas", see="guardaanagramas")))(((leranagramas)))((("função", "definido pelo programador", "leranagramas", see="leranagramas")))
```

2020-07-21 23:53 UTC, abelsiqueira commented on book/src/chap14.asciidoc
> +. Para verificar novamente, você pode usar o comando Unix +diff+.
```suggestion
. Para verificar novamente, você pode usar o comando Unix +diff+.

```

2020-07-21 23:59 UTC, merged