Chapter17
JuliaIntro/JuliaIntroBR.jl pull request #28
Opened 2020-06-06 19:55 UTC by joaoluisro

2020-07-06 01:44 UTC, chunggnuhc requested changes
1st review

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +No Julia você tem a habilidade de escrever código que opera em tipos diferentes. Isto é chamado de programação genérica.
```suggestion
No Julia, você tem a habilidade de escrever código que opera em tipos diferentes. Isto é chamada de programação genérica.
```
A habilidade de escrever código que opera em tipos diferentes é chamada de programação genérica. Foi isso q eu entendi, por isso q sugeri a alteração.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Neste capítulo irei discutir o uso de declarações de tipos em Julia, e também introduzirei métodos que são maneiras de implementar comportamentos diferentes para uma função dependendo dos tipos de se
```suggestion
Neste capítulo, irei discutir o uso de declarações de tipo em Julia, e também introduzirei os métodos que são os recursos usados para implementar os comportamentos diferentes para uma função, dependendo dos tipos de seus argumentos. Isto é chamado de despacho múltiplo.
```
A alteração que eu sugeri foge um pouco da tradução, mas na minha opinião, ela traz mais clareza na informação sobre os métodos.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O operador +::+ anexa _anotações de tipo_ à expressões e variáveis:
```suggestion
O operador +::+ anexa _anotações de tipo_ às expressões e variáveis:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O operador +::+ também pode ser acrescentado ao lado esquerdo da atribuição, ou como uma parte de uma declaração.
```suggestion
O operador +::+ também pode ser acrescentado ao lado esquerdo de uma atribuição, ou como uma parte de uma declaração.
```
Essa frase me parece mal elaborada, pq só lendo a frase eu imaginei q era antes do início da atribuição. Isso é só eu ou é normal vcs (da computação) darem essa direção? Eu só entendi o sentido da frase após ler o exemplo.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +A variável +x+ é sempre do tipo +Float64+ e o valor é sempre convertido para um ponto flutuante se necessário.
```suggestion
A variável +x+ é sempre do tipo +Float64+ e o valor é convertido para um ponto flutuante, quando necessário.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Uma anotação de tipo também pode ser anexada ao cabeçario de uma definição de função:
```suggestion
Uma anotação de tipo também pode ser anexada ao cabeçalho de uma definição de função:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O comportamento padrão em Julia quando tipos são omitidos, é permitir que valores sejam de qualquer tipo (+Any+).
```suggestion
Quando os tipos são omitidos, o comportamento padrão em Julia é permitir que valores sejam de qualquer tipo (+Any+).
```
A tradução tá boa, mas mudei a ordem porque eu em particular não gosto qdo fica "intercalando" frases porque na minha opinião, dificulta a leitura.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Em <<chap16>>, nós definimos uma struct chamada +MeuTempo+ e em <<tempo>>, você escreveu uma função chamada +imprime_tempo+:
```suggestion
Em <<chap16>>, nós definimos uma struct chamada +MeuTempo+ e em <<time>>, você escreveu uma função chamada +imprime_tempo+:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Como você pode ver, declarações de tipos podem e devem ser adicionadas por razões de performance aos campos na definição da struct.
```suggestion
Como você pode ver, as declarações de tipo podem e devem ser adicionadas nos campos da definição da struct por questões de performance.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Para adicionar um _método_ à função +imprime_tempo+ que apenas aceita como argumento um objeto +MeuTempo+, tudo que precisamos fazer é acrescentar +::+ seguido de +MeuTempo+ ao argumento +tempo+ na d
```suggestion
Para adicionar um _método_ à função +imprime_tempo+ que apenas aceita um objeto +MeuTempo+ como argumento, tudo que precisamos fazer é acrescentar +::+ seguido de +MeuTempo+ no argumento +tempo+ na definição de função:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Se você chamar a função +imprime_tempo+ com um objeto diferente de +MeuTempo+, agora você recebe:
```suggestion
Se você chamar a função +imprime_tempo+ com um objeto diferente de +MeuTempo+, agora recebe-se:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +(((returnfloat)))((("função", "definido pelo programador", "retorna_float", see="retorna_float")))
```suggestion
(((retorna_float)))((("função", "definido pelo programador", "retorna_float", see="retorna_float")))
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Para chamar esta função, você deve passar um objeto +MeuTempo+ como argumento:
```suggestion
Para chamar esta função, você deve passar um objeto +MeuTempo+ como um argumento:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +=== Declarações de Tipos
```suggestion
=== Declarações de Tipo
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Note que agora, ela é uma função pura, não um modificador.
```suggestion
Note que agora ela é uma função pura, e não um modificador.
```
Sugestões só para melhorar a fluidez da leitura.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Se você colocar os argumentos na ordem errada, você recebe um erro:
```suggestion
Se você colocar os argumentos na ordem errada, aparece uma mensagem de erro:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +ERROR: MethodError: no method matching increment(::Int64, ::MeuTempo)
```suggestion
ERROR: MethodError: no method matching incrementar(::Int64, ::MeuTempo)
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +A assinatura do método é +incrementar(tempo ::MeuTempo, segundos::Int64)+ e não +incrementar(segundos::Int64, tempo::MeuTempo)+.
```suggestion
A assinatura do método é +incrementar(tempo::MeuTempo, segundos::Int64)+ e não +incrementar(segundos::Int64, tempo::MeuTempo)+.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Reescrevendo +é_depois+ para agir somente em +MeuTempo+ é fácil:
```suggestion
Reescrever +é_depois+ para operar somente com objetos +MeuTempo+ é fácil:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Aliás, argumentos opcionais são implementados como sintaxe para definições múltiplas de métodos. Por exemplo, essa definição:
```suggestion
Aliás, os argumentos opcionais são implementados como sintaxe para as múltiplas definições do método. Por exemplo, essa definição:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um _construtor_ é uma função especial que é chamada para criar um objeto. Os métodos padrões construtores de +MeuTempo+ tem a seguinte assinatura:
```suggestion
Um _construtor_ é uma função especial chamada para criar um objeto. Os métodos construtores padrões de +MeuTempo+ tem a seguinte assinatura:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Nós podemos também adicionar nossos próprios métodos _construtores externos_
```suggestion
Nós podemos também adicionar nossos próprios métodos _construtores externos_:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um método construtor interno é sempre definido dentro do bloco de uma declaração de tipo e tem acesso à função especial chamada +new+ que cria objetos de um novo tipo declarado.
```suggestion
Um método construtor interno é sempre definido dentro do bloco de uma declaração de tipo e tem acesso a uma função especial chamada +new+ que cria objetos de um novo tipo declarado.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O construtor padrão não está disponível se qualquer construtor interno estiver definido. Você deve escrever explicitamente todos os construtores internos que você precisa.
```suggestion
O construtor padrão não é disponibilizado se qualquer construtor interno for definido. Você deve escrever explicitamente todos os construtores internos de que você precisa.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um segundo método sem argumento da função local +new+ existe:
```suggestion
Um segundo método sem argumentos da função local +new+ existe:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Isso permite a criação de estruturas de dados recorrentes, isto é, uma struct no qual um dos campos também é uma struct. Neste caso a struct precisa ser mutável pois seus campos são modificados após
```suggestion
Isso permite a criação das estruturas de dados recorrentes, isto é, uma struct no qual um dos campos também é uma struct. Neste caso, a struct precisa ser mutável pois seus campos são modificados após serem instanciados.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> ++show+ é uma função especial que retorna uma representação de string de um objeto. Por exemplo, aqui está um método +show+ para objetos +MeuTempo+:
```suggestion
+show+ é uma função especial que retorna uma representação de string de um objeto. Por exemplo, aqui está um método +show+ para os objetos +MeuTempo+:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Quando eu crio um novo tipo composto, eu quase sempre começo criando um construtor externo, que facilita a instanciação de objetos, e +show+, que é útil para debugging.
```suggestion
Quando eu crio um novo tipo composto, eu quase sempre começo criando um construtor externo, que facilita a instanciação dos objetos, e +show+, que é útil para a depuração.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Escreva um método construtor externo para a classe +Ponto+ que recebe +x+ e +y+ como parâmetros adicionais e que atribuam a eles seus campos correspondentes.
```suggestion
Escreva um método construtor externo para a classe +Ponto+ que recebe +x+ e +y+ como parâmetros adicionais e que são atribuídos aos campos correspondentes.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Ao definir métodos operadores, você pode especificar o comportamento de operadores em tipos definidos pelo programador. Por exemplo, se você define um método chamado +pass:[+]+ com dois argumentos +M
```suggestion
Ao definir os métodos operadores, você pode especificar o comportamento dos operadores em tipos definidos pelo programador. Por exemplo, ao definir um método chamado +pass:[+]+ com dois argumentos +MeuTempo+, você pode usar o operador +pass:[+]+ em objetos +MeuTempo+.
```
Sugestão para diminuir a repetição de "você".

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +    inttotempo(segundos)
Atenção na tradução no código da linha 347 e 348.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Quando você aplica o operador +pass:[+]+ a objetos +MeuTempo+, o Julia invoca o novo método adicionado. Quando o REPL mostra o resultado, o Julia invoca +show+. Então muita coisa acontece por trás da
```suggestion
Quando você aplica o operador +pass:[+]+ aos objetos +MeuTempo+, o Julia invoca o novo método adicionado. Quando o REPL mostra o resultado, o Julia invoca +show+. Então muita coisa acontece por trás das cortinas!
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Na secção anterior nós adicionamos dois objetos +MeuTempo+, mas você também pode adicionar um inteiro ao objeto +MeuTempo+:
```suggestion
Na seção anterior, nós adicionamos dois objetos +MeuTempo+, mas você também pode adicionar um inteiro ao objeto +MeuTempo+:
```
A palavra secção está correta, mas ela é usada no português de Portugal.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Adição é um operador comutativo, então temos que adicionar outro método.
```suggestion
Adição é um operador comutativo, por isso temos que adicionar outro método.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +A escolha de qual método executar quando a função é aplicada é chamado de _despacho_. O Julia permite que o processo de despacho escolha qual método de uma função chamar baseada no número de argument
```suggestion
A escolha de qual método executar quando a função é aplicada é chamada de _despacho_. O Julia permite que o processo de despacho escolha qual método de uma função chamar baseado no número de argumentos dados, e nos tipos de todos os argumentos da função. Usar todos os argumentos de uma função para escolher qual método deve ser invocado é conhecido como _despacho múltiplo_.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +* Se ambos operandos são objetos ponto, o método deve retornar um novo objeto ponto cuja coordenada +x+ é a soma das coordenadas +x+ dos operandos, e da mesma forma para as coordenadas +y+.
```suggestion
* Se ambos operandos são objetos ponto, o método deve retornar um novo objeto ponto cuja coordenada +x+ é a soma das coordenadas +x+ dos operandos, e proceder da mesma forma para as coordenadas +y+.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O despacho múltiplo é útil quando é necessáriO, mas (felizmente) ele não é sempre necesário. Muitas vezes você pode evitá-lo escrevendo funções que funcionam corretamente para argumentos com tipos di
```suggestion
O despacho múltiplo é útil quando é necessário, apesar de (felizmente) ele não ser sempre necessário. Muitas vezes você pode evitá-lo escrevendo funções que funcionam corretamente para os argumentos com tipos diferentes.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Muitas das funções que nós escrevemos para string também funcionam para outros tipos de sequência. Por exemplo, em <<dictionary_collection_counters>> nós usamos +histograma+ para contar o número de v
```suggestion
Muitas das funções que nós escrevemos para as strings também funcionam para os outros tipos de sequência. Por exemplo, em <<dictionary_collection_counters>> nós usamos +histograma+ para contar o número de vezes de cada letra que aparece em uma palavra.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Esta função também funciona para listas, tuplas, e até mesmo dicionários, contanto que para os elementos de +s+ exista uma função hash, então eles podem ser usados como chaves em +d+.
```suggestion
Esta função também funciona para as listas, as tuplas, e até mesmo os dicionários, contanto que para os elementos de +s+ exista uma função hash, para que eles possam ser usados como chaves em +d+.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +(((polymórfica)))
```suggestion
(((polymórfico)))
```
Como o gênero não é claro pq não sei o q eu toh fazendo atribuição, eu deixo a sugestão de colocar no masculino.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Por exemplo, a função embutida +sum+, que soma elementos de uma sequência, funciona contanto que os elementos da sequência suportam adição.
```suggestion
Por exemplo, a função embutida +sum+, que soma os elementos de uma sequência, funciona contanto que os elementos da sequência possam realizar a adição.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Já que um método +pass:[+]+ é fornecido para objetos +MeuTempo+, eles funcionam com +sum+:
```suggestion
Já que um método +pass:[+]+ é fornecido para os objetos +MeuTempo+, eles funcionam com +sum+:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
>  === Debugging
```suggestion
=== Depuração
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O melhor tipo de Polimorfismo é o tipo não intencional, no qual você descobre que uma função já escrita por você pode ser aplicada a um tipo que você nunca planejou.
```suggestion
O melhor tipo de polimorfismo é o tipo não intencional, no qual se descobre que uma função que você escreveu pode ser aplicada a um tipo que você nunca planejou.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um dos objetivos do despacho múltiplo é facilitar a manutenção de software, o que significa que você pode manter o programa funcionando quando outras partes do sistema mudam, e modificam o programa p
```suggestion
Um dos objetivos do despacho múltiplo é facilitar a manutenção do software, o que significa que você pode manter o programa funcionando quando as outras partes do sistema mudam, e modificar o programa para cumprir novos requisitos.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um princípio de design que ajuda a alcançar esse objetivo é manter as interfaces separadas da implementação. Isto significa que métodos que possuem argumentos denotados com um tipo não devem depender
```suggestion
Um princípio de design que ajuda alcançar esse objetivo é manter as interfaces separadas das implementações. Isto significa que os métodos que possuem os argumentos denotados com um tipo não devem depender de como os campos daquele tipo são representados.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Por exemplo, neste capítulo nós desenvolvemos uma struct que representa o tempo do dia. Métodos que possuem argumentos denotados com este tipo incluem +tempo_para_int+, +é_depois+ e +pass:[+]+.
```suggestion
Por exemplo, neste capítulo nós desenvolvemos uma struct que representa um horário do dia. Métodos que possuem argumentos indicados com este tipo incluem +tempo_para_int+, +é_depois+ e +pass:[+]+.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Como uma alternativa, nós poderiamos substituir estes campos com um único inteiro representando o número de segundos desde a meia-noite. Esta implementação faria com que algumas funções, como +é_depo
```suggestion
Como uma alternativa, nós poderiamos substituir estes campos com um único inteiro representando o número de segundos a partir da meia-noite. Esta implementação faria com que algumas funções, como +é_depois, sejam mais facéis de escrever, mas também faz com que outras funções sejam mais dificéis.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Depois você configurar um novo tipo, você pode descobrir uma implementação melhor. Se outras partes do programas estão usando o seu tipo, pode ser que mudar a interface consuma muito tempo e esteja s
```suggestion
Depois de configurar um novo tipo, você pode descobrir uma implementação melhor. Se outras partes do programas estão usando o seu tipo, pode ser que mudar a interface consuma muito tempo e esteja sujeita a erros.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +(((metódos)))(((debugging)))
```suggestion
(((methods)))(((depuração)))
```
Eu acho q neste caso o autor está falando da função methods. O q vc acha?

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Chamar uma função com os argumentos corretos pode ser difícil quando mais de um método para um função é específicada. O Julia permite examinar as assinaturas dos métodos de uma função.
```suggestion
Chamar uma função com os argumentos corretos pode ser difícil quando mais de um método para a função é específicada. O Julia permite examinar as assinaturas dos métodos de uma função.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Para saber quais métodos estão disponíveis para uma dada função, você pode usar a função +methods+:
```suggestion
Para saber quais os métodos disponíveis para uma dada função, você pode usar a função +methods+:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Neste exemplo, a função +imprime_tempo+ tem 2 métodos: um com argumento +MeuTempo+ e um com argumento +Any+.
```suggestion
Neste exemplo, a função +imprime_tempo+ tem 2 métodos: um com o argumento +MeuTempo+ e um com o argumento +Any+.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O número e tipo de argumentos de um método permitindo o despacho à escolher o método mais específico de uma função durante uma chamada de função.
```suggestion
O número e tipo dos argumentos de um método permitindo o despacho escolher o método mais específico de uma função durante uma chamada da função.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um construtor definido fora da definição de tipo para definir métodos de conveniência para criar um objeto.
```suggestion
Um construtor definido fora da definição de tipo para indicar os métodos convenientes para a criação de um objeto.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um construtor definido dentro da definição de tipo para impor invariantes ou para construir objetos que referem-se a si mesmos.
```suggestion
Um construtor definido dentro da definição de tipo para impor as invariantes ou para construir os objetos que referem a si mesmos.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Mude os campos de +MeuTempo+ para que exista apenas um único campo representando os segundos passados desde a meia-noite. Em seguida modifique os métodos definidos neste capítulo para funcionar com a
```suggestion
Mude os campos de +MeuTempo+ para ter apenas um único campo representando os segundos passados após a meia-noite. Em seguida modifique os métodos definidos neste capítulo para funcionar com a nova implementação.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Reescreva +tempo_para_int+ e +int_para_tempo+ (de <<prototyping_versus_planning>>) para especificar seus argumentos.
```suggestion
Reescreva +tempo_para_int+ e +int_para_tempo+ (de <<prototyping_versus_planning>>) para especificar os seus argumentos.
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
>  [[chap17]]
Por gentileza, averiguar como vai ficar a tradução do "MyTime", do "printtime", do "timetoint" e do "inttotime", entre outros objetos/funções/métodos do cap 16.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Estas expressões são definições de método válidas em Julia. Esta é uma notação mais enxuta para definir funções/métodos.
```suggestion
Estas expressões são definições de método válidas em Julia. E é uma notação mais enxuta para definir funções/métodos.
```
Sugestão para melhorar a fluidez da leitura.

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Para impor invariantes, nós precisamos de métodos _construtores internos_:
```suggestion
Para impor as invariantes, nós precisamos de métodos _construtores internos_:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Escreva métodos +pass:[+]+ para objetos ponto:
```suggestion
Escreva métodos +pass:[+]+ para os objetos ponto:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Mas se você tivesse projetado a interface com cuidado, você pode mudar a implementação sem mudar a interface, o que significa que outras partes do programa não precisam mudar.
```suggestion
Mas se você tivesse projetado a interface com cuidado, pode-se mudar a implementação sem mudar a interface, o que significa que outras partes do programa não precisam ser alteradas.
```
A sugestão foi dada só para tirar repetição de "mudar".

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Escreva uma definição para um tipo chamado +Canguru+ com um campo chamado +conteúdo_bolso+ de tipo +Array+ e os seguintes métodos:
```suggestion
Escreva uma definição para um tipo chamado +Canguru+ com um campo chamado +conteúdo_bolso+ do tipo +Array+ e os seguintes métodos:
```

2020-07-06 01:44 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +* Um construtor que inicializa +conteúdo_bolso+ para uma lista vazia.
```suggestion
* Um construtor que inicializa +conteúdo_bolso+ com uma lista vazia.
```

2020-07-06 15:20 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +No Julia você tem a habilidade de escrever código que opera em tipos diferentes. Isto é chamado de programação genérica.
Tem razão, mas será que não fica melhor então:
```suggestion
No Julia você tem a habilidade de escrever código que opera em tipos diferentes. Esta habilidade é chamada de programação genérica.
```

2020-07-06 15:33 UTC, joaoluisro commented on book/src/chap17.asciidoc
>  [[chap17]]
"MyTime" -> "MeuHorário"
"printtime" -> "imprima_horário"
"timetoint" -> "horário_para_int"
"inttotime" -> "int_para_horário"
Isso é o que eu vou usar, pode mudar com a revisão do cap 16.

2020-07-06 15:33 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +Se você colocar os argumentos na ordem errada, você recebe um erro:
na minha opinião fica melhor "você recebe", entendo que é pra evitar a repetição do "você", mas mesmo assim prefiro a tradução anterior. Algo que talvez funcione também é
```suggestion
Se você colocar os argumentos na ordem errada, um erro é gerado:
```
que acredito que satisfaça ambos os lados

2020-07-06 15:54 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +Neste capítulo irei discutir o uso de declarações de tipos em Julia, e também introduzirei métodos que são maneiras de implementar comportamentos diferentes para uma função dependendo dos tipos de se
```suggestion
Neste capítulo irei discutir o uso de declarações de tipos em Julia, e também introduzirei métodos que implementam comportamentos diferentes para uma função dependendo dos tipos de seus argumentos. Isto é chamado de despacho múltiplo.
```
Acho que isso simplifica um pouco as coisas, o que você acha?

2020-07-07 03:26 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +No Julia você tem a habilidade de escrever código que opera em tipos diferentes. Isto é chamado de programação genérica.
A aprovo essa 2a sugestão que vc deu:
```suggestion
No Julia você tem a habilidade de escrever código que opera em tipos diferentes. Esta habilidade é chamada de programação genérica.
```

2020-07-10 03:37 UTC, chunggnuhc requested changes

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Neste capítulo irei discutir o uso de declarações de tipos em Julia, e também introduzirei métodos que são maneiras de implementar comportamentos diferentes para uma função dependendo dos tipos de se
```suggestion
Neste capítulo, irei discutir o uso de declarações de tipo em Julia, e também introduzirei métodos que implementam os comportamentos diferentes para uma função, dependendo dos tipos de seus argumentos. Isto é chamado de despacho múltiplo.
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Se você colocar os argumentos na ordem errada, você recebe um erro:
Eu gosto da opção:
```suggestion
Se você colocar os argumentos na ordem errada, um erro é gerado:
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O operador +::+ também pode ser acrescentado ao lado esquerdo de uma atribuição, ou como uma parte de uma declaração.
```suggestion
O operador +::+ também pode ser acrescentado ao fim do lado esquerdo de uma atribuição, ou como uma parte de uma declaração.
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Quando os tipos são omitidos, o comportamento padrão em Julia é permitir que valores sejam de qualquer tipo (+Any+).
```suggestion
Quando os tipos são omitidos, o comportamento padrão em Julia é permitir que os valores sejam de qualquer tipo (+Any+).
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Para adicionar um _método_ à função +imprima_horário+ que apenas aceita um objeto +MeuHorário+ como argumento, tudo que precisamos fazer é acrescentar +::+ seguido de +MeuHorário+ no argumento +tempo
```suggestion
Para adicionar um _método_ à função +imprima_horário+ que apenas aceita um objeto +MeuHorário+ como argumento, tudo que precisamos fazer é acrescentar +::+ seguido de +MeuHorário+ no final do argumento +tempo+ na definição de função:
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Aqui está uma versão de +incrementa+ (de <<modifiers>>) reescrita para especificar seus argumentos:
O nome da função é **_incrementa_** ou _**incrementar**_?

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +traduz para os seguintes três métodos:
O que vc acha dessa opção? Acho estranho usar "traduz" nos termos da computação, dentro do q eu sei de computação. Mas se vcs da área usam, ignora minha sugestão.
```suggestion
é equivalente para os seguintes três métodos:
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um _construtor_ é uma função especial chamada para criar um objeto. Os métodos construtores padrões de +MeuHorário+ tem a seguinte assinatura:
```suggestion
Um _construtor_ é uma função especial chamada para criar um objeto. Os métodos construtores padrões de +MeuHorário+ têm a seguinte assinatura:
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +        @assert(0 ≤ minuto < 60, "minuto não está entre 0 e 60.")
```suggestion
        @assert(0 ≤ minuto < 60, "Minuto não está entre 0 e 60.")
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +        @assert(0 ≤ segundo < 60, "segundo não está entre 0 e 60.")
```suggestion
        @assert(0 ≤ segundo < 60, "Segundo não está entre 0 e 60.")
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +        @assert(0 ≤ minuto < 60, "minuto está entre 0 e 60.")
```suggestion
        @assert(0 ≤ minuto < 60, "Minuto está entre 0 e 60.")
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +        @assert(0 ≤ segundo < 60, "segundo está entre 0 e 60.")
```suggestion
        @assert(0 ≤ segundo < 60, "Segundo está entre 0 e 60.")
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Isso permite a criação das estruturas de dados recorrentes, isto é, uma struct no qual um dos campos também é uma struct. Neste caso, a struct precisa ser mutável pois seus campos são modificados apó
```suggestion
Isso permite a criação das estruturas de dados recorrentes, isto é, uma struct no qual um dos campos é a própria struct. Neste caso, a struct precisa ser mutável pois seus campos são modificados após serem instanciados.
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Adicionar ao comportamento de um operador para que funcione com tipos definidos pelo programador é chamado de _sobrecarga de operador_.
Vc traduz "operator overloading" para "sobrecarga de operador", mas no título está "Operador de Sobrecarga". Não seria melhor usar a mesma tradução tanto no título (linha 352) e nas linhas 385, 386 e até no glossário?

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +    incrementa(tempo, segundos)
É incrementa ou incrementar?

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +* Se ambos operandos são objetos ponto, o método deve retornar um novo objeto ponto cuja coordenada +x+ é a soma das coordenadas +x+ dos operandos, e proceder da mesma forma para as coordenadas +y+.
```suggestion
* Se ambos operandos são objetos ponto, o método deve retornar um novo objeto ponto cuja coordenada +x+ é a soma das coordenadas +x+ dos operandos, e deve proceder da mesma forma para as coordenadas +y+.
```

2020-07-10 03:37 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Por exemplo, neste capítulo nós desenvolvemos uma struct que representa um horário do dia. Métodos que possuem argumentos indicados com este tipo incluem +horário_para_int+, +é_depois+ e +pass:[+]+.
```suggestion
Por exemplo, neste capítulo nós desenvolvemos uma struct que representa um horário do dia. E os métodos que possuem argumentos indicados com este tipo incluem +horário_para_int+, +é_depois+ e +pass:[+]+.
```

2020-07-11 20:59 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +Aqui está uma versão de +incrementa+ (de <<modifiers>>) reescrita para especificar seus argumentos:
o nome da função é +incrementa+ mesmo, pode haver confusão pois no cap 16 o autor também define +increment!+,
mas como ele se refere a <<modifiers>> a tradução pro cap 16 ficou +incrementa+ mesmo.

2020-07-11 21:00 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +(((incrementar)))
```suggestion
(((incrementa)))
```

2020-07-11 21:00 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +function incrementar(tempo::MeuHorário, segundos::Int64)
```suggestion
function incrementa(tempo::MeuHorário, segundos::Int64)
```

2020-07-11 21:00 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +julia> incrementar(início, 1337)
```suggestion
julia> incrementa(início, 1337)
```

2020-07-11 21:02 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +traduz para os seguintes três métodos:
```suggestion
é equivalente aos seguintes três métodos:
```
concordo, mas não seria mais correto dessa forma?

2020-07-11 21:02 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +    segundos += tempotoint(tempo)
```suggestion
    segundos += tempo_para_int(tempo)
```

2020-07-11 21:03 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +    inttotempo(segundos)
```suggestion
    int_para_tempo(segundos)
```

2020-07-11 21:04 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +=== Operador de Sobrecarga
```suggestion
=== Sobrecarga de Operador
```

2020-07-11 21:05 UTC, joaoluisro commented on book/src/chap17.asciidoc
> +(((polymórfica)))
```suggestion
(((polimórfica)))
```

2020-07-16 23:33 UTC, chunggnuhc requested changes
3rd review

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Neste capítulo, irei discutir o uso de declarações de tipo em Julia, e também introduzirei métodos que implementam os comportamentos diferentes para uma função, dependendo dos tipos de seus argumento
```suggestion
Neste capítulo, discutiremos o uso de declarações de tipo em Julia, e também introduziremos métodos que implementam os comportamentos diferentes para uma função, dependendo dos tipos de seus argumentos. Isto é chamado de despacho múltiplo.
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Você pode invocar incrementar da seguinte maneira:
```suggestion
Você pode invocar incrementa da seguinte maneira:
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +julia> incrementar(1337, início)
```suggestion
julia> incrementa(1337, início)
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +ERROR: MethodError: no method matching incrementar(::Int64, ::MeuHorário)
```suggestion
ERROR: MethodError: no method matching incrementa(::Int64, ::MeuHorário)
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +A assinatura do método é +incrementar(tempo::MeuHorário, segundos::Int64)+ e não +incrementar(segundos::Int64, tempo::MeuHorário)+.
```suggestion
A assinatura do método é +incrementa(tempo::MeuHorário, segundos::Int64)+ e não +incrementa(segundos::Int64, tempo::MeuHorário)+.
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +traduz para os seguintes três métodos:
Vc tá correto... o melhor é:
```suggestion
é equivalente aos seguintes três métodos:
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +[[construtor]]
```suggestion
[[constructor]]
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Nós podemos também adicionar nossos próprios métodos _construtores externos_:
```suggestion
Nós podemos também adicionar os nossos próprios métodos _construtores externos_:
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Um método construtor interno é sempre definido dentro do bloco de uma declaração de tipo e tem acesso a uma função especial chamada +new+ que cria objetos de um novo tipo declarado.
```suggestion
Um método construtor interno é sempre definido dentro do bloco de uma declaração de tipo e tem acesso a uma função especial chamada +new+ que cria os objetos de um novo tipo declarado.
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +Isso permite a criação das estruturas de dados recorrentes, isto é, uma struct no qual um dos campos é a própria struct. Neste caso, a struct precisa ser mutável pois seus campos são modificados após
```suggestion
Isso permite a criação das estruturas de dados recorrentes, isto é, uma struct no qual um dos campos é a própria struct. Neste caso, a struct precisa ser mutável pois os seus campos são modificados após serem instanciados.
```

2020-07-16 23:33 UTC, chunggnuhc commented on book/src/chap17.asciidoc
> +O despacho múltiplo é útil quando é necessário, apesar de (felizmente) ele não ser sempre necessário. Muitas vezes você pode evitá-lo escrevendo funções que funcionam corretamente para os argumentos
```suggestion
O despacho múltiplo é útil quando é necessário, apesar de (felizmente) ele não ser sempre necessário. Muitas vezes você pode evitá-lo escrevendo funções que funcionam corretamente para os argumentos com os tipos diferentes.
```

2020-07-17 14:17 UTC, chunggnuhc approved these changes

2020-07-22 16:57 UTC, abelsiqueira approved these changes

2020-07-22 16:57 UTC, abelsiqueira commented on book/src/chap17.asciidoc
> +Ao definir os métodos operadores, você pode especificar o comportamento dos operadores em tipos definidos pelo programador. Por exemplo, ao definir um método chamado +pass:[+]+ com dois argumentos +M
```suggestion
Ao definir métodos para os operadores, você pode especificar o comportamento dos operadores em tipos definidos pelo programador. Por exemplo, ao definir um método chamado +pass:[+]+ com dois argumentos +MeuHorário+, você pode usar o operador +pass:[+]+ em objetos +MeuHorário+.
```

2020-07-22 16:57 UTC, merged