Chapter 16 - PTBR
JuliaIntro/JuliaIntroBR.jl pull request #30
Opened 2020-06-12 15:30 UTC by gustavosarturi

2020-06-23 21:49 UTC, joaoluisro requested changes
primeira revisão.

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Agora que sabemos como criar novos tipos compostos, o próximo passo é escrever funções que recebem objetos definidos pelo programador como parâmetro e retorna-los como resultados. Neste capítulo apre
```suggestion
Agora que sabemos como criar novos tipos compostos, o próximo passo é escrever funções que recebem objetos definidos pelo programador como parâmetro e retornam estes objetos como resultado. Neste capítulo apresentaremos um “programa funcional” e dois novos planos de desenvolvimento de programa.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((Time)))((("tipo", "Datas", "Time", see="Time")))
```suggestion
(((Time)))((("tipo", "Dates", "Time", see="Time")))
```
Dates é um pacote

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escreva uma função chamada +imprima_hora+ que recebe um objeto +minha_hora+ e imprima-a em forma de +hora:minuto:segundo+. A instrução +@printf+ do módulo StdLib +Printf+ imprime um inteiro com o for
```suggestion
Escreva uma função chamada +imprime_hora+ que recebe um objeto +minha_hora+ e imprima-o em forma de +hora:minuto:segundo+. A instrução +@printf+ do módulo StdLib +Printf+ imprime um inteiro com o formato de sequência `"%02d"` usando pelo menos dois dígitos, incluindo um zero inicial se necessário.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((imprima_hora)))((("função", "definido pelo programador", "imprima_hora", see="imprima_hora")))
```suggestion
(((imprime_hora)))((("função", "definido pelo programador", "imprime_hora", see="imprime_hora")))
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escreva uma função booleana chamada +é_depois+ que recebe dois objetos +minha_hora+, +t1+ e +t2+, e retorna +true+ se +t1+ segue +t2+ cronologicamente e +false+ caso contrário. Desafio: não use um co
```suggestion
Escreva uma função booleana chamada +é_depois+ que recebe dois objetos +minha_hora+, +t1+ e +t2+, e retorna +true+ se +t1+ segue +t2+ cronologicamente e +false+ caso contrário. Desafio: não use uma declaração +if+.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Aqui vai um simples protótipo de +add_tempo+:
```suggestion
Aqui vai um simples protótipo de +soma_tempo+:
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((add_tempo)))((("função", "definido pelo programador", "add_tempo", see="add_tempo")))
```suggestion
(((soma_tempo)))((("função", "definido pelo programador", "soma_tempo", see="soma_tempo")))
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function add_tempo(t1, t2)
```suggestion
function soma_tempo(t1, t2)
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +A função cria um novo objeto +minha_hora+, inicializando os seus campos e retornando uma referência a um novo objeto. Isso é chamado de _função pura_ pois não modifica nenhum dos objetos que são pass
```suggestion
A função cria um novo objeto +minha_hora+, inicializando os seus campos e retornando uma referência ao novo objeto. Isso é chamado de _função pura_ pois não modifica nenhum dos objetos que são passados como argumentos e não tem efeito, como exibir um valor ou obter entrada do usuário, além de retornar um valor.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Para testar essa função, criaremos dois objetos +minha_hora+: +start+ que contém a hora de início de um filme, como _Monthy Python: Em Busca do Cálice Sagrado_, e +duração+ que contém o tempo de exib
```suggestion
Para testar essa função, criaremos dois objetos +minha_hora+: +start+ que contém a hora de início de um filme, como _Monthy Python: Em Busca do Cálice Sagrado_, e +duração+ que contém o tempo de duração do filme, que é de uma hora e 35 minutos.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> ++add_tempo+ descobre quando que o filme irá terminar.
```suggestion
+soma_tempo+ descobre quando o filme irá terminar.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +O resultado, +10:80:00+ talvez não seja o que esperávamos. O problema é que essa função não lida com casos onde o número de segundos ou minutos são adicionados a mais que sessenta. Quando isso ocorre
```suggestion
O resultado, +10:80:00+ talvez não seja o que esperávamos. O problema é que essa função não lida com casos no qual o número de segundos ou minutos ultrapassam sessenta. Quando isso ocorre, temos que "carregar" os segundos extras para a coluna de minutos ou os minutos extras para a coluna de horas. Aqui vai uma versão aprimorada:
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function add_tempo(t1, t2)
```suggestion
function soma_tempo(t1, t2)
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Apesar desta função estar correta, está começando a ficar grande. Iremos ver uma alternativa mais resumida brevemente.
```suggestion
Apesar desta função estar correta, ela está começando a ficar grande. Iremos ver uma alternativa mais resumida em breve.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Em certos momentos, é últil para uma função modificar os objetos que recebe como parâmetros. Neste caso, as mudanção são visíveis a quem chama. Função que funcionam dessa maneiro são ditas _modificad
```suggestion
Em certos momentos, é útil para uma função modificar os objetos que recebe como parâmetros. Neste caso, as mudanção são visíveis para quem a chama. Funções que funcionam dessa maneira são chamadas de _modificadoras_.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> ++incrementa!+, que adiciona um número de segundos dados para um objeto +minha_hora+, pode ser escrito naturalmente como um modificador. Segue abaixo um rascunho:
```suggestion
+incrementa!+, que adiciona um dado número de segundos à um objeto +minha_hora+, pode ser escrito naturalmente como um modificador. Aqui está um rascunho:
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((incrementa)))((("função", "definido pelo programador", "incrementa!", see="incrementa!")))
```suggestion
(((incrementa!)))((("função", "definido pelo programador", "incrementa!", see="incrementa!")))
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escreva uma versão correta de +incremento!+ que não conheça loop algum.
```suggestion
Escreva uma versão correta de +incrementa!+ que não contenha nenhum laço.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Qualquer coisa que pode ser feita com modificadores podem ser feitas com funções puras. De fato, algumas linguagens de progração permite apenas funções puras. Há algumas evidências de que programas q
```suggestion
Qualquer coisa que pode ser feita com modificadores também pode ser feita com funções puras. De fato, algumas linguagens de progração permitem apenas funções puras. Há algumas evidências de que programas que usam funções puras são rápidos para serem desenvolvidas e menos propensos a erros do que programas que usam modificadores. Porém, às vezes modificadores são convenientes e programas funcionais tendem a ser menos eficientes.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Em geral, recomendamos que você escreva funções puras sempre que for razoável e reccorer a modificadores apenas se há uma vantagem atraente. Essa abordagem pode ser chamada de _programa funcional_.
```suggestion
Em geral, recomendamos que você escreva funções puras sempre que for razoável e recorrer a modificadores apenas se há uma vantagem atraente. Essa abordagem pode ser chamada de _estilo de programação funcional_.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((programa funcional)))
```suggestion
(((estilo de programação funcional)))
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escreva uma versão "pura" de +incremento+ que cria e retorna um novo objeto +minha_hora+ em vez de modificar o parâmetro.
```suggestion
Escreva uma versão "pura" de +incrementa+ que cria e retorna um novo objeto +minha_hora+ ao invéz de modificar o parâmetro.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +O plano de desenvolvimento que estamos demonstrando é chamado de "protótipo e correção". Para cada função, escrevemos um protótipo que executa cálculos básicos e depois testamos, fragmentando erros n
```suggestion
O plano de desenvolvimento que estamos demonstrando é chamado de “protótipo e correção”. Para cada função, escrevemos um protótipo que executava os cálculos básicos e depois testavamos-o, corrigindo os erros ao longo do caminho.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((plano de desenvolvumento de programa)))(((protótipo e correção)))
```suggestion
(((plano de desenvolvimento de programa)))(((protótipo e correção)))
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Essa abordagem pode ser efetiva, especialmente quando você ainda não tem um entendimento profundo acerca do problema. Mas correções incrementais podem gerar códigos que por vezes são desnecessariamen
```suggestion
Essa abordagem pode ser efetiva, especialmente quando você ainda não tem um entendimento profundo acerca do problema. Mas correções incrementais podem gerar código que é desnecessariamente complicado, já que ele lida com muitos casos especiais, e também que não é confiável, já que é difícil saber se você encontrou todos os erros.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Uma alternativa é o _desenvolvimento projetado_, em que uma visão de alto nível do problema pode facilitar muito a programação. Neste caso, o insight é que um objeto Time é realmente um número de trê
```suggestion
Uma alternativa é o _desenvolvimento projetado_, em que uma visão de alto nível do problema pode facilitar muito a programação. Neste caso, o insight é que um objeto Time é realmente um número de três dígitos na base 60 (consulte https://pt.wikipedia.org/wiki/Sistema_de_numera%C3%A7%C3%A3o_sexagesimal)! O atributo dos segundos é a “coluna de ums”, o atributo de munutos é a “coluna de sessentas” e o atributo da hora é a “coluna de três mil e seiscentos”.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Quando escrevemos +add_tempo+ e +incremento!+, efetivamente estamos realizando uma adição na base 60, que é justamente o porquê de termos que carregar de uma coluna para outra.
```suggestion
Quando escrevemos +soma_tempo+ e +incrementa!+, efetivamente estavamos realizando uma adição na base 60, que é a razão de termos carregado de uma coluna para a próxima.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Abaixo temos uma função que converte as horas em inteiros.
```suggestion
Abaixo temos uma função que converte um objeto minha_hora para inteiros.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((conversão_inteiro)))((("função", "definido pelo programador", "conversão_inteiro", see="conversão_inteiro")))
```suggestion
(((hora_para_int)))((("função", "definido pelo programador", "hora_para_int", see="hora_para_int")))
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function conversão_inteiro(tempo)
```suggestion
function hora_para_int(tempo)
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Logo baixo temos uma função que converte um inteiro a +minha_hora+ (lembre-se que +divrem+ divide o primeiro argumento pelo segundo e retorna o quociente e o resto como uma tupla):
```suggestion
Aqui temos uma função que converte um inteiro para +minha_hora+ (lembre-se que +divrem+ divide o primeiro argumento pelo segundo e retorna o quociente e o resto como uma tupla):
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((conversão_tempo)))((("função", "definido pelo programador", "conversão_tempo", see="conversão_tempo")))
```suggestion
(((int_para_hora)))((("função", "definido pelo programador", "int_para_hora", see="int_para_hora")))
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function conversão_tempo()
```suggestion
function int_para_hora()
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Talvez você tenha que pensar um pouco e executar alguns testes para se convercer de que essas funções estão corretas. Uma forma de testar é verificar que +conversão_inteiro(conversão_inteiro(x)) == x
```suggestion
Talvez você tenha que pensar um pouco e executar alguns testes para se convencer de que essas funções estão corretas. Uma forma de testar é verificar que +int_para_hora(hora_para_int(x)) == x+ para quaisquer valores de +x+. Esse é um exemplo de verificação de consistência.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Uma vez que você esteja convicto que está correto, você poderar usar-los para reescrever +add_tempo+
```suggestion
Uma vez que você esteja convencido de que elas estão corretas, você poderá usá-las para reescrever +soma_tempo+
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function add_tempo(t1, t2)
```suggestion
function soma_tempo(t1, t2)
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    segundos = conversão_inteiro(t1) + conversão_inteiro(t2)
```suggestion
    segundos = tempo_para_int(t1) + tempo_para_int(t2)
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    conversão_inteiro(segundos)
```suggestion
    tempo_para_int(segundos)
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Reescreva +incremento!+ usando +conversão_inteiro+ e +conversão_tempo+.
```suggestion
Reescreva +incrementa!+ usando +tempo_para_int+ e +int_para_tempo+.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Algumas vezes, converter da base 60 para a base 10 e vice-versa é mais difícil que lidar com tempo. A conversão de base é mais abstracta; nossa intuição por lidar com valores de tempo é melhor.
```suggestion
Algumas vezes, converter da base 60 para a base 10 e vice-versa é mais difícil do que lidar com tempo. A conversão de base é mais abstrata; a nossa intuição para lidar com valores de tempo é melhor.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +No entanto, se tivermos a visão de tratar horas como números de base 60 e investirmos esforço em escrever as funções de conversão (+conversão_inteiro+ e +conversão_tempo+), chegamos a um programa que
```suggestion
Mas se nós tivermos a ideia de tratar horas como número de base 60 e investir na escrita de funções de conversão (+tempo_para_int+ e +int_para_tempo+), nós temos um programa que é menor, mais fácil de ler e depurar, e mais confiável.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Também é mais fácil acrescentar recursos depois. Por exemplo, imagine subtrair dois objetos +minha_hora+ para encontrar a duração entre eles. Uma abordagem ingênua seria implementar a subtração com t
```suggestion
Também é mais fácil acrescentar característica depois. Por exemplo, imagine subtrair dois objetos +minha_hora+ para encontrar a duração entre eles. Uma abordagem ingênua seria implementar a subtração com empréstimo. Porém, usar funções de conversão seria mais fácil e, provavelmente, mais correto.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Ironicamente, tornar um problema mais difícil (ou mais geral) facilita (porque há menos casos especiais e menos oportunidades de erro).
```suggestion
Ironicamente, as vezes tornar um problema mais difícil (ou mais geral) facilita (porque há menos casos especiais e menos oportunidades de erro).
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Requisitos como esses são ditos _invariantes_ porque sempre devem ser verdadeiros. Para dizer de outra forma, se não forem verdadeiros, algo deu errado.
```suggestion
Requisitos como esses são ditos _invariantes_ porque eles sempre devem ser verdadeiros. Para dizer de outra forma, se eles não forem verdadeiros, algo deu errado.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escrever código para verificar requisitos invariantes pode ajudar a descobrir erros e encontrar suas causas. Por exemplo, você pode ter uma função como +hora_válida+, que receba um objeto +minha_hora
```suggestion
Escrever código para verificar requisitos invariantes pode ajudar a descobrir erros e encontrar suas causas. Por exemplo, você pode ter uma função como +hora_válida+, que receba um objeto +minha_hora+ e retorna +false+ se ela violar um requisito invariante:
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function add_tempo(t1,t2)
```suggestion
function soma_tempo(t1,t2)
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +        error("objeto minha_hora inválido em add_tempo")
```suggestion
        error("objeto minha_hora inválido em soma_tempo")
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Ou você pode usar uma instrução +@asset+, que verifica determinado requisito invariável e cria uma exceção se ela falhar:
```suggestion
Ou você pode usar uma instrução +@asset+, que verifica determinado requisito invariável e gera uma exceção se ele falhar:
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((@assert)))((("instrução", "Base", "@assert", see="@assert")))
```suggestion
(((@assert)))((("macro", "Base", "@assert", see="@assert")))
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function add_tempo(t1, t2)
```suggestion
function soma_tempo(t1, t2)
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +instruções +@assert+ são úteis porque distinguem o código que lida com condições normais do código que verifica erros.
```suggestion
Macros +@assert+ são úteis porque distinguem o código que lida com condições normais do código que verifica erros.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Plano de desenvolvimento que implica uma compreensão de alto nível do problema e mais planejamento que desenvolvimento incremental ou desenvolvimento prototipado.
```suggestion
Plano de desenvolvimento que implica uma compreensão de alto nível do problema e mais planejamento do que desenvolvimento incremental ou desenvolvimento prototipado.
```

2020-06-23 21:49 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +O Julia fornece objetos de tempo que são similares aos objetos +minha_hora+ desse capítulo, mas eles fornecem um conjunto rico de funções e operadores. Leia a documentação em https://docs.julialang.o
desalinhado

2020-06-25 13:16 UTC, gustavosarturi commented on book/src/chap16.asciidoc
> +O Julia fornece objetos de tempo que são similares aos objetos +minha_hora+ desse capítulo, mas eles fornecem um conjunto rico de funções e operadores. Leia a documentação em https://docs.julialang.o
@joaoluisro - Apenas no Github. A numeração tá correta.

2020-06-25 13:16 UTC, gustavosarturi commented on book/src/chap16.asciidoc
> +O Julia fornece objetos de tempo que são similares aos objetos +minha_hora+ desse capítulo, mas eles fornecem um conjunto rico de funções e operadores. Leia a documentação em https://docs.julialang.o
@joaoluisro - Apenas no github, no código tá correto.

2020-07-02 00:54 UTC, joaoluisro requested changes

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Agora que sabemos como criar novos tipos compostos, o próximo passo é escrever funções que recebem objetos definidos pelo programador como parâmetro e retornam estes objetos como resultado. Neste cap
```suggestion
Agora que sabemos como criar novos tipos compostos, o próximo passo é escrever funções que recebem objetos definidos pelo programador como parâmetro e retornam estes objetos como resultado. Neste capítulo apresentaremos um “estilo de programação funcional” e dois novos planos de desenvolvimento de programa.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Como outro exemplo de um tipo composto, definiremos uma +struct+ chamada +minha_hora+ que grava a hora do dia. A definição de estrutura se parece como:
```suggestion
Como outro exemplo de um tipo composto, definiremos uma +struct+ chamada +minha_hora+ que grava a hora do dia. A definição da estrutura se parece como:
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Nas próximas seções, escreveremos duas funções que adicionam valores de tempo. Elas demonstrarão dois tipos de funções: funções puras e modificadas. Elas também demonstrarão um plano de desenvolvimen
```suggestion
Nas próximas seções, escreveremos duas funções que adicionam valores de tempo. Elas demonstrarão dois tipos de funções: funções puras e modificadoras. Elas também demonstrarão um plano de desenvolvimento que chamaremos de _protótipo e correção_, que é uma forma de combater um problema complexo começando com um protótipo simples e aos poucos lidar com as complicações.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Apesar desta função estar correta, ela está começando a ficar grande. Iremos ver uma alternativa mais resumida em breve.
```suggestion
Apesar desta função estar correta, ela está começando a ficar grande. Veremos uma alternativa mais concisa em breve.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Neste caso, não basta carregar uma vez; temos que continuar a fazer isso até que +tempo.segundo+ seja menor que 60. Uma solução é substituir os comandos +if+ com os comandos +while+. O que fará com q
```suggestion
Neste caso, não basta carregar uma vez; temos que continuar a fazer isso até que +tempo.segundo+ seja menor que 60. Uma solução é substituir as declarações +if+ com as declarações +while+. O que fará com que a função fique correta, porém, não muito eficiente.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Qualquer coisa que pode ser feita com modificadores também pode ser feita com funções puras. De fato, algumas linguagens de progração permitem apenas funções puras. Há algumas evidências de que progr
```suggestion
Qualquer coisa que pode ser feita com modificadores também pode ser feita com funções puras. De fato, algumas linguagens de programação permitem apenas funções puras. Há algumas evidências de que programas que usam funções puras são mais rápidos para serem desenvolvidos e menos propensos a erros do que programas que usam modificadores. Porém, às vezes modificadores são convenientes e programas funcionais tendem a ser menos eficientes.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escreva uma versão "pura" de +incrementa+ que cria e retorna um novo objeto +minha_hora+ ao invéz de modificar o parâmetro.
```suggestion
Escreva uma versão “pura” de +incrementa+ que cria e retorna um novo objeto +minha_hora+ ao invéz de modificar o parâmetro.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Uma alternativa é o _desenvolvimento projetado_, em que uma visão de alto nível do problema pode facilitar muito a programação. Neste caso, o insight é que um objeto Time é realmente um número de trê
```suggestion
Uma alternativa é o _desenvolvimento projetado_, no qual obter uma visão de alto nível do problema pode facilitar muito a programação. Neste caso, podemos perceber que um objeto Time é na verdade um número de três dígitos na base 60 (consulte https://pt.wikipedia.org/wiki/Sistema_de_numera%C3%A7%C3%A3o_sexagesimal)! O atributo dos segundos é a “coluna de ums”, o atributo de munutos é a “coluna de sessentas” e o atributo da hora é a “coluna de três mil e seiscentos”.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Essa observação nos sugerem uma outra abordagem de todo o problema—podemos converter objetos +minha_hora+ para inteiros e obter uma vantagem do fato de que o computador sabe como realizar artimética
```suggestion
Essa observação nos sugere uma outra abordagem para todo o problema—podemos converter objetos +minha_hora+ para inteiros e obter uma vantagem do fato de que o computador sabe como realizar artimética inteira.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    segundos = tempo_para_int(t1) + tempo_para_int(t2)
```suggestion
    segundos = hora_para_int(t1) + hora_para_int(t2)
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    tempo_para_int(segundos)
```suggestion
    int_para_hora(segundos)
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Reescreva +incrementa!+ usando +tempo_para_int+ e +int_para_tempo+.
decidir entre tempo_para_int int_para_tempo e hora_para_int e int_para_hora

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((add_tempo)))(((error)))
```suggestion
(((soma_tempo)))(((error)))
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    segundos = conversão_inteiro(t1) + conversão_inteiro(t2)
```suggestion
    segundos = hora_para_int(t1) + hora_para_int(t2)
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    conversão_tempo(segundos)
```suggestion
   int_para_hora(segundos)
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    segundos = conversão_inteiro(t1) + conversão_inteiro(t2)
```suggestion
    segundos =hora_para_int(t1) + hora_para_int(t2)
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    conversão_tempo(segundos)
```suggestion
    int_para_tempo(segundos)
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Então use +multime+ para escrever uma função que receba um objeto +minha_hora+ representando o tempo até o fim de uma corrida e um número que represente a distância e retorne um objeto +minha_hora+ c
```suggestion
Em seguida use +mul_hora+ para escrever uma função que receba um objeto +minha_hora+ representando o tempo até o fim de uma corrida e um número que represente a distância e retorne um objeto +minha_hora+ com o ritmo médio (tempo por quilômetro).
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +. Para duas pessoas nascidas em dias diferentes, há um dia em que uma tem o dobro da idade da outra. Esse é o dia duplo deles. Escreva um programa que faça dois aniversários e calcule o dia duplo.
```suggestion
. Para duas pessoas nascidas em dias diferentes, há um dia em que uma tem o dobro da idade da outra. Esse é o dia duplo deles. Escreva um programa que receba dois aniversários e calcule o dia duplo.
```

2020-07-02 00:54 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +. Para lhe desafiar um pouco, escreva a versão mais geral que calcula o dia em que uma pessoa está com latexmath:[\(n\)] vezes mais antiga que a outra.
```suggestion
. Para lhe desafiar um pouco, escreva a versão mais geral que calcula o dia em que uma pessoa é latexmath:[\(n\)] vezes mais velha que a outra.
```

2020-07-02 20:00 UTC, gustavosarturi commented on book/src/chap16.asciidoc
> +Reescreva +incrementa!+ usando +tempo_para_int+ e +int_para_tempo+.
Foi uma alteração sua. Vou ter que rever com cuidado pra ver o que, que é o que.

2020-07-03 17:52 UTC, abelsiqueira commented on book/src/chap16.asciidoc
> +O Julia fornece objetos de tempo que são similares aos objetos +minha_hora+ desse capítulo, mas eles fornecem um conjunto rico de funções e operadores. Leia a documentação em https://docs.julialang.o
Falta um espaço na última linha que quebra aqui

2020-07-06 15:18 UTC, joaoluisro requested changes

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Como outro exemplo de um tipo composto, definiremos uma +struct+ chamada +minha_hora+ que grava a hora do dia. A definição da estrutura se parece como:
```suggestion
Como outro exemplo de um tipo composto, definiremos uma +struct+ chamada +MeuHorário+ que guarda o horário do dia. A definição da estrutura se parece como:
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((minha_hora)))((("tipo", "definido pelo programador", "minha_hora", see="minha_hora")))
```suggestion
(((MeuHorário)))((("tipo", "definido pelo programador", "MeuHorário", see="MeuHorário")))
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Representa a hora do dia.
```suggestion
Representa o horário do dia.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +struct minha_hora
```suggestion
struct MeuHorário
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +O nome +Time+ já é utilizado no Julia e para evitar um conflito de nomes, escolhemos +minha_hora+. Podemos criar um novo objeto +minha_hora_:
```suggestion
O nome +Time+ já é utilizado no Julia e para evitar um conflito de nomes, escolhemos +MeuHorário+. Podemos criar um novo objeto +MeuHorário+:
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +julia> time = minha_hora(11, 59, 30)
```suggestion
julia> time = MeuHorário(11, 59, 30)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +minha_hora(11, 59, 30)
```suggestion
MeuHorário(11, 59, 30)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +O diagrama de objeto para +minha_hora+ se parece com a <<fig16-1>>.
```suggestion
O diagrama de objeto para +MeuHorário+ se parece com a <<fig16-1>>.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escreva uma função chamada +imprime_hora+ que recebe um objeto +minha_hora+ e imprima-o em forma de +hora:minuto:segundo+. A instrução +@printf+ do módulo StdLib +Printf+ imprime um inteiro com o for
```suggestion
Escreva uma função chamada +imprime_horário+ que recebe um objeto +MeuHorário+ e imprima-o em forma de +hora:minuto:segundo+. A instrução +@printf+ do módulo StdLib +Printf+ imprime um inteiro com o formato de sequência `"%02d"` usando pelo menos dois dígitos, incluindo um zero inicial se necessário.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((imprime_hora)))((("função", "definido pelo programador", "imprime_hora", see="imprime_hora")))
```suggestion
(((imprime_horário)))((("função", "definido pelo programador", "imprime_horário", see="imprime_horário")))
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escreva uma função booleana chamada +é_depois+ que recebe dois objetos +minha_hora+, +t1+ e +t2+, e retorna +true+ se +t1+ segue +t2+ cronologicamente e +false+ caso contrário. Desafio: não use uma d
```suggestion
Escreva uma função booleana chamada +é_depois+ que recebe dois objetos +MeuHorário+, +t1+ e +t2+, e retorna +true+ se +t1+ segue +t2+ cronologicamente e +false+ caso contrário. Desafio: não use uma declaração +if+.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    minha_hora(t1.hora + t2.hora, t1.minuto + t2.minuto, t1.segundo + t2.segundo)
```suggestion
    MeuHorário(t1.hora + t2.hora, t1.minuto + t2.minuto, t1.segundo + t2.segundo)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +A função cria um novo objeto +minha_hora+, inicializando os seus campos e retornando uma referência ao novo objeto. Isso é chamado de _função pura_ pois não modifica nenhum dos objetos que são passad
```suggestion
A função cria um novo objeto +MeuHorário+, inicializando os seus campos e retornando uma referência ao novo objeto. Isso é chamado de _função pura_ pois não modifica nenhum dos objetos que são passados como argumentos e não tem efeito, como exibir um valor ou obter entrada do usuário, além de retornar um valor.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Para testar essa função, criaremos dois objetos +minha_hora+: +start+ que contém a hora de início de um filme, como _Monthy Python: Em Busca do Cálice Sagrado_, e +duração+ que contém o tempo de dura
```suggestion
Para testar essa função, criaremos dois objetos +MeuHorário+: +início+ que contém a hora de início de um filme, como _Monthy Python: Em Busca do Cálice Sagrado_, e +duração+ que contém o tempo de duração do filme, que é de uma hora e 35 minutos.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function imprima_hora(tempo::minha_hora)
```suggestion
function imprima_horário(tempo::MeuHorário)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +julia> início = minha_hora(9, 45, 0);
```suggestion
julia> início = MeuHorário(9, 45, 0);
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +julia> duração = minha_hora(1, 35, 0);
```suggestion
julia> duração = MeuHorário(1, 35, 0);
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +julia> fim = add_tempo(início, duração);
```suggestion
julia> fim = soma_horário(início, duração);
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +julia> imprima_hora(fim)
```suggestion
julia> imprima_horário(fim)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +O resultado, +10:80:00+ talvez não seja o que esperávamos. O problema é que essa função não lida com casos no qual o número de segundos ou minutos ultrapassam sessenta. Quando isso ocorre, temos que
```suggestion
O resultado, +10:80:00+ talvez não seja o que esperávamos. O problema é que essa função não lida com casos no qual o número de segundos ou minutos ultrapassam sessenta. Quando isso ocorre, temos que “carregar” os segundos extras para a coluna de minutos ou os minutos extras para a coluna de horas. Aqui vai uma versão aprimorada:
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    minha_hora(hora, minuto, segundo)
```suggestion
    MeuHorário(hora, minuto, segundo)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Neste caso, não basta carregar uma vez; temos que continuar a fazer isso até que +tempo.segundo+ seja menor que 60. Uma solução é substituir as declarações +if+ com as declarações +while+. O que fará
```suggestion
Neste caso, não basta carregar uma vez; temos que continuar a fazer isso até que +tempo.segundo+ seja menor que 60. Uma solução é substituir as declarações +if+ por declarações +while+. O que fará com que a função fique correta, porém, não muito eficiente.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function soma_tempo(t1, t2)
```suggestion
function soma_horário(t1, t2)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Aqui vai um simples protótipo de +soma_tempo+:
```suggestion
Aqui vai um simples protótipo de +soma_horário+:
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((soma_tempo)))((("função", "definido pelo programador", "soma_tempo", see="soma_tempo")))
```suggestion
(((soma_horário)))((("função", "definido pelo programador", "soma_horário", see="soma_horário")))
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> ++soma_tempo+ descobre quando o filme irá terminar.
```suggestion
+soma_horário+ descobre quando o filme irá terminar.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function soma_tempo(t1, t2)
```suggestion
function soma_horário(t1, t2)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Quando escrevemos +soma_tempo+ e +incrementa!+, efetivamente estavamos realizando uma adição na base 60, que é a razão de termos carregado de uma coluna para a próxima.
```suggestion
Quando escrevemos +soma_horário+ e +incrementa!+, efetivamente estavamos realizando uma adição na base 60, que é a razão de termos carregado de uma coluna para a próxima.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Uma vez que você esteja convencido de que elas estão corretas, você poderá usá-las para reescrever +soma_tempo+
```suggestion
Uma vez que você esteja convencido de que elas estão corretas, você poderá usá-las para reescrever +soma_horário+
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function soma_tempo(t1, t2)
```suggestion
function soma_horário(t1, t2)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function soma_tempo(t1,t2)
```suggestion
function soma_horário(t1,t2)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +        error("objeto minha_hora inválido em soma_tempo")
```suggestion
        error("objeto MeuHorário inválido em soma_horário")
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Reescreva +incrementa!+ usando +tempo_para_int+ e +int_para_tempo+.
não alterei nada, se alguma coisa foi alterada foi por que eu fiz uma sugestão e você aceitou. O que tem que ser decidido é se duas funções que são chamadas de +timetoint+ e +inttotime+ traduzem pra +tempo_para_int+ e +int_para_tempo+ ou +hora/horario_para_int+ e +int_para_hora/horario+

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +function soma_tempo(t1, t2)
```suggestion
function soma_horário(t1, t2)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Também é mais fácil acrescentar característica depois. Por exemplo, imagine subtrair dois objetos +minha_hora+ para encontrar a duração entre eles. Uma abordagem ingênua seria implementar a subtração
```suggestion
Também é mais fácil acrescentar característica depois. Por exemplo, imagine subtrair dois objetos +MeuHorário+ para encontrar a duração entre eles. Uma abordagem ingênua seria implementar a subtração com empréstimo. Porém, usar funções de conversão seria mais fácil e, provavelmente, mais correto.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Um objeto +minha_hora+ é bem formado se os valores de +minuto+ e +segundo+ estão entre 0 e 60 (incluindo 0 mas não 60) e se +hora+ é positivo. +hora+ e +minuto+ devem ser valores integrais mas talvez
```suggestion
Um objeto +MeuHorário+ é bem formado se os valores de +minuto+ e +segundo+ estão entre 0 e 60 (incluindo 0 mas não 60) e se +hora+ é positivo. +hora+ e +minuto+ devem ser valores integrais mas talvez devessemos permitir que +segundo+ tenha uma parte fracional.
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escrever código para verificar requisitos invariantes pode ajudar a descobrir erros e encontrar suas causas. Por exemplo, você pode ter uma função como +hora_válida+, que receba um objeto +minha_hora
```suggestion
Escrever código para verificar requisitos invariantes pode ajudar a descobrir erros e encontrar suas causas. Por exemplo, você pode ter uma função como +hora_válida+, que receba um objeto +MeuHorário+ e retorna +false+ se ela violar um requisito invariante:
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((soma_tempo)))(((error)))
```suggestion
(((soma_horário)))(((error)))
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    segundos =hora_para_int(t1) + hora_para_int(t2)
```suggestion
    segundos = hora_para_int(t1) + hora_para_int(t2)
```

2020-07-06 15:18 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +    @assert(hora_válida(t1) && hora_válida(t2), "objeto minha_hora inválido em add_tempo")
```suggestion
    @assert(hora_válida(t1) && hora_válida(t2), "objeto MeuHorário inválido em soma_horário")
```

2020-07-06 17:21 UTC, gustavosarturi commented
@joaoluisro - Alterei os nomes das funções, removi o "_". Se for alterar o nome de alguma função, me avisa pra dar um CTRL+F pra não ficar alguma função não alterada despercebida.

2020-07-07 23:40 UTC, joaoluisro requested changes

2020-07-07 23:40 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +julia> time = MeuHorário(11, 59, 30)
```suggestion
julia> horario = MeuHorário(11, 59, 30)
```

2020-07-07 23:40 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +=== Hora
```suggestion
=== Horário
```

2020-07-07 23:40 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Escreva uma função chamada +mulhora+ que pega um objeto +MeuHorário+ e um número, e retorna um novo objeto +MeuHorário+ que contém o produto do +MeuHorário+ original e do número.
```suggestion
Escreva uma função chamada +mult_horário+ que pega um objeto +MeuHorário+ e um número, e retorna um novo objeto +MeuHorário+ que contém o produto do +MeuHorário+ original e do número.
```

2020-07-07 23:40 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +(((mulhora)))((("função", "definido pelo programador", "mulhora", see="mulhora")))
```suggestion
(((mult_horário)))((("função", "definido pelo programador", "mult_horário", see="mult_horário")))
```

2020-07-07 23:40 UTC, joaoluisro commented on book/src/chap16.asciidoc
> +Em seguida use +mulhora+ para escrever uma função que receba um objeto +MeuHorário+ representando o tempo até o fim de uma corrida e um número que represente a distância e retorne um objeto +MeuHorár
```suggestion
Em seguida use +mult_horário+ para escrever uma função que receba um objeto +MeuHorário+ representando o tempo até o fim de uma corrida e um número que represente a distância e retorne um objeto +MeuHorário+ com o ritmo médio (tempo por quilômetro).
```

2020-07-08 14:40 UTC, joaoluisro approved these changes

2020-07-22 14:43 UTC, abelsiqueira approved these changes

2020-07-22 14:43 UTC, abelsiqueira commented on book/src/chap16.asciidoc
> +Uma alternativa é o _desenvolvimento projetado_, no qual obter uma visão de alto nível do problema pode facilitar muito a programação. Neste caso, podemos perceber que um objeto Time é na verdade um
```suggestion
Uma alternativa é o _desenvolvimento projetado_, no qual obter uma visão de alto nível do problema pode facilitar muito a programação. Neste caso, podemos perceber que um objeto Time é na verdade um número de três dígitos na base 60 (consulte https://pt.wikipedia.org/wiki/Sistema_de_numera%C3%A7%C3%A3o_sexagesimal)! O atributo dos segundos é a “coluna de uns”, o atributo de munutos é a “coluna de sessentas” e o atributo da hora é a “coluna de três mil e seiscentos”.
```

2020-07-22 14:43 UTC, abelsiqueira commented on book/src/chap16.asciidoc
> +Ou você pode usar uma instrução +@asset+, que verifica determinado requisito invariável e gera uma exceção se ele falhar:
```suggestion
Ou você pode usar uma instrução +@assert+, que verifica determinado requisito invariável e gera uma exceção se ele falhar:
```

2020-07-22 14:43 UTC, abelsiqueira commented on book/src/chap16.asciidoc
> +. Para duas pessoas nascidas em dias diferentes, há um dia em que uma tem o dobro da idade da outra. Esse é o dia duplo deles. Escreva um programa que receba dois aniversários e calcule o dia duplo.
```suggestion
. Para duas pessoas nascidas em dias diferentes, há um dia em que uma tem o dobro da idade da outra. Esse é o Dia do Dobro deles. Escreva um programa que receba dois aniversários e calcula o Dia do Dobro.
```

2020-07-22 14:43 UTC, abelsiqueira commented on book/src/chap16.asciidoc
> +. Para lhe desafiar um pouco, escreva a versão mais geral que calcula o dia em que uma pessoa é latexmath:[\(n\)] vezes mais velha que a outra.
```suggestion
. Para lhe desafiar um pouco, escreva a versão mais geral que calcula o dia em que uma pessoa é latexmath:[\(n\)] vezes mais velha que a outra.

```

2020-07-22 14:43 UTC, merged