Chapter 21 - PTBR
JuliaIntro/JuliaIntroBR.jl pull request #32
Opened 2020-06-24 02:08 UTC by chunggnuhc

2020-07-05 22:01 UTC, joaoluisro requested changes
1st review

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Geralmente os erros de sintaxe são fáceis de corrigir depois de você descobrir quais são eles. E infelizmente as mensagens de erro muitas vezes não são úteis. As mensagens mais comuns são +ERROR: Loa
```suggestion
Geralmente os erros de sintaxe são fáceis de corrigir depois de você descobrir quais são eles. E infelizmente as mensagens de erro muitas vezes não são úteis. As mensagens mais comuns são +ERROR: LoadError: syntax: incomplete: premature end of input+ e +ERROR: LoadError: syntax: unexpected "="+, que não são muito informativas.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +. Se você tiver strings de múltiplas linhas com aspas triplas, confira se a string foi finalizada corretamente. Uma string não finalizada pode causar um erro de token inválido no final do seu program
```suggestion
. Se você tiver strings de múltiplas linhas com aspas triplas, confira se a string foi finalizada corretamente. Uma string não finalizada pode causar um erro de token inválido no final do seu programa, ou pode tratar a parte seguinte do programa como uma string até chegar à próxima string. No segundo caso, ela pode não produzir uma mensagem de erro!
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +. Quando não se fecha um operador aberto —+(+, +{+, ou +[+—faz com que o Julia continue com a próxima linha como parte do comando atual. Geralmente, um erro ocorre quase imediatamente na próxima linh
```suggestion
. Um operador de abertura não fechado —+(+, +{+, ou +[+—faz com que o Julia continue com a próxima linha como parte do comando atual. Geralmente, um erro ocorre quase imediatamente na próxima linha.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +* Os erros de sintaxe são descobertos pelo interpretador quando ele está traduzindo o código fonte em código byte. Eles sinalizam que há algo errado com a estrutura do programa. Exemplo: omitir a pal
```suggestion
* Os erros de sintaxe são descobertos pelo interpretador quando ele está traduzindo o código fonte para código byte. Eles sinalizam que há algo errado com a estrutura do programa. Exemplo: omitir a palavra-chave +end+ no final de um bloco de funções gera a mensagem um tanto redundante +ERROR: LoadError: syntax: incomplete: function requires end+.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +* Os erros de tempo de execução são produzidos pelo interpretador se algo der errado durante a execução do programa. A maioria das mensagens de erro de tempo de execução inclui as informações sobre o
```suggestion
* Os erros de tempo de execução são produzidos pelo interpretador se algo der errado durante a execução do programa. A maioria das mensagens de erro de tempo de execução inclui as informações sobre o local da ocorrência do erro e quais as funções que estavam sendo executadas. Exemplo: Uma recursão infinita eventualmente gera o erro de tempo de execução +ERROR: StackOverflowError+.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +* Na maioria das vezes, uma recursão infinita fará com que o programa funcione por um tempo e depois aparecerá uma mensagem de erro +ERROR: LoadError: StackOverflowError+. Se isso acontecer, vá para
```suggestion
* Na maioria das vezes, uma recursão infinita fará com que o programa funcione por um tempo e em seguida gere uma mensagem de erro +ERROR: LoadError: StackOverflowError+. Se isso acontecer, vá para a subseção <<infinite_recursion>> mais adiante.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Se você não estiver recebendo esse erro, mas desconfia que há um problema com um método ou uma função recursiva, ainda assim poderá usar as técnicas de <<infinite_recursion>>.
```suggestion
Se você não estiver recebendo esse erro, mas desconfia que há um problema com um método ou uma função recursiva, você ainda pode usar as técnicas descritas em <<infinite_recursion>>.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Na maioria das vezes, a recursão infinita faz com que o programa funcione por um tempo e depois aparece uma mensagem de erro +ERROR: LoadError: StackOverflowError+.
```suggestion
Na maioria das vezes, a recursão infinita faz com que o programa funcione por um tempo e em seguida gere uma mensagem de erro +ERROR: LoadError: StackOverflowError+.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Uma operação de indexação em um +AbstractDict+ (+Dict+) ou +Set+ como se um objeto tentasse acessar ou apagar um elemento inexistente.
```suggestion
Uma operação de indexação em um objeto do tipo +AbstractDict+ (+Dict+) ou +Set+ tentou acessar ou apagar um elemento inexistente.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Certamente que você deve criar e testar componentes à medida que desenvolve o programa. Então ao encontrar um problema, deve haver apenas uma pequena quantidade de código novo que não se sabe se está
```suggestion
É claro que você deve criar e testar componentes à medida que desenvolve o seu programa. Então ao encontrar um problema, deve haver apenas uma pequena quantidade de código novo que não se sabe se está ou não correto.
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +==== Tenho uma Grande Expressão Bizarra e Não Faz o Que Eu Presumo
```suggestion
==== Tenho uma Grande Expressão Bizarra e Ela Não Faz o Que Eu Espero
```

2020-07-05 22:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +==== Tenho uma Função Que Não Retorna o Que Eu Presumo
```suggestion
==== Tenho uma Função Que Não Retorna o Que Eu Espero
```

2020-07-06 05:09 UTC, chunggnuhc commented on book/src/chap21.asciidoc
> +Uma operação de indexação em um +AbstractDict+ (+Dict+) ou +Set+ como se um objeto tentasse acessar ou apagar um elemento inexistente.
Pode ser assim:
```suggestion
Uma operação de indexação em um objeto do tipo +AbstractDict+ (+Dict+) ou +Set+ como se um objeto tentasse acessar ou apagar um elemento inexistente.
```
No meu entendimento da frase, a partir de "like object...", é como se o autor tivesse dando um exemplo. E a sua sugestão tira essa ideia de exemplo e coloca uma afirmação.

2020-07-06 05:11 UTC, chunggnuhc commented on book/src/chap21.asciidoc
> +. Quando não se fecha um operador aberto —+(+, +{+, ou +[+—faz com que o Julia continue com a próxima linha como parte do comando atual. Geralmente, um erro ocorre quase imediatamente na próxima linh
Pode ser?
```suggestion
. Um operador inicial não fechado —+(+, +{+, ou +[+—faz com que o Julia continue com a próxima linha como parte do comando atual. Geralmente, um erro ocorre quase imediatamente na próxima linha.
```

2020-07-14 21:01 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Uma operação de indexação em um +AbstractDict+ (+Dict+) ou +Set+ como se um objeto tentasse acessar ou apagar um elemento inexistente.
na minha opinião o "like object" se refere a um objeto "quase do tipo",  o meu problema com essa frase é a segunda parte : 
"como se um objeto tentasse acessar ou apagar um elemento inexistente", isso não me parece coerente, já que a frase original é: 
" into an +AbstractDict+ (+Dict+) or +Set+ like object tried to access or delete a non-existent element."
pra mim o autor quis dizer que um uma operação de indexação em um "AbstractDict ou Set like object" tentou acessar ou deletar um elemento não existente, pra descrever o erro que ocorreu.

2020-07-14 21:05 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +. Quando não se fecha um operador aberto —+(+, +{+, ou +[+—faz com que o Julia continue com a próxima linha como parte do comando atual. Geralmente, um erro ocorre quase imediatamente na próxima linh
acho que ai estaria fugindo da tradução. "opening operator" -> "operador inicial" não me parece a melhor opção.

2020-07-17 01:33 UTC, chunggnuhc commented on book/src/chap21.asciidoc
> +. Quando não se fecha um operador aberto —+(+, +{+, ou +[+—faz com que o Julia continue com a próxima linha como parte do comando atual. Geralmente, um erro ocorre quase imediatamente na próxima linh
Blz. Vou usar o termo "operador de abertura não fechado".

2020-07-17 01:36 UTC, chunggnuhc commented on book/src/chap21.asciidoc
> +Quando seu programa estiver sintaticamente correto, o Julia poderá lê-lo e, pelo menos, começar a executá-lo. O que poderia dar errado?
```suggestion
Quando seu programa estiver sintaticamente correto, o Julia poderá lê-lo e, pelo menos, começar a executá-lo. O que poderia dar de errado?
```

2020-07-17 01:48 UTC, chunggnuhc commented on book/src/chap21.asciidoc
> +Uma operação de indexação em um +AbstractDict+ (+Dict+) ou +Set+ como se um objeto tentasse acessar ou apagar um elemento inexistente.
Entendi seu ponto de vista. Aceitei a tua sugestão.

2020-07-17 01:50 UTC, chunggnuhc commented on book/src/chap21.asciidoc
> +Para simplificar o programa, existem muitas coisas que você pode fazer. Primeiro, reduza o problema no qual o programa está trabalhando. Por exemplo, se você estiver fazendo uma busca em uma lista, b
```suggestion
Para simplificar o programa, existem muitas coisas que se pode fazer. Primeiro, reduza o problema no qual o programa está trabalhando. Por exemplo, se você estiver fazendo uma busca em uma lista, busque em uma pequena lista. No caso do programa receber a entrada do usuário, passe a entrada mais simples que cause o problema.
```

2020-07-17 04:13 UTC, joaoluisro requested changes

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +* Os erros de sintaxe são descobertos pelo interpretador quando ele está traduzindo o código fonte para código byte. Eles sinalizam que há algo errado com a estrutura do programa. Exemplo: omitir a p
```suggestion
* Os erros de sintaxe são descobertos pelo interpretador quando ele está traduzindo o código fonte para código byte. Eles sinalizam que há algo errado com a estrutura do programa. Exemplo: omitir a palavra-chave +end+ no final de um bloco de função gera a mensagem um tanto redundante +ERROR: LoadError: syntax: incomplete: function requires end+.
```
acho que fica melhor pois evita a ambiguidade de "bloco de funções" e "o bloco das funções"

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +. Certifique-se que você tem a palavra-chave +end+ no final de cada comando composto, incluindo os blocos de +for+, +while+, +if+, e +function+.
```suggestion
. Certifique-se que você tem a palavra-chave +end+ no final de cada comando composto, incluindo os blocos +for+, +while+, +if+, e +function+.
```

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +. Assegure-se que quaisquer strings no código estejam entre aspas. Certifique-se de que todas as aspas são "aspas retas", e não as “aspas encaracoladas” (ou “aspas inglesas”).
```suggestion
. Assegure-se que quaisquer strings no código estejam entre aspas correspondentes. Certifique-se de que todas as aspas são "aspas retas", e não as “aspas encaracoladas” (ou “aspas inglesas”).
```
incluindo o termo "matching"

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Esse problema é mais comum quando seu arquivo consiste em funções e classes, mas na verdade não chama uma função para iniciar a execução. Isto pode ser intencional se você planeja importar este módul
```suggestion
Esse problema é mais comum quando seu arquivo consiste de funções e classes, mas não chama uma função para iniciar a execução. Isto pode ser intencional se você planeja importar este módulo apenas para fornecer as classes e as funções.
```

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Agora, quando você executar o programa no modo de depuração, verá o valor das variáveis e a condição em cada iteração do laço. A última vez que o laço for percorrido, a condição deve ser +false+. Se
```suggestion
Agora, quando você executar o programa no modo de depuração, verá o valor das variáveis e a condição a cada iteração do laço. A última vez que o laço for percorrido, a condição deve ser +false+. Se o laço continuar, você poderá ver os valores de +x+ e +y+ e poderá descobrir por que eles não estão sendo atualizados corretamente.
```

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Se existe um caso base mas o programa não parece alcançá-lo, adicione um comando de impressão no começo da função para imprimir os parâmetros. E quando você executar o programa, verá algumas linhas d
```suggestion
Se existe um caso base mas o programa não parece alcançá-lo, adicione um comando de impressão no começo da função para imprimir os parâmetros. E quando você executar o programa, verá algumas linhas de saída toda vez que a função for chamada, e verá também os valores dos parâmetros. Se os parâmetros não se moverem em direção ao caso base, você terá algumas idéias sobre o porquê disso ocorrer.
```
acredito que fica melhor

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Se você não tem certeza de como o fluxo de execução está se movendo pelo seu programa, adicione comandos de impressão no início de cada função com uma mensagem como “inserindo a função foo”, sendo fo
```suggestion
Se você não tem certeza de como o fluxo de execução está se movendo pelo seu programa, adicione comandos de impressão no início de cada função com uma mensagem como “entrando na função foo”, sendo foo o nome da função.
```

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +E quando você executar o programa, eles imprimirão cada função que for chamada.
```suggestion
E quando você executar o programa, um rastro de cada função que for chamada será exibido.
```

2020-07-17 04:13 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Uma chamada de sistema falhou devido a um código errado.
```suggestion
Uma chamada de sistema falhou com um código de erro.
```

2020-07-19 19:21 UTC, joaoluisro requested changes

2020-07-19 19:21 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Para simplificar a saída, você pode remover ou comentar os comandos de impressão que não estão ajudando, ou combiná-las, ou formatar a saída para facilitar a compreensão.
```suggestion
Para simplificar a saída, você pode remover ou comentar os comandos de impressão que não estão ajudando, ou combiná-los, ou formatar a saída para facilitar a compreensão.
```

2020-07-19 19:21 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Para simplificar o programa, existem muitas coisas que se pode fazer. Primeiro, reduza o problema no qual o programa está trabalhando. Por exemplo, se você estiver fazendo uma busca em uma lista, bus
```suggestion
Para simplificar o programa, existem muitas coisas que se pode fazer. Primeiro, reduza o problema no qual o programa está trabalhando. Por exemplo, se você estiver fazendo uma busca em uma lista, busque em uma lista pequena. No caso do programa receber a entrada do usuário, passe a entrada mais simples que cause o problema.
```

2020-07-19 19:21 UTC, joaoluisro commented on book/src/chap21.asciidoc
> +Da mesma forma, reescrever uma parte do código pode te ajudar a encontrar os erros sutis. Se fizer uma mudança que você acha que não deve afetar o programa, e ela afeta, isso pode te dar uma dica.
```suggestion
Da mesma forma, reescrever uma parte do código pode te ajudar a encontrar os erros sutis. Se você fizer uma mudança que você acha que não deve afetar o programa, e ela afeta, isso pode te dar uma dica.
```
Eu entendo que é pra evitar a repetição do "você", mas eu acho que a frase fica estranha. Minha opinião é claro.

2020-07-22 04:15 UTC, joaoluisro approved these changes

2020-07-22 20:34 UTC, abelsiqueira approved these changes

2020-07-22 20:34 UTC, abelsiqueira commented on book/src/chap21.asciidoc
> +Se um programa para e parece não estar fazendo nada, ele está “travando”. Frequentemente isso significa que ele está detido em um laço infinito ou em uma repetição infinita.
```suggestion
Se um programa para e parece não estar fazendo nada, ele está “travado”. Frequentemente isso significa que ele está detido em um laço infinito ou em uma repetição infinita.
```

2020-07-22 20:34 UTC, abelsiqueira commented on book/src/chap21.asciidoc
> +Lembre-se, o objetivo não é apenas fazer o programa funcionar. O objetivo é aprender como fazer o programa funcionar.
```suggestion
Lembre-se, o objetivo não é apenas fazer o programa funcionar. O objetivo é aprender como fazer o programa funcionar.

```

2020-07-22 20:35 UTC, merged