Chapter 19 - PTBR
JuliaIntro/JuliaIntroBR.jl pull request #33
Opened 2020-06-26 16:14 UTC by gustavosarturi

2020-07-16 18:11 UTC, chunggnuhc requested changes
1st review

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Uma das metas deste livro é ensinar o mínimo possível de Julia. Quando havia duas formas de fazer algo, escolhíamos uma e evitavamos mencionar a outra. Ou às vezes, utilizamos a segunda forma como ex
```suggestion
Uma das nossas metas para este livro é ensinar o mínimo possível de Julia. Quando havia duas formas de fazer algo, escolhíamos uma e evitávamos mencionar a outra. Ou às vezes, propúnhamos a segunda forma como exercício.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Agora queremos retornar a algumas coisas boas que ficaram pra trás. O Julia oferece uma variadade de recursos que não são realmente necessários – você pode escrever um bom código sem eles – mas com e
```suggestion
Agora queremos retornar a algumas coisas boas que ficaram pra trás. O Julia oferece uma variadade de recursos que não são realmente necessários—você pode escrever um bom código sem eles—mas com eles pode-se escrever um código mais conciso, legível ou eficiente e, às vezes, todos os três.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Neste capítulo e no próximo, iremos discutir coisas que deixamos para trás nos capítulos anteriores:
```suggestion
Neste e no próximo capítulo, iremos discutir coisas dos capítulos anteriores que deixamos para trás:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Podemos nomear os componentes de uma tupla, criando uma tupla nomeada.
```suggestion
Você pode nomear os componentes de uma tupla, criando uma tupla nomeada.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Com tuplas nomeadas, os campos podem ser acessados por nome usando a sintaxe do ponto +(x.a)+.
```suggestion
Nas tuplas nomeadas, os campos podem ser acessados pelo nome usando a sintaxe do ponto +(x.a)+.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((tuplas nomeadas)))(((sintaxe do ponto)))
```suggestion
(((tupla nomeada)))(((sintaxe do ponto)))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Esses são exemplos de _funções anônimas_. Funções anônimas geralmente são usadas como argumentos para outras funções:
```suggestion
Estes são os exemplos de _funções anônimas_. E elas geralmente são usadas como argumentos para outras funções:
```
Estou usando estes porque é um passado próximo.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((funções anônimas)))(((Plots)))((("módulo", "Plots", see="Plots")))(((plot)))((("função", "Plots", "plot", see="plot")))
```suggestion
(((função anônima)))(((Plots)))((("módulo", "Plots", see="Plots")))(((plot)))((("função", "Plots", "plot", see="plot")))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Uma função no Julia pode ser definida através de uma sintaxe compacta:
```suggestion
Uma função no Julia pode ser definida por uma sintaxe compacta:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
Trocar **_myplot_** para **_meu_plot_** na linha 80, 83 e 84.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +_Argumentos de palavras-chave_ em uma função são especificadas depois de um ponto e vírgula na assinatura, mas pode ser chamado com uma vírgula.
```suggestion
_Argumentos de palavras-chave_ em uma função são especificados depois de um ponto e vírgula na assinatura, apesar de poder ser chamado com uma vírgula.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +=== Fechamentos
```suggestion
==== Fechamentos
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um _fechamento_ é a técnica que permite uma função capturar uma variável definida fora do escopo de chamada de função.
```suggestion
Um _fechamento_ é uma técnica que permite uma função capturar uma variável definida fora do escopo da chamada de função.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Nesse exemplo, a função +foo+ retorna uma função anônima que possui acesso ao argumento +x+ da função +foo+. +bar+ aponta para a função anônima e retorna o valor do argumento de +foo+.
```suggestion
Nesse exemplo, a função +foo+ retorna uma função anônima que possui acesso ao argumento +x+ da função +foo+. A variável +bar+ aponta para a função anônima e retorna o valor do argumento de +foo+.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um _bloco_ é uma forma de agrupar diversos comandos. Um bloco começa com a palavra chave +begin+ e finaliza com +end+.
```suggestion
Um _bloco_ é uma forma de agrupar diversos comandos. Um bloco começa com a palavra chave +begin+ e termina com +end+.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +No <<chap04>> a macro +@svg+ foi introduzida:
```suggestion
No <<chap04>>, a macro +@svg+ foi introduzida:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Neste exemplo, a macro +@svg+ possui um argumento único, i.e. um bloco agrupando 3 chamadas de funções.
```suggestion
Neste exemplo, a macro +@svg+ possui um argumento único, i.e. um bloco que está agrupando 3 chamadas de função.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Em <<reading_and_writing>> tivemos que fechar o arquivo após o término da gravação. Isso pode ser feito automaticamente usando um _bloco do_:
```suggestion
Em <<reading_and_writing>>, tivemos que fechar o arquivo após o término da escrita. Isso pode ser feito automaticamente usando um _bloco do_:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Nesse exemplo, +fout+ é um fluxo de arquivo usado para saída.
```suggestion
Nesse exemplo, +fout+ é um fluxo de arquivo usado para a saída.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +julia> dado = "Aqui está a acácia,\no emblema de nossa terra.\n"
Sugestão para colocar "algo brasileiro":
```suggestion
julia> dado = "O meu nome é Severino, \nnão tenho outro de pia.\n"
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +"Aqui está a acácia,\no emblema de nossa terra.\n"
```suggestion
"O meu nome é Severino, \nnão tenho outro de pia.\n"
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um bloco +do+ pode "capturar" variáveis de seus escopos anexos. Por exemplo, a variável +dado+ no exemplo acima de +open pass:[...] do+ é capturada de outro escopo.
```suggestion
Um bloco +do+ pode “capturar” as variáveis de seus escopos anexos. Por exemplo, a variável +dado+ no exemplo acima de +open pass:[...] do+ é capturada de outro escopo.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((?:)))((("operator", "Base", "?:", see="?:")))((("operador ternário", see="?:")))
```suggestion
(((?:)))((("operador", "Base", "?:", see="?:")))((("operador ternário", see="?:")))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  even
Traduzir a linha 210 e 211.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +A expressão antes de +?+ é uma expressão de condição. Se a condição for +true+, a expressão antes de +:+ é avaliada, caso contrário, a expressão depois de +:+ é avaliada.
```suggestion
A expressão antes de +?+ é uma condição. Se a condição for +true+, a expressão antes de +:+ é avaliada, caso contrário, a expressão depois de +:+ é avaliada.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Os operadores +&&+ e +||+ fazem uma _avaliação de curto-circuito_: O próximo argumento só é avaliado quando é necessário para determinar o valor final.
```suggestion
Os operadores +&&+ e +||+ fazem uma _avaliação de curto-circuito_: o próximo argumento só é avaliado quando é necessário determinar o valor final.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Por exemplo, uma rotira de fatorial por recursão pode ser definida da seguinte maneira:
```suggestion
Por exemplo, uma rotina recursiva do fatorial pode ser definida da seguinte maneira:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +    n >= 0 || error("n deve ser inteiro positivo")
Na matemática, principalmente em otimização, há diferença entre não negativo e positivo. Não negativo inclui o zero e o positivo não inclui.
```suggestion
    n >= 0 || error("n deve ser inteiro não negativo")
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +==== Tarefas (também conhecido Corrotina)
```suggestion
==== Tarefas (também conhecido como Corrotina)
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Uma _tarefa_ é uma estrutura de controle que pode passar pelo controle cooperativo sem retornar. Em Julia, uma tarefa pode ser implementada como uma função tendo como primeiro argumento um objeto de
```suggestion
Uma _tarefa_ é uma estrutura de controle que pode passar pelo controle cooperativamente sem retornar. Em Julia, uma tarefa pode ser implementada como uma função tendo como o primeiro argumento um objeto de canal (+Channel+). Um canal é usado para passar valores de uma função para quem a chamou.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +A sequência de Fibonnaci pode ser gerada usando uma tarefa.
```suggestion
A sequência de Fibonnaci pode ser gerada por uma tarefa.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((tarefa)))(((Canal)))((("tipo", "Base", "Channel", see="Channel")))(((put!)))((("função", "Base", "put!", see="put!")))
```suggestion
(((tarefa)))(((Channel)))((("tipo", "Base", "Channel", see="Channel")))(((put!)))((("função", "Base", "put!", see="put!")))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> ++put+ armazena valores em um objeto de canal e +take!+ lê valores de:
```suggestion
+put+ armazena os valores em um objeto de canal e +take!+ lê os valores dele:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O construtor +Channel+ cria uma tarefa. A função +fib+ é suspendida depois de cada chamada para +put!+ e retorna depois de +take!+. Por questões de performance, muitos valores das sequências são arma
```suggestion
O construtor +Channel+ cria a tarefa. A função +fib+ é suspendida aṕos cada chamada para +put!+ e retorna depois de +take!+. Por questões de performance, diversos valores das sequências são armazenadas temporariamente no objeto de canal durante um ciclo de retomada/suspensão.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um tipo concreto que consiste em bits antigos simples é chamado de _tipo primitivo_. Ao contrário da maioria das linguagens, com Julia, você pode declarar seus próprios tipos primitivos. Os tipos pri
```suggestion
Um tipo concreto que consiste em bits simples e antigos é chamado de _tipo primitivo_. Ao contrário da maioria das linguagens, no Julia, você pode declarar seus próprios tipos primitivos. Os tipos primitivos padrões são definidos da mesma maneira:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O exemplo à seguir cria um tipo primitivo +Byte+ e um construtor:
```suggestion
O exemplo a seguir cria um tipo primitivo +Byte+ e um construtor:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +A função +reinterpret+ é usada para armazenar os bits de um inteiro não assinado com 8 bits (+UInt8+) no bit.
```suggestion
A função +reinterpret+ é usada para armazenar os bits de um inteiro não assinado com 8 bits (+UInt8+) no byte.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((reinterpret)))((("função", "Base", "reinterpret", see="reinterpret")))(((UInt8)))((("Tipo", "Base", "UInt8", see="UInt8")))
```suggestion
(((reinterpret)))((("função", "Base", "reinterpret", see="reinterpret")))(((UInt8)))((("tipo", "Base", "UInt8", see="UInt8")))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O tipo de sistema do Julia é _paramétrico_, o que significa que os tipos podem possuir parâmetros.
```suggestion
O tipo de sistema do Julia é _paramétrico_, significando que os tipos podem possuir parâmetros.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  end
Traduzir **_Point_** para **_Ponto_** na linha 328, 338 e 339.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Isso define um novo tipo paramétrico, +Point{T<:Real}+, segurando duas "coordenadas" de tipo +T+, da qual pode ser qualquer tipo contendo +Real+ como supertipo.
```suggestion
Isso define um novo tipo paramétrico, +Ponto{T<:Real}+, segurando duas "coordenadas" do tipo +T+, da qual pode ser de qualquer tipo desde que tenha +Real+ como supertipo.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Tipos de Parâmetros são introduzidos depois do nome do tipo, cercado por chaves:
```suggestion
Parâmetros do tipo são introduzidos depois do nome do tipo, cercado por chaves:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Além dos tipos compostos, tipos abstratos e tipos primitivos também podem ter um parâmetro de tipo.
```suggestion
Além dos tipos compostos, tipos abstratos e tipos primitivos também podem ter um parâmetro do tipo.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Ter tipos concretos para campos de estrutura é absolutamente recomendado por motivos de desempenho, portanto, é uma boa maneira de tornar o +Point+ rápido e flexível.
```suggestion
Ter tipos concretos nos campos da struct é absolutamente recomendado por motivos de desempenho, portanto essa é uma boa maneira de tornar +Ponto+ rápido e flexível.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +==== Tipo de União
```suggestion
==== União dos Tipos
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um _tipo de união_ é um tipo paramétrico abstrato que pode atuar como qualquer um dos seus tipos de argumento:
```suggestion
Uma _união de tipo_ é um tipo paramétrico abstrato que pode atuar como qualquer um dos tipos do seu argumento:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((tipo união)))(((Union)))((("tipo", "Base", "Union", see="Union")))
```suggestion
(((união de tipo)))(((Union)))((("tipo", "Base", "Union", see="Union")))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Uma união de tipo é na maioria das linguagens de computador uma construção interna para raciocinar sobre tipos. Julia, no entanto, expõe esse recurso a seus usuários porque um código eficiente pode s
```suggestion
Uma união de tipo é na maioria das linguagens de computador uma construção interna para refletir sobre os tipos. O Julia, no entanto, expõe esse recurso aos seus usuários porque um código eficiente pode ser gerado quando a união de tipos possui um pequeno número de tipos. Esse recurso oferece ao programador do Julia uma tremenda flexibilidade para controlar o despacho.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  ----
Traduzir **_isintpoint_** na linha 375, 376 e 379, e traduzir **_Point_** na linha 377

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Qualquer objeto arbitrário de Julia pode ser "chamado". Tais objetos "chamáveis" às vezes são chamados de "funtores".
```suggestion
Qualquer objeto arbitrário de Julia pode ser “chamado”. Tais objetos “chamáveis” às vezes são denominados  _funtores_.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  ----
Verificar as traduções que devem ser feitas da linha 390 a linha 400. Eu sei q dá p traduzir Polynomial, mas não cheguei a olhar com mais atenção.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  ----
Verificar as traduções que devem ser feitas da linha 407 e 408.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  ----
Traduzir **_Point_** da linha 419 até 424, **_implicit_** nas linhas 419 e 423 e **_explicit_** na linha 421.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Construtores internos e externos padrão são gerados para cada +T+:
```suggestion
Construtores internos e externos padrões são gerados para cada +T+:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  ----
Traduzir **_Point_** nas linhas 432, 435 e 438.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Quando +x+ e +y+ possuem tipos diferentes, o seguinte construtor externo pode ser definido:
```suggestion
Quando +x+ e +y+ possuem tipos diferentes, o subsequente construtor externo pode ser definido como:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  Point(x::Real, y::Real) = Point(promote(x,y)...);
```suggestion
Ponto(x::Real, y::Real) = Ponto(promote(x,y)...);
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O Julia tem um sistema para promover argumentos para um tipo comum. Isso não é feito automaticamente, mas pode ser facilmente estendido.
```suggestion
O Julia tem um sistema para promover argumentos para um tipo comum. Isso não é feito automaticamente, mas pode ser facilmente realizado.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um valor pode ser convertido de um tipo para outro:
```suggestion
Um valor pode ser convertido de um tipo para o outro:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  ----
Traduzir **_Point_** na linha 477 até 480.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Os métodos para a função +promote+ normalmente não são definidos diretamente, mas a função auxiliar +promover_rule+ é usada para especificar as regras da promoção:
```suggestion
Em geral, os métodos para a função +promote+ não são diretamente definidos, mas a função auxiliar +promote_rule+ é usada para especificar as regras da promoção:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  (((promote_rule)))((("function", "Base", "promote_rule", see="promote_rule")))
```suggestion
(((promote_rule)))((("função", "Base", "promote_rule", see="promote_rule")))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +=== Meta-programação
```suggestion
=== Metaprogramação
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +A próxima etapa é analisar cada string em um objeto chamado _expression_, representado pelo tipo Julia +Expr+:
```suggestion
A próxima etapa é analisar cada string em um objeto chamado _expression_, representado pelo tipo +Expr+ do Julia:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((expressão)))(((Expr)))((("tipo", "Base", "Expr", see="Expr")))(((parse)))((("função", "Meta", "parse", see="parse")))
```suggestion
(((expression)))(((Expr)))((("tipo", "Base", "Expr", see="Expr")))(((parse)))((("função", "Meta", "parse", see="parse")))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +A função +dump+ exibe objetos expr com anotações.
```suggestion
A função +dump+ detalha os objetos expr.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Expressões podem ser construídas diretamente prefixando +:+ entre parênteses ou usando um bloco de aspas
```suggestion
Expressões podem ser diretamente construídas prefixando +:+ entre parênteses ou usando uma citação em bloco
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Cada módulo possui sua própria função +eval+ que avalia expressões em seu escopo.
```suggestion
Cada módulo possui sua própria função +eval+ que avalia as expressões em seu escopo.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Quando você está usando muitas chamadas para a função +eval+, geralmente isso significa que algo está errado. +eval+ é considerado "mal".
```suggestion
Quando você está usando muitas chamadas para a função +eval+, geralmente isso significa que algo está errado. A função +eval+ é considerado do “mal”.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Macros podem incluir código gerado em um programa. Um _macro_ mapeia uma tupla de objetos +Expr+ diretamente para uma expressão compilada:
```suggestion
Macros podem incluir o código gerado em um programa. Uma _macro_ mapeia uma tupla de objetos +Expr+ diretamente para uma expressão compilada:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +As macros são chamadas com o prefixo +@+ (sinal de arroba). A chamada de macro +@containervariavel letters 1+ é substituída por:
```suggestion
As macros são chamadas ao colocar o prefixo +@+ (sinal de arroba) em seus nomes. A macro chamada +@containervariavel letras 1+ é substituída por:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  :(letters1 = letters[1])
Traduzir **_letters_**.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> ++@macroexpand @containervariavel letters 1+ retorna essa expressão que é extremamente útil para depuração.
```suggestion
+@macroexpand @containervariavel letras 1+ retorna essa expressão que é extremamente útil para a depuração.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Este exemplo ilustra como uma macro pode acessar o nome de seus argumentos, algo que uma função não pode fazer. A expressão de retorno precisa ser "escapada" com +esc+, pois precisa ser resolvida no
```suggestion
Este exemplo ilustra como uma macro pode acessar o nome dos seus argumentos, algo que uma função não pode fazer. O comando return precisa ser “escapada” com +esc+, pois precisa ser resolvida no ambiente da chamada da macro.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +As macros geram e incluem fragmentos de código personalizado durante o tempo de análise, portanto, _antes_ que o programa completo seja executado.
```suggestion
As macros geram e incluem fragmentos de código personalizado durante o tempo de análise, portanto, _antes_ da execução do programa completo.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +A macro +@generated+ cria código especializado para métodos, dependendo dos tipos de argumentos:
```suggestion
A macro +@generated+ cria código especializado para os métodos, dependendo dos tipos de argumentos:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  ----
Traduzir **_square_** na linha 614.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Para o chamador, a função _generated_ se comporta como uma função regular:
```suggestion
Para quem chama, a _função gerada_ se comporta como uma função regular:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +julia> x = square(2); # note: output é da declaração println() no corpo
```suggestion
julia> x = quadrado(2); # nota: output é da declaração println() no corpo
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  julia> y = square("spam");
```suggestion
julia> y = quadrado("spam");
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O tipo de elemento dessa lista é +Union{Missing, T}+, com +T+ o tipo de valores não ausentes.
```suggestion
O tipo de elemento dessa lista é +Union{Missing, T}+, sendo +T+ o tipo de valores não ausentes.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +As funções de redução retornam +missing+ quando chamadas em listas que contêm valores ausentes
```suggestion
As funções de redução retornam +missing+ quando chamadas nas listas que contêm valores ausentes
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Nessa situação, use a função +skipmissing+ para pular os valores ausentes:
```suggestion
Nessa situação, use a função +skipmissing+ para ignorar os valores ausentes:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Muitos códigos estão escritos em C ou Fortran. Reutilizar o código testado geralmente é melhor do que escrever sua própria versão de um algoritmo. Julia pode chamar diretamente as bibliotecas C ou Fo
```suggestion
Muitos códigos estão escritos em C ou Fortran. Reutilizar o código testado geralmente é melhor do que escrever sua própria versão de um algoritmo. Julia pode chamar diretamente as bibliotecas existentes em C ou Fortran usando a sintaxe +ccall+.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Em <<databases>>, introduzimos uma interface Julia na biblioteca GDBM de funções de banco de dados. A biblioteca está escrita em C. Para fechar o banco de dados, uma chamada de função para +close(db)
```suggestion
Em <<databases>>, introduzimos uma interface Julia para a biblioteca GDBM de funções de banco de dados. A biblioteca está escrita em C. Para fechar o banco de dados, uma chamada de função para +close(db)+ teve que ser feita:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um objeto dbm possui um campo +handle+ do tipo +Ptr{Cvoid}+. Este campo contém um ponteiro C que se refere ao banco de dados. Para fechar o banco de dados, a função C +gdbm_close+ deve ser chamada te
```suggestion
Um objeto dbm possui um campo +handle+ do tipo +Ptr{Cvoid}+. Este campo guarda um ponteiro C que se refere ao banco de dados. Para fechar o banco de dados, a função C +gdbm_close+ deve ser chamada tendo como único argumento o ponteiro C apontando para o banco de dados e sem valor de retorno. O Julia faz isso diretamente com a função +ccall+ tendo como argumentos:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +* uma trupla que consiste em um símbolo que contém o nome da função que queremos chamar: +:gdbm_close+ e a biblioteca compartilhada especificada como uma sequência: +"libgdm"+,
```suggestion
* uma tupla que consiste em um símbolo que contém o nome da função que queremos chamar: +:gdbm_close+ e a biblioteca compartilhada especificada como uma string: +"libgdm"+,
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +* uma tupla de tipos de argumentos: +(Ptr{Cvoid},)+ e
```suggestion
* uma tupla com tipos de argumentos: +(Ptr{Cvoid},)+ e
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O mapeamento completo da biblioteca GDBM pode ser encontrada como um exmplo nas fontes do JuliaIntroBR.
```suggestion
O mapeamento completo da biblioteca GDBM pode ser encontrada como um exemplo no repositório do JuliaIntroBR.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +fechamentos::
```suggestion
fechamento::
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Função que captura variáveis de seu escopo definido.
```suggestion
Função que captura as variáveis do seu escopo definido.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +bloqueio let::
Na linha 129, vc traduz **_let block_** como **_bloco let_**. Gostaria de saber se vc vai adotar **_bloco let_** ou **_bloqueio let_** para a tradução de **_let block_**.

Depois de vc se decidir, se necessário, fazer mudança na linha 707 e 708.

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +funções anônimas::
```suggestion
função anônima::
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Função definida sem possuir nome.
```suggestion
Função definida sem ter um nome.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Argumentos identificados pelo nome em vez de apenas pela posição.
```suggestion
Argumentos identificados pelo nome e não só pela posição.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Operador de fluxo de controle usando três operandos para especificar uma condição, uma expressão a ser executada quando a condição render +true+ e uma expressão a ser executada quando a condição rend
```suggestion
Operador de fluxo de controle que usa três operandos para especificar uma condição, uma expressão a ser executada quando a condição produz +true+ e uma expressão a ser executada quando a condição produz +false+.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Avaliação de um operador booleano para o qual o segundo argumento é executado ou avaliado apenas se o primeiro argumento não for suficiente para determinar o valor da expressão.
```suggestion
Avaliação de um operador booleano na qual o segundo argumento é executado ou avaliado apenas se o primeiro argumento não for suficiente para determinar o valor da expressão.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Recurso de fluxo de controle que permite que os cálculos sejam suspensos e retomados de maneira flexível.
```suggestion
Recurso de fluxo de controle que permite a suspensão dos cálculos e a retomada deles de maneira flexível.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Tipo de concreto cujos dados consistem em bits antigos simples.
```suggestion
Tipo concreto cujos dados consistem em bits simples e antigos.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +tipo de união::
```suggestion
união de tipo::
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((tipo de união)))
```suggestion
(((união de tipo)))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Tipo que está parametrizado.
```suggestion
Tipo que é parametrizado.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  (((functor)))
```suggestion
(((funtor)))
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Conversão valores de tipos mistos em um único tipo comum.
```suggestion
Conversão de valores de tipos mistos em um único tipo comum.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Tipo de Julia que contém uma construção de linguagem.
```suggestion
Tipo do Julia que contém uma construção de linguagem.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Forma de incluir o código gerado no corpo final de um programa.
```suggestion
Forma de incluir o código gerado no final do corpo de um programa.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um bloco +let+ é últil para criar novas ligações, i.e. locais que podem se referir a valores.
```suggestion
Um bloco +let+ é útil para criar novas ligações, i.e. locais que podem se referir a valores.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +No exemplo, a primeira macro +@show+, mostra o +x+ local, a global +y+ e a local indefinida +z+. As variáveis globais são intocáveis.
```suggestion
No exemplo, a primeira macro +@show+ mostra o +x+ local, a global +y+ e a local indefinida +z+. As variáveis globais são intocáveis.
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Podemos adicionar nossos próprios métodos +convert+:
```suggestion
Podemos adicionar os nossos próprios métodos +convert+:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +_Promoção_ é a conversão de valores de tipos mistos para um único tipo comum:
```suggestion
_Promoção_ é a conversão de valores dos tipos mistos para um único tipo comum:
```

2020-07-16 18:11 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O código Julia pode ser representado como uma estrutura de dados da própria linguagem. Isso permite que um programa transforme e gere seu próprio código.
```suggestion
O código Julia pode ser representado como uma estrutura de dados da própria linguagem. Isso permite que um programa transforme e gere o seu próprio código.
```

2020-07-22 22:15 UTC, gustavosarturi commented on book/src/chap19.asciidoc
>  ----
Acredito que sim pois é uma Struct definida pelo programador.

2020-07-23 02:20 UTC, chunggnuhc requested changes
2nd review

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +* suplementos de sintaxe
```suggestion
* os suplementos de sintaxe
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +* funções, tipos e macros diretamente disponíveis em +Base+
```suggestion
* as funções, os tipos e as macros diretamente disponíveis em +Base+
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +* funções, tipos e macros da Biblioteca Padrão
```suggestion
* as funções, os tipos e as macros da Biblioteca Padrão
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um _fechamento_ é uma técnica que permite uma função capturar uma variável definida fora do escopo da chamada de função.
```suggestion
Um _fechamento_ é uma técnica que permite uma função capturar uma variável definida fora do escopo da chamada da função.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +No exemplo, a primeira macro +@show+ mostra o +x+ local, a global +y+ e a local indefinida +z+. As variáveis globais são intocáveis.
```suggestion
Nesse exemplo, a primeira macro +@show+ mostra o +x+ local, a global +y+ e a local indefinida +z+. As variáveis globais são intocáveis.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um bloco +do+ pode “capturar” as variáveis de seus escopos anexos. Por exemplo, a variável +dado+ no exemplo acima de +open pass:[...] do+ é capturada de outro escopo.
```suggestion
Um bloco +do+ pode “capturar” as variáveis dos seus escopos anexos. Por exemplo, a variável +dado+ em +open pass:[...] do+ no exemplo acima é capturada de outro escopo.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O _operador ternário_, +?:+, é uma alternativa para uma declaração +if-else+ usada quando você precisa fazer uma escolha entre valores de expressão única.
```suggestion
O _operador ternário_ +?:+ é uma alternativa para uma declaração +if-else+ usada quando você precisa fazer uma escolha entre valores de expressão única.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +==== Tarefas (também conhecido como Corrotina)
```suggestion
==== Tarefas (também conhecida como Corrotina)
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O construtor +Channel+ cria a tarefa. A função +fib+ é suspendida aṕos cada chamada para +put!+ e retorna depois de +take!+. Por questões de performance, diversos valores das sequências são armazenad
```suggestion
O construtor +Channel+ cria a tarefa. A função +fib+ é suspendida aṕos cada chamada para +put!+ e retorna depois de +take!+. Por questões de performance, diversos valores da sequência são armazenados temporariamente no objeto de canal durante um ciclo de retomada/suspensão.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um tipo concreto que consiste em bits simples e antigos é chamado de _tipo primitivo_. Ao contrário da maioria das linguagens, no Julia, você pode declarar seus próprios tipos primitivos. Os tipos pr
```suggestion
Um tipo concreto que consiste em bits simples e antigos é chamado de _tipo primitivo_. Ao contrário da maioria das linguagens, no Julia você pode declarar os seus próprios tipos primitivos. Os tipos primitivos padrões são definidos da mesma maneira:
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Parâmetros do tipo são introduzidos depois do nome do tipo, cercado por chaves:
```suggestion
Parâmetros de tipo são introduzidos depois do nome do tipo, cercado por chaves:
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Além dos tipos compostos, tipos abstratos e tipos primitivos também podem ter um parâmetro do tipo.
```suggestion
Além dos tipos compostos, tipos abstratos e tipos primitivos também podem ter um parâmetro de tipo.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +==== União dos Tipos
```suggestion
==== União de Tipo
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
>  ----
Traduzir **_IntOrString_** nas linhas 356, 358 e 360.

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Uma união de tipo é na maioria das linguagens de computador uma construção interna para refletir sobre os tipos. O Julia, no entanto, expõe esse recurso aos seus usuários porque um código eficiente p
```suggestion
Uma união de tipo é na maioria das linguagens de computador uma construção interna para pensar sobre os tipos. O Julia, no entanto, expõe esse recurso aos seus usuários porque um código eficiente pode ser gerado quando a união de tipo possui um pequeno número de tipos. Esse recurso oferece ao programador do Julia uma tremenda flexibilidade para controlar o despacho.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Quando você está usando muitas chamadas para a função +eval+, geralmente isso significa que algo está errado. A função +eval+ é considerado do “mal”.
```suggestion
Quando você está usando muitas chamadas para a função +eval+, geralmente isso significa que algo está errado. A função +eval+ é considerada do “mal”.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Aqui está uma simples macro:
```suggestion
Aqui está uma macro simples:
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +(((@containervariavel)))((("macro", "definido pelo programador", "@containervariavel", see="@containervariavel")))
```suggestion
(((@containervariável)))((("macro", "definido pelo programador", "@containervariável", see="@containervariável")))
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +macro containervariavel(container, elemento)
```suggestion
macro containervariável(container, elemento)
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +As macros são chamadas ao colocar o prefixo +@+ (sinal de arroba) em seus nomes. A macro chamada +@containervariavel letras 1+ é substituída por:
```suggestion
As macros são chamadas ao colocar o prefixo +@+ (sinal de arroba) em seus nomes. A macro chamada +@containervariável letras 1+ é substituída por:
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> ++@macroexpand @containervariavel letras 1+ retorna essa expressão que é extremamente útil para a depuração.
```suggestion
+@macroexpand @containervariável letras 1+ retorna essa expressão que é extremamente útil para a depuração.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Este exemplo ilustra como uma macro pode acessar o nome dos seus argumentos, algo que uma função não pode fazer. O comando return precisa ser “escapada” com +esc+, pois precisa ser resolvida no ambie
```suggestion
Este exemplo ilustra como uma macro pode acessar o nome dos seus argumentos, algo que uma função não pode fazer. O comando return precisa ser “escapado” com +esc+, pois precisa ser resolvido no ambiente da chamada da macro.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +A macro +@generated+ cria código especializado para os métodos, dependendo dos tipos de argumentos:
```suggestion
A macro +@generated+ cria código especializado para os métodos, dependendo dos tipos dos argumentos:
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +julia> x = quadrado(2); # nota: output é da declaração println() no corpo
```suggestion
julia> x = quadrado(2); # nota: a saída é da declaração println() no corpo
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +* uma tupla com tipos de argumentos: +(Ptr{Cvoid},)+ e
```suggestion
* uma tupla com os tipos de argumentos: +(Ptr{Cvoid},)+ e
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Bloqueia a alocação de novas ligações de variáveis.
```suggestion
Bloco que aloca novas ligações de variáveis.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Recurso de fluxo de controle que permite a suspensão dos cálculos e a retomada deles de maneira flexível.
```suggestion
Recurso de fluxo de controle que permite a suspensão e a retomada dos cálculos de maneira flexível.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Um _bloco_ é uma forma de agrupar diversos comandos. Um bloco começa com a palavra chave +begin+ e termina com +end+.
```suggestion
Um _bloco_ é uma forma de agrupar diversos comandos. Um bloco começa com a palavra-chave +begin+ e termina com +end+.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +O mapeamento completo da biblioteca GDBM pode ser encontrada como um exemplo no repositório do JuliaIntroBR.
```suggestion
O mapeamento completo da biblioteca GDBM pode ser encontrado como um exemplo no repositório do JuliaIntroBR.
```

2020-07-23 02:20 UTC, chunggnuhc commented on book/src/chap19.asciidoc
> +Instâncias que representam pontos de dados sem valor.
```suggestion
Instâncias que representam informações sem valor.
```

2020-07-23 13:05 UTC, merged