Backcover translation
JuliaIntro/JuliaIntroBR.jl pull request #43
Opened 2020-10-29 08:14 UTC by RenanOD

2020-10-29 12:32 UTC, abelsiqueira requested changes
Olá @RenanOD, obrigado pela contribuição. Fiz algumas modificações baseadas nas escolhas que fizemos para a tradução geral do livro.

PS. Quanto tempo, como é que você tá?

2020-10-29 12:32 UTC, abelsiqueira commented on book/src/backcover.asciidoc
> +Se você acabou de começar a aprender programação, Julia é uma excelente linguagem dinâmica compilada just-in-time de sintaxe limpa. Esse guia hands-on usa Julia (versão 1.0) para ensinar a programar
```suggestion
Se você acabou de começar a aprender programação, Julia é uma excelente linguagem dinâmica compilada just-in-time de sintaxe limpa. Este guia hands-on usa Julia (versão 1.0) para ensinar a programar passo a passo, começando com os conceitos básicos de programação e prosseguindo até os conceitos avançados, como criação de novos tipos e despacho múltiplo.
```

2020-10-29 12:32 UTC, abelsiqueira commented on book/src/backcover.asciidoc
> +JuliaIntro é ideal para alunos de ensino médio ou superior, bem como autodidatas, quem estuda em casa e profissionais que precisam aprender o básico de programação.
```suggestion
Introdução à Programação em Julia é ideal para alunos de ensino médio ou superior, bem como autodidatas, quem estuda em casa e profissionais que precisam aprender o básico de programação.
```

2020-10-29 12:32 UTC, abelsiqueira commented on book/src/backcover.asciidoc
> +* Use técnicas de debugging pra corrigir a sintaxe, tempo de execução e erros de semântica
```suggestion
* Use técnicas de depuração pra corrigir erros de sintaxe, de tempo de execução e de semântica
```

2020-10-29 12:32 UTC, abelsiqueira commented on book/src/backcover.asciidoc
> +* Explore o projeto de interfaces e estruturas de dados com estudos de caso
```suggestion
* Explore o design de interfaces e estruturas de dados com estudos de caso
```

2020-10-29 15:08 UTC, RenanOD commented
Logo mais faço as alterações.

> PS. Quanto tempo, como é que você tá?

Opa, já ia fazer um ano :laughing: To bem até, e vc?

2020-10-29 19:22 UTC, RenanOD commented on book/src/backcover.asciidoc
> +Se você acabou de começar a aprender programação, Julia é uma excelente linguagem dinâmica compilada just-in-time de sintaxe limpa. Esse guia hands-on usa Julia (versão 1.0) para ensinar a programar
corrigido

2020-10-29 19:26 UTC, RenanOD commented
Ajustes feitos! Após o merge pode adicionar a tag `hacktoberfest-accepted` por favor? Assim completo o evento :sweat_smile:

2020-10-30 12:16 UTC, abelsiqueira commented
A saber é preciso que o repositório tenha a tag hacktoberfest, senão não vale. Tenho um outro repositório fácil de contribuir também: https://github.com/abelsiqueira/Jet.jl.

2020-10-30 12:18 UTC, merged

2020-10-30 12:20 UTC, abelsiqueira commented
Obrigado. Coloquei hacktoberfest no repo. Se não aparecer pra você no seu perfil me avisa.

E tô bem também, trabalhando bastante, fazendo um monte de vídeo no youtube, cuidando do CiDAMO, etc. Não suma! Abraço

2020-11-03 16:27 UTC, RenanOD commented
Valeu! O CiDAMO continua ativo, com reuniões e projetos? @abelsiqueira

2020-11-03 16:45 UTC, abelsiqueira commented
Continua sim. Estamos online agora, claro. Temos as reuniões internas e estamos fazendo meetups mensais na última quinta do mês. As gravações ficam aqui: https://www.youtube.com/abelsiqueira