chapter 4 translation PTBR
JuliaIntro/JuliaIntroBR.jl pull request #6
Opened 2020-04-27 23:39 UTC by joaoluisro

Também vamos ter que mexer no próprio pacote ThinkJuliaPTBR, já que existem algumas funções (como ```Turtle()```,  ```forward()```, ...) que podem ser traduzidas.

2020-05-01 18:48 UTC, joaoluisro commented
@abelsiqueira

2020-05-05 04:19 UTC, chunggnuhc requested changes
1st review finished.

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Os exemplos neste capítulo podem ser executados em um notebook gráfico no JuliaBox, que combina código, texto formatado, matemática e multimídia em um único docoumento (ver <<juliabox>>).
"... em um único documento..." (erro de digitação)

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Um _módulo_ é um arquivo que contém uma coleção de funções relacionadas. O Julia fornece alguns módulos na sua biblioteca padrão. Funcionalidades adicionais podem ser adicionadas a partir de uma cres
Eu gostaria de sugerir "Mais funcionalidades podem ser adicionadas....", que evita a repetição de adicionais e depois o adicionadas.

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Antes de podermos usar as funções em um módulo, temos que importá-lo usando a declaração +using+:
Eu gostaria de sugerir "Antes de podermos usar as funções de um módulo....", porque é o que usualmente falado.

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O módulo +ThinkJulia+ módulo proporciona a função chamada +Turtle+ que cria um objeto +Luxor.Turtle+, no qual o atribuimos a uma variável chamada +🐢+ (*+\:turtle: TAB+*).
(1) "O módulo +ThinkJulia+ possui/tem uma função.... que cria um objeto +Luxor.Turtle+, que atribuímos a uma ...."
(2) Só verifica com Abel só tb faremos a tradução desse pacote. Se sim, então teria q trocar para "O módulo +PenseJulia+ ..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Logo após criarmos a tartaruga, podemos chamar a função que a move ao redor de um desenho. Por exemplo, para mover a tartaruga para a frente:
"Logo após criarmos a tartaruga, podemos chamar uma função..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +A palavra-chave +@svg+ executa um macro que desenha a imagem SVG. Macros são uma parte importante, mas avançadas, do Julia.
(1) "A palavra-chave +@svg+ executa um macro que desenha uma imagem SVG." 
(2) Eu gostaria de sugerir "Macros são uma parte importante, e avançada, do Julia."
(3) Macro é geralmente usada com artigo feminino ou masculino. Na minha opinião, o usual é "A macro..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Os argumentos de +forward+ são a tartaruga e a distância em pixeis, portanto o tamanho real depende do seu monitor.
(1) Conforme https://www.flip.pt/Duvidas-Linguisticas/Duvida-Linguistica/DID/3416, então seria "... a tartaruga e a distância em pixels ..."
(2) Minha sugestão: "... portanto o tamanho real do movimento depende do seu monitor."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Além disso, cada tartaruga está segurando uma caneta, que pode estar tanto para baixo ou para cima; se a caneta está para baixo, a tartaruga deixa uma trilha quando ela move-se. <<fig04-1>> mostra a
(1) "a tartaruga deixa uma trilha quando ela se move."
(2) "As funções +penup+ e +pendown+ significam respectivamente “caneta para cima” e “caneta para abaixo”."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Agora modifique o macro para desenhar um quadrado. Não vá até que você o faça funcionar!
(1) Uma sugestão: dentro do que pesquisei na internet, a maioria usa "a macro".
(2) "Não avance até que você faça isso funcionar!"

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +=== Repetição simples
"Repetição Simples"

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Esse é o uso mais simples da declaração +for+; nós veremos mais usos mais tarde. Mas isso deve ser o suficiente para que você possa reescrever o seu programa que desenha um quadrado. Não vá até que v
"Não continue até que você o faça."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Uma declaração +for+ também é chamada de _laço_, pois o fluxo de execução percorre o corpo e em seguida retorna até o topo em um ciclo. Neste caso, ela percorre o corpo quatro vezes.
Aprendi com Gustavo que tem que "Nesse caso, ela percorre..." porque vc está se refeindo a algo já citado no seu texto.

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Essa versão é na verdade um pouco diferente do código que desenha um quadrado visto anteriormente, pois faz mais uma curva depois de desenhar o último lado do quadrado. A curva adicional leva mais te
Eu gostaria de sugerir "... Essa versão também faz a tartaruga retornar para sua posição inicial, de frente à direção inicial."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +A seguir estão uma série de exercícios utilizando turtles. Elas tem o propósito de serem divertidas, mas tem um objetivo também. Enquanto você trabalha com elas, pense sobre qual é o objetivo.
Eu gostaria de sugerir "A seguir, há uma série de exercícios que usa turtles. Ela foram elaboradas para serem divertidas, mas também tem um propósito."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +A secção seguinte contém soluções para os exercícios, então não olhe até que você termine-os (ou pelo menos tentou).
(1) Eu sei que seção é igual a secção, mas usualmente no Brasil usamos mais o seção. Então, recomendo "A seção seguinte contém soluções..."
(2) "... não olhe até que você terminar (ou pelo menos tentar)."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Adicione outro parâmetro, chamado +com+, em +quadrado+. Modifique o corpo para que o comprimento dos lados seja +com+, e então modifique a chamada de função para fornecer um segundo argumento. Execut
(1) "e então modifique a chamada de função para receber um segundo argumento."

(2) Decidir se vai ser com "o macro" ou "a macro".

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Escreva uma função chamada +círculo+ que recebe uma tartaruga< +t+, e raio< +r+, como parâmetros e que desenha um círculo aproximado através da chamada de +polígono+ com um comprimento e número de la
"Escreva uma função chamada +círculo+ que recebe uma tartaruga +t+, e raio +r+ como parâmetros e que desenha uma figura próximo a um círculo através da chamada de +polígono+ com um comprimento e número de lados apropriados."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Descubra a circumferência do círculo e garanta que +com * n == circumferência+.
Determine a circunferência do círculo e garanta que +com * n == circunferência+."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Faça uma versão mais genérica de +círculo+ chamada +arc+ que recebe um parâmetro adicional +ângulo+, que determina qual fração de círculo desenhar. +ângulo+ é uma unidade de graus, então quando +ângu
(1) "Faça uma versão mais geral de ..."
(2) Trocar arc por arco.
(3) "+ângulo+ é uma medida em graus, então..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O primeiro exercício pede para que você coloque o seu código de desenhar quadrado em uma definição de função, e em seguida, chame essa função utilizando tartaruga como parâmetro. Aqui está a solução:
Minha sugestão: "... em uma definição de função, e que em seguida você chame essa função utilizando tartaruga ..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Dentro da função, +t+ refere-se à mesma tartaruga +🐢+, então +turn(t, -90)+ tem o mesmo efeito que +turn(🐢+, -90+. Neste caso, por que não chamar o parâmetro +🐢+ ? A idéia é que +t+ pode ser qualquer
(1) falta fechar um parênteses: "então +turn(t, -90)+ tem o mesmo efeito que +turn(🐢+, -90+)." 
(2) tem q tirar os espaços entre a tartaruga: "Neste caso, por que não chamar o parâmetro +🐢+?" 
(3) "A ideia é que +t+ pode ser qualquer tartaruga..."
(4) "e passá-la como argumento para +quadrado+:"

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Envolver um pedaço de código em uma função é chamado de _encapsulamento_. Um dos benefícios do encapsulamento é que ele anexa um nome ao código, que serve como uma forma de documentação. Outra vantag
"se você está re-utilizando o código" -> colocar o artigo

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Adicionar um parâmetro a uma função é chamado de _generalização_ pois faz com que a função seja mais genérica: na versão anterior, o quadrado sempre tem o mesmo tamanho; nesta versão ele pode ter qua
Mnha sugestão: "... pois faz com que a função seja mais abrangente: ..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O próximo passo também é generalização. Ao invés de desenhar quadrados, +polígono+ desenha polígonos regulares com qualquer número de lados. Aqui está a solução:
"O próximo passo também é a generalização." -> colocar artigo

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Este exemplo desenha um polígono de 7 lados com comprimento 70.
"Este exemplo desenha um heptágono de lado medindo 70.

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O próximo passo é escrever +círculo+, que recebe um raio, +r+, como parâmetro. Aqui está uma solução simples que usa +polígono+ para desenhar um polígono de 50 lados:
"O próximo passo é escrever +círculo+, que recebe um raio +r+ como parâmetro. 

Só para não tirar a fluidez do texto.

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +    circumferência = 2 * π * r
circunferência

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +    com = circumferência / n
circunferência

Aproveite para dar um replace para corrigir o "circumferência".

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +A primeira linha computa a circumferência de um círculo com raio latexmath:[\(r\)] usando a fórmula latexmath:[\(2 \pi r\)]. +n+ é o número de segmentos de linha em nossa aproximação de um círculo, e
Eis a minha sugestão: "+n+ é o número de segmentos de linha usados na nossa aproximação de um círculo, e +com+ é o comprimento de cada segmento. Portanto, +polígono+ desenha um polígono de 50 lados que se aproxima um círculo de raio +r+."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Este processo-reorganizar um programa para melhorar interface e facilitar reuso de código é chamado de _refatoração_. Neste caso, nós percebemos que havia código similar em +arc+ e +polígono+, então
(1) "Este processo de reorganização de um programa para melhorar a interface e facilitar o reuso de código ..."
(2) "então nós “fatoramos-o” para dentro de +polílinha+." -> faltou acento

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Se nós tivessemos planejado com antecedência, nós poderiamos ter escrito +polílinha+ primeiro e evitado a refatoração, mas você frequentemente não sabe o suficiente no começo de um projeto para plane
"Se nós tivéssemos planejado com antecedência..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +=== Um plano de desenvolvimento
Um Plano de Desenvolvimento

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +(((plano de desenvolvimento de programa)))
Minha sugestão: "(((plano de desenvolvimento para um programa)))"

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +. Comece escrvendo um pequeno programa sem definições de funções.
Erro de digitação

"Comece escrevendo um pequeno ..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +. Uma vez que você fez com que o seu programa funcione, identifique um pedaço coerente dele, encapsule-o em uma função e dê a ele um nome.
"... e dê a ela um nome."

Porque vc dá o nome para a função.

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +. Repita os passos 1-3 até que você tenha um conjunto de funções que funcionam. Copie e cole código para evitar re-digitá-los (e re-debugá-los).
(1) Tenho usado a tradução "programas funcionais" para "working functions". Fica a sugestão.
(2) "Copie e cole o código para evitar..." -> faltou o artigo
(3) "para evitar redigi-los (e re-debugá-los)."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +. Busque por oportunidades de melhora no programa através da refatoração. Por exemplo, se você tem um código similar em vários lugares, considere fatorá-lo em um função geral apropriada.
" em uma função geral apropriada."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Um _docstring_ é uma string que vem antes de uma função, e explica sua interface (“doc” refere-se a “documentação”). Aqui está um exemplo:
Minha sugestão: "Um _docstring_ é uma string que vem antes de uma função, e descreve sua interface (“doc” refere-se a “documentação”)."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
>  (((docstring)))(((triple quotes)))((("pass:[&quot;&quot;&quot;]", see="triple quotes")))
(((aspas triplas)))

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Ela explica que efeito cada parâmetro tem no comportamento da função e qual tipo cada parâmetro deve ser (se não é óbvio).
(1) Arrumar as linhas. Colocar td na linha 436.
(2) Minha sugestão: "Ela explica que efeito cada parâmetro tem na execução da função e ..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Uma interface é como um contrato entre a função e quem a chama. Quem chama concorda em fornecer certos parâmetros e a função concorda em fazer certo trabalho.
"e a função concorda em fazer um certo trabalho."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Por exemplo, +polílinha+ requer quatro argumentos: +t+ tem que ser uma tartaruga; +n+ tem que ser um inteiro; +com+ deve ser um número positivo; e +ângulo+ tem que ser um número, que é assumido estar
Minha sugestão: "+ângulo+ tem que ser um número, que assume-se ser uma medida em graus."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Esses requerimentos são chamados de _pré-condições_ pois eles deveriam ser verdadeiros antes que a função execute. Inversamente, condições no final da função são chamadas de _pós-condições_. Pós-cond
"Esses requerimentos são chamados de precondições..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +(((pré-condição)))(((pós-condição)))
(((precondição)))
e assim vai... usa o replace para arrumar o "pré-condição" e o "pré-condições"

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Se as pré-condições são satisfeitas e as pós-condições não, o bug está na função. Se as suas pré- e pós-condições forem claras, elas podem ajudar na hora de debugar.
"Se as precondições são satisfeitas e as pós-condições não, então o bug está na função."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Uma parte do programa que executa repetidamente.
"Uma parte do programa que é executado repetidamente."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O processo de transformar a sequência de declarações em uma definição de função.
Minha sugestão: "O processo de transformar uma sequência de comandos em uma definição de função."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O processo de substituir algo desnecessariamente específico (como um número) com algo geral adequado (como uma variável ou parâmetro).
"O processo de substituir algo desnecessariamente específico (como um número) por algo mais adequadamente irrestrito (como uma variável ou parâmetro)."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Uma descrição de como usar uma função, incluindo o nome e as descrições dos argumentos e o valor de retorno.
"Uma descrição de como usar uma função, incluindo o nome, as descrições dos argumentos e o valor de retorno."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Digite o código neste cápitulo em um notebook.
"Digite o código deste capítulo em um notebook."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +. Desenhe um diagrama de pilha que mostra o estado do programa enquanto ele é executado +círculo(🐢, raio)+. Você pode contar no dedo ou adicionar declarações de impressão no código.
Minha sugestão: "Desenhe um diagrama de pilha que mostra o fluxo de execução de +círculo(🐢, raio)+."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +. A versão de +arc+ em <<refatoração>> não é muito precisa dado que a aproximação linear do círculo está sempre fora do verdadeiro círculo. Como resultado, a tartaruga acaba alguns pixéis depois do d
(1) "Como resultado, a tartaruga acaba alguns pixels desviado do destino correto."
(2) "Se você desenhar o diagrama, você poderá ver como ela funciona."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +    turn(t, ang_passo/2)
Não esquece de verificar as linhas e se elas correspondem.

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Escreva um conjunto geral de funções apropriadas que podem desenhar formas como as em <<fig04-3>>.
"...que podem desenhar formas como as de <<fig04-3>>."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +As letras do alfabeto podem ser construídas a partir de um número moderado de elementos básicos, como linhas verticais e horizontais e algumas curvas. Projete um alfabeto que pode ser desenhado com o
(1) "como linhas verticais, horizontais e algumas curvas."
(2) "com o menor número de elementos básicos e em seguida escreva funções que podem desenhar as letras."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Você deve escrever uma função para cada letra, com nomes +desenha_a+, +desenha_b+, etc. E coloque suas funções em um arquivo chaamdo _letras.jl_.
"em um arquivo chamado _letras.jl_."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +A _interface_ de uma função é um resumo de como ela deve ser usada: quais são os parâmetros? O que a função faz? E qual o seu valor de retorno? Uma interface é “limpa” se permite ao chamador da funçã
"Uma interface é “limpa” se permite àquele que chamou a função fazer tudo o que ele quer sem precisar lidar com detalhes desnecessários."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Ele introduz o turtle graphics, um jeito de criar desenhos programáveis. O pacote turtle graphics não está incluso na biblioteca padrão do Julia, portanto o módulo ThinkJulia tem que ser adicionado n
Na minha opinião seria interessante colocar essa descrição em frente do termo "turtle graphics". para que o leitor não fique tão perdido de início. Por exemplo: "Ele introduz o pacote turtle graphics, um jeito de criar desenhos por meio de um programa. Turtle graphics não está ...."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +A sintaxe de uma declaração +for+ é similar à uma definição de função. Ela possui um cabeçalho e um corpo que termina com a palavra-chave +end+. O corpo pode conter qualquer número de declarações.
"A sintaxe de uma declaração +for+ é similar a uma definição de função."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +    polygon(t, n, com)
Acho q tem q traduzir esse "polygon".

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Em vez de bagunçar a interface, é melhor escolher um valor apropriado de +n+ dependendo de +circunfêrencia+:
"+circunferência+" -> erro de digitação

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +    polygon(t, n, com)
Acho q tem q traduzir o "polygon".

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Adicionar 3 à +n+ garante que o polígono tenha no mínimo 3 lados.
"Adicionar 3 a +n+" -> sem crase

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Quando eu escrevi +círculo+, eu pude re-utilizar +polígono+ pois um polígono com vários lados é uma boa aproximação de um círculo. Mas +arc+ não é igualmente cooperativo; não podemos usar +polígono+
"Quando eu escrevi +círculo+, eu pude reutilizar..."

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +    polyline(t, n, com, ângulo)
Acho q tem q traduzir o "polyline" aqui e na linha 362,

2020-05-05 04:19 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Esse processo tem algumas desvantagens-nós veremos as alternativas mais tarde-mas pode ser utíl se você não sabe previamente como dividir o programa em funções. Essa abordagem permite que você planej
"... mas pode ser útil ..."

2020-05-05 07:37 UTC, joaoluisro commented on book/src/chap04.asciidoc
> +Um _módulo_ é um arquivo que contém uma coleção de funções relacionadas. O Julia fornece alguns módulos na sua biblioteca padrão. Funcionalidades adicionais podem ser adicionadas a partir de uma cres
Boa sugestão, não tinha percebido a repetição.

2020-05-05 07:39 UTC, joaoluisro commented on book/src/chap04.asciidoc
> +O módulo +ThinkJulia+ módulo proporciona a função chamada +Turtle+ que cria um objeto +Luxor.Turtle+, no qual o atribuimos a uma variável chamada +🐢+ (*+\:turtle: TAB+*).
Acho que futuramente sim, mas deixei pra não causar nenhum problema de execução do código.

2020-05-06 21:08 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O módulo +ThinkJulia+ módulo proporciona a função chamada +Turtle+ que cria um objeto +Luxor.Turtle+, no qual o atribuimos a uma variável chamada +🐢+ (*+\:turtle: TAB+*).
(1) falta acento no verbo conjugado "atribuímos"
(2) ok. Coloquei um item no googledocs sobre a tradução do pacote thinkJulia

2020-05-06 21:41 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +A seguir estão uma série de exercícios utilizando turtles. Elas tem o propósito de serem divertidas, mas tem um propósito também. Enquanto você trabalha com elas, pense sobre qual é o propósito.
Vc está repetindo propósito em um curto espaço numa mesma frase. Nesse caso, recomendo voltar a sua tradução anterior: "Elas tem o propósito de serem divertidas, mas com um objetivo também."

2020-05-06 21:41 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +A secção seguinte contém soluções para os exercícios, então não olhe até que você termine-os (ou pelo menos tentou).
Falta essa mudança.

2020-05-06 21:49 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Dentro da função, +t+ refere-se à mesma tartaruga +🐢+, então +turn(t, -90)+ tem o mesmo efeito que +turn(🐢+, -90+. Neste caso, por que não chamar o parâmetro +🐢+ ? A idéia é que +t+ pode ser qualquer
Faltou tirar o acento de "ideia". 
(3)"A ideia é que +t+ pode ser qualquer tartaruga..."

2020-05-06 22:02 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O próximo passo é escrever +círculo+, que recebe um raio, +r+ como parâmetro. Aqui está uma solução simples que usa +polígono+ para desenhar um polígono de 50 lados:
Tirar a vírgula presente na frase "... que recebe um raio, +r+ como parâmetro".

2020-05-06 22:02 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Este processo-reorganizar um programa para melhorar interface e facilitar reuso de código é chamado de _refatoração_. Neste caso, nós percebemos que havia código similar em +arc+ e +polígono+, então
Faltaram essas mudanças.

2020-05-07 00:30 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +(((docstring)))(((aspas triplas)))((("pass:[&quot;&quot;&quot;]", see="triple quotes")))
Acho q tem que traduzir o triple quotes no último parênteses.

2020-05-07 00:30 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O processo de substituir algo desnecessariamente específico (como um número) por algo mais adequadamento irrestrito (como uma variável ou parâmetro).
adequadamente

2020-05-07 00:30 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +    ângulo: ângulo feito pelo arcoo, em graus
corrigir os "arcoo"

2020-05-07 00:30 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Esse processo tem algumas desvantagens-nós veremos as alternativas mais tarde-mas pode ser utíl se você não sabe previamente como dividir o programa em funções. Essa abordagem permite que você planej
ainda tem erro na palavra útil

2020-05-07 01:18 UTC, chunggnuhc requested changes
Mais modificações para fazer.

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
na linha 105, fecha as aspas duplas em "... see="declaração for)))"

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Quando eu escrevi +círculo+, eu pude reutilizar +polígono+ pois um polígono com vários lados é uma boa aproximação de um círculo. Mas +arco+ não é igualmente cooperativo; não podemos usar +polígono+
Corrigir "arcoo"

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
>  end
Na linha 334, "Ao invés disso, chamaremos a função mais geral +polílinha+:"

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Se nós tivéssemos planejado com antecedência, nós poderiamos ter escrito +polílinha+ primeiro e evitado a refatoração, mas você frequentemente não sabe o suficiente no começo de um projeto para plane
"Às vezes refatoração é um sinal de que você aprendeu alguma coisa."

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Esse processo tem algumas desvantagens-nós veremos as alternativas mais tarde mas pode ser utíl se você não sabe previamente como dividir o programa em funções. Essa abordagem permite que você planej
O traço de "-nós veremos as alternativas mais tarde-" foi apagado.

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +searcoh:
O que aconteceu aqui? Pq vc fez essa mudança?

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Por exemplo, +polílinha+ requer quatro argumentos: +t+ tem que ser uma tartaruga; +n+ tem que ser um inteiro; +com+ deve ser um número positivo; e +ângulo+ tem que ser um número, que é assume-se ser
Tirar "é" da frase "que é assume-se ser uma medida em graus."

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
>  (((declaração using)))
O significa em inglês de módulo é "A file that contains a collection of related functions and other definitions."

Eu acho q em português fica: "Um arquivo que contém uma coleção de funções  e outras definições relacionadas."

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Uma parte do programa que é executado repetidamente.
Desculpa, aqui é "Uma parte do programa que é _executada_ repetidamente."

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +As letras do alfabeto podem ser construídas a partir de um número moderado de elementos básicos, como linhas verticais, horizontais e algumas curvas. Projete um alfabeto que pode ser desenhado com o
"e em seguida escreva funções que _desenhem as_ letras."

2020-05-07 01:18 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +.Espiral de arcohimedes
O que aconteceu aqui? Pq vc fez essa alteração?

2020-05-08 19:47 UTC, joaoluisro commented on book/src/chap04.asciidoc
> +.Espiral de arcohimedes
ctrl + f "arc" -> "arco", acabou pegando outras coisas.

2020-05-13 23:11 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +Se nós tivéssemos planejado com antecedência, nós poderiamos ter escrito +polílinha+ primeiro e evitado a refatoração, mas você frequentemente não sabe o suficiente no começo de um projeto para plane
"nós _poderíamos_ ter escrito +polílinha+ primeiro e evitado a refatoração..."

faltou acento no poderíamos

2020-05-13 23:11 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +.Espiral de arcohimedes
Hum.... entendi.

Acabei não vendo isso antes, mas é "Espiral de _Arquimedes_".

2020-05-13 23:13 UTC, chunggnuhc commented on book/src/chap04.asciidoc
> +O módulo +ThinkJulia+ módulo proporciona a função chamada +Turtle+ que cria um objeto +Luxor.Turtle+, no qual o atribuimos a uma variável chamada +🐢+ (*+\:turtle: TAB+*).
"O módulo +ThinkJulia+ possui uma função chamada +Turtle+ que cria um objeto +Luxor.Turtle+, **_que_** atribuímos a uma variável chamada +🐢+ (*+\:turtle: TAB+*)."

2020-05-22 01:26 UTC, chunggnuhc commented
Na minha opinião, tá td certo.

2020-05-22 14:12 UTC, abelsiqueira requested changes
João, obrigado pela tradução e Kally, obrigado pela revisão.
Fiz algumas mudanças adicionais mas vou tentar dar merge eu mesmo. Não sei se vai funcionar já que o branch é no seu repositório.

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Além disso, cada tartaruga está segurando uma caneta, que pode estar tanto para baixo ou para cima; se a caneta está para baixo, a tartaruga deixa uma trilha quando ela se move. <<fig04-1>> mostra a
```suggestion
Além disso, cada tartaruga está segurando uma caneta, que pode estar tanto para baixo ou para cima; se a caneta está para baixo, a tartaruga deixa uma trilha quando ela se move. <<fig04-1>> mostra a trilha deixada pela tartaruga. As funções +penup+ e +pendown+ significam respectivamente “caneta para cima” e “caneta para baixo”.
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Os ângulos externos de um polígono regular de latexmath:[\(n\)] lados somam latexmath:[\(\frac{360}{n}\)] graus.
```suggestion
Os ângulos externos de um polígono regular de latexmath:[\(n\)] lados são iguais a latexmath:[\(\frac{360}{n}\)] graus.
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +O próximo passo também é a generalização. Ao invés de desenhar quadrados, +polígono+ desenha polígonos regulares com qualquer número de lados. Aqui está a solução:
```suggestion
O próximo passo também é uma generalização. Ao invés de desenhar quadrados, +polígono+ desenha polígonos regulares com qualquer número de lados. Aqui está a solução:
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Quando eu escrevi +círculo+, eu pude reutilizar +polígono+ pois um polígono com vários lados é uma boa aproximação de um círculo. Mas +arco+ não é igualmente cooperativo; não podemos usar +polígono+
```suggestion
Quando escrevemos +círculo+, pudemos reutilizar +polígono+ pois um polígono com vários lados é uma boa aproximação de um círculo. Mas +arco+ não é igualmente cooperativo; não podemos usar +polígono+ ou +círculo+ para desenhar um arco.
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Uma alternativa é começar com uma cópia de +polígono+ e transformá-lo em +arco+. O resultado pode parecer algo como:
```suggestion
Uma alternativa é começar com uma cópia de +polígono+ e transformá-la em +arco+. O resultado pode parecer algo como:
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +A segunda metade dessa função parece-se com +polígono+, mas nós não podemos reusar +polígono+ sem mudar a interface. Nós poderíamos generalizar +polígono+ para receber +ângulo+ como terceiro argument
```suggestion
A segunda metade dessa função parece-se com +polígono+, mas nós não podemos reusar +polígono+ sem mudar a interface. Nós poderíamos generalizar +polígono+ para receber +ângulo+ como terceiro argumento, mas então +polígono+ não seria mais um nome apropriado! Ao invés disso, chamaremos a função mais geral +polilinha+:
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +(((polílinha)))((("função", "definido pelo programador", "polílinha", see="polílinha")))
```suggestion
(((polilinha)))((("função", "definido pelo programador", "polilinha", see="polilinha")))
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +function polílinha(t, n, com, ângulo)
```suggestion
function polilinha(t, n, com, ângulo)
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Agora nós podemos reescrever +polígono+ e +arco+ para usar +polílinha+:
```suggestion
Agora nós podemos reescrever +polígono+ e +arco+ para usar +polilinha+:
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +    polílinha(t, n, com, ângulo)
```suggestion
    polilinha(t, n, com, ângulo)
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +    polílinha(t, n, com_passo, ang_passo)
```suggestion
    polilinha(t, n, com_passo, ang_passo)
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Este processo de reorganização de um programa para melhorar interface e facilitar o reuso de código é chamado de _refatoração_. Neste caso, nós percebemos que havia código similar em +arco+ e +polígo
```suggestion
Este processo de reorganização de um programa para melhorar interface e facilitar o reuso de código é chamado de _refatoração_. Neste caso, nós percebemos que havia código similar em +arco+ e +polígono+, então nós o “fatoramos” para dentro de +polilinha+.
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Se nós tivéssemos planejado com antecedência, nós poderíamos ter escrito +polílinha+ primeiro e evitado a refatoração, mas você frequentemente não sabe o suficiente no começo de um projeto para plane
```suggestion
Se nós tivéssemos planejado com antecedência, nós poderíamos ter escrito +polilinha+ primeiro e evitado a refatoração, mas você frequentemente não sabe o suficiente no começo de um projeto para planejar todas as interfaces. A partir do momento em que você começa a programar, você passa a entender o problema melhor. Às vezes refatoração é um sinal de que você aprendeu alguma coisa.
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Um _docstring_ é uma string que vem antes de uma função, e descreve sua interface (“doc” refere-se a “documentação”). Aqui está um exemplo:
```suggestion
Uma _docstring_ é uma string que vem antes de uma função e descreve sua interface (“doc” refere-se a “documentação”). Aqui está um exemplo:
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +polílinha(t, n, com, ângulo)
```suggestion
polilinha(t, n, com, ângulo)
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +function polílinha(t, n, com, ângulo)
```suggestion
function polilinha(t, n, com, ângulo)
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +help?> polílinha
```suggestion
help?> polilinha
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +  polílinha(t, n, com, ângulo)
```suggestion
  polilinha(t, n, com, ângulo)
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Por exemplo, +polílinha+ requer quatro argumentos: +t+ tem que ser uma tartaruga; +n+ tem que ser um inteiro; +com+ deve ser um número positivo; e +ângulo+ tem que ser um número, que assume-se ser um
```suggestion
Por exemplo, +polilinha+ requer quatro argumentos: +t+ tem que ser uma tartaruga; +n+ tem que ser um inteiro; +com+ deve ser um número positivo; e +ângulo+ tem que ser um número, que assume-se ser uma medida em graus.
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +precondições são de responsabilidade de quem chama a função. Se quem chama viola uma (propriamente documentada!) precondição e a função não funciona adequadamente, o bug está em quem chamou, e não na
```suggestion
precondições são de responsabilidade de quem chama a função. Se quem chama viola uma precondição (propriamente documentada!) e a função não funciona adequadamente, o bug está em quem chamou, e não na função.
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Plano de desenvolvimento::
```suggestion
plano de desenvolvimento::
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +(((Plano de desenvolvimento)))
```suggestion
(((plano de desenvolvimento)))
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Desenha um arcoo dado o raio e ângulo:
```suggestion
Desenha um arco dado o raio e ângulo:

```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +t é uma tartaruga.
```suggestion
e o ângulo (em graus) entre eles.  t é uma tartaruga.
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +    polílinha(t, n, com_passo, ang_passo)
```suggestion
    polilinha(t, n, com_passo, ang_passo)
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +    # linear do arco
```suggestion
    # fazendo uma leve curva para a esquerda antes de iniciar
    # reduz o erro causado pela aproximação linear do arco
```

2020-05-22 14:12 UTC, abelsiqueira commented on book/src/chap04.asciidoc
> +Você deve escrever uma função para cada letra, com nomes +desenha_a+, +desenha_b+, etc. E coloque suas funções em um arquivo chamado _letras.jl_.
```suggestion
Você deve escrever uma função para cada letra, com nomes +desenha_a+, +desenha_b+, etc., e coloque suas funções em um arquivo chamado _letras.jl_.
```

2020-05-22 14:18 UTC, merged