Chapter3
JuliaIntro/JuliaIntroBR.jl pull request #8
Opened 2020-04-29 01:06 UTC by chunggnuhc

Chapter 3 finished.

2020-04-29 19:25 UTC, abelsiqueira requested changes
Obrigado @chunggnuhc, fiz algumas modificações. Quando fizer as correções me marque.

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +=== Chamada de funções
Chamadas

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Julia fornece funções que convertem valores de um tipo para outro. A função +parse+ recebe uma string e a converte em qualquer tipo de número, se puder, ou caso contrário mostra o erro:
ou dá erro caso contrário

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Em Julia, a maioria das familiares funções matemáticas estão diretamente disponíveis:
funções matemáticas familiares

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +decibels = 10 * log10(razão)
decibéis

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +(((seno)))((("função", "Base", "seno", see="sin")))(((função trigonométrica)))
Aqui acho que o Base sin não converte, talvez só o primeiro.

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Até este momento, vimos os elementos de um programa—variáveis, expressões e afirmações—isoladamente, sem detalhar em como combiná-las.
statements -> declarações. @joaoluisro, confirma?

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +julia> minutos = horas * 60 # right
`# certo`
e 
`# errado`
embaixo

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +=== Adição de novas funções
Adicionando novas funções

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Embora tenhamos usado só as funções que vêm com Julia até agora, também é possível adicionar novas funções. A _definição de função_ especifica o nome de uma nova função e a sequência de comandos que
_definição da função_

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> ++função+ é uma palavra-chave que indica a definição de função. O nome da função é +imprimirletras+. As regras para nomes de funções são as mesmas dos nomes de variáveis: eles podem conter quase todos
Primeiro +function+ não traduz.

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Reunindo os pedaços de código da seção anterior, todo o programa inteiro fica assim:
"todo o programa inteiro" -> "o programa completo"

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +function imprimir2vezes(bruce)
bruce -> bruno?

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +function concatenar2partes(parte1, parte2)
cattwich faz contatena e imprime 2 vezes. Talvez um nome melhor seja `concat2vezes`.

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +A ordem das funções no stacktrace (ou rastreamento de pilha) é a ordem inversa dos quadros no diagrama de pilha. A função atualmente em execução fica no topo.
remove o stacktrace

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +propAurea = (sqrt(5) + 1) / 2
só `aurea` ou `áurea`.

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
>  === Debugging
"Debugging ou Depuração"

NDT: ...

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Quando você elimina o impossível, o que sobra por mais incrível que pareça só pode ser a verdade.
Tendo eliminado o impossível, aquilo que resta, ainda que improvável, deve ser a verdade.

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +(((debugging experimental debugging)))(((Holmes, Sherlock)))(((Doyle, Arthur Conan)))
sobrou um debugging

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +(((Linux))) (((Torvalds, Linus))))
Users'

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Uma sequência nomeada de comandos que realiza alguma operação útil. As funções podem ou não nessitar de argumentos e podem ou não gerar um resultado.
sumiu um (((função)))

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Escreva uma função denominada +alinharADireita+ que recebe uma string denominada +s+ como parâmetro e imprime a string com espaços suficientes à esquerda de modo que a última letra da string esteja n
`alinharadireita`. No livro usamos `camelcase`, infelizmente.

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +Um objeto de função é um valor que você pode associar a uma variável ou passar como argumento. Por exemplo, +fazer2vezes+ é uma função que pega um objeto de função como argumento e o chama duas vezes
Um objeto do tipo função

2020-04-29 19:25 UTC, abelsiqueira commented on book/src/chap03.asciidoc
> +. Escreva uma função +imprimirGrid+ que desenha uma grade da seguinte maneira:
imprimirgrade

2020-04-30 00:19 UTC, chunggnuhc commented
Corrections made and some text modified.

2020-04-30 13:18 UTC, abelsiqueira approved these changes

2020-04-30 13:23 UTC, abelsiqueira commented
@christianpeel, looks like I don't have write permission, can you grant me it?

2020-04-30 14:44 UTC, christianpeel commented
> @christianpeel, looks like I don't have write permission, can you grant me it?

Done.  I gave you admin access

2020-04-30 15:47 UTC, merged