Chapter 01 - PTBR
JuliaIntro/JuliaIntroBR.jl pull request #9
Opened 2020-04-29 19:58 UTC by gustavosarturi

Comentários removidos.

2020-04-30 02:27 UTC, abelsiqueira commented on book/src/chap01.asciidoc
Gustavo, arruma esse espaçamento aqui pra mim, por favor. Faz o commit, pusha e vê se funcionou.

2020-05-01 13:17 UTC, abelsiqueira requested changes
Obrigado @gustavosarturi, fiz algumas correções. Peça o review quando estiver pronto pra eu ver.

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +O ((("cientistas da computação, habilidades de", seealso="programação")))objetivo deste livro é ensinar você a pensar como um cientista da computação. Esse meio de pensamento combina algumas das melh
Esse meio de pensamento -> Essa maneira de pensar

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +A ((("resolução de problemas")))habilidade mais importante para um cientista da computação é a solução de problemas. Solucionar problemas significa ter habilidade para formular problemas, pensar em s
solução de problemas -> resolução de problemas
Solucionar -> Resolver
clara e precisa -> clara e precisamente

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +À princípio, você estará aprendendo a programar, uma habilidade muito útil à você. Após, você usará a programação como um significado para o fim. Na medida que formos evoluindo, esse fim ficará mais
À princípio -> Por um lado
útil à você -> útil por si só
Após -> Por outro
como um significado para o fim -> para alcançar um objetivo

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Os ((("instruções", seealso="sentenças"))) detalhes são diferentes em diferentes linguagens de programação, mas algumas instruções básicas aparecem em praticamente em todos os idiomas:
senteças -> comandos

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Um ((("Julia", "executando")))dos desafios de começar com o Julia é que talvez você precise instalá-lo a um software relacionado ao seu computador. Se você está familiarizado com o seu sistema operac
precise instalá-lo a um software relacionado ao -> precise instalá-lo e softwares relacionados no

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +No navegador, você pode executar o https://www.juliabox.com[JuliaBox]. Nenhuma instalação é necessária - Apenas escolha um navegador, faça o _log in_ e comece a programar (veja <<juliabox>>).
Faltou os (((...)))

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +No navegador, você pode executar o https://www.juliabox.com[JuliaBox]. Nenhuma instalação é necessária - Apenas escolha um navegador, faça o _log in_ e comece a programar (veja <<juliabox>>).
@christianpeel looks like JuliaBox is closing down. I think we can open an issue on the ThinkJulia repo?

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +O Julia _REPL_ (Read-Eval-Print Loop, que traduzido ao pé da letra, significa Ler, Avaliar e Repetição de impressão) é um programa que lê e executa os códigos do Julia. Você pode começar o REPL abrin
O _REPL_ (...) do Julia

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +As primeiras contém informações sobre o REPL, que deve ser diferente para você. Porém, você deve checar que o número da versão seja pelo menos 1.0.0.
primeiras linhas

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +A última linha é um _prompt_ que indica que o REPL está pronto para você inserir o código. Se você digitar uma linha de código e pressionar Enter, o REPL exibirá o seguinte resultado:
(((...)))

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +=== O primeiro programa
O Primeiro Programa

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +== O caminho da programação
Camel Case nos títulos

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Este ((("declaração de impressão", "função println")))((("saída", "declaração de impressão")))é um exemplo de uma declaração de impressão, embora não imprima nada no papel. Ele exibe o resultado na t
comando

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Os parênteses indicam que +printl+ é uma função. Nós chegaremos em funções no <<Capítulo 3>>. ((("<<chap03>>"")))
println

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +O operador ((("$$/$$ (operador de divisão)", primary-sortas="* divisão")))((("divisão", "operador de divisão ($$/$$)"))) +/+ executa divisão:
operador aparece depois

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Finalmente, o operador ((("$$^$$ (caret)", "operador de exponenciação", primary-sortas="* circunflexo")))((("operador de exponenciação ($$^$$)")))((("circunflexo ($$^$$)", "operador de exponenciação"
de novo
aumenta -> eleva

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Um _valor_ ((("valores"))) é uma das coisas mais básicas que um programa trabalha, como uma letra ou um número. Alguns valores que vimos até agora são 2, 42.0, e +"Olá, Mundo!"+.
+2+, +42.0+

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Inteiros pertencem ao tipo +Int64+, strings pertencem a +String+, e pontos flutuantes pertencem a +Float54+.
54

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +E ((("aspas (&quot;&#x2026;&quot;)", "anexo de strings")))((("&quot;&#x2026;&quot; (aspas)", "anexo de strings", primary-sortas="* aspas")))quanto a valores como +"2"+ e +"42.0"+? Eles parecem número
enclosing strings -> delimitação de strings

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +=== Linguagem Formal e Natural
gens

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +_Linguagens Naturais_ ((("linguagem natural", id="ch1nat", range="startofrange"))) são aquelas linguagens que as pessoas falam, como Inglês, Espanhol, Português e o Francês. Eles não são projetados p
Elas
lhes impor

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Regras ((("tokens", id="ch1nat5", range="startofrange")))((("estrutura", id="ch1nat6", range="startofrange")))de sintaxe são fornecidas em dois tipos, pertencentes a _tokens_ e _estrutura_. Tokens sã
token -> símbolo

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +O segundo tipo de regra de sintaxe pertence ao caminho que tokens são combinados. A equação latexmath:[\(3+=3\)] não é permitida porque mesmo que latexmath:[\(+\)] e latexmath:[\(=\)] sejam tokens pe
Volta o espaço entre +=

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Quando ((("análise"))) você lê uma sentença em Poruguês ou uma declaração numa linguagem formal, você tem que descrever a estrutura (apesar de que em uma linguagem natural você faz isso subconsciente
chaamdo

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Linguagens naturais são cheias de ambiguidades, com pessoas acordando com elas e usando em pistas contextuais e outras informações. Linguagens formais são designadas para serem próximas e completamen
que as pessoal lidam usando pistas...
designado não significa fazer design. Use desenvolvidas
Essa frase inteira precisa ser revista, favor ler antes de submeter.

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Para compensar a ambiguidade e reduzir os mal-entendidos, as línguas naturais empregam muita redundância. Como resultado, eles geralmente são detalhados. Linguagens formais são menos redundantes e ma
estamos usando linguagens, não línguas
verbose -> prolixas

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +As línguas naturais estão cheias de expressões idiomáticas e metáforas. Se eu disser: "O centavo caiu", provavelmente não há centavo e nada está caindo (nesse idioma significa que alguém entendeu alg
The penny dropped é uma expressão, nas faz sentido a tradução literal.
Nosso equivalente é "a ficha caiu".

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Como todos nós crescemos falando línguas naturais, às vezes é difícil nos adaptarmos às línguas formais. A diferença entre linguagem formal e natural é como a diferença entre poesia e prosa, mas mais
linguagens

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Programadores ((("erros (bugs)")))((("debugar", "emoções de, lidando com")))cometem erros. Por motivos caprichosos, erros de programação são chamados de _bugs_ e o processo de rastrea-los é chamado d
caprichosos -> lúdicos

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Um ((("tipo inteiro (Int64)")))tipo de que rerpesenta todos os números.
rerpesenta

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +um ((("string"))) tipo que representa uma sequência de caracteres.
Um

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Qualquer ((("linguagem formal"))) uma das linguagens que as pessoas foram designadas para propósitos específicos, como representar ideias matematicas ou programas de computador. Todas ((("programming
designadas -> desenvolvidas

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Qualquer ((("linguagem formal"))) uma das linguagens que as pessoas foram designadas para propósitos específicos, como representar ideias matematicas ou programas de computador. Todas ((("programming
matemáticas

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Qualquer ((("linguagem formal"))) uma das linguagens que as pessoas foram designadas para propósitos específicos, como representar ideias matematicas ou programas de computador. Todas ((("programming
programming language

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +O ((("estrutura")))caminho que os tokens são combinados.
A maneira

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +análise::
analisar

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Sempre que você estiver experimentando um novo recurso, tente cometer erros. Por exemplo, no "Olá, mundo!" programa, o que acontece se você deixar de fora uma das aspas? E se você deixar de fora os d
"Olá, mundo!" Programa?

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Sempre que você estiver experimentando um novo recurso, tente cometer erros. Por exemplo, no "Olá, mundo!" programa, o que acontece se você deixar de fora uma das aspas? E se você deixar de fora os d
os dois?

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +. Em uma declaração impressa, o que acontece se você deixar de fora um dos parênteses ou ambos?
Em um comando de impressão

2020-05-01 13:17 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +. Quantos segundos existem em 42 minutos 42 segundos?
minutos e 42

2020-05-01 14:20 UTC, christianpeel commented on book/src/chap01.asciidoc
> +No navegador, você pode executar o https://www.juliabox.com[JuliaBox]. Nenhuma instalação é necessária - Apenas escolha um navegador, faça o _log in_ e comece a programar (veja <<juliabox>>).
Good catch! I had not noticed that Juliabox is shutting down.  One choice to replace it is [mybinder](mybinder.org), which was very responsive the first time I accessed it this morning, and did not work the second time.  Another option is [NextJournal](https://nextjournal.com/); with a bit of work the entire book could be made a LiveJournal article. You're welcome to open an issue on ThinkJulia; I'll do it this evening if I don't see one from you.  

BTW, you're making quick progress!

2020-05-01 18:20 UTC, christianpeel commented
FYI, I closed this PR and then opened it solely to trigger Travis

2020-05-01 19:00 UTC, abelsiqueira commented
Unfortunately, the site only builds when the owner's fork has Travis and `GITHUB_AUTH` setup. We can either
- Enable it for everyone, or
- Always create a branch inside `JuliaIntro`.

2020-05-02 00:35 UTC, christianpeel commented
After I changed a few things, the site builds for me, see for example the [HTML from my cp/test](https://juliaintro.github.io/JuliaIntroBR.jl/cp/test/index.html) branch. So I guess that if we gave everyone write access and they pushed branches to this repo before making a PR, each branch would build a version of the book.   The `.travis.yml` file has the line  `if: type != pull_request` that I think is preventing the book to be built for pull requests such as the current one.

2020-05-02 00:46 UTC, abelsiqueira commented
> So I guess that if we gave everyone write access and they pushed branches to this repo before making a PR, each branch would build a version of the book.

Yes. Alternatively, I could give them access to my CiDAMO branch, which would keep the `gh-pages` here cleaner, or they could enable travis in their repository, which would build the `gh-pages` there.

> The `.travis.yml` file has the line `if: type != pull_request` that I think is preventing the book to be built for pull requests such as the current one.

That condition prevents the pull requests to run the `deploy` part, but even if I let it run the deploy (and remove a similar `if` in my `deploy.jl`), the pull request from outside repos don't have access to the `GITHUB_AUTH` variable, so it can't push to the `gh-pages` in this repo.

2020-05-02 01:08 UTC, christianpeel commented
I gave everyone write access (Since you're an admin, you can change their permissions yourself if you want) so they can push branches here.  I don't mind if gh-pages gets cluttered; we can delete the branch occasionally if the clutter is too much.

2020-05-05 02:08 UTC, christianpeel commented
@abelsiqueira  Are you waiting on this PR for me?  I'm happy for it to be merged.

2020-05-05 02:10 UTC, abelsiqueira commented
No, I still have to review the changes. I'll get a couple of hours in this by Wednesday.

2020-05-06 18:38 UTC, abelsiqueira requested changes
Gustavo, só mais umas pequenas modificações.

2020-05-06 18:38 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +_Linguagens Naturais_ ((("linguagem natural", id="ch1nat", range="startofrange"))) são aquelas linguagens que as pessoas falam, como Inglês, Espanhol, Português e o Francês. Elas não são projetados p
projetadas, elas

2020-05-06 18:38 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Regras ((("símbolo", id="ch1nat5", range="startofrange")))((("estrutura", id="ch1nat6", range="startofrange")))de sintaxe são fornecidas em dois tipos, pertencentes a _símbolo_ e _estrutura_. Símbolo
pertencentes a _símbolos_ e _estrutura_

2020-05-06 18:38 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +O segundo tipo de regra de sintaxe pertence ao caminho que símbolos são combinados. A equação latexmath:[\(3 +=3\)] não é permitida porque mesmo que latexmath:[\(+\)] e latexmath:[\(=\)] sejam símbol
caminho -> maneira

2020-05-06 18:38 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Essa é um@ sentença bem estruturada em portuguê$ com t*kens inválidos. Essa frase possui todos os símbolos válidos, mas com estrutura invalida.
t*kens

2020-05-06 18:38 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Quando ((("análise"))) você lê uma sentença em Poruguês ou uma declaração numa linguagem formal, você tem que descrever a estrutura (apesar de que em uma linguagem natural você faz isso subconsciente
Poruguês

2020-05-06 18:38 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Para compensar a ambiguidade e reduzir os mal-entendidos, as linguagens naturais empregam muita redundância. Como resultado, eles geralmente são detalhadas. Linguagens formais são menos redundantes e
eles -> elas

2020-05-06 18:38 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Programadores ((("erros (bugs)")))((("debugar", "emoções de, lidando com")))cometem erros. Por motivos lúdicos, erros de programação são chamados de _bugs_ e o processo de rastrea-los é chamado de _d
rastreá-lo

2020-05-11 16:31 UTC, gustavosarturi commented on book/src/chap01.asciidoc
> +Essa é um@ sentença bem estruturada em portuguê$ com t*kens inválidos. Essa frase possui todos os símbolos válidos, mas com estrutura invalida.
Está correto, não? Nesse exemplo o autor quis dar um exemplo de frase com símbolos. 4LG0 4551M

2020-05-11 16:33 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Essa é um@ sentença bem estruturada em portuguê$ com t*kens inválidos. Essa frase possui todos os símbolos válidos, mas com estrutura invalida.
t*okens -> simb°lo$ ou algo assim

2020-05-11 22:52 UTC, abelsiqueira commented on book/src/chap01.asciidoc
> +Essa é um@ sentença bem estruturada em portuguê$ com t*kens inválidos. Essa frase possui todos os símbolos válidos, mas com estrutura invalida.
Faltou este.

2020-05-11 23:01 UTC, merged